### ISSUE TITLE
Improving cryptic error messages in GCHP

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#101]
This is a loose list of the GCHP errors that could have better error messages.

Feel free to add any crypric errors you encounter here, and I'll try my best to improve the error messages.

**Comment by lizziel** [comment]
Here are some more potential user errors that may or may not have cryptic error messages. I haven't tested them all with recent MAPL. I'll try to remember to add to this list as I think of or encounter more.

- [ ] Typos in HEMCO_Config.rc
- [ ] Typos in ExtData.rc
- [ ] Incorrect format in time units in import file
- [ ] Integers in import file
- [ ] Incorrect grid resolution in restart file
- [ ] Duplicate entries in any config file
- [ ] End time before start time or before start time + duration

**Comment by LiamBindle** [comment]
Starting in MAPL 2.8.3 errors opening NetCDF files will show (1) the offending file's path, (2) the NetCDF error code, and (3) the error code as a string. For example, what used to look like

```
pe=00213 FAIL at line=00245    NetCDF4_FileFormatter.F90                <status=13>
pe=00213 FAIL at line=00090    MAPL_ExtDataCollection.F90               <status=13>
pe=00213 FAIL at line=00232    FileMetadata.F90                         <can not find time>
pe=00213 FAIL at line=00083    FileMetadataUtilities.F90                <status=1>
pe=00213 FAIL at line=02777    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00213 FAIL at line=01512    MAPL_ExtDataGridCompMod.F90              <status=1>
```

will now be

```
nf90_open: returned error code (13) opening ./MetDir/2016/12/MERRA2.20161214.A3dyn.05x0625.nc4 [Permission denied]
pe=00213 FAIL at line=00245    NetCDF4_FileFormatter.F90                <status=13>
pe=00213 FAIL at line=00090    MAPL_ExtDataCollection.F90               <status=13>
pe=00213 FAIL at line=00232    FileMetadata.F90                         <can not find time>
pe=00213 FAIL at line=00083    FileMetadataUtilities.F90                <status=1>
pe=00213 FAIL at line=02777    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00213 FAIL at line=01512    MAPL_ExtDataGridCompMod.F90              <status=1>
```

See: https://github.com/GEOS-ESM/MAPL/pull/962

**Comment by LiamBindle** [comment]
I think #53 could be consolidate here.

> The MAPL debug print option gives lots of information during the information collection stage of MAPL ExtData, such as parsing Extdata.rc and finding files with the right times. However, the regridding part of ExtData is very murky and GCHP seemlingly stalls for a while without any printing at all during this phase. If the run times out due to an issue not caught with error handling then it is hard to know where it went wrong.
> 
> This feature request is really for GEOS-ESM/MAPL but we can put it in with GCHP in mind and then submit it as a PR to go to the upstream MAPL.

**Comment by LiamBindle** [comment]
- [ ] Warning if a blank `cap_restart` exists
