### ISSUE TITLE
[QUESTION] how to update gFTL path after compilation?

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#102]
Hello, 
I am using GCHP v 12.9.3 and I would like to ask you a question related to gFTL.
The model was running without error and then I had to move the gFTL file in another directory. 
Now, the run crashes after 3 seconds (segmentation fault). 
Is it possible to change the gFTL path after compliling the model?

Thank you in advance, 
Maria

**Comment by lizziel** [comment]
Hi Maria, does your gFTL symbolic link in the run directory point to the new location?  Also, when you moved gFTL did you rebuild it? If you've done all this and you still get a run-time error, I suggest recompiling, but skipping the recompile of ESMF. It is possible the MAPL build uses a full path for gFTL. 

That being said, we are no longer supporting the GCHP 12 series. I strongly urge you to move to GCHP 13 which is easier to use than GCHP 12, and much faster to build. gFTL is a git submodule in GCHP 13 and you do not need to worry about where to store it. For the new GCHP user guide, which details how to get and use GCHP 13, see [https://readthedocs.org/projects/gchp/](https://readthedocs.org/projects/gchp/).

**Comment by lizziel** [comment]
Hi @mtsivlidou, were you able to resolve this issue?

**Comment by mtsivlidou** [comment]
Hello, I tried to fix v 12.9.3 but it was not working, so I switched to v13. Thank you for the suggestions.
