### ISSUE TITLE
[BUG/ISSUE] GCHP v13.0.2 monthly simulation with multirun option crashes before writing output of 1st job

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#103]
### Description of the problem
I split a 2-month simulation to 2 jobs (with monthly diagnostic on) and the 1st job crashes just before writing the output. 
(I have tested the multirun script splitting a 2-hour simulation into 2 jobs of 1+1 hour and it is working. Also, I tested the monthly simulation without the multirun option and it produces output for this month without any error). 
I would appreciate it if you could provide some help to solve my issue. 
Thank you in advance,
Maria 

### GEOS-Chem version
GCHP 13.0.2

### Log files
- Build log (if applicable):
[CMakeOutput.log.txt](https://github.com/geoschem/GCHP/files/6570264/CMakeOutput.log.txt)

- Run log (if applicable): [multirun_error_output_slurm-621139.out.txt](https://github.com/geoschem/GCHP/files/6570252/multirun_error_output_slurm-621139.out.txt)

- Run script (if applicable): [gchp.multirun.run.txt](https://github.com/geoschem/GCHP/files/6570250/gchp.multirun.run.txt)
[gchp.multirun.sh.txt](https://github.com/geoschem/GCHP/files/6570251/gchp.multirun.sh.txt)

[simple_job.sh.txt](https://github.com/geoschem/GCHP/files/6570320/simple_job.sh.txt)

### Software versions
- Compilers (Intel or GNU, and version):  intel/18.2
- NetCDF version:  netcdf/4.7.4-intelmpi
- MPI version: intelmpi/18.2
- ESMF version: 8.0.1
cmake/3.13.0
hdf5/1.8.21-intelmpi

**Comment by LiamBindle** [comment]
I haven't had a chance to try the monthly diagnostics yet, and I use my own multisegment script because our cluster uses LSF, so I might not be the best person to tackle this, but I figured I would take a look. 

The top bit of Maria's stack trace is:
<details>
<summary>(Click to expand)</summary>

```
 AGCM Date: 1997/01/31  Time: 23:40:00  Throughput(days/day)[Avg Tot Run]:  141.6  489.4  498.0  TimeRemaining(Est) 000:00:08   15.4% :  13.8% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  3.246E+04  0.000E+00
     - DO_STRAT_CHEM: Linearized strat chemistry at 1997/01/31 23:40
     - LINOZ_CHEM3: Doing LINOZ
 AGCM Date: 1997/01/31  Time: 23:50:00  Throughput(days/day)[Avg Tot Run]:  141.6   89.2   89.4  TimeRemaining(Est) 000:00:04   15.4% :  13.8% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  3.246E+04  0.000E+00
 
 Writing:   6225 Slices to File:  OutputDir/GCHP.Emissions.19970116_1200z.nc4
 Writing:      4 Slices to File:  OutputDir/GCHP.Metrics.19970116_1200z.nc4
 Writing:  20808 Slices to File:  OutputDir/GCHP.SpeciesConc.19970116_1200z.nc4
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             

Stack trace terminated abnormally.
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
gchp               0000000002E272A3  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B3DF2B33630  Unknown               Unknown  Unknown
gchp               0000000002E26E87  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B3DF2B33630  Unknown               Unknown  Unknown
srun: error: olympecomp158: task 75: Exited with exit code 174
srun: Terminating job step 621139.0
slurmstepd: error: *** STEP 621139.0 ON olympecomp72 CANCELLED AT 2021-05-28T17:23:14 ***
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
gchp               0000000002E2722E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002ADF2B548630  Unknown               Unknown  Unknown
libmpi.so.12       00002ADF2A7E2073  PMPIDI_CH3I_Progr     Unknown  Unknown
libmpi.so.12.0     00002ADF2A9482F3  Unknown               Unknown  Unknown
libmpi.so.12.0     00002ADF2AAE5CB8  Unknown               Unknown  Unknown
libmpi.so.12.0     00002ADF2AAE8026  Unknown               Unknown  Unknown
libmpi.so.12.0     00002ADF2A82717D  Unknown               Unknown  Unknown
libmpi.so.12       00002ADF2AB93467  MPI_Win_fence         Unknown  Unknown
libmpifort.so.12.  00002ADF2A22C69D  pmpi_win_fence_       Unknown  Unknown
gchp               00000000019E7EE6  Unknown               Unknown  Unknown
gchp               000000000192FB9E  Unknown               Unknown  Unknown
gchp               000000000195E256  Unknown               Unknown  Unknown
gchp               0000000001919C87  Unknown               Unknown  Unknown
gchp               00000000019EC40D  Unknown               Unknown  Unknown
gchp               000000000192AA9C  Unknown               Unknown  Unknown
gchp               000000000196CA92  Unknown               Unknown  Unknown
gchp               0000000001974E10  Unknown               Unknown  Unknown
gchp               00000000016F0530  mapl_historygridc        3570  MAPL_HistoryGridComp.F90
gchp               0000000002236759  Unknown               Unknown  Unknown
gchp               000000000223A32B  Unknown               Unknown  Unknown
gchp               0000000001E20F75  Unknown               Unknown  Unknown
gchp               0000000002237DBA  Unknown               Unknown  Unknown
gchp               00000000022D4C4D  Unknown               Unknown  Unknown
gchp               0000000001AB754F  Unknown               Unknown  Unknown
gchp               00000000013EA1C7  mapl_genericmod_m        1824  MAPL_Generic.F90
gchp               0000000002236759  Unknown               Unknown  Unknown
gchp               000000000223A32B  Unknown               Unknown  Unknown
gchp               0000000001E20F75  Unknown               Unknown  Unknown
gchp               0000000002237DBA  Unknown               Unknown  Unknown
gchp               00000000022D4C4D  Unknown               Unknown  Unknown
gchp               0000000001AB754F  Unknown               Unknown  Unknown
gchp               000000000148FADA  mapl_capgridcompm        1125  MAPL_CapGridComp.F90
gchp               000000000148F12C  mapl_capgridcompm        1012  MAPL_CapGridComp.F90
gchp               000000000148ED93  mapl_capgridcompm         732  MAPL_CapGridComp.F90
gchp               0000000002236759  Unknown               Unknown  Unknown
gchp               000000000223A32B  Unknown               Unknown  Unknown
gchp               0000000001E20F75  Unknown               Unknown  Unknown
gchp               0000000002237DBA  Unknown               Unknown  Unknown
gchp               00000000022D4C4D  Unknown               Unknown  Unknown
gchp               0000000001AB754F  Unknown               Unknown  Unknown
gchp               0000000001492393  mapl_capgridcompm         861  MAPL_CapGridComp.F90
gchp               000000000148A91F  mapl_capmod_mp_ru         323  MAPL_Cap.F90
gchp               000000000148A485  mapl_capmod_mp_ru         198  MAPL_Cap.F90
gchp               000000000148906C  mapl_capmod_mp_ru         157  MAPL_Cap.F90
gchp               000000000148874F  mapl_capmod_mp_ru         131  MAPL_Cap.F90
gchp               000000000042417D  MAIN__                     29  GCHPctm.F90
gchp               00000000004231DE  Unknown               Unknown  Unknown
libc-2.17.so       00002ADF2CC0F555  __libc_start_main     Unknown  Unknown
gchp               00000000004230E9  Unknown               Unknown  Unknown
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
gchp               0000000002E2722E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B28EA2EE630  Unknown               Unknown  Unknown
libmpi.so.12       00002B28E9588440  PMPIDI_CH3I_Progr     Unknown  Unknown
libmpi.so.12.0     00002B28E96EE2F3  Unknown               Unknown  Unknown
libmpi.so.12.0     00002B28E988BCB8  Unknown               Unknown  Unknown
libmpi.so.12.0     00002B28E988E026  Unknown               Unknown  Unknown
libmpi.so.12.0     00002B28E95CD17D  Unknown               Unknown  Unknown
libmpi.so.12       00002B28E9939467  MPI_Win_fence         Unknown  Unknown

```

</details>

The top of the trace is MAPL_HistoryGridComp.F90:3570 which is ([here](https://github.com/geoschem/MAPL/blob/a9590432be58889e4277253c7872d982980e4bb3/base/MAPL_HistoryGridComp.F90#L3570)):
```fortran
   call o_Clients%done_collective_stage()
```
which is a call to [this subroutine](https://github.com/geoschem/MAPL/blob/a9590432be58889e4277253c7872d982980e4bb3/pfio/ClientManager.F90#L332-L344):

```fortran
   subroutine done_collective_stage(this, unusable, rc)
      class (ClientManager), intent(inout) :: this
      class (KeywordEnforcer), optional, intent(out) :: unusable
      integer, optional, intent(out) :: rc


      type (ClientThread), pointer :: clientPtr
   
      clientPtr =>this%current()
      call clientPtr%done_collective_stage()


      _RETURN(_SUCCESS)
      _UNUSED_DUMMY(unusable)
   end subroutine done_collective_stage
```

This crash happened when it was writing the first month's data.

@lizziel do you have any ideas? Seems like maybe something we should bring up at the next MAPL telecon.

**Comment by lizziel** [comment]
Given the two 1-hr consecutive runs work, as does a single run 1-month run, I can only guess something is happening in the set up for monthly in the runConfig.sh script. I'll try it out with 13.0.2 to see if I can reproduce.

**Comment by WilliamDowns** [comment]
Looks like this is probably happening at the same point in MAPL where my crashes on AWS occur (see [this comment](https://github.com/GEOS-ESM/MAPL/issues/739#issuecomment-821301026) for a collection of similar stack traces). Unclear if this one is happening at the same point / for the same reason in the Win_fence call, though. 

@mtsivlidou can you put `export I_MPI_DEBUG=4` in your environment file, submit a run of any length, and post the initial part of your log file that contains something like the following (if this doesn't happen, let me know):

```
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 8  Build 20200624 (id: 4f16ad915)
[0] MPI startup(): Copyright (C) 2003-2020 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
MPI startup(): Warning: I_MPI_PMI_LIBRARY will be ignored since the hydra process manager was found
[0] MPI startup(): libfabric version: 1.10.1-impi
libfabric:6558:core:core:ofi_reg_dl_prov():578<warn> dlopen(/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib/prov/libpsmx2-fi.so): libpsm2.so.2: cannot open shared object file: No such file or directory
libfabric:6558:core:core:ofi_reg_dl_prov():578<warn> dlopen(/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib/prov/libmlx-fi.so): libucp.so.0: cannot open shared object file: No such file or directory
[0] MPI startup(): libfabric provider: efa
libfabric:32337:core:core:ofi_reg_dl_prov():578<warn> dlopen(/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib/prov/libpsmx2-fi.so): libpsm2.so.2: cannot open shared object file: No such file or directory
libfabric:32337:core:core:ofi_reg_dl_prov():578<warn> dlopen(/opt/intel/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfabric/lib/prov/libmlx-fi.so): libucp.so.0: cannot open shared object file: No such file or directory
[0] MPI startup(): Rank    Pid      Node name                 Pin cpu
[0] MPI startup(): 0       6558     compute-dy-c5n18xlarge-1  0
[0] MPI startup(): 1       32337    compute-dy-c5n18xlarge-2  0
```

If we can't reproduce the crash on our system, you could try enabling the external output server as a temporary solution (I'll wait to describe how until we see what happens with this run setup on our cluster).

**Comment by WilliamDowns** [comment]
Also, what resolution are you running at? In my AWS Intel MPI setup, I found that at c90 or higher with no external output server I need to use >216 cores or else I encounter a crash like this, with the important caveat that when using >216 cores in that setup I get an infinite hang at output time instead of a crash. Nevertheless, increasing core counts could be something else to try if we can't reproduce your issue.

**Comment by lizziel** [comment]
I tried a C24 multi-run with monthly diagnostics set in runConfig.sh using 13.0.2 and transport tracer simulation. I did not run into any problems, but I also am not using Intel MPI.

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for your answers. 
I use c48 with 144 cores and 6 nodes (24 cores per node). Do you think this might be related to the problem?
I will send you the log file as soon as the job has completed.

Do you think I should switch to openmpi instead of intelmpi?
Thank you 
Maria

**Comment by WilliamDowns** [comment]
Feel free to post the log file before the run has completed; the bit I'm interested in occurs before hour 0 of the run. 

If you have OpenMPI available, definitely try out building and running GCHP with it instead of Intel MPI. I've found it to be less prone to crashes like this one in my testing.

**Comment by mtsivlidou** [comment]
Please find attached the log file for one-hour simulation. 
[ghcp.log.txt](https://github.com/geoschem/GCHP/files/6586937/ghcp.log.txt)

**Comment by WilliamDowns** [comment]
I'll try to replicate your environment + run setup as best I can on my cluster and report back what happens. In the meantime, feel free to try OpenMPI and see if that avoids the issue.

**Comment by WilliamDowns** [comment]
I recreated your run setup and tried to follow your library setup, but I was unable to pass the first few minutes of a simulation using Intel Compilers 2021.2 + Intel MPI 2019.10 or 2018.2. I was able to run successfully using Intel MPI 2019.10 + GNU Compiler Collection 9.3.0. Are you able to try using OpenMPI (at least 3.0, preferably >=4.0) or GNU compilers >= 8.3? OpenMPI in particular would be your best bet.

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for your answer. 
What do you mean that you were unable to pass the first few minutes of the simulation? For my case, 1-hour simulation and 1-month simulation was wokring with this run setup. The problem was when I was trying to use multirun option for 2 jobs of 1 month each. Only for the multirun, it crashed before writing the output of the first job. 
Also, with  Intel MPI 2019.10 + GNU Compiler Collection 9.3.0, what kind of simulation was successful (single or with multirun option)? 
I am working on it. I compiled again with intel/18.2 and openmpi/icc/3.0.2. I will let you know when the job has finished.
Thank you again. 
Maria

**Comment by WilliamDowns** [comment]
I encountered errors when reading initial input files when using IMPI 2018.2 + Intel 2021 compilers, and errors in the first dry deposition stage of the run when using IMPI 2019.10 + 2021 compilers. I'm not sure why, as 2019.10 + 2021 compilers has worked for me on other systems in the past. For IMPI 2019.10 + GNU 9.3, I used the same multirun setup + monthly diagnostics setup you're using and completed the first month successfully (other month is still running).

**Comment by mtsivlidou** [comment]
Hello, 
When I compile with intel/18.2 and openmpi/3.0.2, the output is written for both months. 
Maria

**Comment by mtsivlidou** [comment]
Hello, 
As I told you my monthly simulations with multi-run option seems to work. In runconfig I used: 
Start_Time="19970101 000000"
End_Time="19970301 000000"
Duration="00000100 000000"
Num_Runs=2
Monthly_Diag=1 

The diagnostics are:
GCHP.SpeciesConc.19970116_1200z.nc4
GCHP.SpeciesConc.19970215_0000z.nc4

I was expecting the diagnostics to be for the same date of the month/same utc time. I would like to kindly ask you why there is this difference between the months. 
Thank you, 
Maria

**Comment by lizziel** [comment]
Hi Maria,

The date in the time-averaged diagnostic filenames for all GCHP versions prior to 13.1 are the _mid-point_ of the averaging time. Since January and February have different number of days the timestamp in the filename is different. However, both represent the average for the full month.

Starting in 13.1, which is about to be released, the filename format matches that of GEOS-Chem Classic, namely it will show the _start time_ rather than mid-point of the time-averaging field. This will be less confusing and much easier to program post-processing scripts.

**Comment by mtsivlidou** [comment]
Thank you for the clarification.
Maria
