### ISSUE TITLE
[BUG/ISSUE] ExtData debug logging not working in dev branch

### ISSUE THREAD

**Issue by TerribleNews** [geoschem/GCHP#107]
### Description of the problem
My fresh dev branch run directory and binary are crashing on what looks like a missing input file, so I tried to turn on ExtData debug logging to find out what file it is. But when I follow the instructions in runConfig.sh, it doesn't add any debug output. 

### GEOS-Chem version
Git commit 2a495bc

### Description of code modifications
Added `Turn on debug printout? : T` to `input.geos`
Added debug to root_level of CAP.EXTDATA in logging.yml:
```
   CAP.EXTDATA:
       handlers: [mpi_shared]
       level: WARNING
       root_level: DEBUG
       propagate: false

```

### Log files
```
...
onc_CH2O SpeciesConc_CH2ICl SpeciesConc_CH2IBr SpeciesConc_CH2I2 SpeciesConc_CH2Cl2 SpeciesConc_CH2Br2 SpeciesConc_CFC12 SpeciesConc_CFC115 SpeciesConc_CFC114 SpeciesConc_CFC113 SpeciesConc_CFC11 SpeciesConc_CCl4 SpeciesConc_C3H8 SpeciesConc_C2H6 SpeciesConc_BrSALC SpeciesConc_BrSALA SpeciesConc_BrO SpeciesConc_BrNO3 SpeciesConc_BrNO2 SpeciesConc_BrCl SpeciesConc_Br2 SpeciesConc_Br SpeciesConc_BENZ SpeciesConc_BCPO SpeciesConc_BCPI SpeciesConc_ATOOH SpeciesConc_ALK4 SpeciesConc_ALD2 SpeciesConc_AERI SpeciesConc_ACTA SpeciesConc_ACET


                                                             Mem/Swap Used (MB) at HISTMAPL_GenericInitialize=  1.498E+04  0.000E+00
                                                          Mem/Swap Used (MB) at EXTDATAMAPL_GenericInitialize=  1.500E+04  0.000E+00
pe=00002 FAIL at line=00258    NetCDF4_FileFormatter.F90                <status=2>
pe=00002 FAIL at line=00090    MAPL_ExtDataCollection.F90               <status=2>
pe=00002 FAIL at line=00256    FileMetadata.F90                         <can not find time>
pe=00002 FAIL at line=00286    FileMetadataUtilities.F90                <status=1>
pe=00002 FAIL at line=01033    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00008 FAIL at line=00258    NetCDF4_FileFormatter.F90                <status=2>
pe=00008 FAIL at line=00090    MAPL_ExtDataCollection.F90               <status=2>
pe=00008 FAIL at line=00256    FileMetadata.F90                         <can not find time>
pe=00008 FAIL at line=00286    FileMetadataUtilities.F90                <status=1>
pe=00008 FAIL at line=01033    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00008 FAIL at line=01839    MAPL_Generic.F90                         <needs informative message>
pe=00002 FAIL at line=01839    MAPL_Generic.F90                         <needs informative message>
pe=00002 FAIL at line=00766    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=00621    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=00908    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=00245    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00154    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00766    MAPL_CapGridComp.F90                     <status=1>
pe=00008 FAIL at line=00621    MAPL_CapGridComp.F90                     <status=1>
pe=00008 FAIL at line=00908    MAPL_CapGridComp.F90                     <status=1>
pe=00008 FAIL at line=00245    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
pe=00008 FAIL at line=00154    MAPL_Cap.F90                             <status=1>
...
```

### Software versions
Intel 2020
netcdf 4.4
mpi-sgi

**Comment by WilliamDowns** [comment]
Disregarding the issue with the debugging output, I ran into the same error message in the past month. I'm not 100% sure, but I think it occurred when I changed GCHP versions from 13.0.0 to 13.0.1, and I think it ended up being due to missing the DUST_DEAD files because online dust emissions became default in that version.

**Comment by TerribleNews** [comment]
Thanks for the tip. I tried manually syncing my `HEMCO/DUST_DEAD` folder to harvard and unfortunately it still crashes in the same way.

**Comment by lizziel** [comment]
It looks like I neglected to add the very important information that the prints are sent to new file allPEs.log. Do you see that file and does it include any useful information? I will update the docs to include this info,.

**Comment by TerribleNews** [comment]
Ah, yes! That file is indeed there and the last line of it is a file that I don't have. 😁 Thank you! 

Edit: I noticed the `cleanRunDir.sh` script doesn't appear to remove this file.

**Comment by gopikrishnangs44** [comment]
[](url)I am also facing a similar issue on GCHP 13.4.0 

The last few lines of all_PES.log are:
0000: MAPL.GENERIC: INFO: Started the  'Run' stage of the gridded component 'GCHPctmEnv'
0000: MAPL.GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHPctmEnv'
0000: MAPL.GENERIC: INFO: Started the  'Run' stage of the gridded component 'DYNAMICS'
0000: MAPL.GENERIC: INFO: Finished the 'Run' stage of the gridded component 'DYNAMICS'
0000: MAPL.GENERIC: INFO: Started the  'Run' stage of the gridded component 'GCHPchem'
0000: MAPL.GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHPchem'
0000: MAPL.GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHP'
0000: MAPL.GENERIC: INFO: Started the  'Run' stage of the gridded component 'HIST'
0000: MAPL.GENERIC: INFO: Finished the 'Run' stage of the gridded component 'HIST'
0000: MAPL.GENERIC: INFO: Started the  'Run' stage of the gridded component 'EXTDATA'



I am also attaching my run log.
[slurm-954598.out.txt](https://github.com/geoschem/GCHP/files/9862723/slurm-954598.out.txt)
