### ISSUE TITLE
[BUG/ISSUE] GCHP v 13.0.2 crashes after some calculations of second job in multirun option

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#116]
### Description of the problem
I use GCHP v 13.0.2 with multirun option. For example, for simuation period 19970701-19970901, I split it in 2 jobs. 
When the second jobs is starting, after some calculation, it is crashing.
In slurm-655291.out, Error message says first :
forrtl: severe (174): SIGSEGV, segmentation fault occurred

It occurs in an MPI communication, called form :
gchp               0000000000C27845  fv_tracer2d_mod_m        1120  fv_tracer2d.F90
gchp               0000000000C2B52F  fv_tracer2d_mod_m        1048  fv_tracer2d.F90
gchp               000000000090B1BA  advcore_gridcompm         840  AdvCore_GridCompMod.F90

When I restart the simualtion from 19970801-19971001, the first month runs without any problem and the same error occurs in the second job. 
I tried multirun option splitting 3-hour simualtion in 3 jobs and all the jobs are successfull. 

I have already contacted the support team of the cluster I am working and there is no issue in the hardware or software of the cluster, they believe Error that occur in MPI communication might be a side effect coming from the calling function (in fv_tracer2d.F90 ?). Also, it looks like (2nd job 655291) memory needs per task are far underneath the limit of 5 GB per task/process. 

I would appreciate if you could help me with this issue. 
Thank you in advance.
Maria

### GEOS-Chem version
GCHP v13.0.2

### Description of code modifications
No modifications.

### Log files
- Build log (if applicable):  [CMakeOutput.log.txt](https://github.com/geoschem/GCHP/files/6822130/CMakeOutput.log.txt)

- Run log (if applicable):  [slurm-655291.out.txt](https://github.com/geoschem/GCHP/files/6822163/slurm-655291.out.txt)

- Run script (if applicable):  
- 1st job: [slurm-655290.out.txt](https://github.com/geoschem/GCHP/files/6822227/slurm-655290.out.txt)

-2nd job: [gchp.multirun.sh.txt](https://github.com/geoschem/GCHP/files/6822169/gchp.multirun.sh.txt)

[gchp.multirun.run.txt](https://github.com/geoschem/GCHP/files/6822167/gchp.multirun.run.txt)

[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/6822181/runConfig.sh.txt)

### Software versions
- Compilers (Intel or GNU, and version): intel/18.2
- NetCDF version: netcdf/4.7.3-openmpi
- MPI version:  openmpi/icc/3.0.2
- ESMF version: 8.0.1
- cmake/3.13.0
- hdf5/1.10.2-openmpi

###

**Comment by lizziel** [comment]
Hi Maria, usually an MPI issue in the middle of a long run is related to a system problem or the underlying MPI library. We are using GCHP 13 with OpenMPI 4 and ifort19+ / gfortran 8.3+. Would you be able to switch to one of these combinations?
 
I also recommend upgrading to GCHP 13.1. That version has more recent versions of MAPL and FV libraries. I am not sure if this will solve your issue (as I said, sudden mid-run MPI failures are generally due to system issues) but it is worth a shot. Also, 13.1 has monthly diagnostics so you will not need to split up runs into monthly segments to get monthly averages.

**Comment by mtsivlidou** [comment]
But is it possible to change the resolution of the met files while creating a run dir?
I use MERRA2 files, but instead of the native resolution I was trying to switch to 2x2.5. Thats why I was using the change_met.sh:
#!/bin/bash
if [[ $# -ne 1 ]]; then
echo "Must provide path to either GEOS_2x2.5/MERRA2 or GEOS_2x2.5/GEOSFP"
exit 70
fi
if [[ -L MetDir ]]; then unlink MetDir; fi
 For MERRA-2
sed -i "s/05x0625\.nc/2x25.nc/g" ExtData.rc
ln -s $1 MetDir
exit 0

**Comment by lizziel** [comment]
Ah, I see what you are doing now. Sorry for the confusion. I will follow-up on the thread for issue https://github.com/geoschem/GCHP/issues/114 which is where this came up.

**Comment by mtsivlidou** [comment]
Is there any way to install 13.1 with spack? Or I have to install only the dependencies with spack and then compile the code manually?

**Comment by lizziel** [comment]
13.1 is not yet available on Spack, but this should not be a problem. Typically GCHP is cloned and Spack is used only to build and install dependencies. The dependencies can then be loaded in an environment file prior to compiling and building GCHP. This allows easily switching between GCHP versions while using the same set of dependencies. It also allows easy use of the same GCHP code with different sets of libraries built with Spack, e.g. using different compilers/MPI.

**Comment by mtsivlidou** [comment]
I cloned GCHP with git clone https://github.com/geoschem/GCHP.git ~/GCHP
but    git checkout 13.1gives me an error:                     
error: pathspec '13.1' did not match any file(s) known to git
Thank you for your time!

**Comment by lizziel** [comment]
Hi @mtsivlidou, were you able to install new libraries and get GCHP working?

**Comment by mtsivlidou** [comment]
Hello, 
No, I am still trying to find the right libraries  to make it work. 
I am on vacations for the next 2 weeks. I will keep you updated about my progress when I am back.
Thank you,
Maria

**Comment by mtsivlidou** [comment]
Hello, 
I tried several combinations of the available libraries, but the compilation was not successful. 
The problem was related to compability issues of the netcdf library, so I asked the support team to install gchp dependencies for me. 
The versions I asked was in accordance to #80 :
- gcc/gfortran 9.3.0
- OpenMPI 4.0.2
- netCDF-Fortran 4.5.2
- netCDF-C 4.7.3
- HDF5 1.10.6

Could you please confirm that these libraries/versions are efficient for long-term runs of v13?
Thank you in advance, 
Maria

**Comment by lizziel** [comment]
Hi Maria,
Those library versions should be fine for GCHP 13. For future reference you can find the required library list at [https://gchp.readthedocs.io/en/latest/getting-started/requirements.html](https://gchp.readthedocs.io/en/latest/getting-started/requirements.html).

**Comment by mtsivlidou** [comment]
Hello, 
Yes I am aware of this library list, however the version of netcdf is not specifed. This is why I asked for confirmation. Thank you!

**Comment by LiamBindle** [comment]
Hi Maria, I think those library versions should be okay. For GCHP the most important version requiremetns are compiler version numbers, and MPI version numbers. IIRC I didn't specify NetCDF version requirements because I believe GCHP should be compatible with all the versions that are still available (even back before NetCDF-C and NetCDF-Fortran were split into their own packages).

It's difficult to say what MPI verions will be performant because it's platform specific and very complicated. In general, I think the best advise we can give is to use the latest MPI and compiler versions that you can.

**Comment by lizziel** [comment]
Hi @mtsivlidou, I will close this out now. If you have additional GCHP questions please open a new issue.
