### ISSUE TITLE
[BUG/ISSUE] GCHP simulations with >1000 cores crash on Pleiades 

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#117]
### Description of the problem
On Pleiades GCHP simulations with >1000 cores crash. 

More info can be found here: https://github.com/GEOS-ESM/MAPL/issues/911

### GEOS-Chem version
13.0 but also affects 13.1

### Description of code modifications
n/a

### Log files
- Build log (if applicable):
- Run log (if applicable):
- Run script (if applicable):

### Software versions
- Compilers (Intel or GNU, and version): GNU and Intel
- NetCDF version: n/a
- MPI version: MPT
- ESMF version: n/a

**Comment by LiamBindle** [comment]
The culprit is the section of `runConfig.sh` that automatically sets `WRITE_RESTART_BY_OSERVER` to `YES` if the core count is >1000. Setting `WRITE_RESTART_BY_OSERVER: NO` seems to fix the issue and I was able to run a 2400 core simulation ok.

Side note: I saw pretty decent performance on 2400 cores. I was getting 70day/day at C180.

Related issues:
* https://github.com/GEOS-ESM/MAPL/issues/548

**Comment by LiamBindle** [comment]
I'm reading about `WRITE_RESTART_BY_OSERVER` to better understand what it does and how we should fix this.

**Comment by LiamBindle** [comment]
I confirmed that `WRITE_RESTART_BY_OSERVER: NO` works for both Intel and GNU compilers.

Unrelated note: C180 on 1152 cores is 10% faster with GNU than Intel on Pleiades.

**Comment by lizziel** [comment]
I think the `WRITE_RESTART_BY_OSERVER` should only be set to `YES` if using OpenMPI, although I did not implement it this way in `runConfig.sh`. See also https://github.com/GEOS-ESM/MAPL/issues/548.

**Comment by lizziel** [comment]
I also noticed that if you run with >1000 cores then `WRITE_RESTART_BY_OSERVER` is always set to `YES` but not set to `NO` if you subsequently use fewer than 1000 cores. I think `runConfig.sh` needs some work with regards to the automatic setting of this in `GCHP.rc`.

**Comment by lizziel** [comment]
I think any bug fix for this can go into the next Z version.

**Comment by lizziel** [comment]
This bug fell by the wayside and has not had a fix go in yet. @LiamBindle, based on your experiences with high core counts do you have a recommendation for ideal behavior in `runConfig.sh` to auto-set `GCHP.rc` setting `WRITE_RESTART_BY_OSERVER` based on core count?

**Comment by LiamBindle** [comment]
@lizziel Sorry this slipped my mind. No, I don't have a good handle on it. I think your suggestion to turn it on iff OpenMPI and >1000 cores is the best recommendation we can make right now.

**Comment by lizziel** [comment]
Okay, that's easy then since that's the current behavior. I just need to make the update to explicitly set it to off if < 1000.

**Comment by lizziel** [comment]
@LiamBindle, could we close out this issue?

**Comment by LiamBindle** [comment]
This should be mostly fixed by https://github.com/geoschem/geos-chem/pull/835. We might want to keep an eye on this though if we get reports of simulations crashing at start up for high core counts.
