### ISSUE TITLE
[FEATURE REQUEST] Rebuild minimum file set with ifort like currently done in gfortran

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#12]
Changing a line in MAPL_ExtDataGridComp.F90 results in recompiling all of MAPL_Base and FVdycore when rebuilding with ifort. Only MAPL_ExtDataGridComp.F90 is rebuilt, however, when building gfortran. This makes developing and debugging with gfortran superior to ifort. It would be great if we could eventually have the same functionality with ifort as well.

**Comment by LiamBindle** [comment]
This is would be a Make---Intel compiler bug. I think it will be highly specific to versions of both, and ultimately, it's outside of our control. A work around would be using a different version of Make and/or Intel compilers, and the solution would be opening an issue with Intel or the GNU project. Is it okay if I close this?

**Comment by lizziel** [comment]
@LiamBindle, do you know of any Intel or Make versions for which this is not an issue? Also, is this behavior documented anywhere in our documentation for compiling? Let's leave this open for now to get answers to these questions.

**Comment by LiamBindle** [comment]
@lizziel I'm not sure, but I can confirm that it affects ours too (Intel 2020, 2021) with GNUMake and Ninja build systems. It must not be Intel--Make version bug then, but `ifort` in general as you suggested. I've seen a couple references to it on the internet:
- https://gitlab.kitware.com/cmake/cmake/-/issues/17524
- https://aoterodelaroza.github.io/devnotes/modern-fortran-makefiles/
- http://fortranwiki.org/fortran/show/Submodules
- https://stackoverflow.com/questions/27984529/clean-way-to-separate-functions-subroutine-declaration-from-definition-in-fortra

It sounds like the term for this is "_fortran compilation cascade_".

According to this comment https://gcc.gnu.org/bugzilla/show_bug.cgi?id=42607#c4, it sounds gfortran considers their handling of this a feature of their compiler.

Maybe @mathomp4 knows? Are you familiar with this and if we can do anything to mitigate these recompile cascades with `ifort`?

**Comment by LiamBindle** [comment]
I added a note about this here: https://gchp.readthedocs.io/en/latest/user-guide/compiling.html#recompiling

**Comment by mathomp4** [comment]
@lizziel @LiamBindle My experience with this (maybe @tclune has more to say) is that Intel can at times be good, and at other times not be. 

For example, today I am trying to fix something in MAPL. I don't know what I'm doing, so I'm recompiling a lot and I'm finding that Intel (19.1.3) is being "good". I edit `MAPL_CubedSphereGridFactory.F90` and all the compiler does is relink:
```console
$ make -j10 install
[  0%] Built target NCEP_sigio
[  0%] Built target NCEP_bacio_r4i4
[  0%] Built target link_target
[  0%] Built target NCEP_bacio_r8i4
...
Scanning dependencies of target MAPL.base
[ 52%] Built target ec2fv.x
[ 52%] Built target ss2fv.x
[ 56%] Built target mom
[ 65%] Built target mom6
[ 65%] Building Fortran object src/Shared/@MAPL/base/CMakeFiles/MAPL.base.dir/MAPL_CubedSphereGridFactory.F90.o
[ 65%] Linking Fortran shared library ../../../../lib/libMAPL.base.so
[ 68%] Built target MAPL.base
[ 68%] Linking Fortran executable ../../../../bin/Regrid_Util.x
...
```

Sometimes I get the compilation cascade and sometimes I don't. It does seem to happen more with Intel than GNU, yes. I think in the past Intel did things like embed timestamps in mod files but I'm not seeing that now:
```console
$ hexyl mapl_cubedspheregridfactorymod.mod | head -20
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 0c 00 01 00 f6 b2 0e 00 ┊ b4 24 00 00 6b 38 32 30 │_0•0××•0┊×$00k820│
│00000010│ 33 30 39 00 0b 00 00 00 ┊ 77 06 00 00 00 00 00 00 │3090•000┊w•000000│
│00000020│ 00 00 00 00 31 39 2e 31 ┊ 00 00 00 00 00 00 00 00 │000019.1┊00000000│
│00000030│ fd f9 33 60 00 00 00 00 ┊ 0b 00 00 00 00 00 00 00 │××3`0000┊•0000000│
│00000040│ 01 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │•0000000┊00000000│
│00000050│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│00000060│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│00000070│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│00000080│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│00000090│ 00 00 00 00 00 00 00 00 ┊ 00 00 00 00 00 00 00 00 │00000000┊00000000│
│000000a0│ 0a 00 00 00 00 00 00 00 ┊ 2f 64 69 73 63 6f 76 65 │_0000000┊/discove│
│000000b0│ 72 2f 73 77 64 65 76 2f ┊ 6d 61 74 68 6f 6d 70 34 │r/swdev/┊mathomp4│
│000000c0│ 2f 4d 6f 64 65 6c 73 2f ┊ 47 45 4f 53 67 63 6d 2d │/Models/┊GEOSgcm-│
```

Now maybe this might be ameliorated with use of submodules in MAPL? I know I've experimented with submodules in GEOS' Moist GC which is a terror to build with Intel (5+ minutes). But with submodules, it can often "skip" that build.

**Comment by tclune** [comment]
submodules had better prevent that cascade.  That is the primary reason they were added to the language.

**Comment by lizziel** [comment]
To be clear, you are talking about Fortran submodules not git submodules. We haven't used, or even talked about, Fortran submodules in GEOS-Chem, but do use git submodules, so it's easy to get confused.

I'm happy to declare this as something beyond our scope and close this issue. I think the note on ReadTheDocs is sufficient. We can just keep an eye out for if this issue disappears at some point due to either changes in compiler or in MAPL.

**Comment by mathomp4** [comment]
> To be clear, you are talking about Fortran submodules not git submodules. We haven't used, or even talked about, Fortran submodules in GEOS-Chem, but do use git submodules, so it's easy to get confused.

Yes. Fortran submodules in this case.

**Comment by LiamBindle** [comment]
Sounds good to me. Thanks for raising this @lizziel.  Thanks @mathomp4 and @tclune for your insights.
