### ISSUE TITLE
[BUG/ISSUE] Build errors when specifying BUILD_TYPE

### ISSUE THREAD

**Issue by kilicomu** [geoschem/GCHP#123]
### Description of the problem
With intel compilers, configuring and building with build types other than the default, specifically:

* `CMAKE_BUILD_TYPE=Release`
* `CMAKE_BUILD_TYPE=Debug`

results in build errors complaining about their being no input files. With GNU compilers, configuring and building with build type `Release` results in similar build errors, but `Debug` does not.

Example errors can be found in the attached log files.

### GEOS-Chem version
GCHP 13.1.2

### Description of code modifications
None.

### Log files
- Build log (if applicable): [intel_build_type_errors.log](https://github.com/geoschem/GCHP/files/6925072/intel_build_type_errors.log), [gfortran_build_type_errors.log](https://github.com/geoschem/GCHP/files/6925077/gfortran_build_type_errors.log)

- Run log (if applicable): N/A
- Run script (if applicable): N/A

### Software versions
- Compilers (Intel or GNU, and version): Intel Fortran 19.0.5.281 / gfortran 9.3.0
- NetCDF version: netCDF-C 4.7.4, netCDF-C++ 4.3.1 netCDF-Fortran 4.5.2
- MPI version: Intel MPI v2018 update 5 build 20190404 / OpenMPI 4.0.3
- ESMF version: 8.0.1

**Comment by lizziel** [comment]
What is the status of this issue? If it does not impact benchmarks we could still get it into 13.3...

**Comment by lizziel** [comment]
If we can't get the fix for this in 13.4 I think we should definitely prioritize for 14.0. @LiamBindle, do you think it could go into 13.4?

**Comment by LiamBindle** [comment]
Fixed in #191. I'll close this when #191 is merged. Debug, Release, and DebugWithReleaseInfo should work.

**Comment by LiamBindle** [comment]
Note that the MAPL 2.16 upgrade is postponed until 14.0. I confirmed that BUILD_TYPE works with those updates.
