### ISSUE TITLE
[BUG/ISSUE] netcdf compilation error 

### ISSUE THREAD

**Issue by cbutenhoff** [geoschem/GCHP#125]
### Description of the problem
Describe your problem problem here.
While compiling GCHP I run into this error message:

  _27 |       use netcdf
      |          1
Fatal Error: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated._

although my netcdf-fortran libraries were built with the same compiler (GNU 9.2.0) I'm using for the GCHP build. 

### GEOS-Chem version
Enter your GEOS-Chem version here.
GCHP v13.1.2

### Description of code modifications
Describe your code modifications here.
None

### Log files
- Build log (if applicable):
- Run log (if applicable):
- Run script (if applicable):
- CMakeCache,txt
[CMakeCache.txt](https://github.com/geoschem/GCHP/files/6964079/CMakeCache.txt)

### Software versions
- Compilers (Intel or GNU, and version): GNU 9.2.0
- NetCDF version: netcdf-4.8.0, netcdf-fortran-4.5.3
- MPI version: openmpi-3.0
- ESMF version: ESMF-8.1.1.

**Comment by LiamBindle** [comment]
@cbutenhoff That's very strange. It look like it's using `/vol/apps/hpc/stow/netcdf-fortran/4.5.3/gcc-9.2.0/include/netcdf.mod`, which based on the path name looks like it should be okay. Is it possible netcdf-fortran was accidentally compiled with a different gfortran?

One thing to try would be checking the gfortran module version for that file. On my system `netcdf.mod` is `/opt/gcc-8/netcdf-fortran-4.5.2/include/netcdf.mod` so I would do

```console
$ cat /opt/gcc-8/netcdf-fortran-4.5.2/include/netcdf.mod | gunzip | head -1
GFORTRAN module version '15' created from netcdf4.f90
``` 

Compare that against any module file in your build directory (any file listed by `find -name '*.mod'`). For example:

```console
$ cat ./src/yaFyaml/include/fy_abstractfile.mod | gunzip | head -1
GFORTRAN module version '15' created from netcdf4.f90
```

Do they match?

**Comment by yantosca** [comment]
@cbutenhoff: Did you use Spack to download the geoschem-gchp dependencies?  It may be that if you have netCDF built for GEOS-Chem "Classic" that this will not work for GCHP.  

See: https://gchp.readthedocs.io/en/latest/supplement/spack.html

**Comment by cbutenhoff** [comment]
Hi Liam,

Thanks for your reply.  In fact they don't match:

    $ more /vol/apps/hpc/stow/netcdf-fortran/4.5.3/gcc-9.2.0/include/netcdf.mod
    GFORTRAN module version '10' created from netcdf.f90

    $ pwd
     /home/cbuten/GCHP/v13.1.2/Code.GCHP/build/src/yaFyaml/include 
    $ cat fy_abstractfile.mod | gunzip | head -1
    GFORTRAN module version '15' created from AbstractFile.F90

Does this mean they were not built with the same gfortran version?

**Comment by cbutenhoff** [comment]
The sysadmin built the dependencies and I don't believe she used Spack.

**Comment by LiamBindle** [comment]
Great! Yeah, that means NetCDF-Fortran was built with a different version of gfortran. Likely what happened is there are multiple `gfortran` versions installed, and the NetCDF-Fortran build system picked up the wrong on by accident.

Recompiling NetCDF-Fortran should fix th problem.

Let me know if you run into any more problems.
