### ISSUE TITLE
[QUESTION] run gchp, error in mpp_domains_define.inc

### ISSUE THREAD

**Issue by clearsky112** [geoschem/GCHP#126]
# Ask a question about GCHP:

Hi,
   I am a new user for GCHP. I run the issue as below:
FATAL from PE     7: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
FATAL from PE    15: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
FATAL from PE    19: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
FATAL from PE    21: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
FATAL from PE    22: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic

My submission script is shown as below:

_#!/bin/bash                                                                                                            
#                                                                                                                      
#SBATCH -J GCHP                                                                                                        
#SBATCH -n 30                                                                                                          
#SBATCH -p RAQM                                                                                                        
#SBATCH --exclusive             # Total number of mpi tasks requested                                                  
#SBATCH --export=ALL     

module purge
module load intelpython3
module load cmake/3.15.4
module load wrf
module load prun/1.3
module load intel/19.1.3.304
module load openmpi3/3.1.4
module load ohpc
ulimit -s unlimited           

rm -f cap_restart gcchem*                        # delete checkpoint/restart spec/data                                 
./runConfig.sh                                   # update configuration files                                          
time prun ./gchp 2>&1 | tee GC.log_

Can you help me resolve the issue? Thanks.

**Comment by LiamBindle** [comment]
Hi @clearsky112, this error:
```
FATAL from PE XX: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
```
means the number of MPI processes in the launch command (`prun`) doesn't match the number of MPI processes in the config files. For example, if you set `TOTAL_CORES=24; NUM_NODES=1; NUM_CORES_PER_NODE=24` in runConfig.sh but launch 6 mpi processes with something like `mpirun -np 6 ./gchp` then you get this error.

I'm not familiar with `prun` but it looks like it's similar to `mpirun`. If that's the case, I think you might want to do `prun -np 30 ./gchp` (assuming TOTAL_CORES=30, NUM_NODES=1, and NUM_CORES_PER_NODE=30 in runConfig.sh). Could you give that a try?

**Comment by clearsky112** [comment]
> Hi @clearsky112, this error:
> 
> ```
> FATAL from PE XX: mpp_domains_define.inc: At least one pe in pelist is not used by any tile in the mosaic
> ```
> 
> means the number of MPI processes in the launch command (`prun`) doesn't match the number of MPI processes in the config files. For example, if you set `TOTAL_CORES=24; NUM_NODES=1; NUM_CORES_PER_NODE=24` in runConfig.sh but launch 6 mpi processes with something like `mpirun -np 6 ./gchp` then you get this error.
> 
> I'm not familiar with `prun` but it looks like it's similar to `mpirun`. If that's the case, I think you might want to do `prun -np 30 ./gchp` (assuming TOTAL_CORES=30, NUM_NODES=1, and NUM_CORES_PER_NODE=30 in runConfig.sh). Could you give that a try?

Thank you so much. I tried and it works now. I forgot to edit runConfig.sh.

**Comment by LiamBindle** [comment]
Great! No problem!
