### ISSUE TITLE
[QUESTION] Plotting GCHP Output

### ISSUE THREAD

**Issue by chen-yuy** [geoschem/GCHP#128]
Hello,
I use GCHP 13.0.2. with setting shows in the following runConfig.sh.txt.
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/6996762/runConfig.sh.txt)
After a 1-year spin-up, I wanna plot the result from output files, however, the result shown in Panoply seems wrong, the resolution of the Xaxis and Yaxis is not related to 4x5 degrees at C24 resolution. Should I turn on the 'stretch' in runConfig.sh file? 
![image](https://user-images.githubusercontent.com/57124663/129657473-ae88f7ba-547f-4947-ac2f-59d798bef3a3.png)

I also append one of my output NetCDF files in a Onedrive shared file (GCHP.SpeciesConc.20180101_0200z.zip)

Thank you for your concern!

**Comment by yantosca** [comment]
Thanks for writing @chen-yuy.  You should use [GCPy](https://gcpy.readthedocs.io) to plot GCHP output instead of Panoply.  The Panoply program cannot handle cubed-sphere visualizations, whereas GCPy can.

**Comment by yantosca** [comment]
Actually my colleague @lizziel tells me that Panoply can plot cubed sphere output for GCHP diagnostics, just not GCHP restart files. GMAO made an update the output file format in one of the MAPL versions that went into a mid-12 GCHP versions, maybe 12.5?

**Comment by lizziel** [comment]
Hi @chen-yuy, have you inspected output files from a short GCHP run to check that they look okay? This would test if your plotting method is working as you expect it. The problem may be plotting, or it may be that the output of 1-year run is not correct.

The stretch option in `runConfig.sh` is for running GCHP using a stretched grid, a way of making a regional area of the globe high resolution. I don't think that is what you are aiming to do here. What do you mean by the X and Y axes not related to 4x5? Do you think the resolution of your data is finer than C24? Could you provide a link to the data file if it publicly accessible?

**Comment by LiamBindle** [comment]
@chen-yuy This is caused by that "Interpolate" check box. If you uncheck that it should work as expected.

**Comment by chen-yuy** [comment]
https://1drv.ms/u/s!Am52oPIhDTrUrzS09EjcSi-59bn7?e=yhPzm5
This is a shared Onedrive file contains one output file, could you download and check it?

By the way, I didn't check the "interpolate" part, I think it should work.

**Comment by chen-yuy** [comment]
And this is my plot code with its result by python. Hope this helps.
[plot_test.zip](https://github.com/geoschem/GCHP/files/7004009/plot_test.zip)

**Comment by LiamBindle** [comment]
Sorry, I meant this check box here
![image](https://user-images.githubusercontent.com/12772306/129828754-77aca7bd-1e31-45a8-bc01-c47d2a70f61e.png)
Panoply turns this on by default but the itnerpolation is undefined at the cubed-sphere edges. If you uncheck this does it fix it?

**Comment by chen-yuy** [comment]
> Sorry, I meant this check box here
> ![image](https://user-images.githubusercontent.com/12772306/129828754-77aca7bd-1e31-45a8-bc01-c47d2a70f61e.png)
> Panoply turns this on by default but the interpolation is undefined at the cubed-sphere edges. If you uncheck this does it fix it?

Yeeeees! It works! :)
Now I want to know how can I reproduce this figure in Python code?
Could you please check my code and result in the report above, and give me some advice? And I have another question related, how can I get one day average from each 4-hours output data, in the report I just do the mathematical addition?

**Comment by chen-yuy** [comment]
> Sorry, I meant this check box here
> ![image](https://user-images.githubusercontent.com/12772306/129828754-77aca7bd-1e31-45a8-bc01-c47d2a70f61e.png)
> Panoply turns this on by default but the interpolation is undefined at the cubed-sphere edges. If you uncheck this does it fix it?

yeeeees! It works :)
Now I want to know how can I reproduce this figure in Python code?
Could you check my code in the report above? And I have another question related, how can I get one day average from each 4-hours output data, should I just calculate the average or do the mathematical addition?

**Comment by chen-yuy** [comment]
![image](https://user-images.githubusercontent.com/57124663/129997982-97836d67-f88b-4bc0-aa8f-fd2143b3600f.png)
I found that when set (nf=3) shown below the screenshot picture, the _matplotlib.pyplot.pcolormesh_ in Python didn't work as I expected.

**Comment by LiamBindle** [comment]
@chen-yuy Sorry for the slow response. This is a know bug with cartopy 0.18 (see https://github.com/SciTools/cartopy/pull/1622). Upgrading to cartopy 0.19 should fix the horizontal streaking.

Note that the whitespace between faces is caused by using grid-box centers (rather than edges) in `pcolormesh()`. If you use grid-box edge coordinates those gaps should go away. You can add these edges to you dataset with `python -m gcpy.append_grid_corners filename.nc`, or if you upgrade to GCHP v13.1 they are now included by default. 


This might be a helpful reference in terms of plotting data: https://gchp.readthedocs.io/en/latest/tutorials/stretched-grid.html#plot-the-output. Let me know if you have any troubles. If you could share code snippets in the thread rather than attached file, that would be greatly appreciated.

**Comment by chen-yuy** [comment]
@LiamBindle Many thanks!
I have regirded my GCHP output files from diagnostic form to classic form by GCpy (that is extremely helpful), I found the data of the regrided files along the "lev" dimension reversed but the coordinatie remains the same as the original file. 
I didn't see any relating pieces of information on the GCpy document, so I want to know is it normal?

**Comment by LiamBindle** [comment]
Great! Happy to help!

Hmm, unfortunately, I'm not too familiar with what GCPy does there. It might be best to open an issue on GCPy, or take a look at the `file_regrid` source code. 

Personally, I recommend regridding using the workflow outlines here:https://github.com/LiamBindle/sparselt (see `examples/`). The gist is (1) create grid definition files with `gridspec-create`, (2) generate the regridding matrix with `ESMF_RegridWeightGen`, and (3) apply the regridding transform to your dataset with a tool like sparselt (Matlab and Julia implementations coming soon). If you have any questions about that, feel free to open an issue in one of those repos and I'd be happy to help.

**Comment by chen-yuy** [comment]
Many thanks to all of you!

**Comment by lizziel** [comment]
The flipping in the lev dimension may be occurring because the `positive `attribute in the diagnostics lev dimension prior to GCHP 13.2 was `down` when it should actually be `up`. I have not looked at the GCPy regridder but I recall someone else brought up this issue recently which prompted me to put a quick fix in MAPL: https://github.com/geoschem/MAPL/pull/10. I believe the regridder was written for use with restart files which have the correct positive attribute so this went under the radar for a little while after the regridding function was added.
