### ISSUE TITLE
pmix option in SLURM run script

### ISSUE THREAD

**Issue by cbutenhoff** [geoschem/GCHP#129]
In the sample SLURM run script provided in the GCHP distribution,  _simple_batch_job.slurm.sh_, srun is used with the option _--mpi-pmix_ to execute GCHP:

 `srun` -n 60 -N 2 -m plane=30 --mpi=pmix ./gchp   # launch 60 GCHP processes

It appears however the SLURM version on our cluster was not built with the pmix plugin as I get this error when I use this srun line in my run script:

`+ srun -m plane=30 --mpi=pmix ./gchp
srun: error: Couldn't find the specified plugin name for mpi/pmix looking at all files
srun: error: cannot find mpi plugin for mpi/pmix
srun: error: cannot create mpi context for mpi/pmix
srun: error: "--mpi=pmix" -- long invalid MPI type, --mpi=list for acceptable types.
`

However I can get gchp to run if I launch it with either mpirun or mpiexec with no pmix setting, such as 

`mpiexec` ./gchp

I'm wondering if this is a valid way of running gchp, or should we rebuild slurm with the pmix option? I'm not familiar with what the setting mpi=pmix does. 
`

**Comment by yantosca** [comment]
Thanks for writing @cbutenhoff.  The runScriptSamples are based on those at the Harvard Cannon cluster and as such are not intended for use on all systems.  You can use the default GCHP run script as a base for further customizations for your own specific system.

**Comment by lizziel** [comment]
We could edit the comments in the simple GCHP run script to be more clear that pmix is not applicable for all SLURM implementations. There are indeed several ways to submit GCHP.

**Comment by cbutenhoff** [comment]
Thanks!

**Comment by lizziel** [comment]
Okay, I am adding this comment to the file, to be included in a future version release. I'll close out this issue now.
```
# Please note that there are several commands that may work to execute GCHP, and the
# provided example may not be appropriate for your system. The command above is for SLURM
# built with PMIx support. Some SLURM implementations have PMI2 support instead, or no
# special MPI processing. Check with your system administrator about the appropriate
# way to use srun. Some users have had better experience using mpirun or mpiexec which
# are MPI-specific run commands implemented in MPI rather than SLURM.
```
