### ISSUE TITLE
[BUG/ISSUE] Start up is very slow

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#132]
### Description of the problem
GCHP's start up is very slow. Usually simulations hang here for a long time

```
ExtData Run_: Start
ExtData Run_: READ_LOOP: Start
ExtData Run_: ---PopulateBundle
ExtData Run_: ---prefetch
```
On a few nodes it might hang for 10s of minutes, but for simulations on many nodes it can hang for hours.  This "hanging" isn't new, but I figured I should open an issue for it.

The behaviour I'd expect is that it should take <10ish minutes to initialize and start time stepping at any resolution.

### GEOS-Chem version
13.0+

### Description of code modifications
n/a

### Log files
- Build log (if applicable): n/a
- Run log (if applicable): n/a
- Run script (if applicable): n/a

### Software versions
- Compilers (Intel or GNU, and version): both
- NetCDF version: n/a
- MPI version: Intel MPI and OpenMPI, likely all though
- ESMF version: n/a

**Comment by LiamBindle** [comment]
@lizziel Do you notice this too?

**Comment by LiamBindle** [comment]
Oh, perhaps is this "hang" when MAPL is generating all the regridding weights? https://github.com/geoschem/GCHP/issues/53

**Comment by LiamBindle** [comment]
It looks like the hang time can get very long if something isn't right with MPI. For example, on one set of our nodes the hang time is >1 hour, but on the other set (with good MPI configuration) the hang time is ~6 minutes.

**Comment by LiamBindle** [comment]
Watching allPEs.log during start up with XXX revealed that it hangs for a long time between these lines
```
0000: MAPL.GENERIC: INFO: Finished the 'Initialize' stage of the gridded component 'EXTDATA'
0000: MAPL.GENERIC: INFO: Started the  'WriteRestart' stage of the gridded component 'GCHP'
```

**Comment by lizziel** [comment]
This is triggering my memory that we used to write a checkpoint file upon start up and it made things slow. I thought I changed the default record frequency in `GCHP.rc` so that it would no longer do that. At the end of that slow-down is there a checkpoint file?
