### ISSUE TITLE
[BUG/ISSUE] Initial restart file must be <60 characters

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#134]
### Description of the problem
The restart file must be in the run directory (or a link to the actual restart file). If you specify an absolute path in for `INITIAL_RESTART` in runConfig.sh the simulation crashes.

### Possible fix
`runConfig.sh` could throw an error if the value of `INITIAL_RESTART` includes `/`. 

### GEOS-Chem version
13.0+

### Description of code modifications
n/a

**Comment by sdeastham** [comment]
How weird! I'd suggest `runConfig.sh` throw an error if `INITIAL_RESTART` *starts* wtih `/`; I think (?) that relative paths are still OK (e.g. `INITIAL_RESTART=OutputDir/restart.nc4`, which you might use if (like me) you want to have `OutputDir` be a softlink to your scratch space while your run dir is in your home directory)

**Comment by lizziel** [comment]
I'd also create a MAPL issue for this. Maybe it would be straightforward to update MAPL to allow absolute paths. I don't think I've ever tried a relative path. Could you follow up here on if that works?

**Comment by LiamBindle** [comment]
Thanks for the clarification. I didn't realize a relative path was okay. I'll double check that and follow up here.

**Comment by LiamBindle** [comment]
Confirmed that relative paths are okay (both subdirectories and relative paths to higher-level directories).

Opened https://github.com/GEOS-ESM/MAPL/issues/990.

**Comment by LiamBindle** [comment]
Turns out this is just a string length bug. The `rstFile` variable is only 60 characters (see [here](https://github.com/geoschem/geos-chem/blob/d7baeb8fe51a66914408e9d1f655dd062bd5d4df/Interfaces/GCHP/Chem_GridCompMod.F90#L380)). I'll fix this.
