### ISSUE TITLE
[SUBMODULE UPDATES] GCHP adjoint skeleton updates

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#146]
## Brief Description

Creating this for @TerribleNews (please correct me if I describe anything incorrectly). This is a super issue for the adjoint skeleton updates. I'm going to be tackling this for 13.3. I'm proposing this new "superproject instructions" workflow for keeping track of pull requests affecting submodules. This way we can keep track of submodule PRs and link the overall update to a GCHP release milestone.  

## Related Issues

* _none_

## Submodule Pull Requests

* [x] https://github.com/geoschem/MAPL/pull/12
* [x] https://github.com/geoschem/HEMCO/pull/97
* [x] https://github.com/geoschem/geos-chem/pull/797

**Comment by LiamBindle** [comment]
All three PRs are merged. The `dev` branches on GCHP and GCClassic are updated to include these PRs.

**Comment by TerribleNews** [comment]
Hooray! Thank you!
