### ISSUE TITLE
[QUESTION]Problems when running a verifying case in GCHP 13

### ISSUE THREAD

**Issue by mmmjjj527** [geoschem/GCHP#148]
# Ask a question about GCHP:

 

Hello,

I tried to run a verifying case after successfully installing the GCHP 13. I didn't change any default files before submitting the job with the command **mpirun -np 24 ./gchp**. However, the simulation just crashed and I could not figure out the root reason after several tries. The error information is as follows: [error.log](https://github.com/geoschem/GCHP/files/7082527/error.log).

Please let me know your solution if any of you have met the same problem. Many thanks!

**Comment by LiamBindle** [comment]
Hi @mmmjjj527 thanks for writing. Did you run `./runConfig.sh` before you did `mpirun -np 24 ./gchp`?

**Comment by mmmjjj527** [comment]
> Hi @mmmjjj527 thanks for writing. Did you run `./runConfig.sh` before you did `mpirun -np 24 ./gchp`?

Thanks for your reply! But it seems that running **./runConfig.sh** didn't solve this problem. I'll check the environment to see if it could be the root reason.

**Comment by lizziel** [comment]
Hi @mmmjjj527, could you upload your config and log files here? It is hard to tell what is going on without seeing your settings and how far into the run your job got. You can add extension '.txt' to each file and drag and drop it into the comment box.

**Comment by LiamBindle** [comment]
Could you also share your MPICH version number and the GCHP version number?

**Comment by mmmjjj527** [comment]
Dear Liam Bindle,


I'm really sorry for the late reply! I didn't check emails from this mailbox these days. In fact, during the other days ago, one of our group members and I came across similar errors when running GCHP on our cluster. We tried to contact the IT Service Department to see if it was caused by the compiling environment. But we have not solve the problem yet. I'll&nbsp; organize our error messages, configuration files and compile environment versions by this week and then send to you in another email.


Many many thanks for your kind work!


Best,
Jia


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geoschem/GCHP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 晚上10:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geoschem/GCHP] [QUESTION]Problems when running a verifying case in GCHP 13 (#148)





 
Could you also share your MPICH version number and the GCHP version number that you're using?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LiamBindle** [comment]
Hi Jia, no worries at all. Thanks for the update.
