### ISSUE TITLE
[DISCUSSION][QUESTION] Comparing the GC classic v12.9.3 and GCHP v13.0.0

### ISSUE THREAD

**Issue by chen-yuy** [geoschem/GCHP#150]
Hi, @lizziel  
Recently I run the GC classic and GCHP during 20180101-20180201 with spin up for 1 year for both models. After checking my results of BrO concentration (mixing ratio) and BrO column density (including total, stratospheric, and tropospheric column), I have found there is an unignorable discrepancy between the outputs of GCHP and GC classic, especially in the northern Pacific ocean (I plot profile in this area) attached following.
This quite confuses me for I have set the same `HEMCO_Config` for both simulations and I want to know exactly what could possibly lead to this.

All GCHP results have been transformed by the GCpy for my plotting.

> GCHP configuration files (c24):
[GCHP.rc.txt](https://github.com/geoschem/GCHP/files/7097835/GCHP.rc.txt)
[gchp.run.txt](https://github.com/geoschem/GCHP/files/7097836/gchp.run.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/7097837/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/GCHP/files/7097838/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7097839/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/GCHP/files/7097840/input.geos.txt)
[runConfig.sh..txt](https://github.com/geoschem/GCHP/files/7097841/runConfig.sh.txt)
[CAP.rc.txt](https://github.com/geoschem/GCHP/files/7097842/CAP.rc.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/7097843/ExtData.rc.txt)
[gchp.env.txt](https://github.com/geoschem/GCHP/files/7097844/gchp.env.txt)

> GEOS_Chem (4x5°):
[getRunInfo.txt](https://github.com/geoschem/GCHP/files/7097868/getRunInfo.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/7097869/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/GCHP/files/7097870/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7097871/HISTORY.rc.txt)
[input.geos.txt](https://github.com/geoschem/GCHP/files/7097872/input.geos.txt)

> Plots of GCHP and GC classic results (hope it shows correctly and clearly)
[PLOTs.pdf](https://github.com/geoschem/GCHP/files/7097903/PLOTs.pdf)

Please ask if I miss any info. Many thanks!

**Comment by lizziel** [comment]
Hi @chen-yuy, our 1-year benchmarks are for different years than you are running but I wonder if comparing your output to our 1-year benchmark results would give insight into the differences. 

The 1-year full chemistry benchmark for 13.0.0 is [here](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_13.0.0#1-year_full-chemistry_benchmarks)

The 13.0 benchmark includes comparison between GC-Classic 13.0 and 12.9, as well as GC-Classic 13.0 versus GCHP 13.0. It does not include GC-Classic 12.9 versus GCHP 13.0, but wonder if you could extrapolate the expected differences from the other plots?

All that being said, I notice that you have offline emissions false in HEMCO_Config.rc. This is consistent with our benchmark simulation which uses online emissions. For GCHP science runs, however, we recommend using the standard simulation which has offline emissions on. This avoids issues of grid-resolution dependencies within some of the online emissions extensions. I am not sure if this is the issue you are seeing, however. If there are still big discrepancies after looking over our benchmark comparisons let us know.

**Comment by chen-yuy** [comment]
Many thanks! @lizziel 
I have checked the benchmark, discrepancies in my results are similar to the comparison of GCC 13.0 versus 12.9, I believe that my confusion could be explained by the version difference and unclear bromine chemistry.

Thank you in addition for your kindness and patience!

**Comment by lizziel** [comment]
Excellent, thanks for following up!
