### ISSUE TITLE
[BUG/ISSUE] Error when trying to restart interrupted simulation using existing restart file GCHP 12.9.3

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#151]
Hello, 
I am Maria Tsivlidou, a PhD student in Laboratoire d'Aerologie in Toulouse, France supervised by Bastien Sauvage and Brice Barret. I am trying to restart a GCHP simulation using an existing restart file, and I would like to kindly ask your assistance for an error I have. 

## Describe the bug:
I used GCHP version 12.9.3 to produce a successful simulation with start date 20080501 and end date 20080601. At the end of the run the checkpoint file was created (gcchem_internal_checkpoint.restart.20080601_000000.nc4.txt). Now I am trying to restart the run since 20080601, but it is not working. 
**Compilation commands**
1.  make clean_all
2.  make build_all

**Run commands**
1. sbatch gchp_nuwa.run
### Error messages
The error message in the gchp.log file is:              Mem/Swap Used (MB) at GIGCenvMAPL_GenericInitialize= 6.8260E+03 0.0
 000E+00
 ERROR: Timer TOTAL needs to be set first
 ERROR: Timer INITIALIZE needs to be set first
 ERROR: Timer TOTAL needs to be set first
 ERROR: Timer INITIALIZE needs to be set first
 ERROR: Timer TOTAL needs to be set first
 ERROR: Timer GenInitTot needs to be set first
 ERROR: Timer --GenInitMine needs to be set first

Also, there are several errors in the slurm.out.txt file attached below. 
### Your GEOS-Chem version and runtime environment:
 - GEOS-Chem version:  GCHP 12.9.3
 - Compiler version: ifort 18.0.2 20180210
 - netCDF version: netcdf/4.7.3-openmpi
 - netCDF-Fortran version (if applicable): __
 - Did you run on a computational cluster, on the AWS cloud: No
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): No 
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - input.geos: [input.geos.txt](https://github.com/geoschem/geos-chem/files/5661789/input.geos.txt)

 - HEMCO_Config.rc: [HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/5661791/HEMCO_Config.rc.txt)

 - GEOS-Chem "Classic" log file: [gchp.log.txt](https://github.com/geoschem/geos-chem/files/5661792/gchp.log.txt)

 - HEMCO.log: [HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/5661790/HEMCO.log.txt)

 - slurm.out or any other error messages from your scheduler: [slurm-510683.out.txt](https://github.com/geoschem/geos-chem/files/5661783/slurm-510683.out.txt)

 - runConfig: [runConfig.sh.txt](https://github.com/geoschem/geos-chem/files/5661788/runConfig.sh.txt)

- sbatch script: [gchp_nuwa.run.txt](https://github.com/geoschem/geos-chem/files/5661793/gchp_nuwa.run.txt)

- checkpoint_restart file: [gcchem_internal_checkpoint.restart.20080601_000000.nc4.txt](https://github.com/geoschem/geos-chem/files/5661794/gcchem_internal_checkpoint.restart.20080601_000000.nc4.txt)

### Additional context
I had the same error even when I tried to restart a 6-month simulation that was interrupted after 3 months, using the last restart file that was created.

**Comment by msulprizio** [comment]
I have transferred this issue to GCHP since it pertains to GCHP simulations

**Comment by mtsivlidou** [comment]
I have been trying to install version 13.1 but I face some issues. Version 13.0 works but gives an error when using multirun option (#116 ). This is why I was wondering if I can use v13.0 skipping the multirun.

**Comment by lizziel** [comment]
You should be able to use 13.0 without multi-run, but I'd still recommend updating versions. If you encounter any issues upgrading then definitely create an issue on GitHub. I'll close out this issue since I think the original question is now resolved.
