### ISSUE TITLE
[BUG/ISSUE] time reference using timeAvg_monthly=1 

### ISSUE THREAD

**Issue by cbutenhoff** [geoschem/GCHP#154]
### Description of the problem

 When I write monthly-averaged diagnostics to file by setting "timeAvg_monthly=1" in runConfig.sh the date of the average is set to the beginning of the month like this:

   ```
     float time(time) ;
                time:begin_date = 20180201 ;
                time:begin_time = 0 ;
                time:long_name = "time" ;
                time:time_increment = 28 ;
                time:units = "days since 2018-02-01 00:00:00" ;
...
time = 0 ;
```
But when I output time-averaged diagnostics in HISTORY.rc using the 'time-averaged' mode, the date is referenced to the middle  of the averaging window, such as this example from a daily-averaged diagnostic:

```
float time(time) ;
                time:begin_date = 20180101 ;
                time:begin_time = 120000 ;
                time:long_name = "time" ;
                time:time_increment = 240000 ;
                time:units = "minutes since 2018-01-01 12:00:00" ;
...
time = 0, 1440, 2880, 4320, 5760, 7200, 8640, 10080, 11520, 12960, 14400,
```

So I just want to verify the timeAvg.monthly feature is working and this is the expected time reference. 

### GEOS-Chem version
13.1.2

**Comment by lizziel** [comment]
Hi @cbutenhoff,
The default time for monthly diagnostics is the start of the averaging period, as you observed. For non-monthly time-averaged diagnostics the default is to use the averaging period mid-point instead. Starting in 13.1 you can change this to use the start time by adding the "timestampStart" field per collection in HISTORY.rc. For example, this is what is would look like for the Emissions collection:
`Emissions.timestampStart: .true.`

If you already have that and it is not working then that is definitely a bug so let us know.

**Comment by cbutenhoff** [comment]
Thanks for the clarification. I just wanted to confirm that the monthly diagnostic was indeed a monthly average given the difference in the timestamp.

**Comment by cbutenhoff** [comment]
One another related item ... 

Is adding the *.monthly field in HISTORY.rc the same as turning "on" timeAvg_monthly in runConfig.sh? Maybe this field is discontinued since I don't see it listed in the HISTORY.rc doc page.

**Comment by LiamBindle** [comment]
@cbutenhoff That's right. The only thing that actually matters is the value in `HISTORY.rc`. The value in runConfig.sh is there for convenience. Keep in mind that running runConfig.sh overwrites parts of HISTORY.rc, so just be a bit careful there. 

Thanks for point out that the `monthly` attribute isn't documented. I'm not familiar with how it works. @lizziel Could you clarify? Is it okay to remove `frequency` and `duration` when using `monthly: 1`?

**Comment by lizziel** [comment]
@cbutenhoff and @LiamBindle, sorry for getting back so late on this. The `*.monthly` field in HISTORY.rc is new in GCHP 13.1 and there are no plans to discontinue it. It is an optional field for collections, but if included you can set it to 1 to turn on monthly time-averaged, or 0 to turn off. Excluding it is the same as including it with value 0.

I have not tested removing frequency and duration from the file collection specs if monthly is turned on. I agree it is confusing to have them there if they are not used. It is possible removing them will throw an error in MAPL. If removing them does work, however, you'd have to remember to put them back if switching monthly diagnostics off. So there are pros and cons to removing them.

The optional fields in HISTORY.rc are unfortunately not all included on the HISTORY.rc ReadTheDocs page right now. That's definitely something that we should do asap.

**Comment by LiamBindle** [comment]
Thanks for clarifying @lizziel. 

I tried `.monthly: 1` with `duration` and `freqency` removed and it looks like it runs okay. I also added `monthly` to the HISTORY.rc docs.

I'm going close this issue but feel free to reopen.
