### ISSUE TITLE
[BUG/ISSUE] Error 137 at MAPL and mpp when compiling GCHP-13.2.0 using gcc 9.3.0

### ISSUE THREAD

**Issue by xpye98** [geoschem/GCHP#156]
### Description of the problem
I install all my dependencies through Spack except CMake, and then compile GCHP-13.2.0 with gcc 9.3.0.
After successful cmake, there are always errors as below when do the `make -j`:

`make[2]: *** [src/MAPL/base/CMakeFiles/MAPL.base.dir/MAPL_CFIO.F90.o] Error 137`
`make[1]: *** [src/MAPL/base/CMakeFiles/MAPL.base.dir/all] Error 2`
and
`make[2]: *** [src/fms_r8/CMakeFiles/fms_r8.dir/mpp/mpp_domains.F90.o] Error 137`
`make[1]: *** [src/fms_r8/CMakeFiles/fms_r8.dir/all] Error 2`

I tried `make -j20` and even higher, it didn't help.

Also, many strange warning happened, see log file for full description,
`/Code.GCHP/src/FMS/affinity/affinity.c:28: warning: "_GNU_SOURCE" redefined`
`Warning: "MPP_TYPE_" redefined`
`Warning: C kind type parameter is for type INTEGER but type at (1) is LOGICAL`
`note: the ABI of passing structure with complex float member has changed in GCC 4.4`

### GEOS-Chem version
GCHP 13.2.0

### Log files
- Build log (if applicable): 
[cmake.log](https://github.com/geoschem/GCHP/files/7154322/cmake.log)
[make.log](https://github.com/geoschem/GCHP/files/7154323/make.log)

### Software versions
- Compilers (Intel or GNU, and version): gcc@9.3.0
- NetCDF version: netcdf-fortran@4.5.3
- MPI version: openmpi@4.1.1
- ESMF version: 8.0.1

**Comment by LiamBindle** [comment]
@xpye98 Thanks for reporting this. To me it looks like the `make` processed was killed, possibly be the operating system or scheduler (I don't see a compiler error in `make.log` but I do see a command that was "killed" which often refers to an OOM-killer). Is it possible your job ran out of memory, or you exceeded a memory limit? 

You could ask for more memory or alternatively you can reduce the amount of memory `make` uses by limiting the number of files it can compile in parallel. For example, `make -j4` limits the number of concurent files being compiled to 4. That will reduce the memory usage by quite a bit.

Does that work?

**Comment by xpye98** [comment]
@LiamBindle Thanks for replying!
Yes, I contact admin and ask them to give me some privilege, and it works now.
To me, these warnings seems to be some FORTRAN legacy, it doesn't affect the run, right?

**Comment by LiamBindle** [comment]
@xpye98 Sorry for the slow reply. Yes, it's okay to ignore those warnings, they are expected. Hopefully in the near future we can eliminate them, but it's safe to ignore them for the time being.
