### ISSUE TITLE
[BUG/ISSUE] Segmentation fault at MAPL_HistoryGridComp.F90 saying invalid memory reference

### ISSUE THREAD

**Issue by xpye98** [geoschem/gchp#157]
### Description of the problem
I ran the test simulation (C24, standard, 6 cores on 1 node) of GCHP 13.2.0.
The slurm file indicates the segmentation fault happened at `/src/MAPL/gridcomps/History/MAPL_HistoryGridComp.F90` line 2336, which is
` call ESMF_StateGet(INTSTATE%GIM(n), &
                  trim(list(n)%field_set%fields(3,1)), field, rc=status )`

It says `Program received signal SIGSEGV: Segmentation fault - invalid memory reference`, see log file below.

 Any suggestions would be appreciated!

### GEOS-Chem version
v13.2.0

### Log files
- Run log (if applicable):
[GCHP.log](https://github.com/geoschem/GCHP/files/7167020/GCHP.log)
[slurm-4616578.txt](https://github.com/geoschem/GCHP/files/7167024/slurm-4616578.txt)
[logfile.000000.txt](https://github.com/geoschem/GCHP/files/7167022/logfile.000000.txt)
[allPEs.log](https://github.com/geoschem/GCHP/files/7167023/allPEs.log)

- Run script (if applicable):
[run.txt](https://github.com/geoschem/GCHP/files/7167026/run.txt)

### Software versions
- Compilers (Intel or GNU, and version): gcc@9.3.0
- NetCDF version: netcdf-fortran@4.5.3
- MPI version: openmpi@4.1.1
- ESMF version: esmf@8.0.1
(all installed using Spack)

**Comment by LiamBindle** [comment]
@xpye98 Thanks for opening this. Sorry for the slow reply, I missed it somehow. 

I don't see anything obvious. It looks like it's crashing parsing `HISTORY.rc`. Did you modify `HISTORY.rc` or is it possible a change was accidentally introduced? Line 3073 of MAPL_HistoryGridComp.F90 is finding a string (in HISTORY.rc I presume) so I wonder if somehow a syntax error got into the config file. I haven't seen this error before. Could you review HISTORY.rc?

If you don't see anything weird, could you share it along with the other config files in your run directory? I can take a look and try running a simulation with them.

---

Version 13.2.1 has some bug fixes and improvements to logging that would be worth getting. If you do 

```console
$ cd GCHP/ 
$ git pull     
$ git checkout 13.2.1
$ git submodule update --recursive
```
that should do the trick. Then you can recompile with `make` (no need to redo `cmake` commands). There were a couple minor changes to the run directory between 13.2.0 and 13.2.1, so you will need to make a new run directory. I think the improvments to logging and error reporting are worth it though.

**Comment by xpye98** [comment]
@LiamBindle Ah, you are right. Some strange symbols are attached to `HISTORY.rc` accidentally. I reproduced the rundir and now it ran to the end successfully. Cheers!

**Comment by LiamBindle** [comment]
Great! Let me know if you run into any more issues.
