### ISSUE TITLE
[BUG/ISSUE] Error running GCHP

### ISSUE THREAD

**Issue by SadiaAfrin9888** [geoschem/gchp#158]
### Description of the problem
While running the GCHP 13.0.0 beta version, I am getting an error immediately after submitting the job. The error message is:
```
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with error code 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[c030:4089892] 23 more processes have sent help message help-mpi-api.txt / mpi-abort
[c030:4089892] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
> 

> `job`

### GEOS-Chem version
GCHP 13.0.0 beta 1

### Description of code modifications
Describe your code modifications here.

### Log files
- Build log (if applicable):
- Run log (if `applicable):`
- Run script (if applicable):

### Software versions
- Compilers (Intel or GNU, and version): Intel 2021.3.0
- NetCDF version: v4.7.3
- MPI version: OpenMPI 4.04
- ESMF version: v8.0.0

**Comment by LiamBindle** [comment]
@SadiaAfrin9888 Thanks for writing. Could you try again with 13.2.1? The version that you are using (13.0.0-beta.1) is quite old now. Just so you know, in case you're following the Youtube tutorial, you can use 13.2.1 the same way as 13.0.0-beta.1.

Additionally, can you include the entire output log file and the script that you used to launch GCHP? That error says something called abort, but it doesn't include any info about what happened.

**Comment by SadiaAfrin9888** [comment]
Thank you so much for your prompt response. Sorry, last time I could not figure out a way to attach files.

This time I tried with the 13.2.1 version, as per your suggestion, still getting a similar kind of error message in the output file (attached):
```
	libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fdac55a0000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fdac5565000)
pe=00022 FAIL at line=02200    MAPL_ExtDataGridCompMod.F90              <From ./HcoDir/Yuan_XLAI/v2021-06/Condensed_Yuan_proc_MODIS_XLAI.025x025.%y4.nc could not find file with extrapolation>
pe=00001 FAIL at line=02200    MAPL_ExtDataGridCompMod.F90              <From ./HcoDir/Yuan_XLAI/v2021-06/Condensed_Yuan_proc_MODIS_XLAI.025x025.%y4.nc could not find file with extrapolation>
pe=00001 FAIL at line=01044    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00001 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'EXTDATA'>
pe=00001 FAIL at line=00766    MAPL_CapGridComp.F90                     <status=1>
pe=00001 FAIL at line=00621    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=02200    MAPL_ExtDataGridCompMod.F90              <From ./HcoDir/Yuan_XLAI/v2021-06/Condensed_Yuan_proc_MODIS_XLAI.025x025.%y4.nc could not find file with extrapolation>
pe=00002 FAIL at line=01044    MAPL_ExtDataGridCompMod.F90              <status=1>
pe=00002 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'EXTDATA'>
.
.
MPI_ABORT was invoked on rank 8 in communicator MPI_COMM_WORLD
with error code 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

Environment Setup File: [gc-hp.bashrc.pdf](https://github.com/geoschem/GCHP/files/7173462/gc-hp.bashrc.pdf)
Job Run File: [GCHP.run.job.pdf](https://github.com/geoschem/GCHP/files/7173463/GCHP.run.job.pdf)
Output: [Output.file.pdf](https://github.com/geoschem/GCHP/files/7173464/Output.file.pdf)
RunConfig File: [runConfig.pdf](https://github.com/geoschem/GCHP/files/7173465/runConfig.pdf)

```
I would highly appreciate it if you could have a look. Thanks.

**Comment by LiamBindle** [comment]
That error looks like the files in `./HcoDir/Yuan_XLAI/v2021-06/` are missing. This is a symlink to the `Yuan_XLAI/v2021-06` subdirectory of your HEMCO data. Do you see any data there? If you don't, you can download it here: http://geoschemdata.wustl.edu/ExtData/HEMCO/Yuan_XLAI/v2021-06/. 

For example,  the file `./HcoDir/Yuan_XLAI/v2021-06/Condensed_Yuan_proc_MODIS_XLAI.025x025.%y4.nc` (replace `%y4` with your simulation's year) needs to exist. You can check this by doing something like `ls ./HcoDir/Yuan_XLAI/v2021-06/Condensed_Yuan_proc_MODIS_XLAI.025x025.2019.nc`.

Also, if you're having trouble attaching files, try uploading a .zip or renaming so they end with .txt.

**Comment by SadiaAfrin9888** [comment]
Thank you so much. I will let you know if I came out with another sort of error after incorporating the missing emission data.

**Comment by SadiaAfrin9888** [comment]
Hi, good afternoon. When I am trying to run GCHPv13.2.1 with 24 processors. It looks like it is running normally without throwing any error in the log file and it also creates output files. However, it is taking only 2.54 minutes for a full month 4x5 simulation, which is weird. Possibly, I am missing something in my run.config file. Also, there I can see some "PET??.ESMF_LogFile" with the following error message. 

"20210919 225204.770 ERROR            PET00 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found
20210919 232022.609 ERROR            PET00 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found
20210927 225010.849 ERROR            PET00 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found
20210930 160851.540 ERROR            PET00 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found
20210930 162505.452 ERROR            PET00 ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found
"
I could not figure out what is driving these issues. I would appreciate it if you could put some thought into it. Please let me know if you need to upload any other information. Thanks in advance. 

[PET00_LogFile.pdf](https://github.com/geoschem/GCHP/files/7262428/PET00_LogFile.pdf)
[slurm-30461.pdf](https://github.com/geoschem/GCHP/files/7262429/slurm-30461.pdf)
[gchp.pdf](https://github.com/geoschem/GCHP/files/7262430/gchp.pdf)
[logfile.pdf](https://github.com/geoschem/GCHP/files/7262431/logfile.pdf)
![Plot_of_output pdf](https://user-images.githubusercontent.com/90787095/135530118-c80959a6-ae5d-4a9f-bce7-79af70085dcb.jpg)

**Comment by LiamBindle** [comment]
Hi @SadiaAfrin9888. Is `Duration=00000000 010000` in runConfig.sh? If so that configures the simulation to run in 1-hour segments. For example, if you want to run a 14 day simulation in 14 consecutive 1-day jobs you would have something like
```
Start_Time="20210101 000000"
End_Time="20210115 000000"
Duration="00000000 000000"
```
This way every job runs for 1 simulation day and then shuts down; all in all, you would need to submit 14 jobs to slurm and configure them to run sequentially. This feature is useful for running long/big simulations. If you set `Duration=00000100 000000` that specifies 1-month segments (it should be equal to the duration of your simulation if you want a single-segment simulation).

Does that make sense?

**Comment by SadiaAfrin9888** [comment]
Thank you so much for your reply. 

Yes, I was running with Duration="00000000 010000", which was probably terminating the simulation after 1 hr. I was also tried with  [Duration="00000100 000000"]. Under this setting, the model is running until the End_date (for a whole month) but creating an output file for every 1hr. Later, I also tried turning on the monthly diagnostic time [Avg_monthly= "1" ] but that also started creating files for every hour.  

So, I am confused, if I want to run a 30-day simulation in 30 consecutive 1-day jobs ( output files for each day or 1 monthly average output file), what are the settings I might have to change? Thanks for your support.

Regards,
Sadia

**Comment by LiamBindle** [comment]
For 1-day segments and monthly output I believe you would want the following (in runConfig.sh):
```
...
Duration="00000001 000000"  # simulation segment's of 1-day
...
timeAvg_monthly="1"         # enable monthly output
``` 

Make sure you execute `./runConfig.sh` whenever you modify it (otherwise your config updates aren't applied).

--- 

### Details
Simulation output is actually configured by the `HISTORY.rc` file; runConfig.sh is a helper script that edits `HISTORY.rc` along with other config files. The documentation for HISTORY.rc is [here](https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html) (note: we haven't added the docs for the monthly option yet). If you make those changes to `runConfig.sh` and the execute `./runConfig.sh` you should see that the appropriate updates the `HISTORY.rc` were made.

---

Does that work?

**Comment by SadiaAfrin9888** [comment]
Thank you for your reply.

**Comment by LiamBindle** [comment]
No problem. I'm going to close this issue but please feel free to reopen.
