### ISSUE TITLE
Error compiling v 13.2

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/gchp#159]
### Description of the problem
Hello, 
I get the following error when I try to compile v 13.2.1:

Fatal Error: Cannot open module file '../mod/gftl_complex32vector.mod0' for writing at (1): Input/output error
/tmpdir/tsivlido/v13.2/GCHP/src/gFTL-shared/src/StringUnlimitedMap.F90:5:2:

Fatal Error: /tmpdir/tsivlido/v13.2/GCHP/build/src/gFTL-shared/mod/types/value_unlimitedPoly.inc: Cannot send after transport endpoint shutdown
compilation terminated.
/tmpdir/tsivlido/v13.2/GCHP/src/gFTL-shared/src/Real64Vector.F90:12:28:

   12 | end module gFTL_Real64Vector

I would appreciate if you could help me with the issue.
Thank you in advance, 
Maria

### GEOS-Chem version
GCHP v 13.2.1   

### Log files
- Build log (if applicable): [ecbuild.log.txt](https://github.com/geoschem/GCHP/files/7187641/ecbuild.log.txt)
- [CMakeOutput.log.txt](https://github.com/geoschem/GCHP/files/7187646/CMakeOutput.log.txt)
-  [CMakeError.log.txt](https://github.com/geoschem/GCHP/files/7187648/CMakeError.log.txt)
- [CMakeCache.txt](https://github.com/geoschem/GCHP/files/7187651/CMakeCache.txt)
- [esmfcompile.log.txt](https://github.com/geoschem/GCHP/files/7187652/esmfcompile.log.txt)
- [esmfinstall.log.txt](https://github.com/geoschem/GCHP/files/7187653/esmfinstall.log.txt)

### Software versions
- Compilers (Intel or GNU, and version): gcc/9.3.0
- NetCDF version: netcdf/4.7.3-openmpi4.0.2-gcc-9.3.0
- MPI version: openmpi/gnu/4.0.2-gcc9.3.0
- ESMF version: 8.0.1 (I compiled it using the libraries above)

**Comment by LiamBindle** [comment]
Hi @mtsivlidou, thanks for opening this. I believe this is a filesystem error.  I've seen "Input/output error" on the cluster I work on, and for me it happens when the filesystem is failing to deliver a file. It looks like "Cannot send after transport endpoint shutdown" is a lustre error, which supports that.

Could you check if `/tmpdir/tsivlido/v13.2/GCHP/build/src/gFTL-shared/mod/types/value_unlimitedPoly.inc` is readable? For example, does `cat /tmpdir/tsivlido/v13.2/GCHP/build/src/gFTL-shared/mod/types/value_unlimitedPoly.inc` give you an error? If you get "Input/output error" you'll have to contact your system administrators.  If you don't get an "Input/output error", could you try recompiling? It might have been a transient error.

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for the answer. 
The folder types (and the value_unlimitedPoly.inc file ) are missing from the /tmpdir/tsivlido/v13.2/GCHP/build/src/gFTL-shared/mod path. 

The mod path includes only 2 files: 
gftl_complex32vector.mod0  gftl_real128vector.mod0. Do you have any idea why?
Maria

**Comment by mtsivlidou** [comment]
I tried to recompile from the beginning and now i get another error, but similar to the previous I think:

/tmpdir/tsivlido/v13.2new/GCHP/src/MAPL/pfio/pFIO_Constants.F90:64:28:

   64 | end module pFIO_ConstantsMod
      |                            1
Fatal Error: Cannot open module file '../../../include/MAPL.pfio/pfio_constantsmod.mod0' for writing at (1): Input/output error
f951: Warning: Include directory '/tmpdir/tsivlido/v13.2new/GCHP/build/include/MAPL.pfio': Cannot send after transport endpoint shutdown
f951: Warning: Include directory '/tmpdir/tsivlido/v13.2new/GCHP/build/include/MAPL.pfio': Cannot send after transport endpoint shutdown
f951: Warning: Include directory '/tmpdir/tsivlido/v13.2new/GCHP/build/include/MAPL.pfio': Cannot send after transport endpoint shutdown
cc1: error: /tmpdir/tsivlido/v13.2new/GCHP/build/include/MAPL.pfio: Cannot send after transport endpoint shutdown
f951: Fatal Error: Cannot delete module file '../../../include/MAPL.pfio/pfio_keywordenforcermod.mod': Cannot send after transport endpoint shutdown
compilation terminated.
f951: Warning: Include directory '../../../include/MAPL.pfio': Cannot send after transport endpoint shutdown
f951: Warning: Include directory '../../../include/MAPL.pfio': Cannot send after transport endpoint shutdown
cc1: fatal error: /tmpdir/tsivlido/v13.2new/GCHP/src/MAPL/pfio/pFIO_ShaveMantissa.c: Cannot send after transport endpoint shutdown
compilation terminated.
f951: Warning: Include directory '../../../include/MAPL.pfio': Cannot send after transport endpoint shutdown
/tmpdir/tsivlido/v13.2new/GCHP/src/MAPL/pfio/AbstractMessage.F90:5:7:

    5 |    use MAPL_ExceptionHandling
      |       1
Fatal Error: Cannot open module file 'mapl_exceptionhandling.mod' for reading at (1): No such file or directory
compilation terminated.
f951: internal compiler error: in cpp_diagnostic_at, at libcpp/errors.c:41

**Comment by LiamBindle** [comment]
I'm afraid I don't. These are lustre errors though, so I think you'll have to contact your system administrators. 

Before that though, you could try a totally new build directory (e.g., `build2/`). If that works, the original "Input/output error" might have left behind a bad-state that is causing the ongoing problem. If you get the same errors in a totally new build directory though, something seems to be going wrong with lustre (the filesystem), so your system's administrators should be able to help.

**Comment by mtsivlidou** [comment]
I started the process from the beginning (cloning the code etc).. and now I get an error when the compilation reaches 100% :+1: 

[100%] Linking Fortran executable ../bin/gchp
MAPL/pfio/libMAPL.pfio.a(DownBit.F90.o): In function `__pfio_downbitmod_MOD_pfio_downbit2d':
/tmpdir/tsivlido/v13.2new/GCHP/src/MAPL/pfio/DownBit.F90:144: undefined reference to `pfio_shavemantissa32_'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/gchp] Error 1
make[1]: *** [src/CMakeFiles/gchp.dir/all] Error 2
make: *** [all] Error 2

Could this also be related to filesystem error?
Thanks

**Comment by mtsivlidou** [comment]
Hello, 
I tried with a new build directory and the compilation seems to work. Thanks again.
Maria

**Comment by LiamBindle** [comment]
Great! No problem.
