### ISSUE TITLE
[FEATURE REQUEST] Vertical advective flux diagnostic

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#16]
GEOS-Chem Classic has diagnostic collection AdvFluxVert to save vertical fluxes in tpcore. There is no equivalent diagnostic in GCHP. Since tpcore is in FV3 we should be able to add in an equivalent diagnostic by creating a new MAPL export in the DYNAMICS grid comp in GCHP.

**Comment by lizziel** [comment]
@LiamBindle, are you working on this feature request? If yes, what is the status? I can change the assignment from me to you.

**Comment by LiamBindle** [comment]
I am and here's the PR: https://github.com/geoschem/GCHP/pull/96

I added a comment with a status update.
