### ISSUE TITLE
[QUESTION] Is there an archive of restart files for GCHP, or can we regrid GC classic restart file to be at GCHP format?

### ISSUE THREAD

**Issue by xpye98** [geoschem/gchp#160]
Hi, all,

I want to know is there an archive of restart files for GCHP, like from benchmark simulations?
Or is there a way we can regrid GC classic restart file to be in GCHP format, as I know there is a archive for GC classic [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0/GCClassic/restarts/).

Thanks in advance!
Xingpei

**Comment by msulprizio** [comment]
Hi @xpye98. Please see http://ftp.as.harvard.edu/gcgrid/geos-chem/10yr_benchmarks/13.0.0-rc.0/GCHP/Checkpoints/ for output from the 10-year GCHP 13.0.0 benchmark.

You may also regrid the GEOS-Chem Classic restarts, which we recommend if doing direct comparisons between GCClassic and GCHP runs. Otherwise, the GCHP restart files should be fine.

**Comment by xpye98** [comment]
@msulprizio Thanks, that helps a lot!
Another little question, how long do I need to spinup for my own simulation with different resolution using these restart files? Is one month enough, or three for safety?

**Comment by LiamBindle** [comment]
@xpye98 I think that should be opened as a [new discussion under geoschem/geos-chem](https://github.com/geoschem/geos-chem/discussions/new). Could you open one and ping us? That way it's archived properly so others can discover it easier.

**Comment by msulprizio** [comment]
Please also see the [GEOS-Chem restart files wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_restart_files) for more information and frequently asked questions.

**Comment by mtsivlidou** [comment]
Hello, 
@xpye98 did you manage to restart a gchp run?? I use the last checkpoint as the initial restart file, but I am not sure if this is enough. Could you please tell me whether you changed anything else in the settings in order to restart the simulation?
Thanks
Maria
