### ISSUE TITLE
[BUG/ISSUE] GCHP v 13.2.1 ESMF error

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/gchp#161]
Hello, 
I just installed GCHP v 13.2.1, one-hour simulation test runs completely (output is written), without any error in the slurm file or gchp.log.

I would like to kindly ask you if you could help me with this error. Could this be related to esmf compilation issue?
Thank you in advance 
Maria

### Description of the problem
20210921 115044.145 ERROR ESMF_Time.F90:1671 ESMF_TimeEQ() Object Set or SetDefault method not called  - Object not Initialized
20210921 115044.188 ERROR ESMF_Config.F90:924 ESMF_ConfigFindLabel Not found  - label EXCLUDE_ADVECTION_TRACERS_LIST: not found

### GEOS-Chem version
GCHP v13.2.1

### Log files
- Build log (if applicable):
[CMakeError.log.txt](https://github.com/geoschem/GCHP/files/7203575/CMakeError.log.txt)

[CMakeOutput.log.txt](https://github.com/geoschem/GCHP/files/7203576/CMakeOutput.log.txt)
- Run log (if applicable): 
[gchp.log.log](https://github.com/geoschem/GCHP/files/7203579/gchp.log.log)

- Run script (if applicable): 
[simple_job.sh.txt](https://github.com/geoschem/GCHP/files/7203581/simple_job.sh.txt)

### Software versions
- Compilers (Intel or GNU, and version): gcc/9.3.0
- NetCDF version: netcdf/4.7.3-openmpi4.0.2-gcc-9.3.0
- MPI version: openmpi/gnu/4.0.2-gcc9.3.0
- ESMF version: 8.0.1 (I compiled this one with the same gcc and openmpi version as above)
- cmake/3.13.0

**Comment by LiamBindle** [comment]
Hi Maria, thanks for opening this. This is a known bug in 13.2.1 and it's safe to ignore.  Your simulation did ran okay.

This is a benign bug that I accidentally introduced in 13.2.1. What happened is I enabled a ESMF feature that generates log files when ESMF encounters an error, but I didn't realize there was a benign ESMF error that we were suppressing. It's safe to ignore these. We should have a fix for it in 13.3, but those PET*.log files are annoying. If you remove [this line](https://github.com/geoschem/GCHP/blob/9dc2340cac684971fa961559a4dc3d8818326ab8/src/GCHPctm.F90#L29) and recompile you won't get those files.

We can leave this open for the time being so others are aware of it.

**Comment by lizziel** [comment]
Another way to disable the ESMF error prints in 13.2.1 is include the following line in config file `GCHP.rc`:

`EXCLUDE_ADVECTION_TRACERS: NO`

This method avoids having to recompile. We will include this fix in an upcoming version.

**Comment by lizziel** [comment]
This fix will be in 13.3.
