### ISSUE TITLE
[BUG/ISSUE] Error while running GCHP with C90 resolution

### ISSUE THREAD

**Issue by SadiaAfrin9888** [geoschem/GCHP#167]
### Description of the problem
I have been trying to run GCHP with C90 resolution. Unfortunately, my simulation is aborting after a minute with the error message that: <<Error during the 'Initialize' stage of the gridded component 'HIST'>>

It feels like something is wrong with the History.rc file, but I could not figure that out. I would appreciate it if you could have a look and suggest the possible source of this error. I am sharing the log files for your consideration. Thanks.
[gchp.run.pdf](https://github.com/geoschem/GCHP/files/7330764/gchp.run.pdf)
[runConfig.pdf](https://github.com/geoschem/GCHP/files/7330765/runConfig.pdf)
[slurm-31255.pdf](https://github.com/geoschem/GCHP/files/7330766/slurm-31255.pdf)
[HISTORY.pdf](https://github.com/geoschem/GCHP/files/7330767/HISTORY.pdf)
[gchp.log.pdf](https://github.com/geoschem/GCHP/files/7330768/gchp.log.pdf)

### GEOS-Chem version
HCHP 13.2.1

### Software versions
- Compilers (Intel or GNU, and version): Intel 2021.3.0
- NetCDF version: 4.7.3
- MPI version: OpenMPI 4.04
- ESMF version: ESMF 8.0.0

**Comment by lizziel** [comment]
Hi @SadiaAfrin9888, it looks likes the error is occurring here, when MAPL is trying to find the `Grid_Labels` entry in `HISTORY.rc`.
https://github.com/geoschem/MAPL/blob/e61ca7455f5e2625f1add27e354e7b959125b922/gridcomps/History/MAPL_HistoryGridComp.F90#L615-L616

I notice in your config file you have that part of the file commented out. Try uncommenting the grid labels list and rerunning. If you do not use the grid labels that is okay, but apparently having them in the file is a requirement.

**Comment by SadiaAfrin9888** [comment]
Thanks for the suggestion. Turning them on solving the problem. Thanks.
