### ISSUE TITLE
[FEATURE REQUEST] Restrict mass balance operation to the troposphere

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#17]
An update to restrict the mass balance operation to the troposphere, submitted by Sebastian Eastham (@sdeastham ) in 12.1.1, has not yet migrated from old GCHP to new GCHPctm. The old GCHP commit is https://github.com/geoschem/gchp/commit/7a4589c276876b6674800f4e4137b575e4def4f5. This update needs to be manually applied to the new FV submodule in GCHPctm, ideally before the 13.0.0 release.

**Comment by sdeastham** [comment]
This should be resolved by PR#1 on geoschem/GFDL_atmos_cubed_sphere
(link: https://github.com/geoschem/GFDL_atmos_cubed_sphere/pull/1)

**Comment by lizziel** [comment]
Thanks @sdeastham !
