### ISSUE TITLE
ERROR: Restart file specified in runConfig.sh not found.

### ISSUE THREAD

**Issue by SadiaAfrin9888** [geoschem/gchp#178]
I have been trying to run GCHP with C48 resolution. Unfortunately, my simulation is aborting immediately with the error message that: <<ERROR: Restart file specified in runConfig.sh not found: initial_GEOSChem_rst.c48_fullchem.nc>>

However, the initial restart file exists under the run directory. I would appreciate it if you could have a look and suggest the possible source of this error. I am sharing the log files for your consideration. Thanks.

[gchp.run.pdf](https://github.com/geoschem/GCHP/files/7548531/gchp.run.pdf)
[input.geos.pdf](https://github.com/geoschem/GCHP/files/7548532/input.geos.pdf)
[runConfig.sh.pdf](https://github.com/geoschem/GCHP/files/7548533/runConfig.sh.pdf)
[HISTORY.rc.pdf](https://github.com/geoschem/GCHP/files/7548552/HISTORY.rc.pdf)

GEOS-Chem version
HCHP 13.2.1

Software versions
Compilers (Intel or GNU, and version): Intel 2021.4.0
NetCDF version: 4.7.3
MPI version: OpenMPI 4.04
ESMF version: ESMF 8.0.0

**Comment by LiamBindle** [comment]
Hi @SadiaAfrin9888,

Is it possible that `initial_GEOSChem_rst.c48_fullchem.nc` in your run directory is pointing to a file that doesn't exist? If you do 

```console
ls -lh initial_GEOSChem_rst.c48_fullchem.nc
```

it will show you where the `initial_GEOSChem_rst.c48_fullchem.nc` symlink is pointing to. Can you check if the file exists?

**Comment by SadiaAfrin9888** [comment]
Thanks for your reply. I believe it exists since it is linking a file "/net/geoschem/data/gcgrid/gcdata/ExtData/GEOSCHEM_RESTARTS/GC_13.0.0/GCHP.Restart.fullchem.20190701_0000z.c48.nc4
"

**Comment by sdeastham** [comment]
Hi @SadiaAfrin9888 - can you try this command out?

`if [[ -e /net/geoschem/data/gcgrid/gcdata/ExtData/GEOSCHEM_RESTARTS/GC_13.0.0/GCHP.Restart.fullchem.20190701_0000z.c48.nc4 ]]; then echo "File exists!"; else echo "File does not exist!"; fi`

**Comment by SadiaAfrin9888** [comment]
Yes, both of you are right. Actually, the file does not exist. Sorry, for this silly question. Thanks.

**Comment by yantosca** [comment]
No problem @SadiaAfrin9888, we can close out this issue now.   Thanks!
