### ISSUE TITLE
[QUESTION] Can GCHP emission outputs be set to the cubed-sphere grid?

### ISSUE THREAD

**Issue by deepangsuc** [geoschem/gchp#182]
Like the outputs files from GCHP can be set to Grid Type : Cubed Sphere/ Lat_Lon, can the same be done to the emissions files ? If so how ?

**Comment by LiamBindle** [comment]
@deepangsuc Emissions diagnostics are handled the same as any other type of diagnostic. To get emissions diagnostics on the simulation's native grid (cubed-sphere), omit the `GRID_TYPE` specifier in the emission collection's definition in HISTORY.rc (`Emissions.` if you're using default collections).
