### ISSUE TITLE
[BUG/ISSUE] Comments in `HISTORY.rc` caused crushing down

### ISSUE THREAD

**Issue by chen-yuy** [geoschem/gchp#184]
This issue is from the HISTORY.rc setting
After I commented out several species I don't need in `Species_Conc` part of `HISTORY.rc`, I could not run GCHP and got the following error. Do you have any idea about this problem?

### GEOS-Chem version
GCHP V13.0.0

### Description of code modifications
As we discussed in #175 , the only difference between work or not work simulation is the commented `Species_Conc`. The duration and frequency of instantaneous collections I set `40000` is working, but as you suggested I will modify it to standard formation.
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/7622552/HISTORY.rc.txt)
### Log files
[gchp.log.201901_HISTORY.txt](https://github.com/geoschem/GCHP/files/7622551/gchp.log.201901_HISTORY.txt)
[run_2560127.err.txt](https://github.com/geoschem/GCHP/files/7622553/run_2560127.err.txt)

**Comment by chen-yuy** [comment]
Hello, @LiamBindle 
I create a new issue here, looking forward to your reply.
Many thanks.

**Comment by LiamBindle** [comment]
Hi @chen-yuy. I'm having trouble reproducing your crash.

I tried 13.0.0 and 13.2.1 with the `HISTORY.rc` you provided and it worked okay for me. I'm using GNU 9.3 compilers. To track this down, could you do the following?
1. Confirm that 13.0.0 crashes with the exact HISTORY.rc file you provided
2. Add the following line *before* [this line](https://github.com/geoschem/MAPL/blob/a9590432be58889e4277253c7872d982980e4bb3/base/MAPL_HistoryGridComp.F90#L3071) and rerun your simulation. What is the bad attribute it prints?
   ```diff
             if (status /= ESMF_SUCCESS)  then
                 if( MAPL_AM_I_ROOT(vm) ) then
                     print *
                     print *, '**************************************************************'
                     print *, 'Attributes NOT set for Collection: ',trim( list(n)%collection )
                     print *, '**************************************************************'
                     print *
                 endif
             endif
   +         write(*,*) '!! THE BAD ATTRIBUTE IS: ',export_name
             _VERIFY(STATUS)
   ```
3. What compiler are you using?
