### ISSUE TITLE
[BUG/ISSUE] APPEND CMD in CMakeList.txt will add semicolon after flags which cause the GCHP build error

### ISSUE THREAD

**Issue by hgrhgy** [geoschem/gchp#185]
### Description of the problem
APPEND CMD in CMakeList.txt will add semicolon after flags which cause the GCHP build error

### GEOS-Chem version
GCHP 13.0.2

### Description of code modifications
modifications in CMakeLists.txt
``` cmake
if("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
  list(APPEND CMAKE_Fortran_FLAGS "-ffree-line-length-none")
  # ADD for replacing the semicolon with space
  + string (REPLACE ";" " " CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS}")
endif()
```

### Log files
```diff
[ 15%] Built target gftl-shared
Scanning dependencies of target yafyaml
[ 15%] Building Fortran object src/yaFyaml/src/CMakeFiles/yafyaml.dir/KeywordEnforcer.F90.o
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
- /bin/sh: 1: -ffree-line-length-none: not found
src/yaFyaml/src/CMakeFiles/yafyaml.dir/build.make:360: recipe for target 'src/yaFyaml/src/CMakeFiles/yafyaml.dir/KeywordEnforcer.F90.o' failed
make[2]: *** [src/yaFyaml/src/CMakeFiles/yafyaml.dir/KeywordEnforcer.F90.o] Error 127
CMakeFiles/Makefile2:3292: recipe for target 'src/yaFyaml/src/CMakeFiles/yafyaml.dir/all' failed
make[1]: *** [src/yaFyaml/src/CMakeFiles/yafyaml.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
```

### Software versions
- Compilers (Intel or GNU, and version): gnu 9.4.0
- NetCDF version: 4.7.4
- MPI version:  3.3.2
- ESMF version: 8.1.1
-  CMAKE version:  3.22.0

**Comment by LiamBindle** [comment]
I believe `CMAKE_Fortran_COMPILER_ID` is a string, not a list ([ref](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_FLAGS.html)), so extra flags would be added like
```cmake
set(CMAKE_Fortran_COMPILER_ID "${CMAKE_Fortran_COMPILER_ID} -ffree-line-length-none")
``` 
Are you trying to add a custom compiler flag to the GCHP build? If so you can set the `GEOSChem_Fortran_FLAGS_GNU` cache variable ([code](https://github.com/geoschem/GCHP/blob/9c3d4f71c8662cd55e7ea54cb3b62a031e5116f8/src/GCHP_GridComp/GEOSChem_GridComp/CMakeLists.txt#L46)). For example

```console
$ cmake . -DGEOSChem_Fortran_FLAGS_GNU="-ffree-line-length-none" 
```

That said, I wasn't aware of any build errors in 13.0.2 that warrant extra compiler args. Are you having trouble compiling 13.0.2? If so, could you share the build log and CMakeCache.txt?

**Comment by hgrhgy** [comment]
I'm sorry I didn't make the problem clear. The code to add the `-ffree-line-length-none` flag is the original code in `https://github.com/geoschem/GCHP/blob/main/CMakeLists.txt`, I just add the code to replace the semicolon with space.
The problem may be compiler related.
The CMakeCache.txt is uploaded
[CMakeCache.txt](https://github.com/geoschem/GCHP/files/7629899/CMakeCache.txt)
.

**Comment by hgrhgy** [comment]
@LiamBindle The problem is that I set the FCFLAGS and FFLAGS in other software build, same as you said. The compiler just accept one style of flags separator.
