### ISSUE TITLE
[BUG/ISSUE] Problem with the output of total precipitation on the ground (Met_PRECTOT) from GCHP simulation

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/gchp#188]
### Description of the problem
I looked at the output variable from GCHP v13.2.1 and found the output of Met_PRECTOT (total precipitaiton on the ground) from both C360 and C90 are basically zero (maximum value 1e-25 mm/day). Then I checked the same variable from GEOSChem classic simulation with same version and same emission inputs, but I found it is not zero everywhere. As GCHP and GCC are using the same source code, it looks like there is something wrong with the output.

The plot from GCHP C360:
![image](https://user-images.githubusercontent.com/75513026/147959970-7f383670-3c43-4af1-a1af-844dde6900a4.png)

The plot from GCHP C90:
![image](https://user-images.githubusercontent.com/75513026/147960078-0de3e98a-afae-4340-b7f6-39be283d75dd.png)

The plot from GCC 2x2.5:
![image](https://user-images.githubusercontent.com/75513026/147960401-e2c5b685-7ec8-471d-9c50-fedf6ef4b5f9.png)

### GEOS-Chem version
v13.2.1

### Description of code modifications
I turned on LUO_WETDEP for both GCHP and GCC, other source codes are left as default.

### Log files
- Build log (if applicable):
- Run log (if applicable):
- Run script (if applicable):

### Software versions
- Compilers (Intel or GNU, and version): Intel
- NetCDF version: 
- MPI version:
- ESMF version:

**Comment by yantosca** [comment]
Thanks for writing @1Dandan.  I wonder if this is a MAPL or MPI issue. 

GCHP relies MAPL and ESMF regridding, wheras and GC-Classic uses the netCDF API and Map_A2A regridding.  It could be that the MAPL regridding is somehow zeroing out the Met_PRECTOT field.

**Comment by sdeastham** [comment]
I don't think this is MAPL. Is `PRECTOT` actually used anywhere in the code? I grepped for it in the GCC and GCHP code and the only places I could find it was as an input or output, never as a functioning variable. It looks like we don't transfer the variable to `State_Met` in `Includes_Before_Run.H`, presumably because it has no function and so just constitutes a memory sink?

**Comment by yantosca** [comment]
That may be it @sdeastham.

**Comment by LiamBindle** [comment]
Yeah it looks like this field isn't used. I'd propose we remove it and check for other no-longer-used fields.

@1Dandan As a solution to your problem, you could use `PRECTOTAL` directly from the meteorological input data (it's in the A1 collection).

**Comment by 1Dandan** [comment]
Okay, thanks @LiamBindle, I will use original Met data directly.
