### ISSUE TITLE
[BUG/ISSUE] Possible memory leak detected in 13.2.1

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/gchp#192]
### What institution are you from?
WashU

### Description of the problem
Aaron, in our group, is running some long term GCHP simulations and his simulations are crashing every 60 days. The log files report increasing memory usage throughout the simulation (reported numbers are 24.4% at start, 31.4% at end).

### GEOS-Chem version
13.2.1 - haven't check other versions though

### Description of code modifications
none

### Log files
- Build log (if applicable):
- Run log (if applicable): [runlog-possible-memory-leak.txt](https://github.com/geoschem/GCHP/files/7929338/runlog-possible-memory-leak.txt)
- Run script (if applicable): [run.bsub.txt](https://github.com/geoschem/GCHP/files/7929343/run.bsub.txt)

### Software versions
- Compilers (Intel or GNU, and version): `ifort (IFORT) 19.1.0.166 20191121`
- NetCDF version:
- MPI version:
- ESMF version:

**Comment by lizziel** [comment]
Regarding the fail message, I found [this post](https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/Assertion-failed-in-ch4-shm-coll-c-at-line-2147/m-p/1186157) that identifies it as an Intel 2019 MPI bug. 

Regarding the memory leak, we can check 1-year benchmark run logs to see if it is happening there too.

**Comment by lizziel** [comment]
It looks like the leak was present in the 13.2.0 1-year GCHP benchmark for transport tracers (22 to 40% over the year).

**Comment by yantosca** [comment]
In the GCHP 13.3.0-rc.1 benchmark we go from 77 GB to 103 GB, or 26 GB/month memory increase:

```console
near start of run ...
Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  7.712E+04  0.000E+00

... near end of run ...
Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  1.036E+05  0.000E+00
```

Similar results are observed in the GCHP 13.4.0-rc.0 1-month benchmark.

**Comment by lizziel** [comment]
As discussed at our meeting earlier today, let's test GCHP with MAPL 2.16 and see if the leak is still there. If it is then the next step would be to bring it up at our next meeting with GMAO.

**Comment by lizziel** [comment]
@kilicomu expressed interest in looking at this too.

**Comment by lizziel** [comment]
@LiamBindle, would you be able to coordinate doing this before you leave?

**Comment by kilicomu** [comment]
@lizziel Do you have a timescale for this (i.e. is it super urgent?)? If not, I'm happy for it to just be assigned to me and I'll make a start on it in the near future when I've got through some of the other stuff that came up at IGC.

**Comment by lizziel** [comment]
This is not urgent. Thanks for taking it on!

**Comment by lizziel** [comment]
I did some tests on my dev version 14.1 that uses MAPL 2.26 and also has the memory leak updates for GEOS-Chem and HEMCO from @yantosca :
https://github.com/geoschem/geos-chem/pull/1353
https://github.com/geoschem/HEMCO/pull/159

These updates appear to nearly (if not fully) eliminate memory leaks in GCHP within the chemistry gridded component. The main remaining (or possibly only) memory leak appears to be in History.

@yantosca was able to hone in on the memory leaks using the gfortran sanitize option very efficiently. I am thinking perhaps GMAO could do the same on GEOS, or at least MAPL, to address the leaks. I will bring it up with developers there. We could also bring in the sanitize option for GCHP.

**Comment by lizziel** [comment]
Remaining memory leaks should be fixed when https://github.com/GEOS-ESM/MAPL/issues/1793 is addressed.
