### ISSUE TITLE
[BUG/ISSUE] Cannot determine link language for targets

### ISSUE THREAD

**Issue by ahsouri** [geoschem/gchp#193]
### What institution are you from?
Harvard-Smithsonian

### Description of the problem
Following the tutorial on Youtube (cmake ..), I ran into this error:

```console
=================================================================
GEOS-Chem  (science codebase)
Current status: 13.3.4
=================================================================
-- Configuring done
CMake Error: Cannot determine link language for target "Headers".
CMake Error: CMake can not determine linker language for target: Headers
CMake Error: Cannot determine link language for target "JulDay".
CMake Error: CMake can not determine linker language for target: JulDay
CMake Error: Cannot determine link language for target "GeosUtil".
CMake Error: CMake can not determine linker language for target: GeosUtil
CMake Error: Cannot determine link language for target "NcdfUtil".
CMake Error: CMake can not determine linker language for target: NcdfUtil
CMake Error: Cannot determine link language for target "History".
```

### GEOS-Chem version
13.3.4

### Description of code modifications
None.

### Log files
- Build log (if applicable): N/A
- Run log (if applicable): N/A
- Run script (if applicable): cmake

### Software versions
- Compilers (Intel or GNU, and version): i
export FC=ifort
export CC=icc
export CXX="icpc -std=gnu++11"
export FC77=ifort
export F77=ifort

Intel 19.0.5.20190815

- NetCDF version: >4
- MPI version: >2.3
- ESMF version:

**Comment by yantosca** [comment]
Thanks for writing @ahsouri.  Try changing
```bash
export CXX="icpc -std=gnu++11"
```
to
```bash
export CXX="icpc"
```
This might be what is causing the issue.

**Comment by ahsouri** [comment]
Thanks, it still gives the same error. These compiler setups have been used to compile WRF, CMAQ, and the OpenMP version of GEOS-Chem. What do you suggest looking into?

**Comment by sdeastham** [comment]
Hi @ahsouri ! I saw an issue like this not too long ago. Can you briefly provide the directory structure you're using? Specifically, from what directory are you running `cmake ..`, what is the directory above it, and what else is in that directory?

**Comment by ahsouri** [comment]
I'm in "Code.gchp".
<img width="1383" alt="Screen Shot 2022-01-25 at 5 23 29 PM" src="https://user-images.githubusercontent.com/40439250/151069757-1b494a7f-bffd-4977-ba0c-43c68bb19910.png">
I created build, then moved to build (i.e., cd build), and "cmake ..". 

Best,

**Comment by ahsouri** [comment]
I just figured out the issue; I pulled the latest version today but the directory is not the same as the latest version. I got rid of it entirely and cloned the latest repository. It's working! Sorry, my bad!

**Comment by LiamBindle** [comment]
Thanks for the update! No problem at all.
