### ISSUE TITLE
[BUG/ISSUE] Vertical mass flux diagnostic is off by 1.0/(dt*MAPL_GRAV)

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/gchp#196]
### What institution are you from?
WashU

### Description of the problem
See https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/issues/159.

Fix is https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/commit/99b2e9a123525bd18fa366d778f852530101bb64#diff-3dd8e979b916d8034f7682465fb7f31ce0021dda0299b0314edaa496387a21df

### GEOS-Chem version
13.4.0

### Description of code modifications
n/a

### Log files
- Build log (if applicable):
- Run log (if applicable):
- Run script (if applicable):

### Software versions
- Compilers (Intel or GNU, and version):
- NetCDF version:
- MPI version:
- ESMF version:

**Comment by LiamBindle** [comment]
The fix can go in 13.4.1

**Comment by lizziel** [comment]
I brought this into 13.4.0 via cherry-picking the [fix](https://github.com/GEOS-ESM/FVdycoreCubed_GridComp/commit/99b2e9a123525bd18fa366d778f852530101bb64#diff-3dd8e979b916d8034f7682465fb7f31ce0021dda0299b0314edaa496387a21df).
