### ISSUE TITLE
[QUESTION] Spin-up period

### ISSUE THREAD

**Issue by lorenzocostantino** [geoschem/gchp#197]
I am using GCHP 13.3.4 at C180. My aim is to run several one-year (the full 2019) simulations to perform a sensitivity study.
For each run, I want to swicth on/off (or just modify) some emission fluxes (PM, NOx, SO2) and analyse the impact on air quality at ground level (PM, NOx, SO2 and O3). I would like to ask your opinion to be sure of the reliability of my results. 

1) I see that some RESTART files are provided, e.g. for the year I need to run my simulations you provide :
http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2021-09/GCHP.Restart.fullchem.20190101_0000z.c180.nc4
or
http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2022-01/GCHP.Restart.fullchem.20190101_0000z.c180.nc4
What is the difference in the two data sets (v2021-09 versus v2022-01) ? The GCHP version used to run them?

2) If I use one of the previous RESTART files for 20190101, is the model already "warm"?
In other words: can I start my 2019 simulation directly on 20190101, without any spin-up period?

3) If I DO need a spin up period: what is the best (or minimum) spin-up period required for this kind of sensitivity study? For other models I have already used (at continental scale), one week is usually enough (e.g., WRF, CHIMERE) to spin-up. Of course, I would like to spend as little CPU resources as possible to run the spin-up period. 
Does the spin-up period should increase with increasing model resolution? 

4) Doing some preliminary tests, I saw that no error or warning arises if I use a RESTART file which is not consistent with the starting date of my simulation. 
For instance : if I link my initial_GEOSChem_rst.c180_fullchem.nc to GCHP.Restart.fullchem.20190101_0000z.c180.nc4 but start my simulation on 20190102, this seems to be completely legal. Is that right ? 

5) Consequently, if I DO need a spin-up period : does it make any sense to use the GCHP.Restart.fullchem.20190101_0000z.c180.nc4 file to start the simulation on a previous date (not so far, so that atmospheric state is not so different) let's say 20181225 (or 20181201) and then spin-up for a week (or a month), in order to wait that initial conditions loose their stronger influence ? 
Otherwise, what can I do to start simulations some days before 20190101 (--> No RESTART_FILE (+none) and a very long run as spinup?)?

Thank you in advance.

**Comment by LiamBindle** [comment]
Hi @lorenzocostantino, thanks for writing. These are great questions. Note that in 14.0 we're hoping to make some changes that will make the usage of the restart files easier to understand.

1. 
    > ... What is the difference in the two data sets (v2021-09 versus v2022-01) ?
    
    v2022-01 and v2021-09 are the same&mdash;the only difference is the v2022-01 files explicitly include variables whose initial conditions are zero (v2021-09 omits these variables and relies on an implicit behaviour in MAPL to initialize those variables to zero). This minor tweak in the v2022-01 is because the incoming MAPL updates in 14.0 remove the implicit behaviour. For you situation, you could use either.

2. 
    > If I use one of the previous RESTART files for 20190101, is the model already "warm"?
    In other words: can I start my 2019 simulation directly on 20190101, without any spin-up period?

    Yes, but the c180 restart file actually comes from a c48 simulation (initial conditions regridded to c180), so you'll want to run at least a short spinup.

3. 
    > If I DO need a spin up period: what is the best (or minimum) spin-up period required for this kind of sensitivity study?
    ...
    Does the spin-up period should increase with increasing model resolution?
    
    See [this Q/A thread](https://github.com/geoschem/geos-chem/discussions/911). Your species (PM, NOx, SO2) are all pretty short-lived, so I would say 2-weeks is probably sufficient for those species to relax. Starting your simulation on 2018-12-17 from the `GCHP.Restart.fullchem.20190101_0000z.c180.nc4` (v2021-09) restart file seems reasonable to me.

4. You're correct. The restart file's date is not enforced. Even though it isn't enforced, you need to make sure you're using a restart file for the appropriate season though (i.e., don't use a July restart file in December).

5. Yeah, that's what I was thinking too for your situtation. Personally I would probably use 2 weeks or 1 month.

Hope that helps. Let me know if you have any more questions.

**Comment by lorenzocostantino** [comment]
Dear @LiamBindle, thank you very much. Extremely clear and helpfull.
