### ISSUE TITLE
[BUG/ISSUE] "step size too small" error

### ISSUE THREAD

**Issue by ghost** [geoschem/gchp#202]
### What institution are you from? 
Seoul National University, South Korea

### Description of the problem
I try to test run with c48 from 20200101 to 20200103 with 1-hr duration.
But, model stopped with error message below
![스크린샷 2022-02-25 오후 2 34 44](https://user-images.githubusercontent.com/77944271/155660016-36599ff0-aa38-4f79-aec3-f9ee9d741e3a.png)
What should I do? How to fix it?

Thank you for your help. I greatly appreciate it.

### GEOS-Chem version
13.0.0

### Description of code modifications
Describe your code modifications here.

### Log files
- Build log (if applicable):
- Run log (if applicable): 
[runlog.txt](https://github.com/geoschem/GCHP/files/8138800/runlog.txt)

- Run script (if applicable):
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/8138799/runConfig.sh.txt)

### Software versions
- Compilers (Intel or GNU, and version): gcc 9.3.0
- NetCDF version: netcdf-fortran 4.5.3
- MPI version: OpenMPI 4.1.1
- ESMF version: ESMF 8.0.1

**Comment by yantosca** [comment]
Thanks for writing.  Usually this means a concentration has gotten very low and the chemistry can't converge.  This might be a side-effect of another error, though.

**Comment by lizziel** [comment]
Hi @sel-97, the fullchem restart file that comes with GCHP is for July 1. Using it for Jan 1 might cause problems. Do you get the same problem when starting on July 1st instead?

**Comment by lizziel** [comment]
Hi @sel-97, were you able to resolve this issue?

**Comment by dorosieun** [comment]
Hi @lizziel. I am the same user as @sel-97. 
I changed the simulation date from January 1st, 2020 to July 1st, 2019. But I still got the same problem..
This is part of runlog.
![스크린샷 2022-03-04 오후 3 33 07](https://user-images.githubusercontent.com/87462290/156711933-55580e3b-3897-4801-b88b-8f58d569b72c.png)
![스크린샷 2022-03-04 오후 3 33 35](https://user-images.githubusercontent.com/87462290/156711996-4296575c-3234-4312-a2b2-0e9e05080749.png)

**Comment by yantosca** [comment]
Thanks for the feedback.  That is an error in the integrator.  I wonder if it is either an MPI problem on your system or is caused by bad values in your restart file.

**Comment by sdeastham** [comment]
I wonder if this is related to https://github.com/geoschem/geos-chem/issues/1115#issuecomment-1065294147 ? I would be surprised if this is MPI related.

**Comment by yantosca** [comment]
Good point @sdeatham.
