### ISSUE TITLE
[QUESTION] how to run with multi-node

### ISSUE THREAD

**Issue by dorosieun** [geoschem/gchp#203]
# Ask a question about GCHP:

 

Hi, 
I succeed to run GCHP with one node and multi-core. 
(ex: TOTAL_CORES=36
       NUM_NODES=1 
       NUM_CORES_PER_NODE=36 )
But, I failed to run with multi-node.
The computer that I use has 15 nodes and 36 cores per node. 

The modified part of file is below. 
[ runConfig.sh ]
![스크린샷 2022-02-25 오후 3 05 54](https://user-images.githubusercontent.com/87462290/155663337-4f8dfa28-9d63-4cdf-83f1-254e736ce211.png)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/8139009/runConfig.sh.txt)

This is the batch job run script (I use pbs scheduler)
run code: $qsub gchp.run.sh
![스크린샷 2022-02-25 오후 3 08 16](https://user-images.githubusercontent.com/87462290/155663555-1e382c14-915d-4754-88e0-75cc2ffd830d.png)

and I got this error massage.
![스크린샷 2022-02-25 오후 3 11 21](https://user-images.githubusercontent.com/87462290/155663861-b0cea5c4-f5de-49a1-8593-c13b3d8f486f.png)

Is there anything doesn't match with what I intended?
Should I have to use multirun script to submit a batch job to run GCHP with multi node?

I already watched the GCHP tutorial Youtube and followed.
Thanks to the video, I could compile and run with single node, but there is no example of multi-node run.
So, I need your help.

Thank you for your time and help.

> software versions
Compilers (Intel or GNU, and version): gcc 9.3.0
NetCDF version: netcdf-fortran 4.5.3
MPI version: OpenMPI 4.1.1
ESMF version: ESMF 8.0.1

**Comment by lizziel** [comment]
Hi @dorosieun - Nothing pops out as wrong in your setup. I believe users have run GCHP on Pleiades before and perhaps one of them can help you trouble-shoot running multi-node simulations on that cluster. @LiamBindle, @sdeastham?

Regarding multi-node versus multi-run, you are trying to do a multi-node simulation and not multi-run. Multi-run means submitting multiple consecutive GCHP simulations. For example, splitting up a 1-year run into twelve 1-month jobs would be what we call a multi-run.

**Comment by dorosieun** [comment]
@lizziel, thank you for your kind explanation :>

**Comment by LiamBindle** [comment]
Hi @dorosieun, what cluster are you using? 

It looks like `mpirun` isn't aware of the other host, so I'm wondering if MPI+PBS is misconfigured. Do you have access to a cluster support staff? They would be better able to help with how to launch multinode MPI jobs for your specific cluster.
