### ISSUE TITLE
[QUESTION] Time formats in ExtData

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/gchp#204]
### What institution are you from?
University of York

### Description of the problem
I'm trying to add new emissions from one file to GCHP. I've been able to run the standard model without problems. When I add my emissions file to HEMCO_Config.rc and ExtData.rc, the model falls over at ExtData. It looks like the error is coming from reading the time frequency of the file, but I can't figure out the problem.

The netcdf is COARDS compliant and works without any problems in GCClassic, and I'm using the same line in HEMCO_Config.rc as the GCClassic run.

For clarity: the emissions file has annual emissions, with two variables, "UK" and "ALL".
The relevant HEMCO_Config.rc line is:
`0 EMEP_NO ./EmepDir/NOx_sumallsectors_2000_to_2019.nc ALL 2000-2019/1/1/0 C xy kg/m2/s NO - 1 10000`
And ExtData.rc line:
`EMEP_NO kg/m2/s N Y F%y4-01-01T00:00:00 none none ALL ./EmepDir/NOx_sumallsectors_2000_to_2019.nc`

### GEOS-Chem version
v13.3.4

[ExtData.rc](https://github.com/geoschem/GCHP/files/8140231/ExtData.rc.txt)
[HEMCO_Config.rc](https://github.com/geoschem/GCHP/files/8140232/HEMCO_Config.rc.txt)

```

> `0000: MAPL.GENERIC: INFO: Finished the 'Initialize' stage of the gridded component 'EXTDATA'
> 0000: MAPL.GENERIC: INFO: Started the  'Run' stage of the gridded component 'EXTDATA'
> ...skipping...
> gchp               0000000002F357FB  Unknown               Unknown  Unknown
> gchp               0000000002F656F1  Unknown               Unknown  Unknown
> gchp               0000000002F64415  Unknown               Unknown  Unknown
> gchp               0000000001565720  mapl_filemetadata         155  FileMetadataUtilities.F90
> gchp               00000000018261C4  mapl_extdatagridc        2332  MAPL_ExtDataGridCompMod.F90
> gchp               000000000181C975  mapl_extdatagridc        1392  MAPL_ExtDataGridCompMod.F90
> gchp               00000000021A9AF6  Unknown               Unknown  Unknown
> gchp               00000000021AD8AF  Unknown               Unknown  Unknown
> gchp               00000000021BEF92  Unknown               Unknown  Unknown
> gchp               00000000021AAFAA  Unknown               Unknown  Unknown
> gchp               0000000001EAE3CD  Unknown               Unknown  Unknown
> gchp               0000000001C47CB1  Unknown               Unknown  Unknown
> gchp               00000000014F97DE  mapl_genericmod_m        1839  MAPL_Generic.F90
> gchp               00000000021A9AF6  Unknown               Unknown  Unknown
> gchp               00000000021AD8AF  Unknown               Unknown  Unknown
> gchp               00000000021BEF92  Unknown               Unknown  Unknown
> gchp               00000000021AAFAA  Unknown               Unknown  Unknown
> gchp               0000000001EAE3CD  Unknown               Unknown  Unknown
> gchp               0000000001C47CB1  Unknown               Unknown  Unknown
> gchp               0000000000E6B0D6  mapl_capgridcompm        1233  MAPL_CapGridComp.F90
> gchp               0000000000E68C0A  mapl_capgridcompm        1177  MAPL_CapGridComp.F90
> gchp               0000000000E681B4  mapl_capgridcompm         803  MAPL_CapGridComp.F90
> gchp               00000000021A9AF6  Unknown               Unknown  Unknown
> gchp               00000000021AD8AF  Unknown               Unknown  Unknown
> gchp               00000000021BEF92  Unknown               Unknown  Unknown
> gchp               00000000021AAFAA  Unknown               Unknown  Unknown
> gchp               0000000001EAE3CD  Unknown               Unknown  Unknown
> gchp               0000000001C47CB1  Unknown               Unknown  Unknown
> gchp               0000000000E6D323  mapl_capgridcompm         932  MAPL_CapGridComp.F90
> gchp               0000000000E62A0A  mapl_capmod_mp_ru         246  MAPL_Cap.F90
> gchp               0000000000E62221  mapl_capmod_mp_ru         211  MAPL_Cap.F90
> gchp               0000000000E60E36  mapl_capmod_mp_ru         154  MAPL_Cap.F90
> gchp               0000000000E6053F  mapl_capmod_mp_ru         129  MAPL_Cap.F90
> gchp               0000000000427402  MAIN__                     31  GCHPctm.F90
> gchp               0000000000426092  Unknown               Unknown  Unknown
> libc-2.17.so       00007FCD33990555  __libc_start_main     Unknown  Unknown
> gchp               0000000000425FA9  Unknown               Unknown  Unknown`

```

**Comment by lizziel** [comment]
Hi @LukeFakes. You can try turning on the MAPL ExtData log prints to see if additional information is printed to the log file `allPEs.log`. First check that there isn't already helpful information there. To enable the prints set `CAP.EXTDATA` option `level` in run directory file `logging.yml` to `DEBUG` to send all thread MAPL ExtData (input) prints to output file `allPEs.log`. Then rerun (no need to compile again). More information on that [here](https://gchp.readthedocs.io/en/latest/supplement/rundir-config.html#enable-maximum-print-output).

That being said, based on the traceback it looks like your issue has to do with the time units string in your file. Line 155 of FileMetadataUtilities.F90 is [this](https://github.com/geoschem/MAPL/blob/a96739015a3da07954b17a036add99b20f88bdf0/base/FileMetadataUtilities.F90#L155). The correct format for netcdf time unit metadata should be like "days since 2007-01-01 00:00:00". Days, hours, minutes, and seconds are supported.

**Comment by lizziel** [comment]
Hi @LukeFakes, were you able to resolve this issue?

**Comment by LukeFakes** [comment]
Hi @lizziel, I'm afraid that hasn't solved the problem yet. I've updates the time format from "hours since ..." to "days since..." and turned on the debugging option, but the job still fails. 

I've found using making a global version of the emissions file (previously a regional file over the EMEP domain) lets the model run without errors. 

Is this a known issue? I see that the default HEMCO_Config.rc for GCHP has no regional inventories turned on. Does this mean to use regional inventories we should be using global emissions and region masks?

**Comment by lizziel** [comment]
Hmm, we haven't had any issues running regional inventories in the past, such as DICE-Africa which used to be on by default. Would it be possible to share your regional emissions file with us so we can test with it? I'm curious what the problem is and if we need better error handling to detect it.

**Comment by LukeFakes** [comment]
Hi Lizzie,
So I've been trying to get the files to work using one example file, which had annual emissions.
The HEMCO_Config.rc line I've used is:
`0 EMEP_NO_ALL ./NOx_sumallsectors_2000_to_2019.nc 2000-2019/1/1/0 C xy kg/m2/s NO - 1 10000`
and corresponding ExtData.rc line:
`EMEP_NO_ALL kg/m2/s N Y F%y4-01-01T00:00:00 none none ALL ./NOx_sumallsectors_2000_to_2019.nc`

The file I'm using is here: 
https://drive.google.com/drive/folders/1XvLjChSvYW0Ki-1suUl0xzgg99rJuhgA?usp=sharing

**Comment by sdeastham** [comment]
Hi @LukeFakes - is your HEMCO_Config.rc line complete? There should be an entry between the file path and date string to specify the variable being read (presumably "ALL" in this case).

[EDIT: Of course, an irritating feature of ExtData/HEMCO interactions is that it doesn't really matter what is written there... but I imagine that if it is missing that will upset the HEMCO parser]

**Comment by LukeFakes** [comment]
Sorry, that's a mistake from getting mixed up between edited versions of HEMCO_Config. I'm using:
`0 EMEP_NO_ALL ./NOx_sumallsectors_2000_to_2019.nc ALL 2000-2019/1/1/0 C xy kg/m2/s NO - 1 10000`

**Comment by sdeastham** [comment]
Ah got it! OK, I think I see the issue. The time format in the regional file is corrupted. I see

`time:units = "hours since 2000-01-01 00:00:00 00:00"`

Looking in the MAPL `FileMetadataUtilities.F90` code at the line indicated by the traceback, MAPL is choking when reading the units of time. In this case the problem is that they're specified twice so MAPL can't parse the string. Try dropping the additional "00:00" at the end and see if that helps? I didn't look at the global file I'm afraid so not sure if that has the same issue (which would be weird if that file then works).

EDIT: Just checked and it looks like the GLOBAL file has correctly formatted time units, so I strongly suspect this is the problem!

**Comment by LukeFakes** [comment]
That seems to have been the problem! Thanks for your help. Strange that the same files didn't cause issues in GCClassic runs. 

Thank you both for your help!

**Comment by lizziel** [comment]
I'm glad that fixed it. Unlike GC-Classic, GCHP uses the MAPL library for I/O. MAPL is generally more strict about input file formats than what we have in GC-Classic, hence you didn't have any problems with the file in your GC-Classic runs.
