### ISSUE TITLE
Way to extend the memory capacity of 'ExtData.rc' file 

### ISSUE THREAD

**Issue by SadiaToma** [geoschem/gchp#205]
### Ask a question about GEOS-Chem:
Hi, Good morning. I have been trying to add a new emission inventory in the 'ExtData.rc' file. The simulation is running with a subsection of the inventory. However, fails if I add the full inventory/more lines, and I am getting the following error:

`Modifying HEMCO_Config.rc
Setting CO2 concentration to 423.9 ppmv
pe=00019 FAIL at line=00496    MAPL_CapGridComp.F90                     <status=30>
pe=00019 FAIL at line=00827    MAPL_CapGridComp.F90                     <status=30>
pe=00019 FAIL at line=00433    MAPL_Cap.F90                             <status=30>
pe=00019 FAIL at line=00309    MAPL_Cap.F90                             <status=30>
pe=00019 FAIL at line=00151    MAPL_Cap.F90                             <status=30>
pe=00019 FAIL at line=00129    MAPL_Cap.F90                             <status=30>
pe=00019 FAIL at line=00029    GCHPctm.F90                              <status=30>
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 19 in communicator MPI_COMM_WORLD
with errorcode 70632384.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[c092:30371] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
pe=00029 FAIL at line=00496    MAPL_CapGridComp.F90                     <status=30>
pe=00029 FAIL at line=00827    MAPL_CapGridComp.F90                     <status=30>
pe=00029 FAIL at line=00433    MAPL_Cap.F90                             <status=30>
pe=00029 FAIL at line=00309    MAPL_Cap.F90                             <status=30>
pe=00029 FAIL at line=00151    MAPL_Cap.F90                             <status=30>
pe=00029 FAIL at line=00129    MAPL_Cap.F90                             <status=30>
pe=00029 FAIL at line=00029    GCHPctm.F90                              <status=30>`

I think it is possibly because of the memory limitation of the 'ExtData.rc' file since I have been trying to include the entire inventory in the 'ExtData.rc' file by removing all possible turned off emissions/met, and the commented lines. I am wondering is there any way to add the memory capacity of the ExtData file? Moreover, I need to add additional lines of code which further needs additional memory space. So, it would be very helpful, if anyone can help me in this regard. 

Thanks,
Sadia

**Comment by sdeastham** [comment]
@lizziel I believe this is another instance of ExtData.rc becoming too long to be held in a single variable of size `ESMF_MAXSTR`. The return code (30) is coming from an ESMF call to read ExtData.rc, and ESMF status 30 is `ESMF_RC_MEM` which should indicate a memory exceedance for a variable (based on other uses of that return code elsewhere in ESMF). I recall that there were a couple of workarounds for this; do you remember what they were, other than just cutting lines out of ExtData.rc? Unfortunately the version of GCHP being modified here is rather old so updating to the new ExtData format isn't an option (even if that was already available).

**Comment by lizziel** [comment]
Unfortunately the only other work-around besides rebuilding ESMF is removing spaces in the uncommented lines in the file. I was able to minimize spaces and get the string small enough to not have to modify ESMF.

If you successfully change ESMF using the guidance from GMAO definitely follow-up here. I found it in ESMF way back when I ran into this issue but that was so long ago I don't recall where it was. Plus it was an older version of ESMF so things may have changed.

**Comment by SadiaToma** [comment]
Hi @lizziel,
Thanks for your reply. Firstly, I tried removing uncommented lines, but that doesn't give me enough space to accommodate the entire new inventory. Secondly, I also tried rebuilding the ESMF and GCHP, but still getting the following error:

`Modifying HEMCO_Config.rc
Setting CO2 concentration to 423.9 ppmv
pe=00021 FAIL at line=00527    MAPL_Config.F90                          <status=536>
pe=00021 FAIL at line=00509    MAPL_CapGridComp.F90                     <status=536>
pe=00021 FAIL at line=00827    MAPL_CapGridComp.F90                     <status=536>
pe=00021 FAIL at line=00433    MAPL_Cap.F90                             <status=536>
pe=00021 FAIL at line=00309    MAPL_Cap.F90                             <status=536>
pe=00021 FAIL at line=00151    MAPL_Cap.F90                             <status=536>
pe=00021 FAIL at line=00129    MAPL_Cap.F90                             <status=536>
pe=00021 FAIL at line=00029    GCHPctm.F90                              <status=536>
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 21 in communicator MPI_COMM_WORLD
with errorcode -2486368.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[c092:17646] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2193
pe=00029 FAIL at line=00527    MAPL_Config.F90                          <status=536>
pe=00029 FAIL at line=00509    MAPL_CapGridComp.F90                     <status=536>
pe=00029 FAIL at line=00827    MAPL_CapGridComp.F90                     <status=536>
pe=00029 FAIL at line=00433    MAPL_Cap.F90                             <status=536>
pe=00029 FAIL at line=00309    MAPL_Cap.F90                             <status=536>`

Do you have any other suggestions for me to move forward? Thanks.

**Comment by sdeastham** [comment]
Hi @SadiaToma - going to that line in `MAPL_Config.F90`, you're hitting an error where `NBUF_MAX` (which is just `MSZ*LSZ`) is still being exceeded. How much did you increase MSZ and/or LSZ? Did you get _any_ increase in the number of lines you could store, and did you completely rebuild (with a clean build directory) GCHP?

**Comment by sdeastham** [comment]
Following up - I see that (maddeningly!) `MAPL_Config.F90` defines its own copies of `MSZ` and `LSZ` on lines 450 and 451. Have you tried increasing those to match the ESMF definitions?

**Comment by lizziel** [comment]
Whether the value should be changed in ESMF or MAPL can be figured out from following the traceback. Have you followed the traceback to see where it is crashing? If it is a call to an ESMF subroutine to get configuration file then the issue is in ESMF. If it's call to a MAPL routine it's in MAPL.

Thanks for the reminder about NBUF_MAX. This jogged my memory about it. You should only need to change one of the two variables since I believe one is the line length and the other is number of lines (excluding commented out and blank lines). The product is therefore used to set the total maximum number of characters.

**Comment by SadiaToma** [comment]
Thanks, @sdeastham  and @lizziel. The issue has been solved by changing the NBUF_MAX and MSZ variables respectively in the ESMF and MAPL config files. Thanks for your suggestions and for helping me out.
