### ISSUE TITLE
[FEATURE REQUEST] Make timing output easier to understand

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#206]
The GCHP log file has timing information printed at the end of the run summarizing the run times of various components in the model. As discussed in https://github.com/geoschem/GCHP/issues/194, the timing results are difficult to parse. This feature request is to improve the timing output so that understanding and getting useful information from the timing summary does not require knowledge of MAPL timers.

A few ideas for this:
1. Send a summary of useful GCHP timing information to an external file. Work is in progress to send timing output for GC-Classic to a json file (see [GEOS-Chem PR #1120](https://github.com/geoschem/geos-chem/pull/1120)). We could do the same for GCHP.
2. Write our own timer summary to the log.
3. Work with GMAO to make the MAPL timer output easier to understand.

**Comment by lizziel** [comment]
Related issues:
https://github.com/GEOS-ESM/MAPL/issues/1418
https://github.com/GEOS-ESM/MAPL/issues/1419

I added documentation to GCHP ReadTheDocs to describe the timers in 13.4. For now it will be under Supplemental Guides ->  Run Directory Configuration -> Debugging -> Configuring MAPL Timers. Timers are not actually configured from the run directory right now but will be in the future, though not until we upgrade to MAPL 3 which is not yet released.

**Comment by lizziel** [comment]
GCHP 14.0.0 uses MAPL 2.18.3 which has improved and expanding timing output. The GCHP timing output section of ReadTheDocs needs to be updated before the release.

**Comment by lizziel** [comment]
I am keeping this feature request open as a reminder to update ReadTheDocs before the 14.1 release. That version uses MAPL 2.26.

**Comment by msulprizio** [comment]
@lizziel Has ReadTheDocs been updated for this yet? This is the only GCHP issue remaining for 14.1.0.

**Comment by lizziel** [comment]
It has not. I'll change the milestone to 14.1.1.

**Comment by lizziel** [comment]
Timing is now described on GCHP ReadTheDocs on the [output files page](https://gchp.readthedocs.io/en/stable/user-guide/output_files.html).
