### ISSUE TITLE
[QUESTION] Setting up an aws ec2 instance with slurm and gchp

### ISSUE THREAD

**Issue by laestrada** [geoschem/gchp#208]
# Ask a question about GCHP:
Marcus wrote:
"I'm a new MSc student looking for running atmospheric models (GCHP) on AWS. I wonder if you could help me setting up an AWS EC2 Instance with Slurm working. I want to run commands with sbatch but I couldn't find any simple way to install that. If there is a AMI or simple help from you that would be great!

best regards,
Marcus"

**Comment by laestrada** [comment]
Thanks for writing in. Getting slurm configured on an EC2 instance can be difficult, so using an existing AMI with slurm installed is probably the easiest option. Are you hoping to run GCHP on a single node or using multiple nodes? 

If single node, then we have an ami available with slurm and the software packages needed for GCClassic installed. It should be pretty easy to install any additional packages through spack.

If multi-node, your best option is to use [AWS parallel cluster](https://docs.aws.amazon.com/parallelcluster/latest/ug/what-is-aws-parallelcluster.html). Parallel cluster is a command line tool used to create a cloud-resident cluster for running HPC applications. Slurm is one of the available job scheduler options available with parallel cluster, but with the default parallel cluster ami you will need to install the software packages needed to run GCHP (we recommend using [spack](https://spack.readthedocs.io/en/latest/) to do this). I can send you some resources to help you with the setup if you would like to go this route, as it is a bit more complicated.

To make multi-node cloud runs easier in the future, we are working on creating a parallel cluster-compatible ami with gchp installed, but it is not currently a high priority, so I do not have an estimate of when such an ami would be released.

If you run into issues, the best place to get help is creating an issue on the GCHP github repository. This allows us to track all the issues in one centralized location and can be helpful for others that are running into the same problems.

--
Lucas

**Comment by LiamBindle** [comment]
Hi Marcus, I've started working on some instructions for setting up AWS ParallelCluster for running GCHP. You can find the instructions here: https://gchp.readthedocs.io/en/docs-updates/ (see [Using AWS ParallelCluster](https://gchp.readthedocs.io/en/docs-updates/supplement/setting-up-aws-parallelcluster.html#id1) and [Building GCHP’s Dependencies](https://gchp.readthedocs.io/en/docs-updates/supplement/building-gchp-dependencies.html)). These are still a work in progress, and I'll be expanding on the AWS ParallelCluster instructions in the coming days.

**Comment by LiamBindle** [comment]
Hi Marcus, the docs are now here:  https://gchp.readthedocs.io/en/docs-dev/.
