### ISSUE TITLE
[QUESTION] Error when running on multinodes : PMIX ERROR: BAD-PARAM in file base/bfrop_base_unpack.c at line 692

### ISSUE THREAD

**Issue by lorenzocostantino** [geoschem/gchp#217]
Hi,
I downloaded and compiled GCHP 13.4.0 (but I see I have same problem with 13.3.4 if I re-compile&run it now, even if I menaged to compile&run it properly in the past). I use ubuntu on a super-computer (CSC).

Everything works fine, if I run gchp exec the with mpirun command : **mpirun -np 6 --oversubscribe ./gchp** 

Everything works fine, if I submit a script (for a single node and 6 tasks) as :  **sbatch C24_batch_job.slurm6.sh** 
where C24_batch_job.slurm6.sh is :
```
#!/bin/bash
#SBATCH --account=xxxxxxx
#SBATCH --ntasks=6
#SBATCH --time=00:05:00
#SBATCH --partition=small  
#SBATCH --mem=36000 
#SBATCH --job-name=GCHP24

# Misc. configuration
module list     # print loaded modules
set -e          # if a subsequent command fails, treat it as fatal (don't continue)
set -x          # for remainder of script, echo commands to the job's log file

# Simple GCHP launch
rm -f cap_restart  gcchem*         # delete restart start time file if present
./runConfig.sh                     # update configuration files
srun ./gchp    
```

I have an error if I try to launch gchp submitting the following script (for 6 nodes and 6 tasks each) : C24_batch_job.slurm-HCP.sh 
where C24_batch_job.slurm-HCP.sh  is
```
#!/bin/bash
#SBATCH --account=xxxxxxx
#SBATCH --job-name=GCHP-test
#SBATCH --partition=large
#SBATCH --time=00:05:00
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=6
#SBATCH --mem-per-cpu=4000

# Misc. configuration
module list     # print loaded modules
set -e          # if a subsequent command fails, treat it as fatal (don't continue)
set -x          # for remainder of script, echo commands to the job's log file

# Simple GCHP launch
rm -f cap_restart  gcchem*                       # delete restart start time file if present
./runConfig.sh                                   # update configuration files

srun  ./gchp     
```
I have the following error in the slurm output 

```
...          
ConcAboveSfc.frequency         : 10000                HISTORY.rc          
ConcAboveSfc.duration          : 240000               HISTORY.rc          
+ srun ./gchp
[r03c46.bullx:18165] PMIX ERROR: BAD-PARAM in file base/bfrop_base_unpack.c at line 692
[r03c46.bullx:18165] PMIX ERROR: BAD-PARAM in file dstore_base.c at line 2225
[r03c08.bullx:23449] PMIX ERROR: BAD-PARAM in file base/bfrop_base_unpack.c at line 692
[r03c08.bullx:23449] PMIX ERROR: BAD-PARAM in file dstore_base.c at line 2225
[r03c26.bullx:102888] PMIX ERROR: BAD-PARAM in file base/bfrop_base_unpack.c at line 692
[r03c26.bullx:102888] PMIX ERROR: BAD-PARAM in file dstore_base.c at line 2225
[r03c40.bullx:168028] PMIX ERROR: BAD-PARAM in file base/bfrop_base_unpack.c at line 692
[r03c40.bullx:168028] PMIX ERROR: BAD-PARAM in file dstore_base.c at line 2225
[r18c12.bullx:77268] PMIX ERROR: BAD-PARAM in file base/bfrop_base_unpack.c at line 692
[r18c12.bullx:77268] PMIX ERROR: BAD-PARAM in file dstore_base.c at line 2225
[r18c11.bullx:18301] PMIX ERROR: BAD-PARAM in file dstore_base.c at line 2225
...
--------------------------------------------------------------------------
WARNING: Open MPI failed to TCP connect to a peer MPI process.  This
should not happen.

Your Open MPI job may now hang or fail.

  Local host: r18c12
  PID:        77268
  Message:    connect() to 10.140.37.199:1027 failed
  Error:      Operation now in progress (115)
...
```

Any idea, if I compiled with bad options or something else ? 
Thanks in advance

**Comment by lizziel** [comment]
Hi @lorenzocostantino, thanks for reaching out. You mentioned you previously were able to build and run 13.3.4. Was that using multiple nodes?  What version of OpenMPI, Slurm, and PMIX are you using? If yes, do you know if there were any recent updates to slurm on your cluster?

The error you are running into looks like a slurm problem that is possibly specific to the version of OpenMPI and PMIX you are using. If there is a cluster admin team I suggest contacting them and letting them know about the error you are encountering. They may need to rebuild one of the libraries with a newer version or you may need an additional command in srun to specify pmix.

**Comment by lorenzocostantino** [comment]
Hi,

thanks for the insight. It really helped. Actually, using spack, I had to load esmf with right dependencies : 
`spack install esmf%gcc@9.1.0  ^netcdf-c^hdf5^openmpi+pmix       schedulers=slurm `
