### ISSUE TITLE
[QUESTION] NOx data CEDSv2 inventory

### ISSUE THREAD

**Issue by lorenzocostantino** [geoschem/gchp#219]
Hi,

I see in urls.txt file that GCHP download the following file for CDESv2 nitrogen emissions : 
`http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2021-06/2019/NO-em-anthro_CMIP_CEDS_2019.nc`

And then it is used to derive emissions by sector, as shown by ExtData.rc :
```
CEDS_NO_AGR  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_agr  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
CEDS_NO_ENE  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_ene  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
CEDS_NO_IND  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_ind  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
CEDS_NO_TRA  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_tra  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
CEDS_NO_RCO  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_rco  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
CEDS_NO_SLV  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_slv  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
CEDS_NO_WST  kg/m2/s N Y F%y4-%m2-01T00:00:00 none none NO_wst  ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc
```

Looking file specifications, it says : **Annual Anthropogenic Emissions of NOx prepared for input4MIPs**

But when selecting a one specific field/sector I see: **NO anthropogenic emissions from .... sector**

I would like to know if this file refers to NO or NOx (or NOx expressed as NO) ?

**Comment by lizziel** [comment]
Hi @lorenzocostantino, thanks for asking about this. While the original CEDS data contains NOx we convert it to NO during pre-processing of the data for use in GEOS-Chem. The pre-processing is briefly mentioned in our data [README](http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2021-06/README), and you can see how this specific conversion is done in file `CEDS_edit.sh` at http://geoschemdata.wustl.edu/ExtData/HEMCO/CEDS/v2021-06/scripts/. It looks like in our pre-processing we did not edit the global metadata and hence `NOx` is still present in some of the attributes.
