### ISSUE TITLE
[FEATURE REQUEST] Erroneous duplicate removal of multi-word debug flags

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#22]
Multi-word compiler arguments should be wrapped in `\"SHELL:word1 [word2 [...]]\"` to prevent CMake from splitting the words up when it removes duplicate command line arguments. I did this for `Release` flags a while back but I didn't do this for `Debug` flags. This needs to be done in 
- [ESMA_cmake/GNU.cmake](https://github.com/geoschem/ESMA_cmake/blob/32a615670b73857c22dd56087678f8fdd82e8f93/GNU.cmake)
- [ESMA_cmake/Intel.cmake](https://github.com/geoschem/ESMA_cmake/blob/32a615670b73857c22dd56087678f8fdd82e8f93/Intel.cmake)

This will break the `Debug` build type until this is fixed.

**Comment by lizziel** [comment]
@LiamBindle I am going to do the pre-release for 13.0.0-alpha.4 in the next couple days. Do you need this included?

**Comment by LiamBindle** [comment]
@lizziel No, but this should be done prior to 13.0.0's release. Seb was trying to compile GCHPctm with debug flags this afternoon and ran into some problems. This issue is just for tracking this bug. Thanks for checking though!

**Comment by lizziel** [comment]
@LiamBindle, are you all set with this issue?

**Comment by LiamBindle** [comment]
The debug build is working now. We can revise it in the future as needed, but this can be closed
