### ISSUE TITLE
[SUBMODULE UPDATES] Implementation of TOMAS in GCHP

### ISSUE THREAD

**Issue by BettyCroft** [geoschem/gchp#220]
## Brief Description

Code updates for implementation of TOMAS in GCHP

## Related Issues

Code updates 1) enabling TOMAS to work in GCHP, 2) removing TOMAS' dependency on bpch diagnostics, 3) adding a TOMAS diagnostic collection and 4) adding blowing snow sea salt to TOMAS. The latter 3 items would also be suitable for GC-Classic.

## Submodule Pull Requests

* [ ] https://github.com/geoschem/geos-chem/pull/1261
* [ ] https://github.com/geoschem/HEMCO/pull/145
* [ ] https://github.com/geoschem/GCHP/pull/221

**Comment by lizziel** [comment]
Thanks @BettyCroft! This update will go into 14.1.0.

**Comment by Jourdan-He** [comment]
Hi @BettyCroft , all your updates have been merged into a feature/TOMAS branch waiting to be tested.

**Comment by Jourdan-He** [comment]
I have test run the updates, and it's completed successfully. Pull requests for merging into dev have been created.

**Comment by BettyCroft** [comment]
Great news - thanks!

**Comment by msulprizio** [comment]
These instructions are now superseded by PR https://github.com/geoschem/GCHP/pull/252.
