### ISSUE TITLE
[BUG/ISSUE] Implementation of HTAPv3 for GCHP without any error but no emission concentration in the output file

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/gchp#225]
### What institution are you from?
Washington University in St. Louis

### Description of the problem
I am trying to add new global HTAPv3 emission inventory for GCHP by editing HEMCO_Config.rc and ExtData.rc files. The simulation ran well without any error message. But the emission and concentration outputs are not reasonable. It looks like the emission from HTAPv3 is not read successfully because the anthropogenic emission is basically zero. For example, Anthropogenic emissions output for NO is only default fill value of 1e-25 at the 72 level.

Concentration output of NO2 at the first level:
![NO2-conc-HTAPv3](https://user-images.githubusercontent.com/75513026/172492237-aea99c01-bcd4-4b92-a6d5-3690aff589f8.PNG)

Anthropogenic emissions of NO from HTAPv3:
![HTAPv3-emission](https://user-images.githubusercontent.com/75513026/172490387-710792db-51a5-4d76-a2b6-7987ab0f36a5.png)
Anthropogenic emissions of NO from default CEDSv2:
![CEDSv2-emission](https://user-images.githubusercontent.com/75513026/172490403-e9ce3ecc-3ccc-4851-b887-08ce2e33d12b.png)

The processed emission files attributes:
```
$ ncdump -h HTAPv3_NO_0.1x0.1_2017.nc
netcdf HTAPv3_NO_0.1x0.1_2017 {
dimensions:
        time = UNLIMITED ; // (12 currently)
        lat = 1800 ;
        lon = 3600 ;
variables:
        double time(time) ;
                time:_FillValue = NaN ;
                time:units = "days since 2000-01-01 00:00:00" ;
                time:delta_t = "0000-01-00 00:00:00" ;
                time:axis = "T" ;
                time:standard_name = "Time" ;
                time:long_name = "Time" ;
                time:calender = "standard" ;
        double lat(lat) ;
                lat:_FillValue = NaN ;
                lat:units = "degrees_north" ;
                lat:axis = "Y" ;
                lat:standard_name = "Latitude" ;
                lat:lomg_name = "Latitude" ;
        double lon(lon) ;
                lon:_FillValue = NaN ;
                lon:units = "degrees_east" ;
                lon:axis = "X" ;
                lon:standard_name = "Longitude" ;
                lon:long_name = "Longitude" ;
        double NO_SHP(time, lat, lon) ;
                NO_SHP:_FillValue = NaN ;
                NO_SHP:long_name = "NO emission in sector SHP" ;
                NO_SHP:units = "kg m-2 s-1" ;
        double NO_ENE(time, lat, lon) ;
                NO_ENE:_FillValue = NaN ;
                NO_ENE:long_name = "NO emission in sector ENE" ;
                NO_ENE:units = "kg m-2 s-1" ;
        double NO_IND(time, lat, lon) ;
                NO_IND:_FillValue = NaN ;
                NO_IND:long_name = "NO emission in sector IND" ;
                NO_IND:units = "kg m-2 s-1" ;
        double NO_SLV(time, lat, lon) ;
                NO_SLV:_FillValue = NaN ;
                NO_SLV:long_name = "NO emission in sector SLV" ;
                NO_SLV:units = "kg m-2 s-1" ;
        double NO_TRA(time, lat, lon) ;
                NO_TRA:_FillValue = NaN ;
                NO_TRA:long_name = "NO emission in sector TRA" ;
                NO_TRA:units = "kg m-2 s-1" ;
        double NO_RCO(time, lat, lon) ;
                NO_RCO:_FillValue = NaN ;
                NO_RCO:long_name = "NO emission in sector RCO" ;
                NO_RCO:units = "kg m-2 s-1" ;
        double NO_WST(time, lat, lon) ;
                NO_WST:_FillValue = NaN ;
                NO_WST:long_name = "NO emission in sector WST" ;
                NO_WST:units = "kg m-2 s-1" ;
        double NO_AGR(time, lat, lon) ;
                NO_AGR:_FillValue = NaN ;
                NO_AGR:long_name = "NO emission in sector AGR" ;
                NO_AGR:units = "kg m-2 s-1" ;

// global attributes:
                :Title = "COARDS/netCDF file containing monthly emissions of NO" ;
                :Conventions = "COARDS" ;
}
```
Example plots from HTAPv3 emissions of NO from sector transportation to show it does have nonzero emissions from the netcdf file:
![NO-2017-HTAPv3](https://user-images.githubusercontent.com/75513026/172491057-1234d02d-42b4-4788-ae0a-65051968c636.PNG)

### GEOS-Chem version
v13.2.1

### Description of code modifications
The source code is left as default. I only changed the HEMCO_Config.rc and ExtData.rc. 
The modified configuration files:
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/8856787/ExtData.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/8856788/HEMCO_Config.rc.txt)
[logging.yml.txt](https://github.com/geoschem/GCHP/files/8856810/logging.yml.txt)

### Log files
- Build log (if applicable):
- Run log (if applicable):
[run-HTAPv3.log.txt](https://github.com/geoschem/GCHP/files/8856835/run-HTAPv3.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/GCHP/files/8856836/HEMCO.log.txt)

The allPEs.log is too large to attach here. The relevant lines are:
```
0047: CAP.EXTDATA: DEBUG:  >> REFFTIME for /storage1/fs1/rvmartin/Active/dandan.z/edgar_HTAPv3_lumped_sector/HTAPv3_NO_0.1x0.1_%y4.nc: <>
0048: CAP.EXTDATA: DEBUG:  >> Frequency     : 0000-00-00 00:00:00
0049: CAP.EXTDATA: DEBUG:  >> REFFTIME for /storage1/fs1/rvmartin/Active/dandan.z/edgar_HTAPv3_lumped_sector/HTAPv3_NO_0.1x0.1_%y4.nc: <>
0050: CAP.EXTDATA: DEBUG:  >> Frequency     : 0000-00-00 00:00:00
0051: CAP.EXTDATA: DEBUG:  >> Frequency     : 0000-00-00 00:00:00
0052: CAP.EXTDATA: DEBUG:  >> REFFTIME for /storage1/fs1/rvmartin/Active/dandan.z/edgar_HTAPv3_lumped_sector/HTAPv3_NO_0.1x0.1_%y4.nc: <>
0053: CAP.EXTDATA: DEBUG:  >> REFFTIME for /storage1/fs1/rvmartin/Active/dandan.z/edgar_HTAPv3_lumped_sector/HTAPv3_NO_0.1x0.1_%y4.nc: <>
0054: CAP.EXTDATA: DEBUG:  >> REFFTIME for /storage1/fs1/rvmartin/Active/dandan.z/edgar_HTAPv3_lumped_sector/HTAPv3_NO_0.1x0.1_%y4.nc: <>

0049: CAP.EXTDATA: DEBUG:  >> REFFTIME for ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc: <>
0050: CAP.EXTDATA: DEBUG:  >> Frequency     : 0000-00-00 00:00:00
0051: CAP.EXTDATA: DEBUG:  >> Frequency     : 0000-00-00 00:00:00
0052: CAP.EXTDATA: DEBUG:  >> REFFTIME for ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc: <>
0053: CAP.EXTDATA: DEBUG:  >> REFFTIME for ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc: <>
0054: CAP.EXTDATA: DEBUG:  >> REFFTIME for ./HcoDir/CEDS/v2021-06/%y4/NO-em-anthro_CMIP_CEDS_%y4.nc: <>

```
### Software versions
- Compilers (Intel or GNU, and version): Intel
- NetCDF version: netcdf-c v 4.7.3; netcdf-fortran v4.5.2
- MPI version:
- ESMF version:

**Comment by lizziel** [comment]
Hi @1Dandan, it's hard to say based on this information alone. To be clear, your run did not have a run-time error, correct? I ask because your log file shows exit with an error after the first hour but you said it ran fine. Did you cancel the job which caused that error?

You can try doing the following and report back:

1) Add HTAP3 inventory diagnostics to `HEMCO_Diagn.rc` and `HISTORY.rc` by looking for existing diagnostics that start with INV in those files. Rerunning (no need to recompile) will output the HTAP3 data directly.
2) try changing the verbose and warnings settings at the top of `HEMCO_Config.rc` to 3 to get maximum output in the `HEMCO.log` file
3) Change the `level` setting in `logging.yml` for `CAP.EXTDATA` back to `WARNING.` This will greatly reduce the file size of `allPEs.log`. The relevant ExtData information in the file will get printed by all processors so we only need one. Alternatively, grep the log file you currently have for just one process, e.g. `0051`. Then search for the HTAP v3 sections and post them here.

**Comment by 1Dandan** [comment]
Thanks @lizziel. Yes, I manually terminated my job after 1 hour simulation. I will try your suggestions and attach relevant log files hopefully by the end of tomorrow.

**Comment by 1Dandan** [comment]
Hi @lizziel. I added HTAPv3 inventory diagnostics in `HEMCO_Diagn.rc` and `HISTORY.rc`, but the Emission output doesn't contain "Inv" diagnostics, and emission diagnostics starting with "Emis" still don't look right with zero emission fluxes. I am wondering if I have missed something else.
The emission output looks like:
[Emissions_attribute.txt](https://github.com/geoschem/GCHP/files/8894179/Emissions_attribute.txt)


The configuration files:
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/8894112/ExtData.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/8894113/HEMCO_Config.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/GCHP/files/8894114/HEMCO_Diagn.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/8894115/HISTORY.rc.txt)
[logging.yml.txt](https://github.com/geoschem/GCHP/files/8894116/logging.yml.txt)

The log files:
[allPEs.log.txt](https://github.com/geoschem/GCHP/files/8894152/allPEs.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/GCHP/files/8894153/HEMCO.log.txt)
[run-HTAPv3.log.txt](https://github.com/geoschem/GCHP/files/8894154/run-HTAPv3.log.txt)

**Comment by lizziel** [comment]
Hi @1Dandan, in your latest run it seems to have gone straight from initialize to finalize, without actually running any timesteps. What are your start and end dates set to in `runConfig.sh`? Also, try setting the `MAPL` entry for `root_level` to `DEBUG` in config file `logging.yml`.

**Comment by 1Dandan** [comment]
Thanks @lizziel, sorry I only checked the updated files. For that run, I used the start date and end date in `runConfig.sh` of 
```
Start_Time="20171201 000000"
End_Time="20171201 010000"
Duration="00000000 010000"
```
I didn't delete `cap_restart` and thus makes the simulation to start from `20171201 010000` for that run and for my current run as well. Thus my current run also starts with `20171201 010000`.

 I ran the simulation again with HTAPv3. I still encounter no emission fluxes problem. I have turned on `MAPL` entry for `root_level` to `DEBUG` for this run.
For the current run, I can see the outputs of starting with `Inv` in emission diagnostics, but still it is zero.
The attributes for the emission outputs:
[emission-attribute-01.txt](https://github.com/geoschem/GCHP/files/8912959/emission-attribute-01.txt)

Configuration files are:
[CAP.rc.txt](https://github.com/geoschem/GCHP/files/8912912/CAP.rc.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/8912913/ExtData.rc.txt)
[GCHP.rc.txt](https://github.com/geoschem/GCHP/files/8912914/GCHP.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/8912915/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/8912916/HISTORY.rc.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/8912917/runConfig.sh.txt)
[logging.yml.txt](https://github.com/geoschem/GCHP/files/8913004/logging.yml.txt)


Log files are:
[allPEs.log.txt](https://github.com/geoschem/GCHP/files/8912962/allPEs.log.txt)
[HEMCO.log.txt](https://github.com/geoschem/GCHP/files/8912963/HEMCO.log.txt)
[run-HTAPv3.log.txt](https://github.com/geoschem/GCHP/files/8912964/run-HTAPv3.log.txt)

**Comment by lizziel** [comment]
Hi @1Dandan, thanks for rerunning and posting all of the config and logs. I've traced the problem to a silent bug we were previously unaware of. In HEMCO_Config.rc you can apparently not use tabs between bracket name and true/false switch in the "Extension switches" section (used for based emissions in addition to extensions).

For HTAPv3 you need to change these lines to use spaces and not tabs:
```
    --> HTAPv3		       :       true	# 2000-2018
    --> HTAPv3_SHIP	       :       true	# 2000-2018
```

I'm going to follow-up with a separate bug report in GEOS-Chem and HEMCO about this so that we can get it fixed asap.

**Comment by 1Dandan** [comment]
Thanks @lizziel , this is really hard to find. Can I use tabs for the specific species emission under HTAPv3 and HTAPv3_SHIP?

**Comment by lizziel** [comment]
I believe you can but I have not tested it. In general it is best not to use tabs in our config files unless required by the config file format.

**Comment by 1Dandan** [comment]
Got it. I will avoid using tabs in config files. Just to let you know it indeed runs well when I replace tabs by spaces.
