### ISSUE TITLE
[QUESTION] ./ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2019 --> missing data 

### ISSUE THREAD

**Issue by lorenzocostantino** [geoschem/gchp#226]
# Ask a question about GCHP:

 

Hi,
I am running GCHP for 2019. 
An execution error has just let me realize that there are no data for 2019 in

http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_BIOVOC/v2019-10/0.5x0.625/2019/
http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_SEASALT/v2019-01/0.5x0.625/2019/
http://ftp.as.harvard.edu/gcgrid/data/ExtData/HEMCO/OFFLINE_SOILNOX/v2019-01/0.5x0.625/2019

for 30 September (for biovoc), October, November, December. How to solve it? 
PS: Can I use the higher res data from 0.25x0.3125/2019/10, - 11,- 12?

**Comment by msulprizio** [comment]
We no longer recommend using the Harvard ftp site. You should use the WashU site instead as that is the most up-to-date. See the following pages:

- https://geos-chem.readthedocs.io/en/latest/inputs/input-overview.html
- http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_BIOVOC/v2021-12/0.5x0.625/
- http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_SOILNOX/v2021-12/0.5x0.625/

We will update to these directories for the final 14.0.0 release. 

Offline sea salt emissions have not been updated beyond yet.  @hongjianweng may be able to provide an update. Last we heard in February 2022, he wrote:

>We have uploaded the new version OFFLINE_BIOVOC and OFFLINE_SOILNOX at native MERRA-2 (0.5 x 0.625, from 1980 to 202012) and GEOS-FP (0.25 x 0.3125, from 2014 to 202009). 
>
>These emissions were generated with GEOS-Chem 13.2.0 and the updates include:
>
>1. Use new version Yuan-processed MODIS LAI (v2021-06);
>2. Fix the unit bug for soil NOx emission;
>3. Add methanol(MOH) variables for biogenic VOCs emissions;
>4. All emissions are now all in kg species/m2/s instead of kgN/m2/s or kgC/m2/s before.
>
>For more information, please see README files, which I have also uploaded to Washu.
>
>I think we should update these new emissions for the next version. As for the update of sea salt and subsequent years soil NOx and biogenic VOCs, I'm afraid it will take longer because I need to prepare my graduation thesis recently, but these updates can be completed in six months.

If offline emissions are not available, you may also choose to enable the online emissions extensions instead.
