### ISSUE TITLE
[QUESTION] Calculating emissions from GCHP diagnostics.

### ISSUE THREAD

**Issue by LukeFakes** [geoschem/gchp#227]
I'm trying to work out the total emissions for a diagnostic from a GCHP stretched grid simulation, and wondered if there's a way to do this similar to the hemco standalone runs in GCClassic?

I have the emissions diagnostic output I need for a one day daily average, but I'm not sure how to get the  equivalent monthly hemco diagnostic, area of the grid cells and how sum over the model levels with a stretched grid.

**Comment by lizziel** [comment]
Hi @LukeFakes, you can get the area from the State_Met%Area field that is output to the State_Met collection. It contains the area per horizontal grid cell on the stretched grid you are running at. You can also add that to any other collection if you want it to be contained in the same file. For levels, do you mean vertical levels? The GCHP run has the same 72 vertical levels regardless of horizontal grid. 

Let us know if this doesn't answer all of your questions.

**Comment by LukeFakes** [comment]
Hi @lizziel, I didn't know that State_Met%Area was an option, thanks for making me aware! I'm trying to figure out why some emissions don't look to be coming out right in a stretched grid simulation and having difficulties, so that'll help

Re: vertical levels. I was getting myself confused about something with vertical emission distributions, not a problem any more.

**Comment by lizziel** [comment]
Okay, glad I could help.
