### ISSUE TITLE
[FEATURE REQUEST] Implement option for monthly checkpoint files in run directories

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#228]
The MAPL version included in GCHP 14.0 has the capability for configuring monthly checkpoint files. This means users should be able to output a restart file on the first the month for simulations long than one month. However, the option to do this is not included in the run directory. This feature should be added.

**Comment by lizziel** [comment]
@Jourdan-He, @LiamBindle mentioned you were going to tackle this one. Let me know when you are ready to work on it.

**Comment by Jourdan-He** [comment]
@lizziel I can work on it this week

**Comment by lizziel** [comment]
@Jourdan-He, I am doing some run directory work for 14.0 this morning and decided to throw in this update at the same time. 14.0.0 is about to be released and the GCHP benchmark plotting issue in GCPy reminded me this feature has not yet been added to the run directory (1-year and 10-year benchmarks need monthly restarts now that we run in 1-year chunks).

**Comment by Jourdan-He** [comment]
@lizziel Just created a PR#1365 for this

**Comment by lizziel** [comment]
@Jourdan-He, sorry, I meant I was already implementing the update. It is now in commit https://github.com/geoschem/geos-chem/commit/cbaa9be3acb6d2970719357ce964ff9ed454bbe9.
