### ISSUE TITLE
[DISCUSSION] Too many GCHP log files?

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#237]
### Discussed in https://github.com/geoschem/GCHP/discussions/153

<div type='discussions-op-text'>

<sup>Originally posted by **lizziel** September  8, 2021</sup>
@msulprizio recently raised the point that there are an abundance of log files in GCHP which makes trouble-shooting non-intuitive. For a recent 13.2 dev run on the Harvard cluster the following output files were produced apart from diagnostics and checkpoints:

- `allPEs.log`
- `gchp.log`
- `HEMCO.log`
- `logfile.000000.out`
- `slurm-jobid.out`
- `warnings_and_errors.log`
- `*.rcx `(one file per collection)

This discussion is about making GCHP logs more intuitive and consequently helpful to users. This could include renaming, consolidating, and/or omitting log files, and expanding documentation about them.

NOTE: I excluded `multirun.log` from the list since we should not support the multi-run script anymore except for GCHP benchmarking on Cannon, which will soon be retired.
</div>

**Comment by lizziel** [comment]
We are moving from GitHub Discussion to GitHub Issues. I locked the original discussion but it is still viewable. Put additional comments in the discussion on this issue instead.

**Comment by sdeastham** [comment]
Are the .rcx files actually log files? I thought they were related to processing of the .rc files, and could be reused?

**Comment by lizziel** [comment]
The .rcx files are separate rc files for each History collection generated at run-time based on content in `HISTORY.rc`. Rather than use `HISTORY.rc` directly, MAPL parses it into the .rcx files and then uses those in a loop to put together the history collection lists. The files are not technically log files, but they are output files containing information about the data output, so it's a gray area.

Currently we don't do anything with these files after the run. It seems overly complicated to reuse them when you could simply reuse `HISTORY.rc` which has all of the same information but in one place. @sdeastham, are you interested in reusing these files, or making that option documented for users?

**Comment by lizziel** [comment]
Updates for 14.0.0:

- `gchp.log` and `HEMCO.log` are combined into one log file. The default name in all run scripts is `gchp.YYYYMMDD_HHmmz.log`, where the date string is simulation start date.
- There is now a [page on ReadTheDocs](https://gchp.readthedocs.io/en/docs-dev/user-guide/output_files.html) which describes all output files.

In a future version we could make custom modifications to our forks to suppress log files that should be ignored, or delete them in run scripts to clean up the run directory. We can also rename `allPEs.log` to something that is more apt.

**Comment by lizziel** [comment]
I am closing this discussion since we do not plan to further reduce configuration files within the next year.
