### ISSUE TITLE
[BUG/ISSUE] CodeDir is incorrectly set when creating GCHPctm run directories

### ISSUE THREAD

**Issue by yantosca** [geoschem/GCHP#24]
### Describe the bug
When I create a GCHPctm run directory, I've noticed that the CodeDir symbolic link points to the wrong directory.  For example, after cloning GCHPctm and checking out the submodules:

```
cd GCHPctm/run
./createRunDir.sh 
... then follow all the prompts to create your desired run dir type ...
... then cd into the rundir you just created...
ls -l CodeDir
```
The output I got was:
```
/n/holyscratch01/jacob_lab/ryantosca/GCHP/GCHPctm/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/run/
```
which is pointing to the run creation directory.  But this should point to the top-level GCHPctm folder, i.e.:
```
/n/holyscratch01/jacob_lab/ryantosca/GCHP/GCHPctm
```

### Quick fix
Manually unlink the CodeDir and reset it to the top-level GCHPctm folder,i.e.
```
unlink CodeDir
ln -s /n/holyscratch01/jacob_lab/ryantosca/GCHP/GCHPctm CodeDir
```
then compile as shown in the README.md

**Comment by lizziel** [comment]
This is odd since I haven't run into this problem and just now created a run directory with the correct CodeDir. What steps are you doing to create the run directory? What version of GCHPctm are you using?

**Comment by lizziel** [comment]
Hmm, I see you listed the steps which are correct. Let's follow up on Slack and post the end result here.

**Comment by yantosca** [comment]
Fixed this issue.  I had aliased "cd" to "cd -P", which forced the long directory path format.  Removing this from my aliases fixed this issue.
