### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by pkasibhatla** [geoschem/gchp#240]
Hi,

I seem to be getting a number of Cmake errors/warnings when I initialize my build directory - though the initialization seems to be successful. 

> -- BASEDIR: IGNORE
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5_hl.a: No such file or directory
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5.a: No such file or directory
> -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5_hl.a: No such file or directory
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5.a: No such file or directory
> -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
> -- Found HDF5: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5.so (found version "1.12.1")  
> -- Found NetCDF4: 1  
> -- Found ESMF: /opt/apps/rhel8/miniconda3/envs/gchp-env/include (found version "8.2.0")
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5_hl.a: No such file or directory
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5.a: No such file or directory
> -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5_hl.a: No such file or directory
> x86_64-conda-linux-gnu-cc: error: /opt/apps/rhel8/miniconda3/envs/gchp-env/lib/libhdf5.a: No such file or directory
> -- HDF5 C compiler wrapper is unable to compile a minimal HDF5 program.
> -- Found NetCDF4: 1  
> -- Found MPI: TRUE (found version "3.1") found components: C CXX Fortran 
> 

I also get a number of warnings that look like this:

> -- Configuring done
> CMake Warning at src/CMakeLists.txt:32 (add_executable):
>   Cannot generate a safe runtime search path for target gchp because files in
>   some directories may conflict with libraries in implicit directories:
> 
>     runtime library [libstdc++.so.6] in /admin/apps/rhel8/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/lib/../lib may be hidden by files in:
>       /opt/apps/rhel8/miniconda3/envs/gchp-env/lib
>     runtime library [libgomp.so.1] in /admin/apps/rhel8/miniconda3/x86_64-conda-linux-gnu/lib may be hidden by files in:
>       /opt/apps/rhel8/miniconda3/envs/gchp-env/lib
> 
>   Some of these libraries may not be found correctly.
> 
> 
> CMake Warning at ESMA_cmake/ecbuild/cmake/ecbuild_add_executable.cmake:188 (add_executable):
>   Cannot generate a safe runtime search path for target pfio_writer.x because
>   files in some directories may conflict with libraries in implicit
>   directories:
> 
>     runtime library [libgomp.so.1] in /admin/apps/rhel8/miniconda3/x86_64-conda-linux-gnu/lib may be hidden by files in:
>       /opt/apps/rhel8/miniconda3/envs/gchp-env/lib
> 
>   Some of these libraries may not be found correctly.
> Call Stack (most recent call first):
>   src/MAPL/pfio/CMakeLists.txt:144 (ecbuild_add_executable)

Is this something that I need to fix, or is it ok given that the initialization seems to have completed successfully:
-

> - Generating done
> -- Build files have been written to: /hpc/home/psk9/GCHP/build
[CMakeCache.txt](https://github.com/geoschem/GCHP/files/9154457/CMakeCache.txt)

**Comment by lizziel** [comment]
Hi Prasad, it appears that cmake is confused by the existence of library files of the same name in two different locations. Do you want to use libraries in /`admin/apps/rhel8/miniconda3/x86_64-conda-linux-gnu/lib` or do you want to use libraries in `/opt/apps/rhel8/miniconda3/envs/gchp-env/lib`? CMake is finding both.

Try adding the one you want to use to `CMAKE_PREFIX_PATH` during the configure step. Do this by including the following when you run cmake:

`-DCMAKE_PREFIX_PATH=/path/to/intended/lib`

More info on this issue is on StackOverflow [here](https://stackoverflow.com/questions/22536567/cmake-cannot-resolve-runtime-directory-path). The second response (starts with "What the warning actually implies") is particularly good.

**Comment by lizziel** [comment]
This issue of multiple libraries may also impact https://github.com/geoschem/geos-chem/issues/1311.

**Comment by pkasibhatla** [comment]
Hi Lizzie,

I tried 
cmake ~/GCHP -DCMAKE_PREFIX_PATH=/opt/apps/rhel8/miniconda3/envs/gchp-env/lib

but I still get the same errors/warnings.

**Comment by pkasibhatla** [comment]
Hi @lizziel,

One of the things I see in the build initialization output are the following lines:

> -- ecbuild   3.0.0	/hpc/home/psk9/GCHP/ESMA_cmake/ecbuild/cmake
> -- cmake     3.19.3	/admin/apps/rhel8/cmake-3.19.3/bin/cmake
> 

My guess is that these lines are the result of

> # Add ESMA_cmake and ecbuild's module directories to the module path
> list(APPEND CMAKE_MODULE_PATH
>   ${CMAKE_CURRENT_SOURCE_DIR}/ESMA_cmake
>   ${CMAKE_CURRENT_SOURCE_DIR}/ESMA_cmake/ecbuild/cmake
> )

in ~/GCHP/CMakeLists.txt.

The cmake that I use for the build initialization is /opt/apps/rhel8/cmake-3.19.3/bin/cmake. So I wonder if adding these modules adds the /admin paths to where cmake is searching for libraries that gives me all those warning about "Cannot generate a safe runtime search path..."

**Comment by lizziel** [comment]
Hi @pkasibhatla, sorry for the delay in getting back to you on this. I am not sure if ecbuild would interfere. It shouldn't since the cmake directory in ecbuild (a GMAO library) is not the same as cmake itself. Are you setting LD_LIBRARY_PATH before configuring with cmake? If not, does setting that fix the problem?

**Comment by pkasibhatla** [comment]
hi @lizziel, yes I am setting LD_LIBRARY_PATH before configuring with cmake. That does not fix the problem.

**Comment by lizziel** [comment]
@LiamBindle, have you seen this error before?

**Comment by LiamBindle** [comment]
Hi Prasad and Lizzie,

These warnings should be safe to ignore. If there is a problem, compiling will fail or the executable will fail to start; if it compiles + doesn't crash when you start it, it's safe to assume everything is okay. If you do run into issues, let us know and we can dig into it deeper, but I don't think this is cause for concern.

**Comment by pkasibhatla** [comment]
Hi Liam,

It compiles and I create the executable "gchp". I then try to run interactively with the command "mpirun -np 24 gchp", but model crashes. Attached file shows the output to the terminal.
[gchpout.txt](https://github.com/geoschem/GCHP/files/9245032/gchpout.txt)

**Comment by lizziel** [comment]
Hi Prasad. GCHP is crashing at this code in MAPL. I suspect the problem is the same as the issue reported here: https://github.com/geoschem/gchp/issues/8.
```
    call ESMF_VMGet(cap%vm, petcount=npes, mpicommunicator=comm, rc=status)
    _VERIFY(status)
     _ASSERT(CoresPerNode <= npes, 'something impossible happened')
```

As described in the issue, this can happen if ESMF is not built with the correct settings. Try checking if ESMF was built with `ESMF_COMM=mpiuni`. This builds ESMF to run in single-processor MPI-bypass mode. Instructions for how to check are in the posted issue.

**Comment by pkasibhatla** [comment]
Thanks @lizziel. It looks like ESMF was indeed build with ESMF_COMM=mpiuni. What should we build it with? I am using OpenMPI 4.1.4.

**Comment by LiamBindle** [comment]
Hi Prasad. The correct environment variable for building ESMF would be `ESMF_COMM=openmpi`. You can find a list of the ESMF build-time environment variables [here](https://earthsystemmodeling.org/docs/release/ESMF_5_2_0p1/ESMF_usrdoc/node9.html). If I recall correctly, `ESMF_BOPT`, `ESMF_COMM`, `ESMF_COMPILER`, `ESMF_ABI`, `ESMF_DIR`, and `ESMF_INSTALL_PREFIX` are the important ones.

**Comment by lizziel** [comment]
@pkasibhatla, did rebuilding ESMF with `ESMF_COMM=openmpi` correct the issue?

**Comment by pkasibhatla** [comment]
@lizziel, yes it did. Thanks!

**Comment by lizziel** [comment]
Great! I'll close out this issue.
