### ISSUE TITLE
Missing MeteorologicalInputs.csv file

### ISSUE THREAD

**Issue by pkasibhatla** [geoschem/gchp#243]
### What institution are you from?
Duke University

### Description of the problem
GCHP docs https://gchp.readthedocs.io/en/latest/user-guide/getting-input-data.html mention downloading MeteorologicalInputs.csv file from http://geoschemdata.wustl.edu/ExtData/DataCatalogs - but file does not exist at that location.

### GEOS-Chem version
GCHP 13.4.1

**Comment by yantosca** [comment]
Hi @pkasibhatla.  Thanks for pointing this out.  The `MeteorologicalInputs.csv` files are also available at the Github repo: https://github.com/geoschem/input-data-catalogs.  Maybe the latest data file has not been copied over to the WashU data server yet.

This reminds us, we have to also make sure that the `.csv` files for 14.0.0 should be pushed to the `input-data-catalogs` repo.  We can take care of that on our end.

**Comment by pkasibhatla** [comment]
Hi @yantosca, the MeteorologicalInputs.csv is not available at the Github repo that you point to either.

**Comment by yantosca** [comment]
Oh sorry.  I think we do not have a MeteorologicalInputs.csv file.  That was how @LiamBindle set up the input-data-catalogs.  Sorry for the confusion.

@LiamBindle: Should we try to add a MeteorologicalInputs.csv file or was there a reason we don't have one?

**Comment by LiamBindle** [comment]
Oops, that file accidentally got deleted with the mix up. I readded it to the [GitHub repository](https://github.com/geoschem/input-data-catalogs/tree/main). It will be back on the website in a day or two.

**Comment by yantosca** [comment]
Thanks @LiamBindle!  I'll also update the geos-chem readthedocs for the meteorological inputs file.

**Comment by LiamBindle** [comment]
It's there now.
