### ISSUE TITLE
bashdatacatalog fetching unnecessary data?

### ISSUE THREAD

**Issue by pkasibhatla** [geoschem/gchp#244]
### What institution are you from?
Duke University

### Description of the problem
I am setting up a test GCHP simulation for one month starting on 2019-07-01 . I use the the command 
`bashdatacatalog-list -am -r 2019-06-30,2019-08-02 -f xargs-curl InputDataCatalogs/*.csv InputDataCatalogs/**/*.csv | xargs curl`
to fetch input data. But there seems to be a lot of data being downloaded that does not seem necessary for the simulation. For example:
```
(status 000)  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191106.nc -> ./HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191106.nc  [0 bytes]
(status 200)  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191107.nc -> ./HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191107.nc  [877474 bytes]
(status 200)  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191108.nc -> ./HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191108.nc  [891975 bytes]
(status 200)  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191109.nc -> ./HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191109.nc  [897591 bytes]
(status 200)  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191110.nc -> ./HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191110.nc  [900164 bytes]
(status 200)  http://geoschemdata.wustl.edu/ExtData/HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191111.nc -> ./HEMCO/OFFLINE_DUST/v2021-08/0.5x0.625/2019/11/dust_emissions_05.20191111.nc  [1206955 bytes]
```

### GEOS-Chem version
GCHP 13.4

Is this related to the Static Overhead referred to in https://github.com/LiamBindle/bashdatacatalog/wiki/Instructions-for-GEOS-Chem-Users?

**Comment by LiamBindle** [comment]
Hi Prasad, this is expected. There's an overview of this caveat here: https://github.com/LiamBindle/bashdatacatalog/wiki/Instructions-for-GEOS-Chem-Users#static-overhead. In brief, the first & last year of climatologies are "always required". In practice, the "extra files" are a small nuisance but it keep the internal logic simple. After you donwload these files once, subsequent downloads won't include so many "extra files".
