### ISSUE TITLE
[BUG/ISSUE] Runs breaking about 30 seconds in

### ISSUE THREAD

**Issue by lfreese** [geoschem/gchp#245]
### What institution are you from?
MIT

### Description of the problem
I submitted a run that has previously worked, but on the most recent submission have had issues, where it breaks within the first 30 seconds. I use modified emissions files, but also checked with the original HEMCO emissions files and am still seeing it break and provide the same error. It looks like some error with time or bounds, but I haven't been able to figure it out.

### GEOS-Chem version
GCHP v 13.3.4

### Description of code modifications
Modified the black carbon emissions, but have also run it without modifications. Turned off chemistry.

### Log files
[slurm-470903.txt](https://github.com/geoschem/GCHP/files/9284553/slurm-470903.txt)
[gchp.txt](https://github.com/geoschem/GCHP/files/9284554/gchp.txt)
[logfile.000000.txt](https://github.com/geoschem/GCHP/files/9284555/logfile.000000.txt)
[allPEs.txt](https://github.com/geoschem/GCHP/files/9284556/allPEs.txt)
[ExtData.txt](https://github.com/geoschem/GCHP/files/9284557/ExtData.txt)
[HEMCO_Config.txt](https://github.com/geoschem/GCHP/files/9284558/HEMCO_Config.txt)
[logging.txt](https://github.com/geoschem/GCHP/files/9284559/logging.txt)

**Comment by lizziel** [comment]
Hi @lfreese, are you using a custom restart file? The end of the `gchp.txt` log shows an error right after trying to read the restart file:

```
Using parallel NetCDF for file: GCHP_restart.nc4
 ESMF_StatePrint: (pet 0):
  State name: GCHPchem_INTERNAL
     status: Unspecified intent direction, object count: 337
     reconcile needed: T
```

The traceback in the slurm log file leads to the problem being a bad status code (-101) in this call in `src/MAPL/base/MAPL_IO.F90`, which is reading the restart file:
```
          status = nf_open(trim(filename),NF_NOWRITE, ncid)
          _VERIFY(STATUS)
```

Are you sure you are running with the same libraries that you built with?

**Comment by lfreese** [comment]
Thanks so much Lizzie! It was the restart file-- weirdly it got corrupted after being consistently used for other runs, which is why I was so lost.

**Comment by lizziel** [comment]
Glad I could help! The MAPL errors that appear in the log file can be cryptic unfortunately if the input files are corrupted.
