### ISSUE TITLE
[BUG/ISSUE] New MAPL version breaks stretched-grid simulations

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/gchp#246]
### What institution are you from?
WashU

### Description of the problem
The latests MAPL upgrade introduced some breaking changes for stretched-grid simulations:
1. `src/MAPL/base/MAPL_CubedSphereGridFactory.F90`  has bugs on L347 and L355. These are new "safety checks", but target_lat is being assigned to target_lon and vice-versa.
2. Stretched-grid restart files now REQUIRE global attributes `STRETCH_FACTOR`, `TARGET_LAT`, and `TARGET_LON`. Our restart files till now have used `stretch_factor`, `target_latitude`, and `target_longitude`. The attributes must be of type float, whereas our restart files have used double until now. These can be added with `ncatted -a STRETCH_FACTOR,global,o,f,1.234 gchp_restart.nc4`.

### GEOS-Chem version
14.0

### Description of code modifications
None

**Comment by lizziel** [comment]
We could put a MAPL fix into 14.0.1 for this. @LiamBindle, have you reported this to GMAO?

**Comment by lizziel** [comment]
This bug is fixed by https://github.com/geoschem/MAPL/pull/22 which will be included in GCHP 14.0.1.

**Comment by lizziel** [comment]
I submitted a bug fix to NASA GMAO in https://github.com/GEOS-ESM/MAPL/pull/1647.

**Comment by mathomp4** [comment]
@LiamBindle @lizziel  

> 2. Stretched-grid restart files now REQUIRE global attributes `STRETCH_FACTOR`, `TARGET_LAT`, and `TARGET_LON`. Our restart files till now have used `stretch_factor`, `target_latitude`, and `target_longitude`. The attributes must be of type float, whereas our restart files have used double until now. These can be added with `ncatted -a STRETCH_FACTOR,global,o,f,1.234 gchp_restart.nc4`.

Are these restarts produced by MAPL or your own code? If by MAPL, it's possible we could figure out how to add these to the restart global metadata via MAPL. (I assume it's possible, but I'm not sure. I know how to do so with History, but the restarts are still a bit of a mystery to me.)

**Comment by lizziel** [comment]
@mathomp4, I believe these are already included in stretched-grid restarts generated by MAPL, as shown [here](https://github.com/GEOS-ESM/MAPL/blob/28a2dbd4b196038d1719cb2336c0616fe1fd20f4/base/NCIO.F90#L3464-L3468).

@LiamBindle, correct me if I am wrong, but I think the previous attributes in the restart file for stretch factor and target coords were added by you upon request by me to be more clear about what the restart files contained. I think I brought this up to Ben who then implemented it in MAPL and added checks that the restart grid matches the run grid. When we updated our MAPL version recently this change was present which subsequently broke our old method.

**Comment by LiamBindle** [comment]
@lizziel, That's right. One thing though
> When we updated our MAPL version recently this change was present which subsequently broke our old method.

Previously there was no enforcement. The new MAPL enforces attributes that happen to have different names from the ones we added a while back.

The only bug is the mismatch of lat<->lon in `src/MAPL/base/MAPL_CubedSphereGridFactory.F90`.

**Comment by mathomp4** [comment]
Ah. okay. I just saw the `ncatted` command and thought maybe that was something we should be doing for you. I figure why postprocess a file when the process could do it. 😄
