### ISSUE TITLE
[BUG/ISSUE] Vertical mass flux diagnostic needs to be scaled by 1/dt

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/gchp#247]
### What institution are you from?
WUSTL

### Description of the problem
The UpwardsMassFlux diagnostic in GCHP has an erroneous `dt` term in it. To correct it, it should be scaled by `1/dt` (dt=300 seconds for fine-resolution simulations).

### GEOS-Chem version
All recent versions

### Description of code modifications
None

**Comment by lizziel** [comment]
@LiamBindle, could you submit a PR for this or point to the line in the code that needs to be changed?

**Comment by lizziel** [comment]
I am passing handling of this issue to @Jourdan-He.

**Comment by Jourdan-He** [comment]
@lizziel @LiamBindle , I just created a PR for this fix.

**Comment by LiamBindle** [comment]
Fixed in #248. Thanks Jourdan!
