### ISSUE TITLE
[QUESTION] STRETCHED GRID SIMULATION 

### ISSUE THREAD

**Issue by gopikrishnangs44** [geoschem/gchp#256]
Should the CS_RES (in  runConfig.sh) and CS_RES_OUT (used to regrid restart file in gcpy.file_regrid)  be the same in a stretched grid simulation?

**Comment by Jourdan-He** [comment]
Hi @gopikrishnangs44 , the more reliable way of regridding files is to use regrid_restart_file.py. I have listed out the steps to use it under this issue: (https://github.com/geoschem/gcpy/issues/161 ). Please refer to this issue, thanks!

**Comment by gopikrishnangs44** [comment]
HI @Jourdan-He, 

I have changed a line in file_regrid from 
ds_out=xr.open_mfdataset(oface_files, combine='**by_coords**', concat_dim='F',engine='netcdf4')
to 
ds_out=xr.open_mfdataset(oface_files, combine='**nested**', concat_dim='F',engine='netcdf4')
which solved that issue.

However, my concern is, when I tried running GCHP 13.4.0 in a stretched grid,

I have gone through the following steps:
1. Regridded (gcpy.file_regrid('GCHP.Restart.fullchem.20190701_0000z.c90.nc4','st_restart_90.nc',dim_format_in='checkpoint', dim_format_out='checkpoint',**cs_res_out=90**,sg_params_out=[3.0,82.0,22.0]))

2. Changes run Config:
   a. Stretch_grid: ON
   b. Lat and Lon (target)
   c. changes the initial restart

I tried 2 different ways, with 
**CS_RES = 24 in runConfig.sh and regridded restart with C90** 
and 
**CS_RES = 24 in runConfig.sh and regridded restart with C24** 

The former one failed and latter was successfull.

And my concern is,
If i am regridding an initial restart file to C90 (cs_res_out=90 in file_regrid), then should I need to use the same resolution in CS_RES in the .runConfig.sh file?

**Comment by Jourdan-He** [comment]
Hi @gopikrishnangs44, since your restart file has been regridded to C90, the CS_RES input in runConfig.sh should be in accordance with the new file grid format, which is 90.

**Comment by gopikrishnangs44** [comment]
@Jourdan-He  Thank You.

In the same way, I tried both cs90 and cs24.

However, cs24 ran successfully (1 node and 6 cores)

while running cs90, I am getting the following error (1 node and 6 cores)
[GC.log](https://github.com/geoschem/GCHP/files/9758507/GC.log)

Can you help me find where this error is from?

**Comment by Jourdan-He** [comment]
Hi @gopikrishnangs44 , for running c90 simulation, you would need more cores. There won't be enough memory with only 6 cores.

**Comment by gopikrishnangs44** [comment]
@Jourdan-He Thank you. CS90 worked with 144 cores and 4 nodes.
