### ISSUE TITLE
GCHP simulation crashes with KPP solver error  

### ISSUE THREAD

**Issue by inder-math** [geoschem/gchp#261]
### What institution are you from?
Washington University in St. Louis 

### Description of the problem
Hi,  This is Inderjeet Singh. I have been doing a stretch grid simulation using GCHP 13.4.0 focussed over North America region for a period of three and half month from July 15, 2020 to October 31, 2020. Following are the important simulation inputs/properties (runConfig.sh file is attached):

**Simulation type: Standard, Full chemistry 
Met field: Merra 2
Simulation resolution: C110
Stretch factor: 1.7
target lat and lon : 48 degree N and 266 degree east** 

The simulation is running fine until GCHP starts simulating the required results for August 6 (i repeated the simulation one more time). It crashes with following error (logfile is attached):
 
**Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   475.805293846684      and H=  1.316905366857939E-013
 INTEGRATE RETURNED ERROR AT:           18          11          11
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   475.695095147834      and H=  9.036986208732714E-014
 INTEGRATE FAILED TWICE !!!**

I don't know what causes this error. Can you please help me fix it? Any suggestion will be appreciated.  I have the attached files which i feel, are necessary to understand the problem. Please find the attachment and  let me know if i am missing any file. 

### GEOS-Chem version
13.4.0

### Description of code modifications
No code modification

### Log files
attached files are run_restartgchp.log, GCHPrun.log, HEMCO_Config.rc, HEMCO.log, runConfig.rc

[GCHP_issue.zip](https://github.com/geoschem/GCHP/files/9845197/GCHP_issue.zip)

**Comment by lizziel** [comment]
Hi Inderjeet, apologies that this issue fell through the cracks. Are you able to get the same setup with a uniform grid rather than stretched grid to work over the same period? If yes, I suggest outputting checkpoint (restart) files periodically throughout your run for both stretched grid and global and then check if there is anything blowing up in early August. You can also compare daily concentrations between global and stretched grid and see if that gives any insight.

**Comment by inder-math** [comment]
Thanks Lizzie!!!!
