### ISSUE TITLE
[SUBMODULE UPDATES] Retire input land-water-ice (LWI) index

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#264]
## Brief Description

There are two related submodule PRs for retiring use of input meteorology field land-water-ice (LWI) index and GEOS-Chem and HEMCO state arrays it is stored in. We are removing LWI as a dependency because it will not be included in the GEOS-IT dataset and determining whether a grid cell is over ocean, ice, or land is possible through other input meteorology fields. It is currently only used for computation in (1) dry deposition if using optional Luo wet deposition, and (2) HEMCO extensions.

## Related Issues

Feature request to retire LWI:
https://github.com/geoschem/geos-chem/issues/1413

## Submodule Pull Requests

* [x] https://github.com/geoschem/geos-chem/pull/1435
* [x] https://github.com/geoschem/HEMCO/pull/170

**Comment by msulprizio** [comment]
These PRs are now included in the `dev/14.1.0` branch. I will close out this feature request.
