### ISSUE TITLE
[BUG/ISSUE] PMIX ERROR and OPAL ERROR when running GCHP from Singularity container

### ISSUE THREAD

**Issue by Twize** [geoschem/gchp#269]
Hi, I am working with Dylan Jones at the University of Toronto, and we are currently trying to run GCHP v13.3 on the Compute Canada Niagara server using the Singularity container approach. I have followed the instructions from this page: https://gchp.readthedocs.io/en/latest/supplement/containers.html#setting-up-and-running-gchp-using-singularity, and have the input data downloaded and everything appears to be set-up correctly.

As a test, I am trying to run just a 1-hour simulation with the default settings at c48 resolution with 6 nodes (40 cores per node), so 240 cores total. When I execute the run through my run-script, I encounter the following error (full Slurm output log is attached): 

[nia1907.scinet.local:174781] PMIX ERROR: PMIX TEMPORARILY UNAVAILABLE in file ptl_tcp.c at line 688
[nia1907.scinet.local:174781] OPAL ERROR: Unreachable in file pmix2x_client.c at line 112
[nia1907.scinet.local:174779] PMIX ERROR: PMIX TEMPORARILY UNAVAILABLE in file ptl_tcp.c at line 688
[nia1907.scinet.local:174779] OPAL ERROR: Unreachable in file pmix2x_client.c at line 112
*** An error occurred in MPI_Init_thread
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[nia1907.scinet.local:174781] Local abort before MPI_INIT completed completed successfully, but am not a$

I seem to encounter this error regardless of how many cores/nodes I try to use. One thing I have noticed is that in the Slurm job scheduler, it shows as there actually being 480 cores being used as opposed to the 240 I specify, however I do not have hyperthreading or anything switched on from what I can tell. 

### Log files
- Slurm run log:
[slurm_output_8450698.txt](https://github.com/geoschem/GCHP/files/10045120/slurm_output_8450698.txt)
- Slurm Run script (added .txt extension for upload): 
[GCHP_batch_job.slurm.sh.txt](https://github.com/geoschem/GCHP/files/10045266/GCHP_batch_job.slurm.sh.txt)
- GCHP run config file (also added .txt): 
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/10045273/runConfig.sh.txt)

### Software versions
- MPI version: 4.0.3
- Singularity: 3.8.7-1.el7

**Comment by Jourdan-He** [comment]
Hi @Twize , could you share what container you used? If it's docker, I can directly test it on my end.

**Comment by Twize** [comment]
Hi @Jourdan-He, yeah I grabbed it from Docker. I believe the version I pulled was 13.3.2 using:

singularity pull gchp.sif docker://geoschem/gchp:13.3.2

**Comment by Twize** [comment]
I'm actually going to close this issue because I was able to compile GCHP from scratch using Spack to build the dependencies, so I don't think I will be using the Singularity approach for running the model. 

However, I was also speaking with the Scinet support team as well and they seem to think the issue had to do with a PMIx timeout when communicating between the Singularity and the server, but they were not able to find a solution either.

**Comment by Jourdan-He** [comment]
@Twize Thanks for the update!
