### ISSUE TITLE
[BUG/ISSUE] GCHP v13.3.2 compilation fails at the end on Linking Fortran Exectuable ../bin/gchp

### ISSUE THREAD

**Issue by Twize** [geoschem/gchp#270]
### Description of issue
I am trying to compile the GCHP v13.3.2 core codes on Compute Canada Niagara, and compiling GCHP fails at the final step when linking the GCHP executable with the following error which appears to be related to my ESMF:

> Scanning dependencies of target gchp
> [100%] Building Fortran object src/CMakeFiles/gchp.dir/GCHPctm.F90.o
> [100%] Linking Fortran executable ../bin/gchp
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o): In function `MPI::Op::Init(void (*)(void const*, void*, int, MPI::Datatype const&), bool)':
> ESMCI_DistGrid_F.C:(.text._ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb[_ZN3MPI2Op4InitEPFvPKvPviRKNS_8DatatypeEEb]+0x19): undefined reference to `ompi_mpi_cxx_op_intercept'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o): In function `MPI::Intracomm::Clone() const':
> ESMCI_DistGrid_F.C:(.text._ZNK3MPI9Intracomm5CloneEv[_ZNK3MPI9Intracomm5CloneEv]+0x2a): undefined reference to `MPI::Comm::Comm()'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o): In function `MPI::Graphcomm::Clone() const':
> ESMCI_DistGrid_F.C:(.text._ZNK3MPI9Graphcomm5CloneEv[_ZNK3MPI9Graphcomm5CloneEv]+0x25): undefined reference to `MPI::Comm::Comm()'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o): In function `MPI::Cartcomm::Sub(bool const*) const':
> ESMCI_DistGrid_F.C:(.text._ZNK3MPI8Cartcomm3SubEPKb[_ZNK3MPI8Cartcomm3SubEPKb]+0x86): undefined reference to `MPI::Comm::Comm()'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o): In function `MPI::Intracomm::Create_graph(int, int const*, int const*, bool) const':
> ESMCI_DistGrid_F.C:(.text._ZNK3MPI9Intracomm12Create_graphEiPKiS2_b[_ZNK3MPI9Intracomm12Create_graphEiPKiS2_b]+0x2c): undefined reference to `MPI::Comm::Comm()'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o): In function `MPI::Cartcomm::Clone() const':
> ESMCI_DistGrid_F.C:(.text._ZNK3MPI8Cartcomm5CloneEv[_ZNK3MPI8Cartcomm5CloneEv]+0x25): undefined reference to `MPI::Comm::Comm()'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o):ESMCI_DistGrid_F.C:(.text._ZNK3MPI9Intercomm5MergeEb[_ZNK3MPI9Intercomm5MergeEb]+0x29): more undefined references to `MPI::Comm::Comm()' follow
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o):(.data.rel.ro._ZTVN3MPI8DatatypeE[_ZTVN3MPI8DatatypeE]+0x78): undefined reference to `MPI::Datatype::Free()'
> /home/d/dylan/tylerw/mymodules/esmf/opt/8.1.0/DEFAULTINSTALLDIR/lib/libO/Linux.gfortran.64.openmpi.default/libesmf.a(ESMCI_DistGrid_F.o):(.data.rel.ro._ZTVN3MPI3WinE[_ZTVN3MPI3WinE]+0x48): undefined reference to `MPI::Win::Free()'
> collect2: error: ld returned 1 exit status
> make[2]: *** [bin/gchp] Error 1
> make[1]: *** [src/CMakeFiles/gchp.dir/all] Error 2
> make: *** [all] Error 2

I was previously able successfully to compile GCHP without this error (i.e., the gchp executable showed up in the /bin/ directory). However, when I tried a 1-hr test simulation, I encountered an error similar to the one mentioned in this thread (https://github.com/geoschem/GCHP/issues/94):

> pe=00000 FAIL at line=00257    MAPL_CapGridComp.F90                 <something impossible happened
>pe=00000 FAIL at line=00851    MAPL_CapGridComp.F90                     <status=1>
>pe=00000 FAIL at line=00322    MAPL_Cap.F90                             <status=1>
>pe=00000 FAIL at line=00198    MAPL_Cap.F90                             <status=1>
>pe=00000 FAIL at line=00157    MAPL_Cap.F90                             <status=1>
>pe=00000 FAIL at line=00131    MAPL_Cap.F90                             <status=1>
>pe=00000 FAIL at line=00029    GCHPctm.F90                              <status=1>

So this led me to noticing that my ESMF was not compiled for parallel with openMPI set (i.e., using `export ESMF_COMM=openmpi`). I rebuilt/recompiled ESMF with openMPI loaded and that flag set, and then tried to recompile GCHP before encountering the compilation error mentioned above. I originally tried with the most recent version of ESMF (v8.5.0b), but thought that it may be too recent, so I built version 8.1.0 as well, however both gave the same GCHP compilation error. 

Any help would be appreciated!

### Log files
- EC Build log:
[ecbuild.log](https://github.com/geoschem/GCHP/files/10095230/ecbuild.log)

- Cmake Cache:
[CMakeCache.txt](https://github.com/geoschem/GCHP/files/10095231/CMakeCache.txt)

-  Compile log file:
[compile_log.txt](https://github.com/geoschem/GCHP/files/10095232/compile_log.txt)

### Software versions
- Compilers (Intel or GNU, and version): gcc/9.2.0
- NetCDF version: netcdf/4.6.3
- MPI version: openmpi/4.0.3 
- ESMF version: esmf/8.1.0

**Comment by lizziel** [comment]
Hi @Twize, we haven't seen this error before. Looking around on the internet I see a very old post with solution of linking with `mpic++` rather than `mpicc` ([see here](https://stackoverflow.com/questions/17548436/openmpi-error-during-compilation)). However, you shouldn't need to mess around with linking flags. The only thing that pops out at me when comparing your `CMakeCache.txt` with mine is that your Fortran and C compilers are listed as the OpenMPI wrappers `mpifort` and `mpicc` rather than the underlying compilers `gfortran` and `gcc`, but I am not sure if that would make a difference. 

I am copying @mathomp4 who is the NASA maintainer of the build code underlying GCHP (libraries [ESMA_cmake](https://github.com/GEOS-ESM/ESMA_cmake) and [ecbuild](https://github.com/GEOS-ESM/ecbuild)). Matt, have you seen this before and have a solution? Perhaps it's a simple environment configuration issue?

Unrelated but important: there have been reported issues with using gcc <=9.3 in GCHP. These only show up if there is a file input problem leading to execution of certain error handling code. However, it is worth upgrading to gcc 10+ to avoid potential issues.

**Comment by Twize** [comment]
Hi @lizziel thanks for the reply. I found that same post earlier, and tried separately linking both ESMF and GCHP with mpic++ instead of mpicc, but neither seemed to fix the issue and the error still showed up at the end of compiling GCHP. Is there a way for me to specify gfortran and gcc instead of mpifort and mpicc just to test (modify CMakeCache.txt or something along those lines)? 

At the moment, I am trying to use Spack to install the dependencies because that might reduce some of the potential issues with linking all of the dependencies and libraries etc. I started the process with GCC 9.3.0, but if you suggest GCC 10+, I will use that instead. The latest release seems to be GCC 10.4, would using this newest version cause issues with GCHP?

**Comment by Twize** [comment]
Quick update, installing the following dependencies with Spack, and then compiling GCHP worked:
gcc@10.4.0 
netcdf-fortran@4.6.0 
cmake@3.16.1
openmpi@4.0.4
esmf@8.3.1  

I have not gotten a chance to do a 1-hr test simulation just yet to make sure it runs fine, but I will update when I do. 

So, I assume the original error must have to do with either the way I manually built/installed ESMF or something else wrong with my environment like you suggested.

**Comment by lizziel** [comment]
Hi @Twize, I'm glad you found a work-around. It would be nice to know the solution to the original problem but probably not worth the time if Spack install works. Fyi we have not used ESMF 8.3 with GCHP so let us know if you run into issues with that version.

**Comment by mathomp4** [comment]
> Hi @Twize, I'm glad you found a work-around. It would be nice to know the solution to the original problem but probably not worth the time if Spack install works. Fyi we have not used ESMF 8.3 with GCHP so let us know if you run into issues with that version.

GEOS (and MAPL) will soon move to a Baselibs with ESMF 8.4.0. We've seen no issues from 8.3 to 8.4 and ESMF didn't anticipate any as well

**Comment by Twize** [comment]
@lizziel just FYI, I was not actually able to use gcc 10+ in the end. I had to use the gcc 9.2.0 compiler + openMPI 4.0.3 which were pre-installed on Compute Canada Niagara, and link those with Spack to build the other dependencies. 

If I didn't do this, I got some error about Munge(which appeared to be a dependency of openMPI w/ Slurm support from Spack) at runtime :

> srun: error: If munged is up, restart with --num-threads=10
> srun: error: Munge encode failed: Failed to access "/gpfs/fs1/home/d/dylan/tylerw/mymodules/spack/opt/spack/linux-centos7-skylake_avx512/gcc-10.4.0/munge-0.5.15-i5wwklcftvvp7x6gorw7cxeenarpog65/var/run/munge/munge.socket.2": No such file or directory (Did you start munged?)
> srun: error: slurm_send_node_msg: auth_g_create: REQUEST_HET_JOB_ALLOC_INFO has authentication error
> srun: error: Unable to confirm allocation for job 8504167: Protocol authentication error
> srun: Check SLURM_JOB_ID environment variable. Expired or invalid job 8504167 

This seemed to clash with the Munge which was already on the cluster, and I wasn't sure how to lead it to the Munge socket that was already running on the server. Pointing Spack to gcc 9.2.0 + openMPI 4.0.3 that was already on the cluster got me around this issue. I'm not sure if this is a known issue or not, or if it's just recommended to use pre-installed compilers and/or openMPI with Spack when working on an HPC cluster.

**Comment by Twize** [comment]
If anyone encounters this issue when trying to compile GCHP, I was able to get past it by explicitly specifying (either in your environment file or manually on the commands line):
`export CC=gcc `
`export CXX=g++ `
`export FC=gfortran `
`export F77=gfortran `
`export F90=gfortran `
before running cmake. As @lizziel mentioned above, the issue seemed to be caused by cmake defaulting to the OpenMPI wrapper versions e.g., `mpicc`, `mpifort` etc, and I guess ESMF had issues with that.
