### ISSUE TITLE
[BUG/ISSUE] State_Met%FRSNO is not assigned to the FRSNO import 

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#277]
Sebastian Eastham (MIT) observed the following issue in the 14.0 10-year benchmark:

> Wintertime ozone at the surface in high northern latitudes is behaving quite differently in GCHP and GCC. Something between 13.0 and 14.0 pushed GCC up ozone by 10-20 ppbv at the ocean surface above ~45N; it’s hard to tell exactly because of the funky color scale, but looking at GCHP I see a much less pronounced increase between 45 and 60 N, and no increase above 60N. The consequence is not only very different ozone over ocean at high northern latitudes in the two configurations, but also very different ozone over land (e.g. northern Russia is now ~8 ppbv wintertime ozone in GCHP and ~20 ppbv wintertime ozone in GCC). Does anyone have any idea why this would be happening? I had wondered if this could be related to halogens from sea salt being excessive in GCHP, but SALA is higher in GCC than in GCHP (at high northern latitudes). I think this is an issue which we picked up around 13.4.0 but thought had been resolved with the correction of the GCC p-fixer bug.

Becky Alexander (UWash) commented that "the ozone deposition was reduced over snow and ice leading to higher ozone over snow-covered surfaces." This led @sdeastham to theorize an issue with identifying snow in GCHP.

I looked into this theory and found that the fraction snow stored in State_Met%FRSNO is not assigned to the import values of FRSNO. This omission leads to fraction snow being all zeros.

This issue will be fixed in 14.1.0.

**Comment by msulprizio** [comment]
The fix for this is now merged into `dev/14.1.0`. I will close out this issue.
