### ISSUE TITLE
[BUG/ISSUE] Unable to output hourly diagnostic collection when Diagn_Monthly is enabled

### ISSUE THREAD

**Issue by msulprizio** [geoschem/gchp#278]
In GCHP 14.0.0, it seems I am unable to save out hourly diagnostics in addition to monthly diagnostics. I tried manually setting the `StratBM` collection frequency and duration in HISTORY.rc to hourly:

```
  StratBM.frequency:      010000
  StratBM.duration:       010000
```

In `setCommonRunSettings.sh` I have enabled `AutoUpdate_Diagnostics` and `Diag_Monthly`. I also commented out `StratBM` in the `Diag_Collections` list there.

```
#---------------------------------------------------------------------
#    DIAGNOSTICS
#---------------------------------------------------------------------
# Auto-update settings in HISTORY.rc for specific collections (enable with ON)
AutoUpdate_Diagnostics=ON

# Instructions to auto-update diagnostics
#   1. Set AutoUpdate_Diagnostics=ON:
#   2. Set Diag_Monthly to compute monthly time-averaged values (0=OFF, 1=ON)
#   3. If Diag_Monthly=OFF:
#        3a. Set Diag_Frequency for diagnostic frequency, format "HHmmSS"
#        3b. Set Diag_Duration for file write frequency, format "HHmmSS"
#        *Note that number of hours may exceed 2 digits, e.g. 744 for 744 hrs
#   4. Edit Diag_Collections list to specify which collections to update
#
Diag_Monthly="1"
Diag_Frequency="010000"
Diag_Duration="010000"
Diag_Collections=(SpeciesConc    \
                  AerosolMass    \
                  Aerosols       \
#                  Budget         \
                  CloudConvFlux  \
                  ConcAfterChem  \
                  DryDep         \
                  DefaultCollection \
                  Emissions      \
                  JValues        \
#                  KppDiags       \
                  LevelEdgeDiags \
                  Metrics        \
                  ProdLoss       \
#                  RadioNuclide   \
#                  RRTMG 	 \
                  StateChm	 \
                  StateMet       \
#		  StratBM        \
#                  Transport	 \
                  WetLossConv    \
                  WetLossLS      \
)
```

Despite the hourly frequency and duration set in HISTORY.rc, I get only monthly files for the StratBM collection (all with `time = UNLIMITED ; // (1 currently)`). 

Here are those config files as well as a log file:

- [HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/10353453/HISTORY.rc.txt)
- [HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/10353454/HISTORY.rc.txt)
- [gchp.20190101_0000z.log.txt](https://github.com/geoschem/GCHP/files/10353455/gchp.20190101_0000z.log.txt)

**Comment by sdeastham** [comment]
Hi @msulprizio - I think a single collection can only have one output frequency, so in this case you'd need to define two: one called (say) "StratMonthly" and another "StratHourly". The best solution would definitely be if `HISTORY.rc` could have some kind of inheritance (so that you could easily define two collection with identical properties other than frequency) but until then I think duplication is the only option.

Did this work before 14.0.0? If so, what was the behavior? I'm surprised because I would think that having one collection with two frequencies would cause issues - at minimum, naming conventions (e.g. there would be two files with identical names for YYYY-MM-01).

**Comment by msulprizio** [comment]
Thanks, @sdeastham. In this case, I only wanted to save out one StratBM collection at hourly intervals -- I didn't need the monthly output at all. I think the issue is that setting `Diag_Monthly="1"` in `setCommonRunSettings.sh` assumes ***all*** diagnostic output should be monthly.

I was able to save out hourly StratBM files in 13.0.0, but that version used a different set if configuration files (e.g. (`runConfig.sh`).

**Comment by lizziel** [comment]
This is very strange since I just did some tests by running setCommonRunSettings.sh locally in the run directory and it worked as expected. The [script](https://github.com/geoschem/geos-chem/blob/8ef9a3be98e1edc2099aed491ba91732545825b5/run/GCHP/setCommonRunSettings.sh.template#L586-L600) includes monthly, frequency, and duration within the loop over the the collection list defined in the file so monthly should only be applied to collections in the local list.

```
#### Set output frequency, duration, and mode
if [[ ${AutoUpdate_Diagnostics} == "ON" ]]; then
   print_msg " "
   print_msg "Diagnostics:"
   print_msg "------------"
   if [[ ${#Diag_Collections[@]} > 0 ]]; then
      for c in ${Diag_Collections[@]}; do
         replace_val $c.monthly     ${Diag_Monthly}   HISTORY.rc
         replace_val $c.frequency   ${Diag_Frequency} HISTORY.rc
         replace_val $c.duration    ${Diag_Duration}  HISTORY.rc
      done
   fi
else
    print_msg "Auto-update of diagnostic settings in HISTORY.rc is turned off"
fi
```

This makes me wonder if setCommonRunSettings.sh had an early exit before it got to the diagnostics update (which is last in the script) or if it wasn't run at all. The default is monthly diagnostics so if the update never happened you would see what you are seeing.

**Comment by lizziel** [comment]
Looking more into this, the Harvard Cannon gchp run script outputs information to the log when setCommonRunSettings.sh is run.

```
# Update config files, set restart symlink, load run env, and do sanity checks            
source setCommonRunSettings.sh > ${log}
source setRestartLink.sh >> ${log}
source gchp.env >> ${log} 
```

In your log file the first thing printed is setting the restart link, which happens after running setCommonRunSettings.sh. Do you have your run script still?

**Comment by msulprizio** [comment]
The run scripts I used were:

- [gchp.run.txt](https://github.com/geoschem/GCHP/files/10354862/gchp.run.txt)
- [gchp.submit_consecutive_jobs.sh](https://github.com/geoschem/GCHP/files/10354864/gchp.submit_consecutive_jobs.sh)

I tried running the year 2019 twice thinking I had the wrong setting for the StratBM collection. The first run I had StratBM included in the `Diag_Collections` list in `setCommonRunSettings.sh`. Here are the log files for that run:

- [gchp.20190101_0000z.log](https://github.com/geoschem/GCHP/files/10353455/gchp.20190101_0000z.log.txt) - same one linked above
- [slurm-32138594.out](https://github.com/geoschem/GCHP/files/10354880/slurm-32138594.out.txt)

 The second time I commented it out. Here are the log files for that run:

- [gchp.20190101_0000z.log](https://github.com/geoschem/GCHP/files/10354912/gchp.20190101_0000z.log.txt)
- [slurm-35238572.out](https://github.com/geoschem/GCHP/files/10354883/slurm-35238572.out.txt)

In the first run, the slurm file includes `++ replace_val StratBM.monthly 1 HISTORY.rc`, etc. The second run did not. However, both of the gchp.20190101_0000z.log files include the text ` DEBUG: monthly averaging is active for collection StratBM` and

```
 Initializing Output Stream: StratBM
 --------------------------- 
       Format: CFIO
         Mode: time-averaged
        Nbits:          100
       Slices:          433
      Deflate:            0
    Frequency: monthly
     Ref_Date:     20190101
     Ref_Time:            0
     Duration: one month
    XY-offset:            0   (DcPc: Dateline Center, Pole Center)
      Fields: SpeciesConc_NO2 SpeciesConc_O3 SpeciesConc_ClO Met_PSC2WET Met_BXHEIGHT Met_AIRDEN Met_AD 
```

**Comment by msulprizio** [comment]
Ah, I think I see the issue. By default `StratBM.monthly` is set to 1 in HISTORY.rc.

https://github.com/geoschem/geos-chem/blob/ee8d0eb04d7ad095fe07fb930f28036f256b6709/run/GCHP/HISTORY.rc.templates/HISTORY.rc.fullchem#L5367-L5387

Does that mean it will always output a monthly mean file regardless of the frequency and duration settings? I think when I ran the simulation I saw it outputting hourly files, but when the run completed I was left with only monthly files.

**Comment by lizziel** [comment]
Right, all collections are set to monthly by default. Excluding a collection from the auto-update list requires manually setting monthly, duration, and frequency to what you want them to be if they are not already set that way. So in this case frequency and duration hourly are already set but monthly was turned on. It would need to be manually turned off before the run.

I'm not sure why it would output hourly files and then only have monthly files at the end. I've never seen history files deleted at the end.

**Comment by msulprizio** [comment]
Thanks! I have resubmitted the run with `StratBM.monthly` set to 0. So far I am getting hourly output files. I'll close out this issue for now and reopen if there are any lingering issues.
