### ISSUE TITLE
[FEATURE REQUEST] RRTMG

### ISSUE THREAD

**Issue by sdeastham** [geoschem/GCHP#28]
There is currently no way to calculate radiative forcing with GCHP. This is in spite of the presence of a version of RRTMG in the GEOS-Chem code.

**Comment by sdeastham** [comment]
NB: I intend to submit a PR to accomplish this (albeit imperfectly) shortly.

**Comment by lizziel** [comment]
This is done for GCHP 13.0.0. See https://github.com/geoschem/geos-chem/issues/350 for a summary of changes and links to related issues and PRs.
