### ISSUE TITLE
[BUG/ISSUE] Configuring GCHP 14.1.0 with Cmake fails at finding ESMA

### ISSUE THREAD

**Issue by Twize** [geoschem/gchp#289]
Hi, I am trying to compile the new version of GCHP (v14.1.0), however, when I attempt to configure the build with cmake, it fails with the following error:

```
CMake Error at CMakeLists.txt:55 (include):
  include could not find load file:

    esma


CMake Error at CMakeLists.txt:58 (ecbuild_declare_project):
  Unknown CMake command "ecbuild_declare_project".


-- Configuring incomplete, errors occurred!
```
I tried running the same cmake command on an earlier version of GCHP (v14.0.2) with the same software setup, but it did not give the same error and I was able to successfully compile the gchp executable. Its unclear what exactly has changed between the two GCHP versions, and the CMakeLists.txt appear to be almost identical. If I try to download and install GCHP v14.1.0 using spack, I encounter the same error.

Any help would be appreciated! 

### GEOS-Chem version
GCHP v14.1.0 

### Log files
- CmakeLists: [CMakeLists.txt](https://github.com/geoschem/GCHP/files/10747501/CMakeLists.txt)
- CmakeCache: [CMakeCache.txt](https://github.com/geoschem/GCHP/files/10747510/CMakeCache.txt)

### Software versions
- Compilers (Intel or GNU, and version): GCC v10.4.0
- NetCDF version: Netcdf-Fortran v4.6.0
- MPI version: intel-mpi v2019.10.317
- ESMF version: v8.3.1

**Comment by lizziel** [comment]
Hi @Twize, I was able to reproduce your error by downloading the code and building without first doing 'git submodule update --init --recursive'. Did you do the git submodule update before you tried to build?

NOTE: We are now asking users to identify themselves and their institution every time they request help. Please do this in the future. Thanks!

**Comment by Twize** [comment]
Hi @lizziel, that was exactly the issue... I must have forgotten to run 'git submodule' when I originally pulled the git repository a few days ago... My bad! 

I'll make sure to identify myself and my institution next time, I forgot to include that info this time, sorry!

**Comment by Twize** [comment]
Hi @lizziel sorry to comment on a closed thread, but is there any way to issue the 'git submodule update' command when downloading GCHP directly through Spack? It seems I can download the default version fine when I don't specify a version (default is v13.4.0 from the looks of it), but if I specify a newer version, using the command for example:

`spack install gchp@14.1.0%gcc@11.3.0 ^intel-mpi`

I get the same error I mentioned above about cmake being unable to find ESMA.

**Comment by lizziel** [comment]
Hi @Twize, I recommend download GCHP dependencies using Spack but not GCHP itself. We do not currently have Spack-built GCHP in our testing pipeline.
