### ISSUE TITLE
[QUESTION] MAPL Error in ExtData

### ISSUE THREAD

**Issue by gopikrishnangs44** [geoschem/gchp#291]
I am using GCHP 13.4.1. The error is:

```
  --- Diagnostics done!
        GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHPchem'
        GENERIC: INFO: Finished the 'Run' stage of the gridded component 'GCHP'
        GENERIC: INFO: Started the  'Run' stage of the gridded component 'HIST'
        GENERIC: INFO: Finished the 'Run' stage of the gridded component 'HIST'
 AGCM Date: 2020/09/30  Time: 23:00:00  Throughput(days/day)[Avg Tot Run]:   74.4   40.8   40.9  TimeRemaining(Est) 097:45:06   19.0% :  16.2% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  5.103E+04  0.000E+00
        GENERIC: INFO: Started the  'Run' stage of the gridded component 'EXTDATA'
pe=00000 FAIL at line=02630    MAPL_ExtDataGridCompMod.F90              <unknown error>
pe=00000 FAIL at line=01465    MAPL_ExtDataGridCompMod.F90              <status=-1>
pe=00000 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Run' stage of the gridded component 'EXTDATA'>
pe=00000 FAIL at line=01236    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=01181    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00804    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00934    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00247    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00154    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00031    GCHPctm.F90                              <status=1>
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 0.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

```

My allPES.log gives the error:

`0000: CAP.EXTDATA: ERROR: ExtData could not find appropriate file from file template  for side R
`

A similar issue is reported here 
https://github.com/geoschem/GCHP/issues/195

I have checked the volcano files, tried re-downloading the D, D+1 and D-1 met files, but still the same error occurs.

**Comment by lizziel** [comment]
Hi @gopikrishnangs44, do you know which file is causing the problem? You can output more information to `allPEs.log` by editing the config file `logging.yml`. See GCHP 13.4.1 ReadTheDocs section on [enable maximum prints](https://gchp.readthedocs.io/en/13.4.1/supplement/rundir-config.html?highlight=debug%20prints#enable-maximum-print-output).

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by gopikrishnangs44** [comment]
```
0007: CAP.EXTDATA: ERROR: ExtData could not find appropriate file from file template  for side R
0008: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Testing for file  for target time 2019-10-01 23:00:00
0009: CAP.EXTDATA: ERROR: ExtData could not find appropriate file from file template  for side R
0010: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Testing for file  for target time 2018-10-01 23:00:00
0011: CAP.EXTDATA: ERROR: ExtData could not find appropriate file from file template  for side R
0000: CAP.EXTDATA: ERROR: ExtData could not find appropriate file from file template  for side R
0001: CAP.EXTDATA: DEBUG:             UpdateBracketTime: Testing for file  for target time 2018-10-01 23:00:00
```

This is what the error is.

**Comment by lizziel** [comment]
It looks like version 13.4.1 the MAPL prints are not extensive enough to give more information. Strangely the file string being printed is empty. You might be able to figure out what file is the issue based on what came before in the log file, i.e. the last successful file. The log should also show the variable in the loop over inputs, but it would be higher in the file than the snipper you copied. You could also follow the traceback message to the location of the error in MAPL and add additional prints if the log does not have more information. After figuring out what file and variable is the issue you should look at the time content of the files and make sure they make sense.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by lizziel** [comment]
Hi @gopikrishnangs44, were you able to fix this issue?

**Comment by gopikrishnangs44** [comment]
Hi @lizziel,

Sorry for the late update. 

No, I was not able to solve the issue. In fact, I tried to run the model from 2019 to 2021 skipping 30th September by using the restart file and restarted the model again from 01 October. For all the 3 years, the model crashed with the same error on the same date (30th September)

**Comment by lizziel** [comment]
Hi @gopikrishnangs44, this definitely sounds like a corrupt file problem. You could try upgrading to the latest GCHP version which has more extensive MAPL error handling, or you could follow the traceback of your current run to file line number where the error is happening. There likely is a variable called `this` for which you can see what derived type it is declared as and check if that derived type includes filename and/or variable name. If it does, you can print it as `this%name`, recompile, rerun, and check the log.

**Comment by gopikrishnangs44** [comment]
Hi @lizziel, Should I need to upgrade to version 14 of GCHP?

**Comment by lizziel** [comment]
You shouldn't need to upgrade, but we do recommend always using the latest version, and that version has better messages about corrupt files.
