### ISSUE TITLE
Can GCHP catch an episode that last for certain days every year with the default emission files?

### ISSUE THREAD

**Issue by Hemrajbhattarai** [geoschem/gchp#292]
I am attempting to use GCHP to capture an annual episode that lasts a few days over the Himalayas, with research suggesting it may be caused by agricultural fires. I have successfully tested my GCHP installation, but I am unsure if the default emission files can accurately capture such a short episode. Can you recommend an emission file that would be better suited for this purpose?

Additionally, I have a question regarding the initial file. To investigate an episode occurring from April 10-13, 2020, I plan to run the model for the entire month of April to observe pre-, during-, and post-conditions. Would it be appropriate to start the model on March 25, let it run for 5 days, and use the last day's (March 31) initial file to simulate April? Would I need to update the initial file again when the model begins simulating April or is the March 31 file sufficient?

Thank you.

**Comment by yantosca** [comment]
Thanks for writing @Hemrajbhattarai.  We are not able to recommend emission configurations.  That question would be better directed to the Emissions Working Group.  Tagging @jaegle @eamarais

If you are using the full-chemistry simulation, we would recommend a spinup of about 6 months.

NOTE: We are now asking users to identify themselves and their institutions when requesting help. Please do this in the future. Thanks!

**Comment by eamarais** [comment]
Hi @Hemrajbhattarai, if it's agricultural fires, check whether GEOS-Chem has the emissions for your year of interest at the appropriate temporal resolution. If so, run and sample the model to see whether these are appropriate. If not, it would be best to seek advice and guidance from the literature and researchers with expertise on this and related topics to get more tailored advice.
