### ISSUE TITLE
[FEATURE REQUEST] Way to generate gridspec files for the model grid

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#30]
It would be useful if there was a way to generate gridspec files for the model grid. I see some references to gridspec files in ExtData output which makes me think MAPL might some support for generating gridspec files, and ESMF supports gridspec inputs. For stretched-grids (and normal cubed-spheres) the grid-box corner coordinates are useful for plotting model output, and a way to generate gridspec files for the model grid seem like the proper and cleanest way to provide these coordinates. This would also facilitate the use of ESMF's offline regridders since `ESMF_RegridWeightGen` and `ESMF_Regrid` can take grid definitions for cubed-sphere and stretched-grid grids in the gridspec file format.  I can inquire about this in the next MAPL call.

It would be nice if there was an option for `geos` like
```
./geos --generate_gridspec
```
that generated the gridspec file.

Note that right now I have a custom script for generating a NetCDF file with corner coordinates, but I think it would be best to avoid solutions like this if possible.

**Comment by lizziel** [comment]
@LiamBindle, is this feature request all set and okay to close? If I recall correctly the new grid spec is included in MAPL 2.6.3 which is going into GCHP 13.1.

**Comment by LiamBindle** [comment]
@lizziel Yeah, I think so. It's possible to generate gridspec files for cubed-sphere and lat-lon grids that are compatible with ESMF with https://github.com/LiamBindle/gridspec. IIUC the the diagnostics in 13.1 now include `corner_lats` and `corner_lons`. These are necessary for conservative regridding and plotting the diagnostics (because the grid is curvilinear). The updated diagnostics aren't [gridspec files](https://arxiv.org/abs/1911.08638), but we can regrid them offline with ESMF using that gridspec utility I wrote now, so I think we can close this. 

Thanks for following up. I'll close
