### ISSUE TITLE
[FEATURE REQUEST] Make GCHP species initial restart handling the same as GC-Classic

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#300]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [X] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### New GCHP feature or discussion

Species are allowed to be missing in initial restart files for GC-Classic benchmark simulations but not for others, e.g. standard simulation. However, in GCHP species are allowed to be missing in all simulations. We should update the GCHP initial restart file handling to match that of GC-Classic. This can be done by adjusting the MAPL restart file attribute of advected and non-advected species when declaring the internal state based on simulation type, such as [here](https://github.com/geoschem/geos-chem/blob/4722f288e90291ba904222f4bbe4fc216d17c34a/Interfaces/GCHP/Chem_GridCompMod.F90#L609). Ideally there would a run-time toggle for this.

**Comment by Twize** [comment]
Hi @lizziel, are there a specific set of species which may be missing from restart files and/or some set of conditions which causes species to be missing? From a quick inspection using ncdump of the restart files from my GCHP v14.1.1 simulation, it looks like at least all of the advected species are present in the restarts which my simulations have produced.

**Comment by lizziel** [comment]
Hi @Twize, this would only impact the initial restart file and not the output restart files. GEOS-Chem always outputs all species at the end regardless of whether all species are in the initial restart file.

**Comment by Twize** [comment]
Got it! Thanks for the clarification.

**Comment by lizziel** [comment]
I just updated my original post to hopefully make it more clear. I agree it was a bit ambiguous.
