### ISSUE TITLE
RRTMG time step not extracted

### ISSUE THREAD

**Issue by sdeastham** [geoschem/gchp#301]
### Name and Institution (Required)

Name: Seb Eastham
Institution: MIT

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

When using GCHP 14.0.0, it is impossible to run RRTMG. An error is thrown stating that the timesteps are not matched. However, GCHP should be automatically setting the RRTMG time step to the value for `RRTMG_DT` in `GCHP.rc`. The error appears to stem from not setting `Input_Opt%TS_RAD` to match `tsRad` after extraction in `Chem_GridCompMod.F90`.

**Comment by yantosca** [comment]
Hi @sdeastham!  This is fixed in 14.1.0.  See: #279

**Comment by sdeastham** [comment]
Hi @yantosca - ah, thanks for the quick response! Serves me right for not doing a thorough enough search. Great to see this was fixed!
