### ISSUE TITLE
Error in WASHOUT for wet deposition in GCHP v14.1.1

### ISSUE THREAD

**Issue by Twize** [geoschem/gchp#302]
### Name and Institution 

Name: Tyler Wizenberg
Institution: University of Toronto

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Hi! I am unfortunately encountering the exact issue described in https://github.com/geoschem/geos-chem/issues/1662 in GCHP v14.1.1. I figured that for searchability by other GCHP users, I would make an issue here because I actually had quite a difficult time finding the aforementioned issue from the geos-chem github. 

#### Short summary of the issue

When running a standard full-chemistry C48 simulation, the simulation will crash at seemingly random (but consistent) times in the model while doing wet deposition. For example, starting a standard full-chem C48 simulation on 2017-01-01, the simulation will consistently crash at 21:00 with the following error: 

```AGCM Date: 2017/01/01  Time: 21:00:00  Throughput(days/day)[Avg Tot Run]:        130.9        272.2        423.2  TimeRemaining(Est) 000:12:22   33.5% :  29.2% Mem Comm:Used
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  5.629E+04  0.000E+00
===============================================================================
WETDEP: ERROR at    8   9   1 for species    2 in area WASHOUT: at surface
 LS          :  T
 PDOWN       :    0.0000000000000000     
 QQ          :    0.0000000000000000     
 ALPHA       :    0.0000000000000000     
 ALPHA2      :    0.0000000000000000     
 RAINFRAC    :    0.0000000000000000     
 WASHFRAC    :    0.0000000000000000     
 MASS_WASH   :    0.0000000000000000     
 MASS_NOWASH :    0.0000000000000000     
 WETLOSS     :                        NaN
 GAINED      :    0.0000000000000000     
 LOST        :    0.0000000000000000     
 DSpc(NW,:)  :                        NaN   5.6420620126013986E-010   5.8324601082917777E-010   6.1846330836059266E-010   6.6549208117434884E-010   7.2309293268396519E-010   7.8812032404432935E-010   8.6366722261545318E-010   9.5190421932233184E-010   1.0529606427208481E-009   1.1725690692752231E-009   1.2818597332708963E-009   1.3714116657733704E-009   1.3941488462256711E-009   1.3139156964441311E-009   1.1864962955399888E-009   9.9820641376508372E-010   7.0416837871267482E-010   3.5379826200402548E-010   5.9135460897663136E-014   0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000        0.0000000000000000     
 Spc(I,J,:N) :                        NaN   3.0982791193475669E-008   3.5753185329073430E-008   4.0771595515725952E-008   4.6558443952367673E-008   5.2826989932550128E-008   5.9367251269425585E-008   6.4136247330152540E-008   6.9901392619715593E-008   7.6440016034191974E-008   8.1623566606436207E-008   8.6174905282504230E-008   1.1755714123698848E-007   1.4188756224578141E-007   1.3414471119276807E-007   1.1768753324513033E-007   1.0139982686312031E-007   8.0551155740553148E-008   1.0277606939823998E-007   1.1108126409528471E-007   9.4924150359122261E-008   7.7521964004264850E-008   7.8797543661241682E-008   8.0806890994737919E-008   6.6504006188435363E-008   5.0261753457022894E-008   3.3889087032865995E-008   2.7195055827409315E-008   2.2579553823914861E-008   1.8770582811521159E-008   1.4990337914427814E-008   1.1777691906397986E-008   4.2885238458446028E-009   2.5316922756005818E-009   4.4336988269850555E-010   3.3913755609947382E-011   6.7797917245334660E-012   4.3632376898685281E-013   1.0414712457732739E-013   3.4726953809195411E-014   1.3855973640070992E-014   3.1231055551011379E-015   4.7089386901041348E-016   8.2754692265600577E-017   2.4809638844755168E-017   1.6597686211466048E-017   1.6382977438540187E-017   1.9578883760333267E-017   3.0537974544903648E-017   5.3294318081424080E-017   7.7153794953072342E-017   1.6035388521672255E-016   2.4513354855514184E-016   3.5772539163132652E-016   3.4937735464529797E-016   1.7947788730563934E-016   2.3404150141730234E-016   2.3354757480963649E-016   4.0991417052973557E-014   1.6834413356462779E-013   2.4433993459057381E-013   3.5748501101302443E-013   4.9337489241841586E-013   5.7533438623964649E-013   6.4290697764850772E-013   7.9066248891754171E-013   7.0693014217421869E-013   7.8492507825650077E-013   1.0823665282548935E-012   1.6432708784930111E-012   2.4296986071037556E-012   2.8165792348551979E-012
===============================================================================
 
GEOS-Chem ERROR [0039]: Error encountered in wet deposition!
 --> LOCATION:  -> at SAFETY (in module GeosCore/wetscav_mod.F90)
 
GEOS-Chem ERROR [0039]: Error encountered in "Safety"!
 --> LOCATION:  -> at Do_Washout_at_Sfc (in module GeosCore/wetscav_mod.F90)
 
GEOS-Chem ERROR [0039]:
 --> LOCATION:  -> at WetDep (in module GeosCore/wetscav_mod.F90)
 
GEOS-Chem ERROR [0039]: Error encountered in "Wetdep"!
 --> LOCATION:  -> at Do_WetDep (in module GeosCore/wetscav_mod.F90)
```

The error appears to be caused by there being NaN values in the species concentration ( `Spc(I,J,:N)`) field at the surface, and by extension the `DSpc(NW,:)` field as well. This leads to the following expression at line 4542 of /GeosCore/wetscav_mod.F90:

`WETLOSS = Spc(N)%Conc(I,J,L) * WASHFRAC - GAINED` 

being evaluated as NaN. It's likely that the error may be coming from deeper within the model and is only being caught by the wet deposition routine. The error occurs at seemingly random, but consistent times given a certain configuration (it will always crash at 20170101 21:00 when running C48). I managed to run a C48 simulation starting on 20170601 and it ran fine up until 20170925 21:40, and then crashed with the same error (and it will continue to crash at this point). 

#### Summary of steps taken and things tested
- Tried changing the initial restart file to one from an already spun-up simulation -> Still crashes with the same error.
- Turning off wet deposition -> Leads to an error in `DO_CLOUD_CONVECTION` at a similar time in the simulation.
- Removing species 2 (ACTA; acetic acid) from the advected species list -> same error occurs with the next wet-deposited species down the list, so likely not species-dependent.
- Use finer time-steps for Chemisty of 600 seconds and Transport/Convection of 300 seconds (vs. 1200s and 600s originally) -> Error still occurs at the same time 
- Try compiling GCHP with a different compiler to rule out issues introduced by my specific compiler version, tested with both GCC 9.4.0 + OpenMPI 4.1.1 and GCC 10.3.0 + OpenMPI 4.1.1 -> Both still produce the same error.
- Try degrading the cube-sphere resolution from C48 to C24 -> Allows the simulation to progress past 20170101 21:00, but it will still crash with the wet deposition error at 20170106 12:20. 

#### Simplest steps to reproduce the issue
1. Initialize a standard full-chem run-directory with MERRA-2 meteorology (I have not tested GEOS-FP yet)
2. Set start date in cap_restart to 20170101, set cube-sphere resolution to C48, copy over the default C48 restart from 20190701 and re-name it to match the 20170101 start date (the issue is not restart dependent). 
3. Run the simulation and it should crash at 20170101 21:00. 

At this point, it feels like I have tested a whole slew of things to no avail, and I am running out of ideas. This bug seems to be quite severe and is preventing me from running longer simulations. Any help on this issue would be appreciated! 

#### Software configuration
Model version: GCHP v14.1.1
Compiler: GCC 9.4.0 (also tested GCC 10.3.0)
OpenMPI: 4.1.1
Cmake: 3.25.0
NetCDF Fortran: 4.6.0
ESMF: 8.3.1

#### Relevant files
GCHP log: [gchp.log](https://github.com/geoschem/GCHP/files/10957559/gchp.log)
Slurm Output: [slurm_output_9036949.txt](https://github.com/geoschem/GCHP/files/10957553/slurm_output_9036949.txt)
Run settings file: [setCommonRunSettings.sh.zip](https://github.com/geoschem/GCHP/files/10957567/setCommonRunSettings.sh.zip)
HEMCO Config: [HEMCO_Config.rc.zip](https://github.com/geoschem/GCHP/files/10957587/HEMCO_Config.rc.zip)

**Comment by lizziel** [comment]
Hi @Twize, thank you for looking into this and reporting so much detailed information. I am going to try to reproduce now.

**Comment by lizziel** [comment]
I was able to reproduce this. I can get the error within 11 hours if I use our restart file for Jan 1, 2019 and start the simulation on Jan 1, 2017. I saved out hourly restart files and can now reproduce with a single run starting on hour 10, and with only chemistry, wetdep, and convection on. I'll let you know when I figure out where the NaN values are coming in.

**Comment by Twize** [comment]
> I was able to reproduce this. I can get the error within 11 hours if I use our restart file for Jan 1, 2019 and start the simulation on Jan 1, 2017. I saved out hourly restart files and can now reproduce with a single run starting on hour 10, and with only chemistry, wetdep, and convection on. I'll let you know when I figure out where the NaN values are coming in.

Hi @lizziel, thanks for the update. I am glad that you were able to reproduce the error, thank you for your help investigating this!

**Comment by lizziel** [comment]
HI @Twize, I created a PR for what I believe fixes the problem. See [here](https://github.com/geoschem/geos-chem/pull/1698).

**Comment by Twize** [comment]
Hi @lizziel, very quick work! This might be a silly question, but is it possible for me to apply the fix to my current GCHP v14.1.1 core codes? If so, how would one apply the bugfix?

**Comment by lizziel** [comment]
Hi @Twize, yes, you can apply the fixes shown in the "Files changed" tab of the pull request. See [here](https://github.com/geoschem/geos-chem/pull/1698/files). Just make sure you apply the changes based on context not specific line numbers listed since my base branch is dev/14.2.0 and not 14.1.1.

Also, for future reference, I honed in on the issue by building with `-DCMAKE_BUILD_TYPE=Debug`, and then running a simulation where I knew it was going to fail. This gave a divide-by-zero error with a traceback to the file and line number. Without building in Debug mode errors like that do not necessarily cause the model to immediately fail but instead crash elsewhere.

**Comment by Twize** [comment]
> Hi @Twize, yes, you can apply the fixes shown in the "Files changed" tab of the pull request. See [here](https://github.com/geoschem/geos-chem/pull/1698/files). Just make sure you apply the changes based on context not specific line numbers listed since my base branch is dev/14.2.0 and not 14.1.1.

Thanks, I was able to apply the fixes and recompile successfully. I will run a test simulation and let you know if it solved the problem. 

> Also, for future reference, I honed in on the issue by building with `-DCMAKE_BUILD_TYPE=Debug`, and then running a simulation where I knew it was going to fail. This gave a divide-by-zero error with a traceback to the file and line number. Without building in Debug mode errors like that do not necessarily cause the model to immediately fail but instead crash elsewhere.

Also thanks for this tip! Now that you mention it I remember reading about building with debug mode in the GCHP readthedocs.io, but for some reason it did not cross my mind other day when I was looking into this bug. I will make use of this in the future.

**Comment by Twize** [comment]
Hi @lizziel, it looks like the bug fix worked. I was able to run a 7 day simulation starting on 20170101 with no crashes. I am going to go ahead and close the issue, thanks for helping squash the bug so quickly!
