### ISSUE TITLE
[BUG/ISSUE] HIST initialization error when cores >3000

### ISSUE THREAD

**Issue by 1Dandan** [geoschem/gchp#303]
### Name and Institution (Required)

Name: Dandan Zhang
Institution: Washington University in St. Louis

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
I am trying to run a C720 simulation with GCHP v13.4.1 on NASA Pleiades system. It works well when total number of cores is <3000. When cores >3000, it shows error about HIST initialization in run.log file and also in ESMF_Grid.F90 saying there is problem of creating grids. I used 3456 cores (24 * 24 * 6), which satisfied the conditions of NY=6*NX. All settings for simulations with different number of cores are the same except the cores/nodes number. Thus I am not sure what it means by the grid creation error.

I have tested total cores 2400 and 2904 which work fine, while cores 3456, 4704, and 5400 give the same error at the initialization stage of HIST due to grid creation error.

#### Specific error message:
In PETxxxx.ESMF_LogFile:
```
20230316 082012.442 ERROR            PET1483 ESMF_Grid.F90:15037 ESMF_GridCreateCubedSphereIReg() Wrong argument specified  - - the total number of elements in dimension 1 does not     add up to tilesize
```
In run.log file:
```
...
  Reading HISTORY RC Files:
  -------------------------
 pe=00368 FAIL at line=00246    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=03182 FAIL at line=00246    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=00368 FAIL at line=00182    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=03182 FAIL at line=00182    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=00368 FAIL at line=00318    MAPL_AbstractGridFactory.F90             <status=15>
 pe=03182 FAIL at line=00318    MAPL_AbstractGridFactory.F90             <status=15>
 pe=00368 FAIL at line=00204    MAPL_GridManager.F90                     <status=15>
 pe=03182 FAIL at line=00204    MAPL_GridManager.F90                     <status=15>
 pe=00368 FAIL at line=00252    MAPL_GridManager.F90                     <status=15>
 pe=03182 FAIL at line=00252    MAPL_GridManager.F90                     <status=15>
 pe=00368 FAIL at line=00669    MAPL_HistoryGridComp.F90                 <status=15>
 pe=03182 FAIL at line=00669    MAPL_HistoryGridComp.F90                 <status=15>
 pe=00368 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'HIST'>
 pe=03182 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'HIST'>
 pe=00368 FAIL at line=00685    MAPL_CapGridComp.F90                     <status=1>
 pe=03182 FAIL at line=00685    MAPL_CapGridComp.F90                     <status=1>
 pe=00368 FAIL at line=00630    MAPL_CapGridComp.F90                     <status=1>
 pe=03182 FAIL at line=00630    MAPL_CapGridComp.F90                     <status=1>
 pe=00368 FAIL at line=00920    MAPL_CapGridComp.F90                     <status=1>
 pe=03184 FAIL at line=00246    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=00368 FAIL at line=00245    MAPL_Cap.F90                             <status=1>
 pe=03184 FAIL at line=00182    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=00368 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
 pe=03184 FAIL at line=00318    MAPL_AbstractGridFactory.F90             <status=15>
 pe=00369 FAIL at line=00246    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=03184 FAIL at line=00204    MAPL_GridManager.F90                     <status=15>
 pe=00369 FAIL at line=00182    MAPL_CubedSphereGridFactory.F90          <status=15>
 pe=03184 FAIL at line=00252    MAPL_GridManager.F90                     <status=15>
 pe=00369 FAIL at line=00318    MAPL_AbstractGridFactory.F90             <status=15>
 pe=03184 FAIL at line=00669    MAPL_HistoryGridComp.F90                 <status=15>
 pe=00369 FAIL at line=00204    MAPL_GridManager.F90                     <status=15>
 pe=03184 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'HIST'>
...
```

#### Configuration/log files for the simulation with 3456 cores
[CAP.rc.txt](https://github.com/geoschem/GCHP/files/10993040/CAP.rc.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/10993041/ExtData.rc.txt)
[GCHP.rc.txt](https://github.com/geoschem/GCHP/files/10993042/GCHP.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/10993043/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/10993044/HISTORY.rc.txt)
[logging.yml.txt](https://github.com/geoschem/GCHP/files/10993045/logging.yml.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/10993046/runConfig.sh.txt)

[run-CEDS01-vert-noLUO-20230316_0926.log.txt](https://github.com/geoschem/GCHP/files/10993798/run-CEDS01-vert-noLUO-20230316_0926.log.txt)
[PET0000.ESMF_LogFile.txt](https://github.com/geoschem/GCHP/files/10993053/PET0000.ESMF_LogFile.txt)

Submitting scripts: 
[run-3456-hybrid.pbs.txt](https://github.com/geoschem/GCHP/files/10993802/run-3456-hybrid.pbs.txt)

loaded environment:
```
  1) git/2.30.2               4) other/mepo               7) comp-gcc/11.2.0-TOSS3   10) hdf4/4.2.12             13) netcdf/4.4.1.1_serial
  2) cmake/3.21.0-TOSS3       5) other/gh                 8) comp-intel/2020.4.304   11) szip/2.1.1              14) GCHPenv/2022-09.Intel
  3) other/manage_externals   6) ImageMagick/7.0.8-53     9) mpi-hpe/mpt.2.25        12) hdf5/1.8.18_serial
```
Plus ESMF v8.0.0

**Comment by lizziel** [comment]
Hi @1Dandan, I don't recall seeing this error before. I am looking into this, and documented some handy links below.

- [ESMF 8.0.1 interface that is being used](https://github.com/esmf-org/esmf/blob/cec0099eb91be8bf93b23954a5bbe10e66f32a2d/src/Infrastructure/Grid/interface/ESMF_Grid.F90#L535-L543)
- E[SMF source code for creation of a regular cubed sphere grid](https://github.com/esmf-org/esmf/blob/cec0099eb91be8bf93b23954a5bbe10e66f32a2d/src/Infrastructure/Grid/interface/ESMF_Grid.F90#L14411-L14441) (1 of 2 procedures for the interface)
- [ESMF sourse code for the creation of an irregular cubed sphere grid](https://github.com/esmf-org/esmf/blob/cec0099eb91be8bf93b23954a5bbe10e66f32a2d/src/Infrastructure/Grid/interface/ESMF_Grid.F90#L14881-L14910) (the other interface, and the one where your error is happening)
- [ESMF code where the error is encountered and caught](https://github.com/esmf-org/esmf/blob/cec0099eb91be8bf93b23954a5bbe10e66f32a2d/src/Infrastructure/Grid/interface/ESMF_Grid.F90#L15045-L15050)
- [MAPL call to ESMF that is failing](https://github.com/GEOS-ESM/MAPL/blob/7029268300e54c32a19fce5516f0fb13d2e47ec1/base/MAPL_CubedSphereGridFactory.F90#L243-L246)

The challenge here is to figure out what is being passed from MAPL to ESMF that is causing the error trap trigger. In particular I am wondering if it is correct that it is trying to create an irregular grid. I would think history would create only regular grids. I realize running these simulations is incredibly expensive so if you can't readily print these out from MAPL we may just need to stare at the code to figure it out. But if you can run again, I'd also be curious about whether the error goes away if you do not turn on any diagnostics.

Pinging @tclune in case he has seen this error before and already has a solution.

**Comment by tclune** [comment]
Am mentioning @nasa-ben as well in case he has a thought.

First odd thing is that History does not usually create CS grids.   Generally CS output is native, and History would just reuse the model grid.   Are you attempting to output on a different CS grid than is used in the model?   Have you explicitly listed a CS grid in your HISTORY.rc file?  (And can you post that file here?

The error itself could suggest that there is some mismatch between the intended decomposition and what was actually requested.  Again, the HISTORY.rc file would likely help to identify this.

If possible, could you add a print to show the value of `this%IM_WORLD` (on the failing process or all processes)?

**Comment by 1Dandan** [comment]
Thanks @lizziel and @tclune. I did not output diagnostics on a different grid. The HISTORY.rc is attached in above description post as HISTORY.rc.txt. The collection I am outputing is:
```
   ACAG.template:     '%y4%m2%d2_%h2%n2z.nc4',
   ACAG.format:       'CFIO',
   ACAG.frequency:    010000
   ACAG.duration:     010000
   ACAG.mode:         'time-averaged'
   ACAG.fields:       'SpeciesConc_NO2     ', 'GCHPchem',
                      'SpeciesConc_NO      ', 'GCHPchem',
                      'SpeciesConc_PAN     ', 'GCHPchem',
                      'SpeciesConc_O3      ', 'GCHPchem',
                      'SpeciesConc_SO2     ', 'GCHPchem',
...
```
For the value of `this%IM_WORLD`, I do see `GCHP.rc` is updated in accordance with C720, do you want me to add printing in source code as well?
In `GCHP.rc`:
```
 # Atmospheric Model Configuration Parameters
 # ------------------------------------------
 NX: 24
 NY: 144
 
 GCHP.GRID_TYPE: Cubed-Sphere
 GCHP.GRIDNAME: PE720x4320-CF
 GCHP.NF: 6
 GCHP.IM_WORLD: 720
 GCHP.IM: 720
 GCHP.JM: 4320
 GCHP.LM: 72
 
 # For stretched grid
 #GCHP.STRETCH_FACTOR: 2.0
 #GCHP.TARGET_LON: 242.0
 #GCHP.TARGET_LAT: 37.0
 
 # For FV advection do not use grid comp name prefix
 IM: 720
 JM: 4320
 LM: 72
 
 GEOSChem_CTM: 1
...
```

**Comment by lizziel** [comment]
I suspect that MAPL History includes the creation of each of the grids listed in the `GRID_LABELS` section of `HISTORY.rc` regardless of whether they are specified for a collection. Here is the code that parses the `GRID_LABELS` section, in `MAPL_HistoryGridComp.F90`. I can test if this is true. If it is, then commenting out all grid labels not used might fix the problem.

```
       OUTPUT_GRIDS: block
         type (ESMF_Grid) :: output_grid
         type (StringGridMapIterator) :: iter
         integer :: nl
         character(len=60) :: grid_type

         call ESMF_ConfigFindLabel ( config,'GRID_LABELS:',rc=STATUS )
         _VERIFY(status)
         tend  = .false.
         do while (.not.tend)
             call ESMF_ConfigGetAttribute ( config,value=tmpstring,default='',rc=STATUS) !ALT: we don't check return status!!!               
             if (tmpstring /= '')  then
                call IntState%output_grids%insert(trim(tmpString), output_grid)
             end if
             call ESMF_ConfigNextLine     ( config,tableEnd=tend,rc=STATUS )
             _VERIFY(STATUS)
          enddo

          iter = IntState%output_grids%begin()
          do while (iter /= IntState%output_grids%end())
             key => iter%key()
             call ESMF_ConfigGetAttribute(config, value=grid_type, label=trim(key)//".GRID_TYPE:",rc=status)
             _VERIFY(status)
             call  ESMF_ConfigFindLabel(config,trim(key)//".NX:",isPresent=hasNX,rc=status)
             _VERIFY(status)
             call  ESMF_ConfigFindLabel(config,trim(key)//".NY:",isPresent=hasNY,rc=status)
             _VERIFY(status)
             if ((.not.hasNX) .and. (.not.hasNY)) then
                if (trim(grid_type)=='Cubed-Sphere') then
                   call MAPL_MakeDecomposition(nx,ny,reduceFactor=6,rc=status)
                   _VERIFY(status)
                else
                   call MAPL_MakeDecomposition(nx,ny,rc=status)
                   _VERIFY(status)
                end if
                call MAPL_ConfigSetAttribute(config, value=nx,label=trim(key)//".NX:",rc=status)
                call MAPL_ConfigSetAttribute(config, value=ny,label=trim(key)//".NY:",rc=status)
             end if
             output_grid = grid_manager%make_grid(config, prefix=key//'.', rc=status)
             _VERIFY(status)
             call IntState%output_grids%set(key, output_grid)
             call iter%next()
          end do
       end block OUTPUT_GRIDS
```

**Comment by lizziel** [comment]
Confirmed. MAPL History is creating all grids listed in `GRID_LABELS` regardless of whether they are used. All of the GCHP `HISTORY.rc` files come with a few examples of `GRID_LABELS`, and those are the ones you have in your file. Comment them out (see example below) and try running again. When I did this in my test MAPL no longer created the grids.
```
GRID_LABELS: #PE24x144-CF
             #PC360x181-DC
             #REGIONAL1x1
    ::
```

**Comment by 1Dandan** [comment]
Thanks @lizziel. It is the reason! After commenting out the lines of `GRID_LABELS` in `HISTORY.rc`, it works fine for simulations with 3456 cores.

**Comment by lizziel** [comment]
Okay, great! I'll make sure those lines are commented out by default in the next version of GEOS-Chem.

@tclune, do you want me to create a MAPL issue about this, or is this behavior expected?

**Comment by tclune** [comment]
Ah - we had networking issues yesterday and I missed a few crucial posts above!    Good catch.   Yes - please open a ticket.   Looks to me like we have 2 problems.  (1) we should not create the grids listed in `GRID_LABELS` unless they are used, and (2) why these were generating an ESMF error.   None of those commented out were referencing CS, so still confusing.

**Comment by lizziel** [comment]
Regarding problem 2, my theory is grid label `PE24x144-CF` is too low resolution for high core counts. That one is C24, which would have 3456 grid cells, exactly the same number of cores used. Maybe the decomposition breaks down at that point, and becomes impossible beyond it.

```
    PE24x144-CF.GRID_TYPE: Cubed-Sphere
    PE24x144-CF.IM_WORLD: 24
    PE24x144-CF.JM_WORLD: 144
    PE24x144-CF.LM: 72
```

**Comment by tclune** [comment]
Ah - and it is my ignorance that did not recognize that as a CS grid.   I saw "PE" and was thinking "Pole-Edge" which is a Lat-lon concept.

You're theory is quite likely right.  But would not hurt for MAPL to generate a better error message in that case if possible.

**Comment by bena-nasa** [comment]
Yes, just remove make the GRID_LABELS: an empty list, then the definitions won't be used to create grids. And trying to create c24 grid on 3000 processors just won't fly, that's just too coarse of grid for that many processors.

**Comment by lizziel** [comment]
We are resolving this issue in GEOS-Chem 14.2.0 by commenting out the example grid labels at the top of `HISTORY.rc`.
