### ISSUE TITLE
Documentation updates to supplemental guides

### ISSUE THREAD

**Issue by yantosca** [geoschem/gchp#308]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### New GCHP feature or discussion

We need to look at the GCHP Supplemental Guides to make sure the instructions have not gone stale.  These include:

- [x] Build dependencies (@yantosca)
- [X] Use GCHP Containers (@yidant)
- [X] Stretched-grid simulation (@lizziel)
- [X] Output along a track (@lizziel)
- [x] Manage a data archive with bashdatacatalog (@yantosca, will point to forked repo at geoschem/bashdatacatalog)
- [X] New supplemental guide for passive species in 14.2.0 (@msulprizio, @yantosca)
- [X] Set up AWS ParallelCluster (@yidant)
 
The following Guides will be left as-is for now
- Cache Input Data on Fast Drives

The remaining Supplemental Guides are shared between GEOS-Chem, GCHP, and HEMCO, and are maintained by @yantosca.

**Comment by lizziel** [comment]
@yantosca, thank you for putting this together! I'll get to checking the stretched grid pages in the next week.

**Comment by yantosca** [comment]
I have updated the geos-chem-shared-docs repository as follows:
- Now point bashdatacatalog supplemental guide to the https://github.com/geoschem/bashdatacatalog wiki (instead of at Liam Bindle's GitHub), see commit https://github.com/geoschem/geos-chem-shared-docs/commit/e59bb2e8323df2af7b9c603d79bb39df65e70cc4
- Updated the "Using KPP with GEOS-Chem" supplemental guide for KPP 3.0.0, see commits https://github.com/geoschem/geos-chem-shared-docs/commit/e8b0bd326a57b6d7207c624205eae35971f20fa4 and https://github.com/geoschem/geos-chem-shared-docs/commit/cf2f56a3a557af56d692fc72132b383664e5a10e

The `docs/dev` branch in the superprojects have all been updated.  Please see the following commits:
- https://github.com/geoschem/GCClassic/commit/b7cdc72cdff4d58d84bf86db0332dcd4b3564229
- https://github.com/geoschem/HEMCO/commit/65146912d385dbb44397a4b59e0ccb7f435a6453
- GCHP: https://github.com/geoschem/GCHP/commit/2cab4602fbc743380513566fd3ed1011895d2da6

**Comment by yantosca** [comment]
The Spack build instructions have now been rewritten.  See: https://geos-chem.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/spack-guide.html 

This guide is shared among GCClassic, GCHP, HEMCO ReadTheDocs sites.

**Comment by lizziel** [comment]
The stretched grid supplementary guide is now updated in the docs/dev branch to be merged in 14.2.

**Comment by lizziel** [comment]
Hi @yidant, I am bringing you in on this GitHub issue since you are working on multi-node GCHP runs on the cloud. The original plan was we would keep the parallelCluster documentation on ReadTheDocs the same since none of us were working on it. Perhaps that has changed now and we can add that supplemental guide to the checklist and assign you?

@SaptSinha, have you had a chance to work on the guides assigned to you?

**Comment by SaptSinha** [comment]
I wanted to share some updates regarding my assigned tasks for updating the documentations.

Regarding the [Use GCHP Containers](https://gchp.readthedocs.io/en/latest/supplement/containers.html#) portion of the documentation, all the sections look okay to me, except for the [link](https://hub.docker.com/r/geoschem/gchp/tags?page=1&ordering=last_updated) that points to the GCHP images on the docker hub which are out of date. The latest image there corresponds to a 13.4.1 build.

Regarding the [Output Along a Track](https://gchp.readthedocs.io/en/latest/supplement/satellite-overpass.html#) portion of the documentation, I have never used this feature till date. Probably someone who has expertise in this area could handle this part of the documentation.

**Comment by lizziel** [comment]
Thanks for the update @SaptSinha. None of us have expertise in the output along a track functionality since it was developed by Liam. Whoever takes it on will need to learn it by following the guide, and made edits/code updates as needed to bring it up to date. Do you think you would be able to do this?

Regarding the GCHP containers section, could you figure out how to update dockerhub to include the latest version releases?

**Comment by SaptSinha** [comment]
Sure, @lizziel. I met with Randall today and he mentioned that @yidant might have already started the process of creating the updated GCHP containers. However, if that is not the case, I am happy to take this up and update the containers/docker images over time and change the documentation accordingly.

Regarding the Output Along a Track feature, I did some preliminary study and must admit that most of this looks Greek to me. I can ask some of the ACAG folks but I am not entirely sure if that would be helpful.

**Comment by SaptSinha** [comment]
Sure, @lizziel. I met with Randall today and he mentioned that @yidant might have already started the process of creating the updated GCHP containers. However, if that is not the case, I am happy to take this up and update the containers/docker images over time and change the documentation accordingly.

Regarding the Output Along a Track feature, I did a preliminary study and much of it appears too unfamiliar. However, I can invest time on this after I clear some of the other tasks from my list that Randall asked me to prioritize.

**Comment by yidant** [comment]
Hi @lizziel and @SaptSinha, I'm still working on some issues on AWS and I'd be glad to take up the work to add ParallelCluster documentation. 

I'm also working on GCHP containers. Feel free to reassign this work to me.

**Comment by lizziel** [comment]
Thanks @yidant. I updated the assignment of GCHP containers to you and also added an entry for ParallelCluster docs. @SaptSinha, I can test out the satellite track output rather than you so you can focus on other things.

**Comment by lizziel** [comment]
I am closing out this issue as all supplemental guides in GCHP are now updated. Maintenance into the future will not be tracked in a github issu.e
