### ISSUE TITLE
Core Not Outputting Data at Certain Time slices

### ISSUE THREAD

**Issue by evangibney44** [geoschem/gchp#310]
### Name and Institution (Required)

Name: Evan Gibney
Institution: MIT Laboratory for Aviation and the Environment 

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Version: GCHP 14.0.1

Description: Simulations run without outputting errors, however, some data variables are not being output from one core at certain time slices.

<img width="462" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/115248285/230800130-11aaa520-3a8e-4993-8b61-249fb934df4d.png">

**Comment by sdeastham** [comment]
A quick note - this has also affected several simulations of mine using an older version of GCHP. The number of cores affected appears to vary between times and variables, and interestingly appears to increase with how far down the list of variables in a single collection the variable is. Error also very unreliable - sometimes doesn't happen at all, sometimes happens across multiple PEs. However when it hits multiple variables, those further down always show gaps on _at least_ all the PEs which are missing from the prior variables.

EDIT: One other thing - the specific PEs which fail to output seem to vary from time slice to time slice. It appears that certain cores are more or less likely than others to fail to report, although I have not dug deep into this as yet.

**Comment by lizziel** [comment]
@evangibney44 and @sdeastham, are you working together on this issue or is this report separate from Seb's via email?

**Comment by sdeastham** [comment]
@evangibney44 came across this issue independently but I am working with him. Unfortunately my suspicion is that the cause is buried deep in MAPL. (EDIT: specifically, my email was about my recent experience observing this issue in a different set of model runs than the ones @evangibney44 describes above)

**Comment by lizziel** [comment]
Okay, let me know if you'd like me to try to reproduce.

**Comment by lizziel** [comment]
@sdeastham, do you have an update for this issue?

**Comment by lizziel** [comment]
I am closing this issue since I am aware that it was fixed. @sdeastham, if you could pass along the details to archive here that would be great.
