### ISSUE TITLE
Can the latest version of GCHP 14.1 simulate CO2?

### ISSUE THREAD

**Issue by helpyuan** [geoschem/gchp#311]
Hi all,

I want to simulate CO2 concentration using GCHP, but I found a previous issue (from https://github.com/geoschem/geos-chem/issues/1341) that GCHP 13.4 cannot simulate CO2 yet. Recently, GCHP has been updated to 14.1, so I would like to ask if GCHP 14.1 can simulate CO2 concentration?

**Comment by sdeastham** [comment]
@yantosca - if not, could you provide a brief summary of what needs to be done please? I've used GCHP to simulate CO2 on multiple occasions so I'm wondering what is actually missing. Happy to assist @helpyuan in fixing whatever the issues are.

**Comment by yantosca** [comment]
@sdeastham @helpyuan: The carbon simulation has a couple of input fields for CO2 that are placed only on 47 levels, which are not compatible with GCHP.  Most of these are oxidants or other P/L from old model runs.  You can take a look at the HEMCO _Config.rc for the carbon simulation.  I haven't gotten to fixing these due to other responsibilities.

**Comment by sdeastham** [comment]
Hi @yantosca - that makes sense! I have scripts which can convert the 47-layer data to 72-layer data. I'll take a look at the HEMCO_Config.rc and see what data needs processing. I may have a few minutes at some point to at least check that GCHP can process the data.

**Comment by helpyuan** [comment]
@yantosca  Does incompatibility mean that GCHP can only simulate 72 levels? In additions, I found optional simulation types from GCHP's user guide (https://gchp.readthedocs.io/en/latest/user-guide/rundir-init.html), including "CO2 w/CMS Flux emissions" and "carbon". What are the differences between these two options in simulating CO2?

![1682562494219](https://user-images.githubusercontent.com/111112591/234744344-90fcca14-073a-4efe-b345-d4512c73a607.jpg)

**Comment by sdeastham** [comment]
With regards to the number of levels, I don't think (?) anyone has ever tried to run GCHP with 47 layers. In principle there's no reason it couldn't be run that way, although the same caveats would of course apply as with GC-Classic when it comes to accuracy of transport. I leave it to @yantosca to comment on the existing C(O2) simulations in GCHP!

**Comment by yantosca** [comment]
@sdeastham: I believe MAPL does not allow you to run with less levels than the defined grid.

**Comment by sdeastham** [comment]
@yantosca - sorry, I should have clarified: there's nothing stopping a user from redefining the grid as 47 layers, as long as they have the necessary input data. I've personally run GCHP with 26 layers (using CAM output) - but it's definitely not for the faint of heart!

**Comment by lizziel** [comment]
Yes, MAPL does not have the vertical regridding, but if all the inputs files are on the run grid then everything should be fine. I am hoping they add in the vertical regridding given there will be a new vertical grid soon...

**Comment by lizziel** [comment]
I will close out this issue now. @helpyuan, if you have any additional questions please create a new GCHP issue.
