### ISSUE TITLE
PETXX.ESMF_LogFile Generation

### ISSUE THREAD

**Issue by evangibney44** [geoschem/gchp#313]
Name: Evan Gibney
Institution: MIT Lab for Aviation and the Environment

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

GCHP Version: 14.0.1

Description of your issue or question:

My simulation is completing normally, however, it is generating "PET00.ESMF_LogFile" files (one for each core used in the simulation). Within each of the logfiles is the following message:

![image](https://user-images.githubusercontent.com/115248285/236472327-821e4944-dbe8-4e73-bcc5-8f697ac1c714.png)

Does this indicate a problem with the simulation output? Is there a way to stop these files from being generated?

For context, my simulation is running with CMIP6 data for 2050.

**Comment by lizziel** [comment]
Hi @evangibney44 - This is a known issue but nothing you should be concerned about. It is on my to do list to take a look at. See also https://github.com/geoschem/GCHP/issues/304 for a tip on how to make it go away.
