### ISSUE TITLE
[BUG/ISSUE] Using total pressure in advection leaves moisture imprint

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#316]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Confirm you have reviewed the following documentation

- [X] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [X] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [X] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [X] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

The GCHP 14.0.0 transport tracer benchmark shows bias in the passive tracer concentrations, with reduced concentrations in areas with greater moisture. See [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.0.0-rc.3/GCHP/TransportTracers/BenchmarkResults/GCHP_version_comparison/PassiveTracers/AnnualMean/PassiveTracers_Surface_AnnualMean.pdf) for the passive tracer annual surface concentrations of 14.0.0 compared to 13.2.0, also shown below. 
Correct passive tracer concentrations in that simulation are uniform, as shown in the 13.2.0 plot in the upper left. The bias in 14.0.0 indicates something is wrong in the model. See [here](http://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_14.0.0#1-year_transport_GCHP_version_comparison_.2814.0.0_vs_13.2.0.29) for all artifacts generated during that benchmark.

<img width="831" alt="Screen Shot 2023-05-19 at 4 05 03 PM" src="https://github.com/geoschem/GCHP/assets/651947/ac81052f-6dd7-411d-ada8-7b8279db8a46">

I looked into the source of the change and traced it to submodule updates submitted in https://github.com/geoschem/GCHP/issues/189 and the accompanying PR https://github.com/geoschem/GCHP/pull/181. The bias source is specifically the change from using dry pressure to total pressure. An unrelated issue came in with that update which did not cause the moisture bias. See https://github.com/geoschem/GCHP/issues/315 for more on that issue.

**Comment by lizziel** [comment]
Here are mass conservation results from a 1-year transport tracer run using winds with dry pressure. I think that the initial difference between restart mass and month 2 (2019-01-01 and 2019-02-01) is because I did not spin up the model. It used a spun up restart file from 14.0.0 which used total pressure in advection. Beyond that initial mass change the mass is very stable.

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  Global Mass of Passive Tracer in gchp.tt.winds.dry.dev
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

 Date        Mass [Tg]
 ----------  ----------------
 2019-01-01   17.6562837481990
 2019-02-01   17.6561229679125
 2019-03-01   17.6561231819488
 2019-04-01   17.6561230851427
 2019-05-01   17.6561230866129
 2019-06-01   17.6561229683662
 2019-07-01   17.6561231418724
 2019-08-01   17.6561230005976
 2019-09-01   17.6561229238939
 2019-10-01   17.6561230222310
 2019-11-01   17.6561229957867
 2019-12-01   17.6561230928585
```

For comparison, here are mass fluctuations using 14.2.0 with total rather than dry pressure in advection. The change is relatively large and has a seasonal cycle. Note that the magnitude of mass change is much greater than what we saw in the 14.0.0 benchmark because that version had a [bug in post-advection pressure](https://github.com/geoschem/GCHP/issues/315) passed to advection that somewhat masked the problem (see mass conservation table of 14.0.0 benchmark [here](http://ftp.as.harvard.edu/gcgrid/geos-chem/1yr_benchmarks/14.0.0-rc.3/GCHP/TransportTracers/BenchmarkResults/GCHP_GCC_comparison/Tables/Passive_mass.txt)).

```
Date        Mass [Tg]
 ----------  ----------------
 2019-01-01   17.6562837481990
 2019-02-01   17.6554432670842
 2019-03-01   17.6556031079333
 2019-04-01   17.6544937839475
 2019-05-01   17.6535518000762
 2019-06-01   17.6518840659412
 2019-07-01   17.6498837803239
 2019-08-01   17.6492738841736
 2019-09-01   17.6508711802673
 2019-10-01   17.6529409655424
 2019-11-01   17.6547134925209
 2019-12-01   17.6557652291479
```

The mass conservation using 14.2.0 with dry pressure is much improved compared to using total pressure but it is still not as good as what we saw in 13.2.0 benchmark, shown here:

```
 Date        Mass [Tg]
 ----------  ----------------
 2019-01-01  17.6561992836073
 2019-02-01  17.6562042748676
 2019-03-01  17.6562042748054
 2019-04-01  17.6562042949576
 2019-05-01  17.6562042757866
 2019-06-01  17.6562042714024
 2019-07-01  17.6562042679971
 2019-08-01  17.6562042791477
 2019-09-01  17.6562042586452
 2019-10-01  17.6562042620417
 2019-11-01  17.6562042708595
 2019-12-01  17.6562042708224
```

**Comment by lizziel** [comment]
The average passive tracer surface concentration over January 2019 when using dry pressure is uniform. Notice that the colorbar has a very large range that would mask small fluctuations from moisture. However, the GCPy colorbar automatically adjusts to show variation so this colorbar indicates uniformity.

<img width="472" alt="Screen Shot 2023-05-22 at 12 41 01 PM" src="https://github.com/geoschem/GCHP/assets/651947/20712025-0e97-4ead-b669-85bce8b77735">

Compare this with the average over January 2019 when using total pressure. Note that this plot includes the post-advection pressure bug.

<img width="449" alt="Screen Shot 2023-05-22 at 12 40 06 PM" src="https://github.com/geoschem/GCHP/assets/651947/0814cbf5-bdfa-418d-ad14-cb6caf03481c">

**Comment by lizziel** [comment]
When using mass fluxes with total pressure in advection there is a small moisture imprint. This plot is the annual mean passive tracer concentration over a 1-year run (2019) using GEOS-IT meteorology. The code used for this run does not have the bug in PLE1 pressure.

<img width="357" alt="Screen Shot 2023-05-22 at 11 50 15 AM" src="https://github.com/geoschem/GCHP/assets/651947/0c080b16-f824-4f4a-9e0e-a9a4c0c2e8b9">

The passive tracer mass change is on par with using dry winds with total pressure, with a relatively large fluctuation over a seasonal cycle.

```
 Date        Mass [Tg]
 ----------  ----------------
 2019-01-01   17.6562836356522
 2019-02-01   17.6519313440552
 2019-03-01   17.6521124962970
 2019-04-01   17.6511320054915
 2019-05-01   17.6503265269776
 2019-06-01   17.6487937873409
 2019-07-01   17.6468571474062
 2019-08-01   17.6461984533542
 2019-09-01   17.6476205923344
 2019-10-01   17.6495061031546
 2019-11-01   17.6514490321127
 2019-12-01   17.6525680402968
```

A job for running a simulation using mass fluxes with dry pressure is pending in the compute queue.

**Comment by msulprizio** [comment]
The pull requests to fix this issue have now been merged into the development branches in the GCHP, geos-chem, and FVdycoreCubed_GridComp repositories.

**Comment by 1Dandan** [comment]
Hi @lizziel, thank you for your effort to correct this advection bug for mass conservation. 
I am interested in running the mass-flux simulations using archived mass fluxes at C720 for met inputs. I noticed the pull requests of https://github.com/geoschem/GCHP/pull/317 and https://github.com/geoschem/geos-chem/pull/1797 are closed and it looks like the bug in mass-flux simulations will be fixed, which will finally go into v14.2.0. 
I am wondering if it is ok that I directly replace corresponding files by those in the pull requests of https://github.com/geoschem/GCHP/pull/317 and https://github.com/geoschem/geos-chem/pull/1797 to have a "correct" mass-flux simulation?
Should I specifically make changes on the basis of GCHP v14, or is it ok based on GCHP v13.4?

**Comment by lizziel** [comment]
Hi @1Dandan, you can bring in the changes from those pull requests to get the updates. However, please note that the mass flux simulation still needs to be looked at further. The 14.2.0 benchmark validation will be for winds only and more work is needed to verify that using dry pressure with mass fluxes, as it is now in 14.2.0, is the best approach. @sdeastham is looking into this, and I plan to as well when I return from a couple trips at the end of this month. Are you interested in helping out with the validation? We could all meet at GCE2 next week to chat.

**Comment by 1Dandan** [comment]
@lizziel Sure, I'll be happy to help with the validation, but may need some guidance for the validation approach. It would be nice to meet you all in person at GCE2.
