### ISSUE TITLE
Input file syntax with modified ExtData.rc for NEI_2011 emissions

### ISSUE THREAD

**Issue by deepangsu** [geoschem/gchp#324]
I am using GCHP 14.1.1, with NEI 2011 hourly emissions switched on over CONUS and CEDS01 at a global scale. 

My simulations run fine with CEDS01, but encounters an error when NEI_2011_hourly is turned on. I have modified HEMCO_Config.rc and ExtData.rc to accommodate the changes to input NEI_2011_hourly. Here is what the error looks like:

Mem/Swap Used (MB) at EXTDATAMAPL_GenericInitialize=  4.227E+04  0.000E+00
 pe=00123 FAIL at line=00572    ExtDataGridCompMod.F90                   <status=41>

This is related to `call ESMF_ConfigGetAttribute(CFtemp, primary%item(totalPrimaryEntries)%units, __RC__)` function in the ExtDataGridCompMod.F90. 

1. I have Set the Verbose and Warnings settings in HEMCO_Config.rc to 3 to send the maximum number of prints to output file HEMCO.log.
2. I have also set CAP.EXTDATA option root_level in config file logging.yml to DEBUG to send root thread MAPL ExtData (input) prints to output file allPEs.log. 

I have done some preliminary trouble shooting to identify the issue is precisely with the format of NEI_2011 hourly files. 

This is the first line of my NEI_2011 input in the ExtData.rc :

"NEI11_SURFACE_NO     kg/m2/s  N Y F2011-%m2-%d2T%h2:00:00 none none          NO       
./NEI2011/%m2/NEI11_0.1x0.1_2011%m2%d2.nc"

Could you please let me know if the input format is correct ?

**Comment by lizziel** [comment]
Hi @deepangsu, could you post your config and log files? If you add extension `.txt` to the files then you can drag and drop them into the comment box. Without seeing the files it is hard to say what is going wrong. I ran into this same error message earlier today and it was due to a random typo in `ExtData.rc` that had nothing to do with units.

**Comment by deepangsu** [comment]
Hi @lizziel. Thank you for your response. I just found some missing data in the input files, that was causing it to crash. 

I can close the issue.
