### ISSUE TITLE
Unable to Select Custom KPP Mechanism When Building

### ISSUE THREAD

**Issue by evangibney44** [geoschem/gchp#328]
### Name and Institution (Required)

Name: Evan Gibney
Institution: MIT Laboratory for Aviation and the Environment

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

I made a minor change to the KPP mechanism and want to rebuild using this custom mechanism. When I run "cmake ../CodeDir -DMECH=custom", I don't see the expected "MECH: fullchem carbon Hg **custom**" verification. Instead, it looks like this:

![image](https://github.com/geoschem/GCHP/assets/115248285/3bdcc9c4-b7b2-465e-9650-7e4df3e7a21d)

Additionally, once I run make, it seems that the KPP/fullchem mechanism is still being referenced as opposed to KPP/custom:

![image](https://github.com/geoschem/GCHP/assets/115248285/7ea18ff3-42d0-4347-ad12-751fe8adcc3c)

I'm wondering if the selection mechanism for KPP was not propagated to GCHP?

**Comment by lizziel** [comment]
Hi @evangibney44, that is correct, the custom mechanism is not implemented in GCHP. Please create a feature request for this on the [geoschem/geos-chem](https://github.com/geoschem/geos-chem) issues page. Thanks!

**Comment by evangibney44** [comment]
Hi @lizziel, thanks for the response - I created a feature request.

**Comment by lizziel** [comment]
Closing this issue. See https://github.com/geoschem/GCHP/issues/329.
