### ISSUE TITLE
Requesting Implementation of Custom KPP Mechanism Selection in GCHP

### ISSUE THREAD

**Issue by evangibney44** [geoschem/gchp#329]
### Name and Institution (Required)

Name: Evan Gibney
Institution: MIT LAE

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### New GCHP feature or discussion

Please implement the custom KPP mechanism selection in GCHP. 

Currently, when I run "cmake ../CodeDir -DMECH=custom" the custom mechanism is not selected.

**Comment by lizziel** [comment]
Thanks @evangibney44 for bringing this up. We will try to get this into 14.3.

**Comment by lizziel** [comment]
Tagging @cbutenhoff who is also interested in the custom mechanism in GCHP.

**Comment by lizziel** [comment]
Hi @evangibney44, when I just tried building our dev/14.2.0 branch with the custom mechanism the custom mechanism was selected. What version are you using? I wonder if a recent version update snuck in the functionality.

**Comment by yantosca** [comment]
@evangibney44: We have also implemented a few fixes in the geoschem/geos-chem repo for the custom mechanism.  See PR #1946 for details.  This will go into version 14.2.1.

**Comment by evangibney44** [comment]
Hi @lizziel, when I submitted this request I was using version 14.0.1. Good to hear the custom mechanism selection is being implemented in the new version!

**Comment by lizziel** [comment]
I will close this issue now. Try again once 14.2.1 is released. You can open a new github issue if you run into any issues.
