### ISSUE TITLE
How to convert a lat-lon grid restart file to a cubed-sphere grid restart file?

### ISSUE THREAD

**Issue by helpyuan** [geoschem/gchp#333]
### Name and Institution (Required)

Name: liumy
Institution: AMS

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hi, I downloaded the “GEOSChem. Restart. fullchem. 20190701.nc4" file from http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/GC_14.0.0/ and tried to run GCHP in C180 grid.  But when I ran "./setRestartLink.sh", it reminded me 
"ERROR: Unable to set symlink gchp_restart.nc4 because file ./Restarts/GEOSChem.Restart.20210101_0000z.c180.nc4 does not exist! Create file or link with that name, or change start date in cap_restart and/or grid resolution in setCommonRunSettings.sh to match restart file that exists.". So I realized that GCHP cannot directly use GC-Classis's restart file and needs to convert the grid.

I found the corresponding C180 restart file on the website, but I still hope to know how to convert the lat lon grid's restart file to a cubed-sphere grid restart file.

**Comment by lizziel** [comment]
Hi @helpyuan, please see the GCPy ReadTheDocs page on regridding for information on how to convert a GC-Classic restart file to a GCHP restart file using python package GCPy.
https://gcpy.readthedocs.io/en/stable/Regridding.html

**Comment by lizziel** [comment]
Hi @helpyuan, were you able to get this working?

**Comment by helpyuan** [comment]
Thank you for your reply @lizziel. I have already done it!
