### ISSUE TITLE
Segmentation fault when run GCHP

### ISSUE THREAD

**Issue by helpyuan** [geoschem/gchp#335]
### Name and Institution (Required)

Name: liumy
Institution: AMS

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hi, I attempted to run GCHP by submitting a slurm script, which is as follows:
[rungchp.sbatch.txt](https://github.com/geoschem/GCHP/files/12182071/rungchp.sbatch.txt)
But soon it ended due to a Segmentation fault, and the output is as follows:
[slurm-1957072.out.txt](https://github.com/geoschem/GCHP/files/12182091/slurm-1957072.out.txt)
[gchp.20210101_0000z.log.txt](https://github.com/geoschem/GCHP/files/12182094/gchp.20210101_0000z.log.txt)
When I run directly from the command line, I also get a similar error:
![command line](https://github.com/geoschem/GCHP/assets/111112591/1842d275-d741-49d6-afe3-f817657e0fd2)
But I can run an example of openmpi:
![test_mpirun](https://github.com/geoschem/GCHP/assets/111112591/ef233fdd-65bf-478e-96ce-13a51dcfe60a)

I don't know why this segment error occurred. It seems that the operation terminated before it reached the mode to start because the log file is empty. 
Is there anybody who can help me? I would greatly appreciate it.

Envrionment:
GCC/13.1.0
GCHP/14.1.1
openmpi/4.1.5
ESMF/8.4.2

GCHP setting:
[setCommonRunSettings.sh.txt](https://github.com/geoschem/GCHP/files/12182169/setCommonRunSettings.sh.txt)

**Comment by lizziel** [comment]
Hi @helpyuan, we now require providing name and institution when submitting GitHub issues. Please edit your initial request with that information.

This appears to be a system issue since the model does not actually start. Try using file runScriptSamples/gchp.local.run to run locally on your cluster and see if that gives additional information. For segmentation faults I would normally recommend building with option -DCMAKE_BUILD_TYPE=Debug, but it appears the issue may occur prior to execution.

**Comment by helpyuan** [comment]
Thank you for your reply @lizziel. I have added my name and institution.

I reinstalled GCHP-14.1.0 on another computer and ran it again, but the above error still occurred. I will try to reinstall the dependency like #290 to see if the problem can be solved.

**Comment by helpyuan** [comment]
After replacing the dependency library again, I can run GCHP without any of the above issues.
