### ISSUE TITLE
Stretch-grid simulation extraction of data for specific latitude and longitude.

### ISSUE THREAD

**Issue by bahg8** [geoschem/gchp#337]
### Name and Institution (Required)

Name: Beatriz Herrera
Institution: University of Toronto

### Confirm you have reviewed the following documentation

- [x [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hi, my colleague and I were working on a C48 stretch-grid simulation over Mexico City (#318) with the following parameters:
```console
CS_RES=48
STRETCH_GRID=ON
STRETCH_FACTOR=15.0
TARGET_LAT=19.2
TARGET_LON=-99.0
```
At this point the simulations seem to run successfully, however, I have some concerns regarding the data extraction. I searched in previous issues, but I didn’t find anything specific regarding data extraction for comparison.  For my work, I am trying to compare GCHP data with ground-based instruments, so I am extracting the GCHP data for specific target longitudes and latitudes, such as Mexico City. For the C48 simulation with stretch grid =OFF, we are using a Python script to extract the data. Basically, this script read the GCHP outputs and merges them, then it uses spherical coordinates to compute a distance between the target lon and lat and finds the cube-face which has the smallest distance to the target lon and lat and then uses this information to create a dataset based on a distance filtering criterion, and finally, we save this dataset in monthly nc files. For the SF=15.0 I use the same Python script but with and smaller distance filtering criterion. 
I attached some figures comparing results from GCHP C48 and GCHP SF=15.0, first, the global plots and then a comparison of the calculated Total columns of NH3 for GCHP C48, GCHP SF=15.0 using the nearest grid to the target lon and lat, and finally the GCHP SF=15.0 using the mean of all the grid cells closer to the target lon and lat.  I would like to ask if you have any recommendations for handling the GCHP stretch grid data or if you think that the figures look reasonable. 
Many thanks 

Please provide as much detail as possible. Always include the GCHP version number and any relevant configuration and log files:
GCHP v14.1.1
GCPy (for regridding): v13.3
Gridspec: v0.1.0
Sparselt: v0.1.3
Compiler: GCC v10.3.0
OpenMPI: v4.1.1
NetCDF Fortran: v4.6.0
Cmake: v3.17.3
ESMF: v8.3.1

![GCHP_github_question](https://github.com/geoschem/GCHP/assets/98115192/5ea0f6be-3eec-4326-a0be-042a8bf03797)

**Comment by yantosca** [comment]
Thanks for writing @bahg8.  In the GCPy `dev` branch we now have a module `gcpy/cstools.py` with routines that should be able to pick out a grid box given a (lat,lon) coordinate.  I have code from a benchmarking script but we haven't made a general-purpose routine to do this yet.  This is on our plate (see feature request #244).

Try the following:
```console
$ git fetch -p
$ git checkout dev
```
Then in your script:
```python
#!/usr/bin/env python

import xarray as xr
from gcpy.util import verify_variable_type
from gcpy.cstools import extract_grid, find_index

def get_nearest_model_data_to_obs_cs(
        gc_data,
        gc_cs_grid,
        lon_value,
        lat_value
):
    """
    Returns GEOS-Chem model data (on a cubed-sphere grid) at the
    grid box closest to an observation site location.

    Args:
    -----
    gc_data : xarray DataArray
        GEOS-Chem output to be processed

    gc_cs_grid: xarray Dataset
        Coordinate arrays defining the cubed-sphere grid.

    lon_value : float
       Longitude value [degrees]

    lat_value : float
        Latitude value [degrees]

    Returns:
    --------
    dataframe: pandas.DataFrame
        Model data closest to the observation site.
    """
    verify_variable_type(gc_data, xr.DataArray)
    verify_variable_type(gc_cs_grid, xr.Dataset)

    # Prevent the latitude from getting too close to the N or S poles
    lat_value = max(min(lat_value, 89.75), -89.75)

    # Indices (nf, yInd, xInd) of box nearest to observation site
    cs_indices = find_index(
        lat_value,
        lon_value,
        gc_cs_grid
    )

    return gc_data.isel(
        nf=cs_indices[0, 0],
        Ydim=cs_indices[1, 0],
        Xdim=cs_indices[2, 0],
    ).to_dataframe()


def main():
   
   # Specify lat/lon values (can also get these from sys.argv)
   lat = ___
   lon = ___

   # Read data
   gc_data = xr.open_dataset("/path/to/your/data")

   # Extract grid information from the dataset
   # (cs_grid is of type xr.Dataset)
   gc_cs_grid = extract_grid(gc_data)

   # Return indices
   index_info = find_index(lat, lon, gc_cs_grid)

if __name__ == "__main__":
    main()
```

I haven't tried this for a stretched-grid yet but I think this should work given the grid definition.

We will try to package this up into GCPy soon.

**Comment by bahg8** [comment]
Hi @yantosca 

Thanks so much for your reply,  I'll check this GCpy option!

**Comment by lizziel** [comment]
This is definitely possible with stretched grid but will require some modification. The function [extract_grid](https://github.com/geoschem/gcpy/blob/91c260d613e71d24f889d2745c174de42ea01161/gcpy/cstools.py#L55-L78) uses the function [gen_grid](https://github.com/geoschem/gcpy/blob/91c260d613e71d24f889d2745c174de42ea01161/gcpy/cstools.py#L317-L372), both in file `cstools.py` in the `dev` branch (follow the links to see the lines of code). The problem is `extract_grid` assumes a regular not stretched grid by not passing the optional stretched grid arguments when it calls `gen_grid`.

What you could do instead is use `gen_grid` directly to create the grid for your resolution and stretched grid parameters. This would bypass using `extract_grid`. An example of using `gen_grid` directly is the docs at the top of the file (see [here](https://github.com/geoschem/gcpy/blob/91c260d613e71d24f889d2745c174de42ea01161/gcpy/cstools.py#L9-L17)). The optional arguments are defined in the gen_grid code (see [here](https://github.com/geoschem/gcpy/blob/91c260d613e71d24f889d2745c174de42ea01161/gcpy/cstools.py#L317-L338)).

**Comment by lizziel** [comment]
I will close out this issue. Please create a new one in the GCPy github if you have any issues using the suggested approach.
