### ISSUE TITLE
[FEATURE REQUEST] Carbon simulations in GCHP

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#339]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### New feature/discussion

I am opening this feature request for tracking progress of implementation of carbon simulations in GCHP, including CO2 and CH4. @yantosca recently did work in GEOS-Chem to add carbon cycle as an option in KPP (see https://github.com/geoschem/GCHP/pull/283). That update was released in version 14.1. However, it is not yet working in GCHP and creating a run directory for it is not currently an option.

We hope to make CO2 available by 14.3.0. CH4 may come later. Updates about it will be documented in this issue.

Tagging Carbon Working Group and interested users: @helpyuan, @akurganskiy, @zha-hash, @kbowman77

### Related issues/PRs

https://github.com/geoschem/GCHP/issues/311
https://github.com/geoschem/GCHP/pull/283
https://github.com/geoschem/geos-chem/pull/1605

**Comment by yantosca** [comment]
Thanks @lizziel!  There is a PR from @msulprizio that needs to go into 14.2.1, which updates the `HEMCO_Config.rc` file for the latest emissions.  Once that goes in I plan on picking up again on the carbon simulation work.

**Comment by kbowman77** [comment]
There’s a lot of interest in this capability.  Let me know where/when we can help.

Kevin

**Comment by yantosca** [comment]
Also see issue https://github.com/geoschem/geos-chem/issues/1984

**Comment by lizziel** [comment]
@msulprizio is now working on this. We hope to get the carbon simulation working in GCHP in version 14.4.0.

**Comment by lizziel** [comment]
The carbon simulations for GCHP are now released in 14.4.0.
