### ISSUE TITLE
[BUG] Parts of GCHPctm built with OpenMP

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#34]
GCHPctm should not be built with OpenMP. However, MAPL is built with OpenMP and possibly other components as well. As a result, I ran into a compile issue with ifort19 for 13.0.0-alpha.8 due to an improper openMP directive (OMP serial). The fix for that issue went into 13.0.0-alpha.9, but the larger issue that GCHPctm is being compiled with OpenMP remains. I believe the issue has to do with the settings in the CMake files within MAPL and this needs to be further looked at.

**Comment by lizziel** [comment]
I believe @LiamBindle fixed this with PR https://github.com/geoschem/GCHPctm/pull/50. It will be included in the 13.0.0 release.

**Comment by LiamBindle** [comment]
btw @lizziel, this is what was causing OpenMP to be enabled on the GCHPctm side (from MAPL)
