### ISSUE TITLE
Restart files when adding new gridded components in GCHP

### ISSUE THREAD

**Issue by ShreyaSharma2023** [geoschem/gchp#344]
### Name and Institution (Required)

Name: Shreya Sharma
Institution: Massachusetts Institute of Technology

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
I have a one-way coupled implementation of MAM7 in GCHP (5 variables being passed from MAM to Chemistry). I added MAM7 as a gridded component which is a sibling of GEOSChem. The run does not exit correctly, with errors in the NetCDF4_FileFormatter while writing out the restart files.

The cmake, make logs and the output files are attached.
Output log: 
[gchp.20190701_0100z.log](https://github.com/geoschem/GCHP/files/12590615/gchp.20190701_0100z.log)
Slurm file: 
[slurm-354058.txt](https://github.com/geoschem/GCHP/files/12590659/slurm-354058.txt)
Cmake log: 
[log.cmake.txt](https://github.com/geoschem/GCHP/files/12590678/log.cmake.txt)
Make log: 
[log.make.txt](https://github.com/geoschem/GCHP/files/12590681/log.make.txt)

Please provide as much detail as possible. Always include the GCHP version number and any relevant configuration and log files.
GCHP: v14.1.1
Compiler: GCC 9.4.0
OpenMPI: 4.1.5
Netcdf-Fortran: 7.2.0
ESMF: 8.3.0

**Comment by yantosca** [comment]
Also tagging @christophkeller

**Comment by lizziel** [comment]
Thanks Shreya. Are you pushing your updates to a fork that you could link to here?

**Comment by lizziel** [comment]
I am specifically looking to see what is at this line. 
`pe=00008 FAIL at line=00155    MAML_OpticsMod.F90                       <needs informative message>`

**Comment by ShreyaSharma2023** [comment]
Hi Lizzie

Here is my fork of GCHP: https://github.com/ShreyaSharma2023/GCHP/tree/Making-MAM-work

I'd disabled all the code related to MAM optics currently since I did not have some external data and I believe those errors were from that.

**Comment by lizziel** [comment]
HI @ShreyaSharma2023, apologies I have not gotten to this. I plan to look at it in the next week.

**Comment by ShreyaSharma2023** [comment]
[gchp.20100101_0000z.log](https://github.com/geoschem/GCHP/files/13107786/gchp.20100101_0000z.log)
[CmakeLog.txt](https://github.com/geoschem/GCHP/files/13108276/CmakeLog.txt)
[MakeLog.txt](https://github.com/geoschem/GCHP/files/13108409/MakeLog.txt)
[gchp.20100101_0000z.txt](https://github.com/geoschem/GCHP/files/13108606/gchp.20100101_0000z.txt)

Hi @lizziel , I have updated the code to remove the error with the optics files and am now getting something that looks like a segmentation fault. Here are the updated files!

**Comment by lizziel** [comment]
Hi @ShreyaSharma2023, the log files you posted show that the run completed successfully.

**Comment by lizziel** [comment]
@ShreyaSharma2023, are you all set now with regards to restart files?
