### ISSUE TITLE
GCHP Singularity Container set up question

### ISSUE THREAD

**Issue by tessac2** [geoschem/gchp#347]
### Name and Institution (Required)

Name: Tessa Clarizio
Institution: University of Illinois Urbana Champaign

### Confirm you have reviewed the following documentation

- [x ] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [ x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x ] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x ] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

I am trying to set up a container for GCHP following the instructions on this website: https://gchp.readthedocs.io/en/latest/supplement/containers.html#software-requirements 

However I am having issues with setting up the system. I am able to use singularity to pull gchp.sif to my system (for version 13.4.1). However I am getting confused at the second step: 

`singularity exec -B DATA_DIR:/ExtData -B WORK_DIR:/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh`

I first tried the following, where I replaced DATA_DIR and WORK_DIR with my actual data directories and work directories, with:

`singularity exec -B /projects/horowitz_group/GEOSChem_input_data/ExtData -B /projects/horowitz_group/tessa/GCHP/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh`

This seemed to work but then after setting up my run, I got issues when it came to moving the pre-built gchp executable and example run scripts to the run directory. I used the command:
`singularity exec /projects/horowitz_group/tessa/GCHP/gchp.sif cp /opt/geos-chem/bin/gchp /projects/horowitz_group/tessa/GCHP/workdir/GCHP_13.4.1`
And got the error that the container creation failed, because the destination must be an absolute path. 

(I am not sure if this is related, but when I set up the run directory I got an error that said `gc-src/src/GCHP_GridComp/GEOSChem_GridComp/geos-chem/run/GCHP/init_rd.sh: line 83: envsubst: command not found`)

I decided to restart from the beginning, and tried the following to see if it would fix the absolute path: 
`singularity exec -B DATA_DIR:/projects/horowitz_group/GEOSChem_input_data/ExtData -B WORK_DIR:/projects/horowitz_group/tessa/GCHP/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh` but now I got an immediate error saying that the directory does not exist (see attached image)
![image](https://github.com/geoschem/GCHP/assets/70339432/3ffbb89e-81d9-485d-9f3c-cecba6ea3f5d)

I am a bit confused as to how to set this container up correctly, any advice would be greatly appreciated!

**Comment by yantosca** [comment]
Thanks for writing Tessa.  Yidan Tang (@yidant) has a lot of experience with containers so I will let her anwser.

**Comment by yidant** [comment]
Hi @tessac2, thanks for asking. 

In this command, 

`singularity exec -B DATA_DIR:/ExtData -B WORK_DIR:/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh`

`-B DATA_DIR:/ExtData` means to mount DATA_DIR to /ExtData. DATA_DIR is the directory where you store data files on your original storage. /ExtData is the mounted DATA_DIR visible in the container and is used as ExtData location. Make sure to replace these names with your actual directory paths when executing commands from these instructions. 

Please refer to the instructions before this command in https://gchp.readthedocs.io/en/latest/supplement/containers.html. 

Also, `docker://geoschem/gchp:14.2.0` is now available! Feel free to use the latest version.

**Comment by tessac2** [comment]
Thanks @yidant! Could you show an example? If I am understanding right, I think I did follow that step when I ran
`singularity exec -B /projects/horowitz_group/GEOSChem_input_data/ExtData -B /projects/horowitz_group/tessa/GCHP/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh`
But then I got errors later on saying that the container creation failed, because the destination must be an absolute path.

**Comment by yidant** [comment]
@tessac2, an example is `singularity exec -B /home/research/name/ExtData:/ExtData -B /home/research/name/GCHP/rundirs:/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh`. Run this command where the .sif is located. 

I couldn't reproduce your issue. Could you provide the path of your data directory, run directory, and where the gchp.sif is located, and a screenshot of the command results? Thank you!

**Comment by tessac2** [comment]
Hi @yidant thank you for your feedback. Currently, these are the paths:

data directory: /projects/horowitz_group/GEOSChem_input_data/ExtData
run directory: /projects/horowitz_group/tessa/GCHP/workdir/rundirs_13.4.1
gchp.sif location: /projects/horowitz_group/tessa/GCHP

I updated my commands to better match what you suggested but I am getting the same error as before. I attached what I attempted in screenshots below. I also attempted version 14.2.0 initially but could not get past the first step, it gave me an error saying there was no such file or directory for stat /opt/geos-chem/bin/createRunDir.sh. 

`singularity exec -B /projects/horowitz_group/GEOSChem_input_data/ExtData:/ExtData -B /projects/horowitz_group/tessa/GCHP/rundirs:/workdir  gchp.sif /opt/geos-chem/bin/createRunDir.sh
`

Version 13.4.1 attempt: 
![image](https://github.com/geoschem/GCHP/assets/70339432/a379fd16-fd7a-4afe-bb26-75b3ded109ed)
![image](https://github.com/geoschem/GCHP/assets/70339432/a4d63719-824b-4902-b61a-327c41f445ae)

Version 14.2.0 error:
![image](https://github.com/geoschem/GCHP/assets/70339432/9d463bd5-49e2-4661-9a8f-55dc809a0298)

**Comment by tessac2** [comment]
I realized I had the wrong type of quotes in the above, which may be the reason for the error. I fixed that but got another error saying there is no such file or directory. 
<img width="461" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/c4df33b6-b9a8-4512-a13a-2f16fa9c1deb">

**Comment by yidant** [comment]
Hi @tessac2 , you need to change your command into

`singularity exec <your_path_to_gchp.sif> cp /opt/geos-chem/bin/gchp /rundir`

The '/rundir' is the mounted run directory visible in the container. The original run directory doesn't exist in your container.

**Comment by yidant** [comment]
I noticed the 'envsubst' message when you create the run directory. I tested it and I think this one matters. The version 13.4.1 container is out-of-date. I've fixed this issue in the version 14.2.0 container. You could pull the updated image again. 

Also, please remove the blank after the comma in the second echo command like below, 

`echo "export SINGULARITY_BINDPATH=\"DATA_DIR:/ExtData,RUN_DIR:/rundir\"" >> ~/.container_run.rc`

The container images and documentation haven't been maintained for a while. We are updating them along with our release of the latest GCHP. Thanks for your feedback!

**Comment by tessac2** [comment]
Thanks @yidant. I have tried again with version 14.2.0. I got the same envsubst error when setting up the run directory. It also said that it detected "dubious ownership" in the repository? I tried to continue on with the instructions but then got an error saying there is no such file or directory for./setEnvironment.sh
<img width="912" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/3466c60d-245b-44e2-ac25-fc05a92fdb3a"><img width="874" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/a7a176da-6783-4da8-bac0-2d68cbe4d881">

**Comment by yidant** [comment]
Hi @tessac2 , it looks like the it didn't source ~/.bashrc properly. Could you try

`singularity exec -B DATA_DIR:/ExtData -B WORK_DIR:/workdir gchp.sif /bin/bash -c ". /etc/bashrc && /opt/geos-chem/bin/createRunDir.sh" `

instead of 

`singularity exec -B DATA_DIR:/ExtData -B WORK_DIR:/workdir gchp.sif /opt/geos-chem/bin/createRunDir.sh`

Also, the `./setEnvironment.sh` is named `./setEnvironmentLink.sh` in version 14.2.0. The updated docs is https://gchp.readthedocs.io/en/latest/supplement/containers.html.

**Comment by tessac2** [comment]
Thanks @yidant. When I do this I still get the envsubst error, and it also says that my default root directory does not exist? I checked the /home/tessac2/.geoschm/config files and it seems correct? 

<img width="829" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/653c09bd-9a11-4602-852d-65ee93ca0dc5">
<img width="752" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/283bdcc8-1b33-4125-9e99-41d4cd566c96">

**Comment by yidant** [comment]
Hi @tessac2, I can't reproduce your issue both on our cluster and local laptop. I would recommend the following: 

1. Make sure your image is the latest version. We have updated the image recently. You can delete the .sif file and pull it again. 
2. Refer to the latest documentation: https://gchp.readthedocs.io/en/latest/supplement/containers.html
3. Try these two (both work for me as my ~/.bashrc includes the global definitions)
`singularity exec -B DATA_DIR:/ExtData -B WORK_DIR:/workdir gchp.sif /bin/bash -c ". /etc/bashrc && /opt/geos-chem/bin/createRunDir.sh"`
`singularity exec -B DATA_DIR:/ExtData -B WORK_DIR:/workdir gchp.sif /bin/bash -c ". ~/.bashrc && /opt/geos-chem/bin/createRunDir.sh" `
4. Consider using Docker directly if it is an option on your cluster.

**Comment by tessac2** [comment]
Hi @yidant, I tried re-downloading the latest image (14.2.1) but I got the same errors as shown above. I tried the two commands you indicated above, the first giving the same error and the second giving additional errors. 

I was wondering what you mean by using Docker directly on the cluster? 

<img width="839" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/5e314093-52ea-44d4-b9c3-670cec39ae58">
<img width="839" alt="image" src="https://github.com/geoschem/GCHP/assets/70339432/41c8cb7f-6979-44d3-af16-2377edd22141">

**Comment by tessac2** [comment]
GCHP was able to be installed upon updating the .bashrc file and using an intel compiler. There were errors when using only gcc compilers.
