### ISSUE TITLE
Can the ObsPack module be used in GCHP?

### ISSUE THREAD

**Issue by helpyuan** [geoschem/gchp#348]
### Name and Institution (Required)

Name: liumy
Institution: AMS

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
In GCClassic-13.3.1, I can sample some greenhouse gases based on observation site files using the ObsPack module. And in compiling GCHP-14.2.0, I also discovered the ObsPack module and found related options in run/geochem_ config.yml.templates/geoschem_config.yml.carbon, as follow:
![obspack](https://github.com/geoschem/GCHP/assets/111112591/43430317-3320-469f-810c-2a2f03a27e1e)

But when I open the ObsPack option like above to configure geoschem_config.yml and run GCHP, the model did not output the relevant ObsPack results. So I want to know if the ObsPack module is still applicable in GCHP?

If it cannot be used, I will plan to write a module for sampling species based on the observation site files, just like the ObsPack module. In this situation, I would like to know if there are any program scripts that can be referenced, and what interactions need to be noted in GCHP?

**Comment by yantosca** [comment]
Thanks for writing.  Currently, the ObsPack diagnostic is only available for GEOS-Chem Classic.  The reason being is that GCHP uses the MAPL library (via the History component) to save all diagnostic I/O to disk.  At the present time, the History component is not compatible with ObsPack.  This would require an update to MAPL which would probably be beyond our scope to implement.

**Comment by helpyuan** [comment]
Thanks @yantosca! Does this mean that if I want to output species sampling based on the observation site files, I need to modify the relevant code in MAPL library? Is there currently no other way besides this?

**Comment by sdeastham** [comment]
Hi @helpyuan - you could try the 1D diagnostics (https://gchp.readthedocs.io/en/dev/user-guide/config-files/HISTORY_rc.html). By specifying the "track" as your stations you should get the output you need - that was actually one of the goals of that feature.

**Comment by lizziel** [comment]
See also the "output along a track" supplemental guide on GCHP ReadTheDocs: https://gchp.readthedocs.io/en/dev/supplement/satellite-overpass.html. If you run into any problems with it let us know.

**Comment by helpyuan** [comment]
Thanks @sdeastham and @lizziel! I will give it a try.

**Comment by lizziel** [comment]
I will close out this issue. If you run into problems using the output along a track option in GCHP please open a new issue.
