### ISSUE TITLE
GCHP dies without an error message when encountering missing species in the restart file (or if restart file does not exist)

### ISSUE THREAD

**Issue by yantosca** [geoschem/gchp#352]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Confirm you have reviewed the following documentation

- [x] [Contributing guidelines](https://gchp.readthedocs.io/en/latest/reference/CONTRIBUTING.html)

### New GCHP feature or discussion
Using the `Require_Species_in_Restart=1` setting in the `setCommonRunSettings.sh` script) will cause GCHP simulations to terminate without a corresponding error message (either in the `gchp*log` file or in `allPEs.log`).  This can give the user a false idea as to what the failure was caused by.

**Comment by yantosca** [comment]
I have also confirmed that no error message is given if the restart is not present in the run directory.  GCHP will proceed to try to initialize Dynamics (and that is the last thing that gets written to `allPEs.log`.

**Comment by lizziel** [comment]
The fixes for these issues will need to go into MAPL. Restarts are handled within the MAPL Generic component based on the restart attribute attached to each internal state variable. When we set `Require_Species_in_Restart=1` in `setCommonRunSettings.sh` the restart attribute is set to required in GCHP subroutine `SetServices`.

**Comment by yantosca** [comment]
@lizziel: I can open a corresponding PR on the MAPL repo.

**Comment by lizziel** [comment]
Thank you!

**Comment by lizziel** [comment]
I am running into this issue while testing RRTMG. I'll check on if we can do anything about it.

**Comment by lizziel** [comment]
I have discussed this with GMAO developers and we now anticipate a fix in MAPL3 which will be part of GCHP 15.0.
