### ISSUE TITLE
Scaling variables in GEOSFP met fields through ExtData.rc or HEMCO_Config.rc

### ISSUE THREAD

**Issue by deepangsu** [geoschem/gchp#358]
Name: Deepangsu Chatterjee
Institution: Washington University in St. Louis

If I were use hourly scaling factor for emissions, I would use a identifier to scale the hourly NOx emissions. For example :

33 PKU_pow_NOx              0.94/0.93/0.93/0.92/0.93/0.96/0.98/0.99/0.98/1.00/1.05/1.03/1.01/1.04/1.05/1.05/1.07/1.06/1.05/1.05/1.03/1.01/0.99/0.96 - - - xy unitless 1 1009

I wanted to know if I can perform similar scaling for variables in the GEOS-FP met fields using the Derived Exports section. If so, could any one share an example that shows how it is done ?

**Comment by yantosca** [comment]
Tagging @lizziel

**Comment by lizziel** [comment]
Hi @deepangsu, if you create an hourly export by reading in a netcdf file then I believe you can use it to scale fields in the Derived Exports section. An example of using that section is computing optical depth as sum of ice and liquid water optical depths (see [here](https://github.com/geoschem/geos-chem/blob/3cd802eb4a9b7a226254fc3938778c8db8c07cf2/run/shared/settings/native_geosfp.txt#L115)). That derived export is a sum but I think you can multiply as well.

**Comment by deepangsu** [comment]
@lizziel Thankyou for your response. 

Could you suggest a process that invloves scaling the time component of an existing variable (eg : PBLH) using scaling factors. 

For example : 

Here I have 24 scalors (for every hour) that I want to scale the original PBLH (and preserve it's variable name so that it can be used by the GCHP code wherever needed),  

[0.94/0.93/0.93/0.92/0.93/0.96/0.98/0.99/0.98/1.00/1.05/1.03/1.01/1.04/1.05/1.05/1.07/1.06/1.05/1.05/1.03/1.01/0.99/0.96]

Is there a way to do that ?

**Comment by lizziel** [comment]
Hi @deepangsu, I recommend creating a new import for this, within derived exports, and then update file Interfaces/GCHP/Includes_Before_Run.H to set State_Met%PBLH (or whatever it is called in GEOS-Chem) to be equal to that import. This would also allow a good sanity check to compare against the original data. To do this you will need to store you hourly factors within a netcdf file that is read in through MAPL and configured in ExtData.rc.

**Comment by deepangsu** [comment]
@lizziel Thank you for your suggestions!
