### ISSUE TITLE
"%m2/$MM" in fullchem simulation cannot recognize the current month

### ISSUE THREAD

**Issue by helpyuan** [geoschem/gchp#361]
### Name and Institution (Required)

Name: liumy
Institution: CAMS

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hi all, I want to run the fullchem simulation, starting from July 2019, and I encountered a strange problem.
The wildcard, "%m2" in ExtData.rc or "$MM" in HEMCO_Config.rc, which seems to be unable to find the correct simulation time. 

As shown in the ERROR log, the month of the file name is "`01`".
![error](https://github.com/geoschem/GCHP/assets/111112591/5c87d8f7-b106-48b4-bda5-98c26e84fe16)

As shown in the HEMCO_Config.log and ExtData.rc, the month of the file name is `wildcard`.
![hemco_config](https://github.com/geoschem/GCHP/assets/111112591/2304ca67-a903-4a3f-858c-3b2fe2a87b3b)
![extdata](https://github.com/geoschem/GCHP/assets/111112591/e695dbee-5c9e-48d7-9707-915799999fdc)

As showin in the GCHP log, the "`Current Date`" is "`2019/07/01`".
![gchplog](https://github.com/geoschem/GCHP/assets/111112591/b5123b7c-bc1e-4d93-9abb-5f6d1dcaca7f)

There are these two files in the “`./HcoDir/C2H6_2010/v2019-06/`” path
![image](https://github.com/geoschem/GCHP/assets/111112591/76cf43b3-bbcb-4e98-a1b2-72837e5a9900)

Could someone tell me where I am not configured correctly? I would be very grateful.

Please provide as much detail as possible. Always include the GCHP version number and any relevant configuration and log files.
[logfile.000000.out.txt](https://github.com/geoschem/GCHP/files/13596942/logfile.000000.out.txt)
[job.2529349.err.txt](https://github.com/geoschem/GCHP/files/13596944/job.2529349.err.txt)
[HISTORY.rc.txt](https://github.com/geoschem/GCHP/files/13596945/HISTORY.rc.txt)
[HEMCO_Diagn.rc.txt](https://github.com/geoschem/GCHP/files/13596946/HEMCO_Diagn.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/13596947/HEMCO_Config.rc.txt)
[geoschem_config.yml.txt](https://github.com/geoschem/GCHP/files/13596948/geoschem_config.yml.txt)
[GCHP.rc.txt](https://github.com/geoschem/GCHP/files/13596949/GCHP.rc.txt)
[gchp.20190701_0000z.log.txt](https://github.com/geoschem/GCHP/files/13596950/gchp.20190701_0000z.log.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/13596951/ExtData.rc.txt)
[cap_restart.txt](https://github.com/geoschem/GCHP/files/13596953/cap_restart.txt)
[allPEs.log.txt](https://github.com/geoschem/GCHP/files/13596954/allPEs.log.txt)

**Comment by lizziel** [comment]
Hi @helpyuan, I wonder if ExtData is looking for the previous month. Unable to find it, it may be searching all the way back to January. Try downloading the June 2010 file and run again. Also turn on ExtData prints to get more information in `allPEs.log`. See [GCHP ReadTheDocs Debugging page](https://gchp.readthedocs.io/en/stable/user-guide/debugging.html#enable-maximum-print-output) for instructions on how to do that. We keep ExtData debug prints off by default because it slows down the model.

**Comment by helpyuan** [comment]
Thanks @lizziel. I downloaded the data for June 2010, but unfortunately, GCHP still reported the same error. I turn on ExtData prints to get more information in allPEs.log, as shown below:
[allPEs.log.txt](https://github.com/geoschem/GCHP/files/13631064/allPEs.log.txt)

I'm not sure if this is related to fixed year data like this. Because after I changed the `C2H6_global_anth_biof.2010%m2.2x25.nc` in Extdatac.rc to `C2H6_global_anth_biof.201007.2x25.nc` and the `C2H6_global_anth_biof.2010$MM.2x25.nc` in HEMOrc to `C2H6_global_anth_biof.201007.2x25.nc`, GCHP seemed to recognize this emission. However, similar errors have been reported in other emissions, and the relevant log files are as follows:
[job.2541503.err.txt](https://github.com/geoschem/GCHP/files/13631204/job.2541503.err.txt)
[gchp.20190701_0000z.log.txt](https://github.com/geoschem/GCHP/files/13631205/gchp.20190701_0000z.log.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/13631206/HEMCO_Config.rc.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/13631207/ExtData.rc.txt)
[allPEs-Bry.log.txt](https://github.com/geoschem/GCHP/files/13631208/allPEs-Bry.log.txt)

**Comment by lizziel** [comment]
Hi @helpyuan, I dug a bit more into the MAPL by following the traceback in your error log:
```
nf90_open: returned error code (2) opening ./HcoDir/STRAT/v2015-01/Bry/GEOSCCM_Bry.200701.day.nc [No such file or directory]
pe=00003 FAIL at line=00280    NetCDF4_FileFormatter.F90                <status=2>
pe=00003 FAIL at line=00097    DataCollection.F90                       <status=2>
pe=00003 FAIL at line=02799    ExtDataGridCompMod.F90                   <status=2>
pe=00003 FAIL at line=02054    ExtDataGridCompMod.F90                   <status=2>
```
It looks like during intitialization MAPL just checks if the January file is available for monthly climatology files, and uses that to make metadata for the import. This is probably because it assumes you have all 12 months of data for your simulation, which makes sense because it assumes you will be running a full year, or at least any month of the year. I bet if you download the full year of data it will work. Alternatively, you can turn off the climatology flag in ExtData.rc and simply use the frequency already set (`F2016-%m2-01T00:00:00`). This should work equally well since it bypasses some of the logic specific to climatology data.

**Comment by lizziel** [comment]
Also note that the filename in `HEMCO_Config.rc` is not actually used. I saw your message that you updated that line as well. That is not necessary for GCHP. We keep it consistent with `ExtData.rc` simply for reference and comparison with GC-Classic `HEMCO_Config.rc` files.

**Comment by helpyuan** [comment]
Thanks @lizziel! You're right, I turned off the climatology flag and GCHP could run successfully. 
This issue has been resolved and I will close it.
