### ISSUE TITLE
GCHP13.2.1 suddenly stopped due to a HEMCO-related issue

### ISSUE THREAD

**Issue by mmmjjj527** [geoschem/gchp#363]
### Name and Institution (Required)

Name: Jia Mao
Institution: CUHK

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [ ] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Hello everyone, I have a few questions regarding the GCHP 13.2.1. When I run simulations using the same restart file, everything goes smoothly for simulations before the year 2015. However, all simulations after the year 2015 suddenly come to a halt on 20150801_220000. I suspect this could be due to missing corresponding input data. Is there a method to identify the missing data? I've also attached the error.log and "print_out.log" for your reference.

[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/13611517/HEMCO_Config.rc.txt)
[runConfig.sh.txt](https://github.com/geoschem/GCHP/files/13611519/runConfig.sh.txt)
[HEMCO.log](https://github.com/geoschem/GCHP/files/13611473/HEMCO.log)
[1430867_error.log](https://github.com/geoschem/GCHP/files/13611471/1430867_error.log)
[1430867_print_out.log](https://github.com/geoschem/GCHP/files/13611472/1430867_print_out.log)

I'll appreciate your insights and suggestions regarding this matter!

**Comment by lizziel** [comment]
Hi @mmmjjj527, you can turn on debug prints for ExtData for find out more about potential errors in inputs. For 13.2, which is a very old version, you do this in ExtData.rc at the top of the file. Set `DEBUG_LEVEL` to 1, and then re-run (no need to recompile).

That being said, the error in the stderr log file indicates the problem is in calling subroutine Set_CH4
`pe=00079 FAIL at line=01292    gchp_chunk_mod.F90                       <Error calling SET_CH4>`

The last message in the HEMCO log has to do with CH4 inputs:                                   
```
 Evaluate field NOAA_GMD_CH4
HEMCO: Leaving GET_CURRENT_EMISSIONS ( 1)
```

The error message in the main log file is this:
```
===============================================================================
GEOS-Chem ERROR: Cannot retrieve data for NOAA_GMD_CH4, CMIP6_Sfc_CH4, or 
SfcVMR_CH4 from HEMCO! Make sure the data source corresponds to your emissions 
year in HEMCO_Config.rc (NOAA GMD for 1978 and later; else CMIP6).
 -> at SET_CH4 (in module GeosCore/set_global_ch4_mod.F90)
===============================================================================
```

Check that you have NOAA_GMD_CH4 data available for that date.

**Comment by mmmjjj527** [comment]
> Hi @mmmjjj527, you can turn on debug prints for ExtData for find out more about potential errors in inputs. For 13.2, which is a very old version, you do this in ExtData.rc at the top of the file. Set `DEBUG_LEVEL` to 1, and then re-run (no need to recompile).
> 
> That being said, the error in the stderr log file indicates the problem is in calling subroutine Set_CH4 `pe=00079 FAIL at line=01292 gchp_chunk_mod.F90 <Error calling SET_CH4>`
> 
> The last message in the HEMCO log has to do with CH4 inputs:
> 
> ```
>  Evaluate field NOAA_GMD_CH4
> HEMCO: Leaving GET_CURRENT_EMISSIONS ( 1)
> ```
> 
> The error message in the main log file is this:
> 
> ```
> ===============================================================================
> GEOS-Chem ERROR: Cannot retrieve data for NOAA_GMD_CH4, CMIP6_Sfc_CH4, or 
> SfcVMR_CH4 from HEMCO! Make sure the data source corresponds to your emissions 
> year in HEMCO_Config.rc (NOAA GMD for 1978 and later; else CMIP6).
>  -> at SET_CH4 (in module GeosCore/set_global_ch4_mod.F90)
> ===============================================================================
> ```
> 
> Check that you have NOAA_GMD_CH4 data available for that date.

Hi @lizziel, I checked the corresponding dataset (HcoDir/NOAA_GMD/v2018-01/monthly.gridded.surface.methane.1979-2020.1x1.nc) before, and found that date is available in the dataset. Here I attached the error.log and "print_out.log" after setting `DEBUG_LEVEL` to 1 for your reference.

<img width="1146" alt="截屏2023-12-14 下午1 08 47" src="https://github.com/geoschem/GCHP/assets/37134077/caa4019a-6d6d-4552-952a-6f91be4cad76">

[1430858_print_out.log.txt](https://github.com/geoschem/GCHP/files/13668667/1430858_print_out.log.txt)
[1430858_error.log.txt](https://github.com/geoschem/GCHP/files/13668668/1430858_error.log.txt)

**Comment by lizziel** [comment]
Hi @mmmjjj527, you may need to change `DEBUG_LEVEL` to a higher number since the log still does not include ExtData prints. Try `DEBUG_LEVEL` equal to 20. Even better would be to try to run a simulation using the latest version. This would be easier to find errors in data. We no longer support 13.2.1.

**Comment by mmmjjj527** [comment]
Hi @lizziel, thanks for the suggestion. I'll try to use a higher version to see if the problem can be solved. :)

**Comment by lizziel** [comment]
Hi @mmmjjj527, were you able to resolve this issue?
