### ISSUE TITLE
How to run a GCHP simulation without Chemistry (only emission)? 

### ISSUE THREAD

**Issue by herizonarivelo** [geoschem/gchp#366]
Name: Herizo Narivelo
Institution: Observatoire du Midi-Pyrénées - Laboratoire d'Aérologie (LA UMR 5560) - Université Toulouse III Paul Sabatier (France)

### Confirm you have reviewed the following documentation

- [ x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [ x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

Dear all, 
I am a newcomer to using the GCHP model.  I used the GCHP v14.2.2 version for my study. My project is to work on a long simulation (several years) with c48 horizontal resolution but before doing these simulation, I am doing a simulation test in order to choose the well start date of my simulation. To do this, I have tried to disable/deactivate the chemistry in the configuration file (setCommonRunSettings.sh), but I seem to be taking a long time with my simulation. For one month period of simulation, it has taken approximately 1 hour of time to complete the run.
Some time ago, a simulation carried out with the previous version of Geos-chem took a few hours to complete simulation over a long period.
For the simulation with take account only the emission, I had set false the fields Chemistry, advection, Cloud, PBL_Mixing, Non_Local_Mixing, DryDep and WetDep in the "setCommonRunSettings.sh" and also set photolysis to false in geoschem_config.yml.
Is there anything I should set to false/comment in a configuration file other than the one I have set to false in setCommonRunSettings.sh?

I have attached my setCommonRunSettings.sh, geoschem_config.yml and GCHP.log for my simulation. It would be great if you could explain my problem for simulation without chemistry which take a long time to complete.

[HEMCO_Config.rc.log](https://github.com/geoschem/GCHP/files/13877084/HEMCO_Config.rc.log)
[setCommonRunSettings.sh.log](https://github.com/geoschem/GCHP/files/13877085/setCommonRunSettings.sh.log)
[geoschem_config.yml.log](https://github.com/geoschem/GCHP/files/13877086/geoschem_config.yml.log)
[gchp.20070701_0000z.log](https://github.com/geoschem/GCHP/files/13877087/gchp.20070701_0000z.log)

Best regards, 
Herizo

**Comment by lizziel** [comment]
Hi @herizonarivelo, it looks like you are doing everythinbg right. Could you try a c24 benchmark simulation using 48 cores? You can create the simulation and run without making any edits to the configuration files. The resulting timing can be compared to our benchmark run for 14.2 to see if they are comparable. It should take about 8 hours (see [here](https://wiki.seas.harvard.edu/geos-chem/index.php/GEOS-Chem_14.2.0#1-month_benchmark_assessment_form)).

**Comment by lizziel** [comment]
@herizonarivelo, were you able to resolve this issue?
