### ISSUE TITLE
MAPL update to improve error handling

### ISSUE THREAD

**Issue by yantosca** [geoschem/gchp#367]
### Name and Institution (Required)

Name: Bob Yantosca
Institution: Harvard + GCST

### Description

This issue is to identify the submodule PRs related to GCHP fixes going into 14.3.0. The PRs are all zero diff and can be brought in at the same time. They include the following:

- https://github.com/geoschem/MAPL/pull/31

Let me know if you have any questions or concerns.

**Comment by lizziel** [comment]
I think 14.3.0 is frozen now so it can go into the next version. I'll rename it to be more generic.

**Comment by lizziel** [comment]
This is now merged into 14.3.1.
