### ISSUE TITLE
Running HEMCO standalone in GCHP

### ISSUE THREAD

**Issue by Aosrain** [geoschem/gchp#371]
### Name and Institution (Required)

Name: Longtao Wu
Institution: JPL

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Hello,

I want to execute HEMCO in standalone mode to generate instantaneous emissions in a netcdf file, which will be utilized in GCHP. Subsequently, I plan to modify the emission file as required and use it as input to run GCHP. How can I configure this simulation in GCHP?

Thanks,

-Longtao

**Comment by lizziel** [comment]
Hi @Longtao, you can input emissions generated by HEMCO standalone by adding them to the `ExtData.rc` and `HEMCO_Config.rc` files as you would other input files for GCHP. All of the "OFFLINE" emissions listed as input were generated using HEMCO standalone so there is precedent for this. The GCHP ReadTheDocs has detailed information about the configuration files [here](https://gchp.readthedocs.io/en/stable/user-guide/configuration-files.html) which you should take a look at. There is also a brief section on adding emissions [here](https://gchp.readthedocs.io/en/stable/user-guide/rundir-config.html#add-new-emissions-files). Let us know if you run into any problems or have any other questions.

**Comment by Aosrain** [comment]
Hi Lizziel,

Thank you for replying. The GCHP emission output is at Cubed-sphere grids. 
           For example: EmisNO2_Total(time, lev, nf, Ydim, Xdim). 
How should I set the SrcDim in HEMCO_Config.rc, "xy"? Do I need do anything to the emission output, such as reshaping or something else?

Thanks,

-Longtao

**Comment by lizziel** [comment]
Hi @Aosrain, it sounds like you are generating emissions by running GCHP and then want to input them for another GCHP run. Is that correct? Where does HEMCO standalone fit into this?

**Comment by Aosrain** [comment]
Hi Lizziel,

Yes, I would like to generating emissions by running GCHP, updating the emissions with data assimilation, then input the updated emissions for another GCHP run. I'm following the method using in CHEEREIO. But it's not clear to me how to add the emission at Cubed-sphere grid as a new emission in HEMCO_Config.rc yet. It would be great if you could share an example demonstrating how it works.

Thanks,

-Longtao

**Comment by lizziel** [comment]
You should be able to add GCHP output diagnostic files to config file `ExtData.rc` the same way you would add lat-lon input files. Have you tried this and run into a problem? See also GCHP issue https://github.com/geoschem/GCHP/issues/325 which is about configuring cubed-sphere files as input to GCHP.

**Comment by Aosrain** [comment]
I have tried to add a scale factor (all the values=1) for NO emission as followings. It works and the output results are identical to those without the scale factor. However, the running time increases significantly from 10 minutes to 100 minutes. Do you have any suggestion to improve the running time? Thanks!

Changes in HEMCO_Config.rc:
< 0 CEDS_NO_AGR     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_agr            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5
< 0 CEDS_NO_ENE     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_ene            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5
< 0 CEDS_NO_IND     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_ind            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5
< 0 CEDS_NO_TRA     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_tra            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5
< 0 CEDS_NO_RCO     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_rco            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5
< 0 CEDS_NO_SLV     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_slv            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5
< 0 CEDS_NO_WST     $ROOT/CEDS/v2021-06/$YYYY/NO-em-anthro_CMIP_CEDS_$YYYY.nc            NO_wst            1750-2019/1-12/1/0 C xy kg/m2/s NO    25/700        1 5

< 700 ASSIM_scalar /nobackupp17/lwu5/GCHP_run/C90_letkf/OutputDir/GCHP_LETKF_scale_factor.nc4 Scalar 2018-2023/1-12/1-31/0-23 RF xy 1  1

Change in ExtData.rc:

< ASSIM_scalar 1 N Y - none none Scalar /nobackupp17/lwu5/GCHP_run/C90_letkf/OutputDir/GCHP_LETKF_scale_factor.nc4

My config, log and scale factor files are attached.

[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/14451651/HEMCO_Config.rc.txt)
[GCHP_LETKF_scale_factor.nc4.txt](https://github.com/geoschem/GCHP/files/14451652/GCHP_LETKF_scale_factor.nc4.txt)
[GCHP.o18611712.txt](https://github.com/geoschem/GCHP/files/14451653/GCHP.o18611712.txt)
[ExtData.rc.txt](https://github.com/geoschem/GCHP/files/14451654/ExtData.rc.txt)

**Comment by lizziel** [comment]
Is the scalar file time-invariant or time-varying? Your `HEMCO_Config.rc` entry indicates it is hourly. That part of the `HEMCO_Config.rc` is ignored by GCHP and `ExtData.rc` is used instead for data frequency. You entered `-` for frequency which indicates time-invariant file. If it is time-varying instead then perhaps MAPL is confused.

**Comment by Aosrain** [comment]
The scalar file is time-invariant. Are there any recommendations I should try?

**Comment by lizziel** [comment]
This is very strange since your CEDS data is monthly. I would think the scale factor would only be applied once. And the regridding should also only occur once since the file is time-invariant.

@msulprizio, @yantosca: any ideas on why adding a scale factor in HEMCO would slow down the model by a factor of 10?

**Comment by Aosrain** [comment]
The notable rise in runtime is due to my adjustment of logging information to the debug level.  The runtime returns to 10 minutes once I revert it back to the warning level. Thank you!

**Comment by lizziel** [comment]
Great, thanks for following up about that. Yes, the debug options make run-time much slower.
