### ISSUE TITLE
List of netCDF file attributes that are incompatible with MAPL

### ISSUE THREAD

**Issue by yantosca** [geoschem/gchp#374]
This PR is intended to document the various netCDF file attributes that cause MAPL to hang (see issue geoschem/GCHP#373).

1. Any field that is of integer type, e.g. `time(int)`

2. `bnds`, `lat_bnds`, `lon_bnds`, `lev_bnds`.  However, I wonder if this is more because `lon_bnds`, `lat_bnds`, `lev_bnds` do not have `long_name` and `units` attributes.  I can test this.
```console
dimensions:
        time = UNLIMITED ; // (1 currently)
        lon = 72 ;
        bnds = 2 ;  <=== incompatible with GCHP
        lat = 46 ;
        lev = 72 ;

        double lon_bnds(lon, bnds) ;
                lon_bnds:_Storage = "chunked" ;
                lon_bnds:_ChunkSizes = 72, 2 ;
                lon_bnds:_DeflateLevel = 1 ;
                lon_bnds:_Endianness = "little" ;
                lon_bnds:_NoFill = "true" ;
        double lat_bnds(lat, bnds) ;
                lat_bnds:_Storage = "chunked" ;
                lat_bnds:_ChunkSizes = 46, 2 ;
                lat_bnds:_DeflateLevel = 1 ;
                lat_bnds:_Endianness = "little" ;
                lat_bnds:_NoFill = "true" ;
        double lev_bnds(lev, bnds) ;
                lev_bnds:standard_name = "atmosphere_hybrid_sigma_pressure_coordinate" ;
                lev_bnds:units = "level" ;
                lev_bnds:formula_terms = "ap: ap_bnds b: b_bnds ps: ps" ;
                lev_bnds:_Storage = "chunked" ;
                lev_bnds:_ChunkSizes = 72, 2 ;
                lev_bnds:_DeflateLevel = 1 ;
                lev_bnds:_Endianness = "little" ;
                lev_bnds:_NoFill = "true" ;
```

3. Area variable without a time dimension:
```console
        float AREA(lat, lon) ;
                AREA:long_name = "Surface area" ;
                AREA:units = "m2" ;
                AREA:_Storage = "chunked" ;
                AREA:_ChunkSizes = 46, 72 ;
                AREA:_DeflateLevel = 1 ;
                AREA:_Endianness = "little" ;
                AREA:_NoFill = "true" ;
```

4. Any variable that does not have the same number of vertical levels as the `lev` dimension.

More to follow

Tagging @lizziel

**Comment by lizziel** [comment]
Transferring to GCHP so we can keep GCHP issues all in the same place.

**Comment by lizziel** [comment]
I think #1 needs to be checked again since @msulprizio pointed out the input meteorology files have time as integer without issue.

**Comment by lizziel** [comment]
GMAO is putting together a guide on netCDF file requirements for MAPL: https://github.com/GEOS-ESM/MAPL/wiki/Guide-to-Supported-ExtData-Input-Files

**Comment by lizziel** [comment]
[ReadTheDocs Debugging page](https://gchp.readthedocs.io/en/stable/user-guide/debugging.html) now links to the GMAO wiki page for MAPL-supported input files.
