### ISSUE TITLE
STRETCHED GRID Error <Found   4 unfulfilled imports in extdata> 

### ISSUE THREAD

**Issue by ast222340** [geoschem/gchp#378]
### Name and Institution (Required)

Name:Sayan
Institution:Vidyasagar university

### Confirm you have reviewed the following documentation

- [Y] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [Y] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [Y] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [Y] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Respected sir/madam,
I want to add METEOROLOGY option true during simulation in HEMCO_Config.rc.So I have changed some things.I am telling where I have changed.
In  HEMCO_Config.rc file,     --> METEOROLOGY            :       true

In  GCHP.rc file,
Toggle to import mass fluxes for use in advection or compute from winds
#-----------------------------------------------------------------------
IMPORT_MASS_FLUX_FROM_EXTDATA: .true.

If thsi option is false then the model is running without any error.
I don't understand what error means.I have attached the Job script and gchp.log file.

[setCommonRunSettings.sh.txt](https://github.com/geoschem/GCHP/files/14251300/setCommonRunSettings.sh.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/GCHP/files/14251301/HEMCO_Config.rc.txt)
[GCHP.rc.txt](https://github.com/geoschem/GCHP/files/14251303/GCHP.rc.txt)
[gchp.20190701.log.txt](https://github.com/geoschem/GCHP/files/14251304/gchp.20190701.log.txt)
[gchp_spons.sh.txt](https://github.com/geoschem/GCHP/files/14251307/gchp_spons.sh.txt)

**Comment by lizziel** [comment]
Hi @ast222340, meteorology is not read in via HEMCO in GCHP. See GCHP ReadTheDocs section on configuring a run for meteorology to learn how that works [here](https://gchp.readthedocs.io/en/stable/user-guide/rundir-config.html#change-input-meteorology).

What are you trying to configure in GCHP? If you would like to use mass fluxes in advection, which is currently an advanced feature still undergoing testing, then you need to create a run directory using native (raw) GEOS-FP fields (or alternatively GEOS-IT if you are using version 14.3.0) and choose the mass flux option during run directory creation. If you see an error in ExtData then you should follow instructions on the debugging page which specifies looking at log file `allPEs.log`. See documentation [here](https://gchp.readthedocs.io/en/stable/user-guide/debugging.html).

**Comment by ast222340** [comment]
Thank you @lizziel,I read the GCHP documentation.
"Need to change the met-field entries in run directory file ExtData.rc after creating a run directory".Already exist "MetDir".
Copy from ExtData.rc
--- 2D variables, 1-hr averaged ---
ALBD     1 N Y F0;003000 none none ALBEDO   ./MetDir/%y4/%m2/MERRA2.%y4%m2%d2.A1.05x0625.nc4
CLDFRC   1 N Y F0;003000 none none CLDTOT   ./MetDir/%y4/%m2/MERRA2.%y4%m2%d2.A1.05x0625.nc4
Here is the path of the MERRA2 file.If we notice the lockfile taking many files as input files but not showing MERRA2 files.where is the problem?

2.That option will be only true when we use data field GEOS-FP.Am i right?
![Screenshot from 2024-02-14 00-04-31](https://github.com/geoschem/GCHP/assets/135971477/d29716d0-d031-4c7c-aa27-59694d749594)

**Comment by lizziel** [comment]
What meteorology are you trying to use?

**Comment by ast222340** [comment]
@lizziel,I want to use MERRA2 meteorology file.

**Comment by lizziel** [comment]
To use MERRA2 meteorology you should not need to change anything after setting up the run directory. You can only use winds in advection with MERRA2. Mass fluxes are not available.
