### ISSUE TITLE
Question about after run 

### ISSUE THREAD

**Issue by ast222340** [geoschem/gchp#381]
### Name and Institution (Required)

Name:Sayan
Institution:Vidyasagar university

### Confirm you have reviewed the following documentation

- [Y] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [Y] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [Y] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [Y] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
After running it shows them in this file.So the model run is not correct.I don't really understand this.
https://gchp.readthedocs.io/en/stable/user-guide/running.html
"Verify a successful run
6.Output file allPEs.log does not contain any error messages."
[allPEs.log.txt](https://github.com/geoschem/GCHP/files/14319974/allPEs.log.txt)

**Comment by lizziel** [comment]
Hi @ast222340, this issue does not contain enough information to understand what the problem is.

**Comment by ast222340** [comment]
Thank you @lizziel.
After the model is run,what is coming in the allPEs.log file gives an indication of which?Does it mean an error?

**Comment by lizziel** [comment]
Your allPEs.log shows this:
```
0000: GCHPctmEnv: INFO: Configured to derive and export mass flux and courant numbers
0000: GCHPctmEnv: INFO: Configured to expect 'bottom-up' meteorological data from 'ExtData'
0000: GCHPctmEnv: INFO: Configured to use dry air pressure in advection
0000: GCHPctmEnv: INFO: Configured to correct native mass flux (if using) for humidity
```
This is informational only and there is no error. If there is an error then "error" will appear in the message.
