### ISSUE TITLE
Problem with C48 and C180 simulation

### ISSUE THREAD

**Issue by ast222340** [geoschem/gchp#383]
### Name and Institution (Required)

Name:Subhadeep Ghosh
Institution:IITD

### Confirm you have reviewed the following documentation

- [Y] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [Y] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [Y] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [Y] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question
Respected sir/madam,
I am facing three problem.I have discussed three problems below.
1. Global C48 model run:
The model is starting to run fine but after exactly three months of running the model is shutting down automatically.No output files are  being generated for last month.I mean model start 20200301 - 20200501,suddenly stop.
Writing:   1008 Slices to File:  OutputDir/GCHP.AerosolMass.20200501_0000z.nc4
 Writing:   6810 Slices to File:  OutputDir/GCHP.Emissions.20200501_0000z.nc4
 Writing:  21384 Slices to File:  OutputDir/GCHP.SpeciesConc.20200501_0000z.nc4
 showing but in OutputDir not found that file.
 for check again starting 20200501 - 20200701,suddenly stop.
 last 20200701 - 20200901,suddenly stop.
 Writing:   1008 Slices to File:  OutputDir/GCHP.AerosolMass.20200901_0000z.nc4
 Writing:   6810 Slices to File:  OutputDir/GCHP.Emissions.20200901_0000z.nc4
 Writing:  21384 Slices to File:  OutputDir/GCHP.SpeciesConc.20200901_0000z.nc4
 all time created  gcchem_internal_checkpoint file.
 gcchem_internal_checkpoint.20200901_0000z.nc4
 I did it three times to be sure but still can't figure out why this is happening.I attached three log and run script files.
 
[gchp.20200301_0000z.log.txt](https://github.com/geoschem/GCHP/files/14408438/gchp.20200301_0000z.log.txt)
[gchp.20200501_0000z.log.txt](https://github.com/geoschem/GCHP/files/14408673/gchp.20200501_0000z.log.txt)
[gchp.20200701_0000z.log.txt](https://github.com/geoschem/GCHP/files/14408680/gchp.20200701_0000z.log.txt)
[gchp_spons.sh.txt](https://github.com/geoschem/GCHP/files/14408684/gchp_spons.sh.txt)

2. Stretched C180 model run:(South Asia)
Same problem here 5 day simulation for model is getting automatic stop.
[gchp.20190701_0000z.log](https://github.com/geoschem/GCHP/files/14408766/gchp.20190701_0000z.log)

3. How to model output C48 convert to regular lat-lon grid
If there is any code to convert it would be great if you share me.

**Comment by lizziel** [comment]
Thanks for writing, @ast222340. There should be another log with information about your PBS job, including reason for stopping, e.g. segmentation fault, running out of memory, or reaching time limit. Do you have that log? Did you check to see how slow your jobs were running? Your core count is very low which would make the model run slowly.

To convert C48 output to regular lat-lon grid you can use the regridding tools in python package GCPy. See https://gcpy.readthedocs.io/en/stable/Regridding.html. You can also configure `HISTORY.rc` to output a collection to a lat-lon grid. Information about how to do that is in the `HISTORY.rc` file and also described at https://gchp.readthedocs.io/en/stable/user-guide/config-files/HISTORY_rc.html and https://gchp.readthedocs.io/en/stable/user-guide/rundir-config.html#output-diagnostics-data-on-a-lat-lon-grid.

**Comment by ast222340** [comment]
Thank you @lizziel.Waited for new simulation that's why don't reply.
I attached PBS and gchp log files.
[gchp.20200901_0000z.log.txt](https://github.com/geoschem/GCHP/files/14453373/gchp.20200901_0000z.log.txt)
[PBS.log.txt](https://github.com/geoschem/GCHP/files/14453382/PBS.log.txt)

From GCPy documentation page,
Regrid a 4x5 GEOS-Chem Classic restart or diagnostic file to a GEOS-Chem Classic 2x2.5 file
Regrid a 4x5 GEOS-Chem Classic restart or diagnostic file to a GCHP C24 restart file:
Regrid a GCHP C48 restart file to a GCHP stretched grid C48 restart file
Nowhere does it say o convert from GCHP output file to lat-lon,It would be great if you look at it again.

From HISTORY.rc file,
GRID_LABELS: #PE24x144-CF
             #PC360x181-DC
             #REGIONAL1x1
    ::

    # Example of cubed-sphere grid at c24 resolution
    PE24x144-CF.GRID_TYPE: Cubed-Sphere
    PE24x144-CF.IM_WORLD: 24
    PE24x144-CF.JM_WORLD: 144
    PE24x144-CF.LM: 72

    # Example of lat-lon global grid at 1x1 resolution
    PC360x181-DC.GRID_TYPE: LatLon
    PC360x181-DC.IM_WORLD: 360
    PC360x181-DC.JM_WORLD: 181
    PC360x181-DC.POLE: PC
    PC360x181-DC.DATELINE: DC
    PC360x181-DC.LM: 72
By default first option is whether to comment out or not,it is taken automatically during the simulation.
According to previous discussion if we want to convert GCHP output file to lat-lon then second option should be 'ON'.
The it becomes a simulation like  GEOS-Chem Classic.Please solve this doubt?

**Comment by lizziel** [comment]
Have you tried using GCPy function `file_regrid` to regrid GCHP cubed-sphere output file to lat-lon? The examples in GCPy are for restart files but I believe it works the same way for non-restart file out. I am tagging @yantosca since he is our GCPy regridding expert. Perhaps we need to add a note that the same method for restart files also works for regridding diagnostic output between GCHP cubed-sphere and lat-lon.

Using the grid labels to output a collection as lat-lon will not make the simulation like GEOS-Chem Classic. The model will still be run at the cubed-sphere grid resolution that you configure in `setCommonRunSettings.sh`. If you specify a grid label within the collection definition in `HISTORY.rc` then the data will be regridded to the grid defined by the grid label just prior to writing out to file. For the grid label to take effect it must be defined in `HISTORY.rc` and included within the `GRID_LABELS` list within `HISTORY.rc` as well.

**Comment by yantosca** [comment]
@ast222340: Is there a reason you need to convert the GCHP output file from cubed-sphere to lat-lon?  If you use the GCPy plotting routines you can create plots directly from the cubed-sphere files. 

Yes, you should be able to regrid from cubed-sphere to lat-lon with the `gcpy.file_regrid` function as noted in the gcpy.readthedocs.io documentation.

**Comment by ast222340** [comment]
Thank you @lizziel @yantosca.
I had a look at the GCPy documentation page.But their is no option cubic sphere grid convert to lat-lon.Which are present
Example 1: Standard Lat-Lon to Cubed-Sphere Regridding
Example 2: Standard Cubed-Sphere to Cubed-Sphere Regridding
Example 3: Standard to Stretched Cubed-Sphere Regridding
There is not mentioned about Cubeb-Sphere to lat-lon.It I have said something wrong,please correct me and tell me the correct thing.

There is no reason to convert.Actually,i f I convert to lat-lon,I get a lot of plotting benefits.Like I ran the model for 2020 C48 Global. Generated monthly output file.My plot is ready with the code that is in the GCPy documentation(Six-panel comparison plots).For my research purpose I am going to modify the plot. I want to plot annual PM25 average, Four season plot, mask the ocean part and need one colorbar.some statistics analysis.If the PM25 had been in Lat-Lon,I could have arranged these tasks very well for me.If would be nice if you could tell me how to do these plots. 
https://gcpy.readthedocs.io/en/stable/Guide-to-Useful-Capabilities.html

**Comment by lizziel** [comment]
GCPy includes several examples of regridding but they are not exhaustive. You should be able to extrapolate from the examples and the documentation for `file_regrid` function to generate lat-lon files from cubed-sphere.

You are welcome to adapt GCPy to your use case. However, the GEOS-Chem Support Team does not provide direct help coding in python for GEOS-Chem data analysis.

**Comment by ast222340** [comment]
Thank you @lizziel.
