### ISSUE TITLE
[BUG/ISSUE] Silent bug using native (raw) GMAO files in GCHP

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#386]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Description of your issue or question

There is a mass conservation problem when using native (raw) GMAO files in GCHP. We see this when using all of the following GCHP meteorology options:
- GEOS-FP native fields with lat-lon winds
- GEOS-FP native fields with cubed-sphere mass fluxes
- GEOS-IT native fields with cubed-sphere winds
- GEOS-IT native fields with cubed-sphere mass fluxes

I have not tested with GEOS-IT lat-lon inputs but expect the same result.

I will look into the issue to find out where the bug is coming in. For now, use GCHP with native fields with caution. If possible, use processed files instead. We have 0.25x0.625 processed lat-lon files available for GEOS-FP and 0.5x0.625 processed lat-lon files for GEOS-IT. Both use 3-hourly winds in advection. This is not ideal but gives better results than using the native files. The difference between native and processed file results is larger than the difference between winds and mass fluxes, as shown by looking at winds versus mass fluxes using raw files for both (plots coming soon).

You can browse plots showing the impact of this bug at the following links:
1. [Restart file differences](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GEOS-IT/passive_tracer_comparison/) across 1-year transport tracer run for various meteorology sources and grid resolutions 
2. Benchmarks of GEOS-FP raw vs processed meteorology files with winds in advection
    - [1-month full chemistry benchmark](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GEOS-FP_raw_vs_processed_winds/1mo_fullchem_benchmark/GEOS-FP_processed_vs_raw_winds_1mo_benchmark/)
    - [1-year transport tracer benchmark](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GEOS-FP_raw_vs_processed_winds/1yr_transport_tracers/)
3. Passive tracer global mass time series
    - [GEOS-IT native met files with CS winds](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GEOS-IT/transport_tracers_discover_runs_raw_GEOSIT/GCC_4x5_vs_GCHP_c30_winds/Tables/Passive_mass.txt)
    - [GEOS-IT processed met files with CS winds](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/GEOS-IT/transport_tracers_cannon_runs_processed_GEOSIT/Passive_mass.txt)
    - [GEOS-FP native files with wind, native files with mass fluxes, and processed files with wind](https://ftp.as.harvard.edu/gcgrid/geos-chem/validation/gchp_mass_fluxes_vs_winds/1yr_transport_tracers/dry_pressure__winds_vs_mass_fluxes/Tables/Passive_mass.txt)

**Comment by lizziel** [comment]
I looked more into this issue and think it has to do with advection but not winds. This is based on the below plots of a 1-day Transport Tracer simulation with advection only turned on.

**Processed input files versus raw input files, but using processed wind in both simulations**

<img width="1113" alt="advOnly_1_vs_3" src="https://github.com/geoschem/GCHP/assets/651947/1cff6684-0fb0-4421-8feb-4ba47b1ca820">


**Using processed input files for both ref and dev _except winds_ shows only noise differences**

<img width="1140" alt="advOnly_1_vs_2" src="https://github.com/geoschem/GCHP/assets/651947/0f1a2193-4833-40b0-b18e-3c7a8dfa1723">


**Using raw input files for both ref and dev _except winds_ shows only noise differences**

<img width="1115" alt="advOnly_3_vs_4" src="https://github.com/geoschem/GCHP/assets/651947/0fa302b4-87b8-4d9c-93f6-b9fd638744c2">


I also looked at raw versus processed input files for runs with advection turned off. The differences look like noise, which leads me to believe this is an advection problem but not the winds fields.

**Zonal mean of processed versus raw input files _with advection turned off_ (winds are not used)**

<img width="1174" alt="allOff_1_vs_3" src="https://github.com/geoschem/GCHP/assets/651947/23172c78-003a-405f-ad6f-add8ff0295e1">

Surface mean of processed versus raw input files  _with advection turned off_ (winds are not used)

<img width="997" alt="allOff_2_vs_3" src="https://github.com/geoschem/GCHP/assets/651947/9cff61e3-aa6d-40d6-8fee-f85392a9f901">

I'll take a look at the advection code. Perhaps there is an over-looked import that needs to be flipped?

Tagging @sdeastham

**Comment by lizziel** [comment]
@sdeastham, the analysis above supports the theory that this issue accounts for the global mass fluctuation when running GCHP with mass fluxes since all mass flux runs use raw GMAO input data.

**Comment by sdeastham** [comment]
Hi @lizziel  - super interesting! A couple of Qs/suggestions:

* When I was looking at the met data, one issue I was seeing was that the global mean dry surface pressure (or equivalently the sum of dry surface pressure times cell area) was not consistent over time. That sent me off down a rabbit hole because without a consistent dry surface pressure it would be impossible to achieve mass consistency. Is that an issue here?
* I agree that whatever is going on, it has something to do with the advection code (as without that there's really no way for a bug like this to creep in). I also agree that this is likely to be a source, and possibly even _the_ source, of the issues with the mass flux runs (so this is even more exciting!). I'm scratching my head now trying to think of which import might be flipped, but I think my suggestion would remain the same - looking at instantaneous fields for some of the imports and checking for inconsistency between runs using the processed and raw files. A vertical flip feels like it would cause bigger issues, but I wouldn't be surprised if there was something like a time interpolation or grid staggering bug.

**Comment by lizziel** [comment]
I believe I found the problem, which appears to be units handling of the pressure and humidity imports within the ctmEnv gridcomp. Both SPHU and PS have different units in processed and raw files (kg/kg vs g/kg, and hPa vs Pa). This is not taken into account when using the fields to compute pressure edge exports used in advection. Stay tuned for verification.

**Comment by lizziel** [comment]
Also note the fix to this will likely solve the total versus dry pressure problems in advection I found in version 14.0.

**Comment by lizziel** [comment]
Hmm, units issue doesn't actually make sense since we have scaling in `ExtData.rc`. Also the SPHU units difference is between StateMet and the files, not the raw vs processed. Regardless, switching surface pressure and humidity from raw to processed fixes the issue. The PS and SPHU outputs from GEOS-Chem look okay, although pressure has noise while humidity is identical. I'll report back when there is a true fix found.

**Comment by lizziel** [comment]
The problem is not the units as I originally thought. The 3D specific humidity array used to compute pressure level edges from surface pressure is assumed to be surface at level 1. When using raw GMAO files humidity is flipped for passing to advection if using total pressure, and is also flipped when setting State_Diag arrays. However, it is not flipped for computing dry pressure levels to pass to advection. The omission of this  causes incorrect dry pressure passed to advection if using raw GMAO files.

Below is a comparison of 1-day runs showing the fix. I believe the remaining difference is due to surface pressure, which is curious since we should get identical results. There may be a lesser bug somewhere. I also wonder about the usage of total pressure in advection. My tests using dry pressure only, and the bug I found would only impact runs with dry pressure. However, there is a mass conservation issue using total pressure that should be revisited.

<img width="1098" alt="Screenshot 2024-03-12 at 10 00 50 AM" src="https://github.com/geoschem/GCHP/assets/651947/f4a15ba9-9c40-4e8c-8a7d-f08ce62f3c04">

**Comment by lizziel** [comment]
Confirmed that surface pressure explains remaining non-noise differences.

**Direct comparison of all processed input met versus all raw input met with advection only on shows 1e-6 bias:**

<img width="1145" alt="Screenshot 2024-03-13 at 1 33 59 PM" src="https://github.com/geoschem/GCHP/assets/651947/8d918a44-b8a3-4a48-b715-22d1a94efe37">

The same case but using processed PS1 and PS2 for both shows only noise on the order of 1e-10:

<img width="1111" alt="Screenshot 2024-03-13 at 1 32 19 PM" src="https://github.com/geoschem/GCHP/assets/651947/f800b343-0214-4ae2-9734-943a130b13d6">

We also see only noise when using raw PS1 and PS2 for both cases:

<img width="1132" alt="Screenshot 2024-03-13 at 1 32 43 PM" src="https://github.com/geoschem/GCHP/assets/651947/9e05b9ff-1c13-4b56-bb62-1a1cc3e7fd27">

**Comment by lizziel** [comment]
This issue is fixed in 14.3.1.
