### ISSUE TITLE
Create Run Directory Problem with 14.2.2 and 14.2.3 container

### ISSUE THREAD

**Issue by computermechanic** [geoschem/gchp#403]
### Name and Institution (Required)

Name: Edward So
Institution: The Chinese University of Hong Kong, ITSC, Research Computing Team

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GCHP version number and any relevant configuration and log files.

I have follow the following containers guide to setup the environment to run GCHP:
https://gchp.readthedocs.io/en/stable/supplement/containers.html

Everythings is fine in both **14.2.0** and **14.2.1** but I got a problem when using **14.2.2** and **14.2.3**.
After I use the containers to create the run directory, I found that the run directory is not well setup.
Most of the .rc files (GCHP.rc,ExtData.rc,HEMCO_Config.rc, etc.) is not present in the run directory.
Also the setCommonRunSettings.sh script is a blank script.
Is there any way to solved the problem of the run directory created by **14.2.2** and **14.2.3** container?

**Comment by lizziel** [comment]
Hi @computermechanic, thanks for reporting this. @yidant, could you look into whether there is a bug in the 14.2.2 and 14.2.3 containers?

**Comment by computermechanic** [comment]
Is there any upate or any work around for the issue?

**Comment by yidant** [comment]
Hi @computermechanic ! Thanks for following up! The bug probably results from the lack of a package 'gettext'. It affects some of the users. I'm currently facing another issue with a module. I'll update the containers after I solve it and let you know. 

If you want to use 14.2.2 and 14.2.3 right now, you can pull 14.3.0 containers instead and build the 14.2.2/14.2.3 GCHP with the environment. The containers later than 14.3.0 have this package installed.

**Comment by lizziel** [comment]
I will close out this issue now since using newer GCHP version containers fixes the problem.
