### ISSUE TITLE
[SUBMODULE UPDATES] MAPL fix for restarting with stretched grid checkpoints

### ISSUE THREAD

**Issue by lizziel** [geoschem/gchp#409]
### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Brief Description

This PR fixes a mismatch between stretched grid target coordinates as computed from attributes in the restart file and in the configuration files. Target lat/lon are read from file as REAL4 and written to checkpoint as REAL4. Conversion to radians, however, uses 180 degrees at double precision, while conversion back to lat/lon uses 180 degrees as single precision. This results in failing the online check that the target coordinates in the restart and the configuration file are identical.

### Submodule Pull Requests

* https://github.com/geoschem/MAPL/pull/34

### Related Issues

* https://github.com/geoschem/GCHP/issues/404

**Comment by yantosca** [comment]
We can now close this issue as https://github.com/geoschem/MAPL/pull/34 has been merged into 14.4.0-alpha.14.
