### ISSUE TITLE
[DISCUSSION] How to implement vertical flipping of imports from ExtData

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#41]
Hi everyone, I was thinking about how to add the ability to vertically flip metfields today (for running from native metfields), and I came to two ideas:
1. Define ExtData variable that need flipping in a config file. Flip those variables in GCHPctmEnv_GridComp. This is only "clean" if GCHPctmEnv_GridComp can have an IMPORT and EXPORT with the same name—does anyone know if that's possible?
2. Add a new derived export function (see [here](https://geos5.org/wiki/index.php?title=Using_the_ExtData_component#Derived_Exports)) to perform vertical flipping.

Any thoughts? Does anyone have a different idea in mind?

**Comment by LiamBindle** [comment]
@lizziel IIRC you had some thoughts on how this should be done. Is that right?

**Comment by lizziel** [comment]
Right, except I need to revisit this since my recollection of it is rusty. Once the 13.0 benchmark is running I can get back to you on this.

**Comment by LiamBindle** [comment]
Will that be sometime next week? To run GCHP with native metfields we need the flipping feature, and at that point we can figure out the minimum set of metfields too. That's why I'm eager to add this feature, but I can wait a week or so.

**Comment by lizziel** [comment]
I'll try to get to this next week. Getting GCHP 13.0 okay to benchmark will take priority but fingers crossed that goes smoothly.

**Comment by LiamBindle** [comment]
Thanks, sounds good!

**Comment by lizziel** [comment]
Sorry this got completely forgotten about for nearly a year! There are separate discussions about this elsewhere. I recently put a proposal in the comment thread at https://github.com/GEOS-ESM/MAPL/issues/284. @LiamBindle, what do you think of the idea I proposed?

**Comment by LiamBindle** [comment]
@lizziel I like it. I think we should close this issue in favor of the MAPL discussion. Is that okay?
