### ISSUE TITLE
ERROR during 'Initialize' stage of the gridded component 'EXTDATA'

### ISSUE THREAD

**Issue by ycyeongi** [geoschem/gchp#416]
### Name and Institution (Required)

Name: chaeyeong
Institution: PNU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

GCHP version : 13.4.1
GCHP stops as shown below. I read https://github.com/geoschem/GCHP/issues/166 but I didn't change my ExtData.rc and HEMCO_Config,rc (only change Dir path and true/false)
[GCHP.zip](https://github.com/geoschem/GCHP/files/15492878/GCHP.zip)

```
                                                             Mem/Swap Used (MB) at HISTMAPL_GenericInitialize=  6.404E+04  4.280E+02
        GENERIC: INFO: Finished the 'Initialize' stage of the gridded component 'HIST'
        GENERIC: INFO: Started the  'Initialize' stage of the gridded component 'EXTDATA'
                                                          Mem/Swap Used (MB) at EXTDATAMAPL_GenericInitialize=  6.406E+04  4.280E+02
pe=00000 FAIL at line=00854    MAPL_ExtDataGridCompMod.F90              <Found 155 unfullfilled imports in extdat>
pe=00000 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'EXTDATA'>
pe=00000 FAIL at line=00778    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00633    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00920    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00245    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00154    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00031    GCHPctm.F90                              <status=1>
[cli_0]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0
pe=00002 FAIL at line=00854    MAPL_ExtDataGridCompMod.F90              <Found 155 unfullfilled imports in extdat>
pe=00002 FAIL at line=01844    MAPL_Generic.F90                         <Error during the 'Initialize' stage of the gridded component 'EXTDATA'>
pe=00002 FAIL at line=00778    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=00633    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=00920    MAPL_CapGridComp.F90                     <status=1>
pe=00002 FAIL at line=00245    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00211    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00154    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00129    MAPL_Cap.F90                             <status=1>
pe=00002 FAIL at line=00031    GCHPctm.F90                              <status=1>
[cli_2]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 0) - process 2
```

**Comment by lizziel** [comment]
Hi @ycyeongi, could you clarify what you changed in the files? It looks like you changed `HEMCO_Config.rc` to set some of the GC-Classic-only options to true. This would cause a problem in GCHP.

**Comment by yantosca** [comment]
Also we would recommend using a newer GCHP version if possible as 13.4.1 is quite old by now.  We are about to release 14.4.0 this week, if you would like to grab this version.  There have been several fixes since 13.4.1.

**Comment by ycyeongi** [comment]
Thank you for your response, @lizziel
Here's what I fixed

```
    --> METEOROLOGY            :       true     # 1980-2021
    --> GC_RESTART             :       true
#------------------------------------------------------------------------------
    --> OFFLINE_DUST           :       false    # 1980-2021
    --> OFFLINE_BIOGENICVOC    :       false    # 1980-2021
    --> OFFLINE_SEASALT        :       false    # 1980-2021
    -->  CalcBrSeasalt         :       false
    --> OFFLINE_SOILNOX        :       false    # 1980-2021
# ----- NON-EMISSIONS DATA ----------------------------------------------------
    --> OLSON_LANDMAP          :       true     # 1985
    --> YUAN_MODIS_LAI         :       true     # 2000-2020
    --> RRTMG                  :       true     # 2002
# -----------------------------------------------------------------------------
104     SoilNOx                : on    NO
105     DustDead               : on    DST1/DST2/DST3/DST4
107     SeaSalt                : on    SALA/SALC/SALACL/SALCCL/SALAAL/SALCAL/BrSALA/BrSALC/MOPO/MOPI

```

**Comment by ycyeongi** [comment]
While waiting for an answer, I downloaded 14.2.3 GCHP and tried to run the model. But another error appeared.

`     object: 333,name: T_PREVDAY
            type: Field
     object: 334,name: TropLev
            type: Field
     object: 335,name: WetDepNitrogen
            type: Field
pe=00000 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00000 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00000 FAIL at line=01226    Chem_GridCompMod.F90                     <status=-1>
pe=00000 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00001 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00001 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00001 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00001 FAIL at line=01226    Chem_GridCompMod.F90                     <status=-1>
pe=00001 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00003 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00003 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00003 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00003 FAIL at line=01226    Chem_GridCompMod.F90                     <status=-1>
pe=00003 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00002 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00002 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00002 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00002 FAIL at line=01226    Chem_GridCompMod.F90                     <status=-1>
pe=00002 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00005 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00005 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00005 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00005 FAIL at line=01226    Chem_GridCompMod.F90                     <status=-1>
pe=00005 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
pe=00004 FAIL at line=06123    MAPL_Generic.F90                         <Factories not equal>
pe=00004 FAIL at line=01609    MAPL_Generic.F90                         <unknown error>
pe=00004 FAIL at line=01047    MAPL_Generic.F90                         <status=-1>
pe=00004 FAIL at line=01226    Chem_GridCompMod.F90                     <status=-1>
pe=00004 FAIL at line=01807    MAPL_Generic.F90                         <status=-1>
                                                         Mem/Swap Used (MB) at DYNAMICSMAPL_GenericInitialize=  6.404E+04  4.480E+02
                                                             Mem/Swap Used (MB) at GCHPMAPL_GenericInitialize=  6.405E+04  4.480E+02
pe=00000 FAIL at line=00167    BaseProfiler.F90                         <Timer <GCHP> does not match start timer <GCHPchem>>
pe=00000 FAIL at line=01825    MAPL_Generic.F90                         <status=1>
pe=00000 FAIL at line=00655    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00959    MAPL_CapGridComp.F90                     <status=1>
pe=00000 FAIL at line=00311    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00258    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00192    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00169    MAPL_Cap.F90                             <status=1>
pe=00000 FAIL at line=00029    GCHPctm.F90                              <status=1>
[cli_0]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 0) - process 0`

This time I only set the file location and didn't touch anything else.

**Comment by lizziel** [comment]
HI @ycyeongi, HEMCO does not handle meteorology, restart files, Olson land map, or LAI and those entries need to remain false. Is there a reason you changed them to true?

To use RRTMG you should create an RRTMG run directory rather than update the run directory manually. Is that what you did?

**Comment by ycyeongi** [comment]
That's what I did when I originally ran GEOS-Chem. So I set it up that way to see if the results would be similar to geos-chem.
I build it with the option cmake . -DRRTMG=y to turn on the RRTMG option.
After reading your comment, I set meteorology, restart files, Olson land map, or LAI to false and tried to run the model. However, GFED4 gave me another error, so I turned GFED4 off and ran the model.

```

                                                             Mem/Swap Used (MB) at HISTMAPL_GenericInitialize=  1.299E+04  5.250E+02
        GENERIC: INFO: Finished the 'Initialize' stage of the gridded component 'HIST'
        GENERIC: INFO: Started the  'Initialize' stage of the gridded component 'EXTDATA'
                                                          Mem/Swap Used (MB) at EXTDATAMAPL_GenericInitialize=  1.299E+04  5.250E+02
        GENERIC: INFO: Finished the 'Initialize' stage of the gridded component 'EXTDATA'
                                                                      Mem/Swap Used (MB) at MAPL_Cap:TimeLoop=  1.645E+04  5.250E+02
        GENERIC: INFO: Started the  'Run' stage of the gridded component 'EXTDATA'
 
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 162861 RUNNING AT amp12
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Killed (signal 9)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
```
When you run the model, you'll get an error like the one above. I think it's an issue with my server, so I'm looking into it.

**Comment by lizziel** [comment]
Hi @ycyeongi, have you tried turning on ExtData debug prints? We have guidance for how to do this on the debugging page of ReadTheDocs: [https://gchp.readthedocs.io/en/latest/user-guide/debugging.html](https://gchp.readthedocs.io/en/latest/user-guide/debugging.html).
