### ISSUE TITLE
error running carbon simulation

### ISSUE THREAD

**Issue by Aosrain** [geoschem/gchp#418]
### Your name

Longtao Wu

### Your affiliation

JPL

### What happened? What did you expect to happen?

During our carbon simulation testing, we encountered an error that seems to be connect to Extdata. Despite reviewing the file links in ExtData.rc, the error remains unresolved. 

### What are the steps to reproduce the bug?

1. Download and compile the code.
2. Download the input datasets.
3. Submit the job.

### Please attach any relevant configuration and log files.

[gchp.20190101_0000z.log](https://github.com/user-attachments/files/15569782/gchp.20190101_0000z.log)
[setCommonRunSettings.sh.txt](https://github.com/user-attachments/files/15569800/setCommonRunSettings.sh.txt)
[ExtData.rc.txt](https://github.com/user-attachments/files/15569806/ExtData.rc.txt)
[GCHP.o19590141.txt](https://github.com/user-attachments/files/15569808/GCHP.o19590141.txt)
[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/15569819/HEMCO_Config.rc.txt)

### What GCHP version were you using?

14.4.0-rc.0

### What environment were you running GCHP on?

Other (please explain below)

### What compiler and version were you using?

ifort 19.1.3.304 20200925

### What MPI library and version were you using?

MPT: libxmpi.so 'HPE MPT 2.28  04/24/23 12:22:36-mraymond'

### Will you be addressing this bug yourself?

Yes, but I will need some help

**Comment by yantosca** [comment]
Thanks for writing @Aosrain.  In the `logging.yml` file, change the `root_level` setting for `CAP.EXTDATA` to 'DEBUG` as shown below:
```yaml
   CAP.EXTDATA:
       handlers: [mpi_shared]
       level: WARNING
       root_level: INFO   <=== Change this to DEBUG
```
This should print the name of each data container that is being read by the ExtData component.  That should allow you to find the data entry that is causing the failure.

Also doublecheck that you have downloaded the latest data for the carbon simulation.  It could be that there is some necessary data missing from your system.

**Comment by yantosca** [comment]
Also tagging @lizziel

**Comment by Aosrain** [comment]
@yantosca The uploaded files are with CAP.EXTDATA in 'DEBUG'.

**Comment by yantosca** [comment]
Thanks @Aosrain. Could you also upload the `allPEs.log` file?  Error/warning messages also get sent there.

**Comment by lizziel** [comment]
Please also see the [Debugging page on GCHP ReadTheDocs](https://gchp.readthedocs.io/en/stable/user-guide/debugging.html). It goes over how to debug input data problems.

**Comment by Aosrain** [comment]
@yantosca @lizziel I found error messages in allPEs.log and updated ExtData.rc accordingly. Now, the error messages related to ExtData.rc are resolved, as shown in the attached allPEs.log (last 10000 lines due to the limitation of file size). However, the job is now hanging for an extended period without any output. Are my edits in ExtData.rc correct? Do you have any suggestions for fixing the current issue? I'll increase TOTAL_CORES to check whether it is due to memory issue.

[ExtData_update.rc.txt](https://github.com/user-attachments/files/15597282/ExtData_update.rc.txt)
[allPes.log_subset.txt](https://github.com/user-attachments/files/15597331/allPes.log_subset.txt)

**Comment by yantosca** [comment]
Hi @Aosrain.  I see the problem.   The problems are with the high-resolution mask files such as:
```console
./HcoDir/MASKS/v2018-09/Mexico_Mask_Mirror.001x001.nc
```
These files (at 0.01 x 0.01 degree)  cause a lot of memory usage in GCHP which may just hang your simulation.  We recently made coarser resolution masks (0.1 x 0.1 degree), which are available in the `/HEMCO/MASKS/v2024-04/` folder of the **GEOS-Chem Data (WashU)** Globus endpoint.

We will make sure that they are also posted on the `geoschemdata.wustl.edu` portal as well.

**Comment by yantosca** [comment]
Also, since you are using version 14.4.0-rc.-0, we would recommend updating to the official 14.4.0 release, which will have the updated HEMCO_Config.rc etc. config files.

**Comment by yantosca** [comment]
Also the new masks are now in this folder on the WashU data portal, thanks to @yidant!

- http://geoschemdata.wustl.edu/ExtData/HEMCO/MASKS/v2024-04/

**Comment by Aosrain** [comment]
@yantosca @yidant @lizziel Thank you! I'll work with the updates next week and let you know if I have any question.

**Comment by Aosrain** [comment]
@yidant Can you upload ./HcoDir/CO2/v2024-01/CHEM/CO2_prod_rates.GEOS5.2x25.72L.nc to http://geoschemdata.wustl.edu/ExtData/HEMCO/CO2/? Thanks.

**Comment by yidant** [comment]
Thanks @Aosrain ! This folder is now available at WashU portal.

**Comment by yantosca** [comment]
@Aosrain: I've uploaded the HEMCO/CO2/v2024-01 folder to the GEOS-Chem Data (WashU) Globus endpoint.  @yidant, could you also make sure that the file syncs properly to the geoschemdata.wustl.edu?

**Comment by Aosrain** [comment]
@yantosca I have updated to the version 14.4.0. Now the ExtData part looks good. However, the job stops with the following error. How to fix it?
==================================
 Doing warm GEOS-Chem restart

       GCHPchem: INFO: GEOS-Chem phase -1:
       GCHPchem: INFO: DoConv   : T
       GCHPchem: INFO: DoDryDep : F
       GCHPchem: INFO: DoEmis   : T
       GCHPchem: INFO: DoTend   : F
       GCHPchem: INFO: DoTurb   : T
       GCHPchem: INFO: DoChem   : T
       GCHPchem: INFO: DoWetDep : F
 HEMCO: array pointer vertically flipped relative to MAPL Import
 AEIC19_MONMEAN_CO
 HEMCO: array pointer vertically flipped relative to MAPL Import
 AEIC19_MONMEAN_CO2
 HEMCO: array pointer vertically flipped relative to MAPL Import GLOBAL_OH
 HEMCO: array pointer vertically flipped relative to MAPL Import CH4_LOSS
 HEMCO: array pointer vertically flipped relative to MAPL Import GLOBAL_Cl
 HEMCO: array pointer vertically flipped relative to MAPL Import PCO_CH4
 HEMCO: array pointer vertically flipped relative to MAPL Import PCO_NMVOC
 HEMCO: array pointer vertically flipped relative to MAPL Import GMI_LOSS_CO
 HEMCO: array pointer vertically flipped relative to MAPL Import GMI_PROD_CO
 HEMCO: array pointer vertically flipped relative to MAPL Import CO2_COPROD
 HEMCO: array pointer vertically flipped relative to MAPL Import ENERGY_LEVS
 HEMCO: array pointer vertically flipped relative to MAPL Import INDUSTRY_LEVS
  --- Do convection now
  --- Convection done!
  --- Do emissions now
  --- Emissions done!
  --- Do turbulence now
  AbsTol(           1 ) =   0.000000000000000E+000
  RelTol(           1 ) =   0.000000000000000E+000
 Forced exit from Rosenbrock due to the following error:
 --> Improper tolerance values
 T=  0.000000000000000E+000 and H=  0.000000000000000E+000

**Comment by Aosrain** [comment]
I found that ATOL and RTOL are set as following in fullchem_mod.F90, but not in carbon_mod.F90. Is it the problem and how to fix it?
    !%%%%% CONVERGENCE CRITERIA %%%%%

    ! Absolute tolerance
    ATOL      = 1e-2_dp

    ! Relative tolerance
    RTOL      = 0.5e-2_dp

**Comment by lizziel** [comment]
Hi @Aosrain, could you create a new issue at github.com/geoschem/geos-chem for the KPP convergence error? This issue is not GCHP-specific but more general for GEOS-Chem. I will close out this issue since the GCHP ExtData error is fixed.

**Comment by Aosrain** [comment]
Thank you @lizziel. I have created a new issue at  https://github.com/geoschem/geos-chem/issues/2341 .
