### ISSUE TITLE
Segmentation fault - invalid memory reference in mapl_capmod_MOD_run_model

### ISSUE THREAD

**Issue by tjansakoo** [geoschem/gchp#420]
### Your name

JANSAKOO Thanapat

### Your affiliation

Kyoto University

### What happened? What did you expect to happen?

I'm trying to run GCHP on our cluster computer. However, after submitting the job via SLURM, I encountered the following error message: "Segmentation fault - invalid memory reference in mapl_capmod_MOD_run_model."

I have already tried using a compiler option to build in debug mode with the following command:

cmake ../CodeDir -DRUNDIR=.. -DCMAKE_BUILD_TYPE=Debug

However, it was not successful.

### What are the steps to reproduce the bug?

-

### Please attach any relevant configuration and log files.

[gchp_log.txt](https://github.com/user-attachments/files/15911049/gchp_log.txt)
[gchp_sbatch.txt](https://github.com/user-attachments/files/15911050/gchp_sbatch.txt)
[gchp_sbatch.sh.1616427.txt](https://github.com/user-attachments/files/15911051/gchp_sbatch.sh.1616427.txt)

### What GCHP version were you using?

14.3.0

### What environment were you running GCHP on?

Local cluster

### What compiler and version were you using?

gcc 12.2.0

### What MPI library and version were you using?

OpenMpi 4.1.5

### Will you be addressing this bug yourself?

Yes, but I will need some help

**Comment by lizziel** [comment]
Hi @tjansakoo, the error traceback is as follows in your log:
```
#8  0x1eb30b7 in __mapl_capmod_MOD_run_model
	at /LARGE0/gr10502/individual/tjansakoo/Geos/rundirs/tmprun/gchp_fullchem_merra2/CodeDir/src/MAPL/gridcomps/Cap/MAPL_Cap.F90:287
```

Have you tried looking at the source code at this line (287) to see what the code is that is triggering the error? This may help figure out what the problem is. I also suggest posting your configuration files here. The run is failing very early which means there is likely something wrong in your run directory set up.

**Comment by tjansakoo** [comment]
Hi @lizziel ,

Thank you very much for your suggestion. I am pleased to inform you that I can now successfully run GCHP. To resolve the issue, I consulted with the administrator of my cluster computer to set up the environment properly and paid careful attention to the configuration files. I greatly appreciate your assistance.

Best regards,
