### ISSUE TITLE
GCHP Carbon and CO2 simulations

### ISSUE THREAD

**Issue by Aosrain** [geoschem/gchp#421]
### Your name

Longtao Wu

### Your affiliation

JPL

### Please provide a clear and concise description of your question or discussion topic.

I have some questions about using GCHP 14.4.0 as follows:
1. For the Carbon simulation, are restart files available at other resolutions? The file provided in the directory http://geoschemdata.wustl.edu/ExtData/GEOSCHEM_RESTARTS/v2023-01/ is only for c24.
2. For the CO2 simulation, does the CO2 simulation work in GCHP 14.4.0? If so, which restart file should I use?

**Comment by yantosca** [comment]
Thanks for writing @Aosrain.

1. We only provide a few example restart files.  However, you can use the `file_regrid.py` program in [GCPy](https://gcpy.readthedocs.io) to create a GCHP restart file from a GEOS-Chem Classic restart file.  You can create a c360 restart file with:

   ```bash
   $ python -m gcpy.file_regrid --filein ${prefix}.nc4         \
            --dim_format_in classic                            \
            --fileout GEOSChem.Restart.20190101_0000z.c24.nc4  \
            --cs_res_out 360                                   \
            --dim_format_out checkpoint

   $ rm -rf conservative_*.nc
   ```
2. The CO2 simulation in GCHP I think is not the same as the CO2 simulation in GEOS-Chem Classic or the GCHP carbon simulation.  I think it is only for inversions (@kbowman77 might know more).

**Comment by msulprizio** [comment]
Also tagging @hannahnesser so she can follow the discussion

**Comment by Aosrain** [comment]
Thank you.
