### ISSUE TITLE
Transporting species initialized in a gridded component outside GeosChem

### ISSUE THREAD

**Issue by ShreyaSharma2023** [geoschem/gchp#424]
### Your name

Shreya Sharma

### Your affiliation

MIT LAE

### Please provide a clear and concise description of your question or discussion topic.

I am trying to advect species which have been initialized outside geoschem in another gridded component for MAM. 
For more information, refer to https://github.com/ShreyaSharma2023/GCHP.git (branch: one-way)

The bundles ([species]_A_[mode], for eg, SU_A_AIT) have been made 'Friendly to dynamics'. I have also added the species in geoschem_config.yaml and to species_database.yml in the run directory. However, I don't seem to see any change in the results before and after doing these steps, which makes me think the species are not getting transported.

Is there another way to have these species transported in GCHP?

**Comment by lizziel** [comment]
Hi Shreya, I think I found the missing step for connecting declared friendlies to advection. We have [this code](https://github.com/ShreyaSharma2023/GCHP/blob/9daff9c19ef93b4dc40cbe7f5918a72454faf763/src/GCHP_GridComp/GCHP_GridCompMod.F90#L401-L407) in GCHP_GridCompMod.F90:
```
    ! AdvCore Tracers                                                                                                     
    !----------------                                                                                                     
    call ESMF_StateGet( GIM(ADV), 'TRADV', BUNDLE, RC=STATUS )
    _VERIFY(STATUS)

    call MAPL_GridCompGetFriendlies(GCS(CHEM), "DYNAMICS", BUNDLE, RC=STATUS )
    _VERIFY(STATUS)
```

It looks like you need to add one of these calls for each of the gridded components you want to connect to advection.

**Comment by ShreyaSharma2023** [comment]
Hi Lizzie
Thanks! Adding this code seems to work. I do get differences in the output now, and the log file also lists all the species in the bundle as being advected. 
I assume I do not need to add the individual species in geoschem_config.yaml and to species_database.yml now? Because I added only one species to them, but I see changes in the values of all species in the bundle.

**Comment by lizziel** [comment]
Correct. These species are part of a different gridded component so should not need to be in any of the GEOS-Chem configuration files. I'm glad it works!
