### ISSUE TITLE
ERROR: cannot find export DryPLEPut a one-line description here

### ISSUE THREAD

**Issue by helpyuan** [geoschem/gchp#427]
### Your name

liumy

### Your affiliation

CAMS

### Please provide a clear and concise description of your question or discussion topic.

I encountered the error '`ERROR: cannot find export DryPLE`' while running only CO2 under the GCHP-14.4.1 carbon module. How can I resolve this issue?

The following are the corresponding output files and configuration files.

[CAP.rc.txt](https://github.com/user-attachments/files/16235626/CAP.rc.txt)
[ExtData.rc.txt](https://github.com/user-attachments/files/16235627/ExtData.rc.txt)
[gchp.20190701_0000z.log.txt](https://github.com/user-attachments/files/16235628/gchp.20190701_0000z.log.txt)
[geoschem_config.yml.txt](https://github.com/user-attachments/files/16235630/geoschem_config.yml.txt)
[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/16235631/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/user-attachments/files/16235632/HISTORY.rc.txt)
[job.10443624.err.txt](https://github.com/user-attachments/files/16235633/job.10443624.err.txt)
[logfile.000000.out.txt](https://github.com/user-attachments/files/16235634/logfile.000000.out.txt)

**Comment by lizziel** [comment]
Hi @liumy, check that the file `src/GCHP_GridComp/FVdycoreCubed_GridComp/AdvCore_GridCompMod.F90` contains the following code:

```
     ! GCHP: dry pressure export to pass to GEOS-Chem
     call MAPL_AddExportSpec ( gc,                                  &
          SHORT_NAME = 'DryPLE',                                    &
          LONG_NAME  = 'dry_pressure_at_layer_edges',               &
          UNITS      = 'Pa'   ,                                     &
          PRECISION  = ESMF_KIND_R8,                                &
          DIMS       = MAPL_DimsHorzVert,                           &
          VLOCATION  = MAPL_VLocationEdge,               RC=STATUS  )
     VERIFY_(STATUS) 
```

Also post the log file `allPEs.log`. This is the MAPL log file (please make sure you read about debugging MAPL errors on the [GCHP debugging page on ReadTheDocs](https://gchp.readthedocs.io/en/stable/user-guide/debugging.html) to know what log files to look at).

**Comment by helpyuan** [comment]
Thanks @lizziel!

**Comment by lizziel** [comment]
@helpyuan, we you able to figure out what the issue was?

**Comment by helpyuan** [comment]
Hi @lizziel , as you pointed out, the file `src/GCHP_GridComp/FVdycoreCubed_GridComp/AdvCore_GridCompMod.F90` does not contain those contents. I just need to download the source code again.

**Comment by lizziel** [comment]
Okay, that makes sense. Thanks for following up!
