### ISSUE TITLE
GCHP run provides unreasonable CO2 values

### ISSUE THREAD

**Issue by kaysuselj** [geoschem/gchp#437]
### Your name

kay suselj

### Your affiliation

JPL

#### (Exp1): Ran out-of-the-box GCHP using single species CO2 on NASA pleiades for 1 month (as in https://github.com/geoschem/GCHP/issues/431)
- Starting date 20190101 
- used restart files provided to Longtao by lizziel: https://github.com/geoschem/GCHP/issues/431
 
 CO2 concentrations within the upper atmosphere exceed reasonable values. Try to understand what's wrong.
 
####  (Exp2): Redo the (Exp 1), but turn off dynamics+convection+chemistry in `geoschem_config.yml`. Under `operations:` set:
 ```
chemistry:
    activate: false
  convection:
    activate: false
  pbl_mixing:
     activate: false
     use_non_local_pbl: false
```

- What I expected: My understanding is that in Exp2, we prescribe surface fluxes of CO2; dynamics and chemistry is off. I expect CO2 concentrations in the first model level to be changing/increasing with time, in the rest of the atmosphere they would stay constant.
- What I see: The CO2 concentrations `SpeciesConcVV_CO2` at the highest model level (`level=1`; lev:positive = "down" ) are increasing with time, in the rest of the atmosphere, they are fairly constant. 

I am not sure, whether:
1. I misunderstand what is up and what is down (is level 1, with lev:positive = "down"  not the top of the atmosphere?).
2. There is a bug in assigning the levels for the `SpeciesConcVV_CO2`
3. Could there be some problem with my setting, is there a bug in GCHP in how levels are understood? It was a little surprising to see that CO2 concentration in (Exp1) are getting out of control in the uppermost model level.  

Any idea on how to deal with this would be appreciated. 

### What are the steps to reproduce the bug?

- run GCHP with single CO2 species for one month.
- took restart file from https://github.com/geoschem/GCHP/issues/431

### What GCHP version were you using?

GCHP 14.4.0

### What environment were you running GCHP on?

Other (please explain below)

### What compiler and version were you using?

NASA pleiades, ifort 19.1.3.304 20200925

### What MPI library and version were you using?

MPT: libxmpi.so 'HPE MPT 2.28 04/24/23 12:22:36-mraymond'

### Will you be addressing this bug yourself?

Yes, but I will need some help

**Comment by yantosca** [comment]
Thanks for writing @kaysuselj.  I think the GCHP diagnostic collections (except Emissions) are flipped so that level=1 is the surface and level=72 is the top of atmosphere.  @lizziel can confirm.

**Comment by lizziel** [comment]
Hi @kaysuselj, this issue is discussed in https://github.com/geoschem/GCHP/issues/21. MAPL currently always writes positive is down in exports, which is incorrect and needs to be addressed. The convention for GCHP diagnostics is all have level 1 as the surface with the exception of the emissions collection which is the opposite (there is another open issue about this on GitHub).

I am currently comparing GCHP and GC-Classic carbon results to sanity check the results. I am seeing discrepancies that need to be investigated. I suggest waiting before using the GCHP carbon simulation.

**Comment by kaysuselj** [comment]
Thanks for the quick response, @yantosca  and @lizziel .

**Comment by yantosca** [comment]
Thanks @kaysuselj.  I will close out this issue for now.  We will hopefully be able to resolve the issues in the GCHP carbon simulation quickly.

**Comment by lizziel** [comment]
I am reopening this issue so that users can see it is not yet resolved.

**Comment by msulprizio** [comment]
Please see the full, continuing discussion in #440
