### ISSUE TITLE
Error when running GCHP container v14.4.0 with Singularity

### ISSUE THREAD

**Issue by cora579** [geoschem/gchp#439]
### Your name

Coralina Hernández Trujillo

### Your affiliation

CIEMAT, Madrid, Spain

### Please provide a clear and concise description of your question or discussion topic.

I have been trying to run GCHP container (version **14.4.0**) with Singularity on Slurm as @mgarciavi mentioned in #438 . I think I'm been able to do the set up succesfully. The issue arise when I run the model, I get the following error message just after **srun** is called:

"./gchp: error while loading shared libraries: libnetcdf.so.19: cannot open shared object file: No such file or directory"

Besides the slurm output (slurm-1844748.txt) where you can see above error, I'm attaching the run script (lanza-gchp.batch_job.txt) with the bash script used to configure settings (setCommonRunSettings.txt). 

Because the error seems to be related to loading the internal environment of the container, I'm also attaching the internal_exec file (internal_exec.txt) and the .container_run.rc (container_run_rc.txt) in case it may help.

Thank you for your help!

[container_run_rc.txt](https://github.com/user-attachments/files/16804004/container_run_rc.txt)
[internal_exec.txt](https://github.com/user-attachments/files/16803935/internal_exec.txt)
[lanza-gchp.batch_job.txt](https://github.com/user-attachments/files/16803936/lanza-gchp.batch_job.txt)
[setCommonRunSettings.txt](https://github.com/user-attachments/files/16803937/setCommonRunSettings.txt)
[slurm-1844747.txt](https://github.com/user-attachments/files/16803938/slurm-1844747.txt)

**Comment by yantosca** [comment]
Tagging @yidant @lizziel

**Comment by lizziel** [comment]
@yidant, would you be able to look into this issue?

**Comment by yidant** [comment]
Hi @cora579, sorry that I didn't have a similar cluster environment right now to test this, but I can provide some of my thoughts. 

I checked in this container and found there's `libnetcdf.so.19` under this path `/opt/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.2.0/netcdf-c-4.9.2-nwa3dhld7f57eewtz2uji2iop4gra5wt/lib`. According to the error message, it is likely that the library path is not set up properly to include this path in the runtime environment. To resolve this, you need to source global environment file (/etc/bashrc) in the runtime environment. 

Could you please try adding this line to your internal_exec.txt before the line `cd /rundir` and try again:

. /etc/bashrc

This file should have contained all the environment settings for GCHP. Hope this helps!
