### ISSUE TITLE
[DISCUSSION] GCHP needs expanded CI or other automated test pipeline

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#44]
This discussion will pick up where issue https://github.com/geoschem/GCHPctm/issues/43 (formerly of GCHP repository) left off. GCHP 13.0.0 includes a continuous integration pipeline via Azure but currently only builds the model. It also only builds with a single configuration of compiler flags.

Having test runs on Azure is challenging due to the size of the GCHP input data but there may be work-arounds to get some simple form of testing implemented. @LiamBindle has also suggested outsourcing automated tests to his local cluster where the input data is available and memory/storage constraints are not an issue. @msulprizio is developing integration testing for GEOS-Chem which could also fulfill some of the GCHPctm automated testing needs.

This discussion is intended to be a forum for people to weigh in on GCHPctm testing needs and help develop a feasible plan to implement over the course of the GCHP 13 series.

**Comment by LiamBindle** [comment]
@msulprizio are your integration tests going to run on Azure? Or are they automated tests on Cannon?

**Comment by msulprizio** [comment]
They would run on Cannon. The first step would be for us to run them manually like we did with the unit tester, then we can think about how to automate it.

**Comment by LiamBindle** [comment]
The "Quick Build" pipeline--now "Quick Test"--includes a runtime test now (#60). It runs a small transport tracer simulation.

**Comment by lizziel** [comment]
Running short GCHP simulation tests is now included in GCHP integration testing. The small transport tracer simulation included in the CI pipeline needs more work. See also https://github.com/geoschem/MinimumStandaloneTransportTracer/issues/1.

**Comment by lizziel** [comment]
Aug 2021 updates:
- ifort is free now so we can add it to the CI
- the quick test updates from @LiamBindle are waiting in the queue pending run directory creation updates being worked on by @msulprizio 

Are there any other CI / automated test updates on the horizon, or can we close out this discussion once the above two updates are in, hopefully 13.3.

**Comment by LiamBindle** [comment]
Once those two items are complete I think we could close this out. At that point we'll have a pretty decent suite of CI tests.
