### ISSUE TITLE
GCHP run crashes almost immediately in MAPL_CapGridComp.F90

### ISSUE THREAD

**Issue by InterstellarPenguin** [geoschem/gchp#443]
### Your name

Linyang Guo

### Your affiliation

UCAS

### What happened? What did you expect to happen?

Hi, everyone!
There is an issue appeared while I'm going to run a carbon simulation. 

### What are the steps to reproduce the bug?

Just for now, i tried to run a 864-core 27-node 10-years GCHP simulation and it crashed immediately. I picked out the important part of the output.log:

### Please attach any relevant configuration and log files.

<img width="954" alt="image" src="https://github.com/user-attachments/assets/6249276c-a871-452c-82b0-6b8ef980088f">
<img width="850" alt="image" src="https://github.com/user-attachments/assets/85095a79-270c-49e1-87a7-10d076df0280">
I've seen a similiar issue that posted on git #8. But I still have no idea about how to fix it. Below is my environment set
[GCHP.intel23.txt](https://github.com/user-attachments/files/17097294/GCHP.intel23.txt)

### What GCHP version were you using?

14.4.3

### What environment were you running GCHP on?

Local cluster

### What compiler and version were you using?

ifort 2021.3.0

### What MPI library and version were you using?

Intel MPI 2021.3.0 

### Will you be addressing this bug yourself?

Yes

**Comment by lizziel** [comment]
Hi, thanks for reaching out about this. I see there are multiple prints of the same message about heartbeat. There should only be one. This makes me think there is a problem with MPI, maybe having to do with ESMF. This is also supported when looking at the MAPL code that the error message points to [here](https://github.com/geoschem/MAPL/blob/231d53cc0b14dc3275cac2867ddb9e15adbc8877/gridcomps/Cap/MAPL_CapGridComp.F90#L322-L324):
```
    call ESMF_VMGet(cap%vm, petcount=npes, mpicommunicator=comm, rc=status)
    _VERIFY(status)
     _ASSERT(CoresPerNode <= npes, 'something impossible happened')
```
Could you check that your ESMF build did not include 'mpiuni'? Also please post your GCHP log file here.

**Comment by InterstellarPenguin** [comment]
@lizziel Good to hear your reply, I've checked the root dir of ESMF, actually I found the setting ' -DESMF_COMM=mpiuni'.
![image](https://github.com/user-attachments/assets/f267cba9-cfce-41c2-ab57-bc8750339581)
Does it means that I should rebuild ESMF ? Btw, as the picture says, I don't have the permissions to edit the files under /public/software/.../esmf/, is it works to reinstall the esmf in my own dir? Here are my files relate to those issues. 
[GCHP.log](https://github.com/user-attachments/files/17107115/GCHP.log)

**Comment by InterstellarPenguin** [comment]
I've solved this issue by rewriting the env files and updating the ESMF module. Thanks again @lizziel

**Comment by lizziel** [comment]
Great, I am glad that worked. Setting `ESMF_COMM` to `mpiuni` prior to building ESMF makes ESMF bypass MPI and run on every processor. This is why there were duplicate messages in your log. From the ESMF docs:

> Alternatively, ESMF comes with a single-processor MPI-bypass library which is the default for Linux and Darwin systems. To force the use of this bypass library set ESMF_COMM equal to "mpiuni".

**Comment by Xinying331** [comment]
Hi,

Could you please share the steps you took to update the ESMF module and modify the environment files? I encountered the exact same issue and have already recompiled the ESMF package, ensuring that all ESMF_COMM settings point to OpenMPI. However, I’m still receiving the same error message. I'm attching my compile and install log file with this comment. I would greatly appreciate any guidance you can provide!  @lizziel @InterstellarPenguin @LiamBindle 

<img width="865" alt="Image" src="https://github.com/user-attachments/assets/52f81cc4-3e8d-4efd-83ed-b56acd09dd61" />

[compile.log](https://github.com/user-attachments/files/19019111/compile.log)

[install.log](https://github.com/user-attachments/files/19019112/install.log)

Thanks,
Xinying

**Comment by lizziel** [comment]
Hi @Xinying331, if ESMF_COMM is set to openmpi then I think you must be encountering a different problem. Please open a new github issue for this. Thanks!

**Comment by Xinying331** [comment]
Got it. Thank you Lizziel! @lizziel
