### ISSUE TITLE
GCHP 13.2.1 Simulation Issue — Abnormal Ozone Output

### ISSUE THREAD

**Issue by mmmjjj527** [geoschem/gchp#451]
### Your name

Mao Jia

### Your affiliation

CUHK

### Please provide a clear and concise description of your question or discussion topic.

 I am reaching out to seek your advice regarding an issue I encountered while running a simulation using GCHP version 13.2.1.

Specifically, I am trying to obtain simulated ozone results for the year 2015. The simulation is set up with the default restart file for July 2019, using the MEIC inventory for China, at a resolution of C90 with a stretch factor of 2. I initiated the run in July 2014, intending to use the period from July to December 2014 as spin-up time.

However, I am facing a puzzling problem: the spatial distribution and values for January to April 2015 appear to be completely incorrect, while the results for July to December 2014 and June to December 2015 seem reasonable. I have attached the monthly MDA8 O3 data I obtained from the raw results for your reference.

<img width="1025" alt="截屏2024-10-15 下午4 58 16" src="https://github.com/user-attachments/assets/664fb27c-fb2f-4007-9326-b5dcf42ef8bb">

<img width="1029" alt="截屏2024-10-15 下午4 59 42" src="https://github.com/user-attachments/assets/29cec64d-42fe-494f-bd55-b363dcc13695">

<img width="1031" alt="截屏2024-10-15 下午5 00 09" src="https://github.com/user-attachments/assets/b044f70f-c9fb-4c94-87d5-a5eed4914489">

This issue doesn't appear to stem from the MEIC inventory, as the results for other months are plausible. Therefore, I am quite confused by this anomaly and was wondering if you have encountered a similar problem or if you might have any suggestions on how to resolve this.

I would greatly appreciate your insights!

[HEMCO_Config.rc.txt](https://github.com/user-attachments/files/17375704/HEMCO_Config.rc.txt)
[HISTORY.rc.txt](https://github.com/user-attachments/files/17375696/HISTORY.rc.txt)
[runConfig.sh.txt](https://github.com/user-attachments/files/17375697/runConfig.sh.txt)

**Comment by yantosca** [comment]
Thanks for writing @mmmjjj527.  GCHP 13.2.1 is no longer supported, as there have been many bug fixes and improvements since then.  We would recommend updating to the most recent version.

**Comment by mmmjjj527** [comment]
Thanks! Will try to move to a recent version.
&nbsp;


maojia527
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bob ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 晚上10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [geoschem/GCHP] GCHP 13.2.1 Simulation Issue — Abnormal Ozone Output (Issue #451)














 
Thanks for writing @mmmjjj527.  GCHP 13.2.1 is no longer supported, as there have been many bug fixes and improvements since then.  We would recommend updating to the most recent version.

**Comment by yantosca** [comment]
Thanks @mmmjjj527.  I'll close out this issue.
