### ISSUE TITLE
Unreasonable CO2 value in GCHP-14.5.0-rc.0

### ISSUE THREAD

**Issue by InterstellarPenguin** [geoschem/gchp#452]
### Your name

Guo LinYang 

### Your affiliation

UCAS

### What happened? What did you expect to happen?

Hi, I've noticed that GCHP 14.5.0-rc.0 was  published on the git, so I wanna give it a try. In the simulation I set by defualt with the restartfile in #431 , the result still remain strange, I'm not sure what is wrong. I post a part of the allPEs.log and other config files below.

### What are the steps to reproduce the bug?

![image](https://github.com/user-attachments/assets/d84cbd1a-113f-4312-aace-bc74fb65f7ec)
![image](https://github.com/user-attachments/assets/2fdd990a-eb40-41e3-a3ad-1875e005ed98)

### Please attach any relevant configuration and log files.

[ExtData.txt](https://github.com/user-attachments/files/17380454/ExtData.txt)
[HEMCO_Config.txt](https://github.com/user-attachments/files/17380455/HEMCO_Config.txt)
[HISTORY.txt](https://github.com/user-attachments/files/17380458/HISTORY.txt)
[logging.txt](https://github.com/user-attachments/files/17380459/logging.txt)
[allPEs.txt](https://github.com/user-attachments/files/17380556/allPEs.txt)
[test.log.txt](https://github.com/user-attachments/files/17380599/test.log.txt)

### What GCHP version were you using?

14.5.0-rc.0

### What environment were you running GCHP on?

Local cluster

### What compiler and version were you using?

ifort 2021.3.0

### What MPI library and version were you using?

Intel MPI 2021.3.0 

### Will you be addressing this bug yourself?

Yes

**Comment by lizziel** [comment]
14.5.0 is not validated for the GCHP carbon simulation. See comments in https://github.com/geoschem/GCHP/issues/440 for timeline and suggestions if you wish to debug yourself.

**Comment by InterstellarPenguin** [comment]
@lizziel Thank you for the information. I was wondering if previous versions, like 13.0.0, are available for GCHP carbon simulations. In #440, I noticed that the bug primarily affects carbon simulations, not full-chemistry simulations. Is that correct?

**Comment by lizziel** [comment]
Carbon simulations for GCHP are not available prior to 14.4. There is a CO2 w/ fluxes option but this was developed for use with the GCHP adjoint. We will be retiring that simulation once the GCHP carbon fixes are released.

**Comment by lizziel** [comment]
Yes, the carbon bugs do not affect full chemistry. The full chemistry is thoroughly vetted every release through benchmarking.

**Comment by InterstellarPenguin** [comment]
I'm glad to hear this, thank you for your help again, @lizziel! Close this issue.
