### ISSUE TITLE
GCHP stopped with no ERROR when starting caculation with more than 2 nodes

### ISSUE THREAD

**Issue by InterstellarPenguin** [geoschem/gchp#453]
### Your name

Guo LinYang 

### Your affiliation

UCAS

### What happened? What did you expect to happen?

Hi, when I'm going to run a carbon/full-chem simulation with more than 2 nodes, the simulation stopped with no error. I wondered if this issue might be caused by my local cluster, so I reached out to the backend administrators. They confirmed that there were no issues with the node scheduling for my experiment, so now I suspect it might be a problem with my configuration. Here are my config files. BTW, the simulation runs smoothly with no more than 2 nodes.

### What are the steps to reproduce the bug?

I named the job file as gchp.job (the content of gchp.txt is shown below), and I submit the job using the command ./SubRunScript.txt. The files are as follows:
[gchp.txt](https://github.com/user-attachments/files/17456112/gchp.txt)
[SubRunScript.txt](https://github.com/user-attachments/files/17456115/SubRunScript.txt)

Is there anything I might be overlooking in my process to correctly submit the job via sbatch?

[full-chem.log](https://github.com/user-attachments/files/17456204/full-chem.log)
[setCommonRunSettings.txt](https://github.com/user-attachments/files/17456207/setCommonRunSettings.txt)

### What GCHP version were you using?

14.4.2

### What environment were you running GCHP on?

Local cluster

### What compiler and version were you using?

ifort 2021.3.0

### What MPI library and version were you using?

Intel MPI 2021.3.0 

### Will you be addressing this bug yourself?

Yes

**Comment by lizziel** [comment]
Hi @InterstellarPenguin, have you tried checking the `allPEs.log` file? You can also enable more MAPL prints to that log by updating `logging.yml` (see GCHP ReadTheDocs for instructions). I also notice that your run script deviates from our recommended run script, particularly exclusion of renaming output restart files. Make sure you do not have restart file `gcchem_internal_checkpoint` in your `Restarts` directory.

**Comment by InterstellarPenguin** [comment]
Thanks for your reply. There are no restart files in the Restarts directory because this is a new run directory. In the previous experiment, I checked if the gcchem_internal_checkpoint still exists.
![image](https://github.com/user-attachments/assets/02a84c60-a2c8-4fd7-86fd-9ab05c669a42)

In the allPEs.log I've noticed there are no bugs about reading input data, so I wonder if the bug might be coming from an issue in the setCommonRunSetting.sh script. BTW, when I turn to DEBUG in logging.yml instead of WARNING, the run stopped both in 2 nodes test and 6 nodes test.
[allPEs.txt](https://github.com/user-attachments/files/17463242/allPEs.txt)

**Comment by lizziel** [comment]
The end of allPEs.log shows this:

```
0000: CAP.EXTDATA: DEBUG: prefetch loop:  126 of 1226 ./MetDir/2015/01/MERRA2.20150101.CN.2x25.nc4
0000: CAP.EXTDATA: DEBUG: prefetch loop:  127 of 1226 ./MetDir/2015/01/MERRA2.20150101.CN.2x25.nc4
0000: CAP.EXTDATA: DEBUG: prefetch loop:  128 of 1226 ./MetDir/2015/01/MERRA2.20150101.CN.2x25.nc4
0000: CAP.EXTDATA: DEBUG: prefetch loop:  129 of 1226 ./MetDir/2015/01/MERRA2.20150101.CN.2x25.nc4
0000: CAP.EXTDATA: DEBUG: prefetch loop:  130 of 1226 ./HcoDir/OFFLINE_LIGHTNING/v2020-03/MERRA2/2001/FLASH_CTH_MERRA2_0.5x0.625_2001_01.nc4
```

So it appears to be hanging at or after variable 130 during prefetch, which is the regridding step of MAPL. Is your run timing out or is it actually stopping, e.g. the job ending. Could you do another run where you apply "tail --follow allPEs.log" to see the file being written real time? I am wondering if when it gets to the step of the prefetch loop whether you see it going very slowly, or increasingly slowly until it suddently stops.

Typically for issues like this we suspect the file system. What type of file system are you using? Is it optimized for I/O? I can also run this by the MAPl developers at NASA GMAO tomorrow since I am meeting with them.

**Comment by InterstellarPenguin** [comment]
The allPEs.log is the same as the last one, and my terminal cannot display all the content with the real time. The earliest lines are around 00:02:00. The run will continue if I don't use the scancel command. Here are my file system list.
![image](https://github.com/user-attachments/assets/ce1d8aeb-c103-4947-a5d2-376f9cea8579)
[allPEs.txt.txt](https://github.com/user-attachments/files/17463872/allPEs.txt.txt)

**Comment by InterstellarPenguin** [comment]
I've tested with nodes ranging from 1 to 5, and the issue occurs when using more than 4 nodes. The total number of cores far below the maximum limit of 864 cores in a c48 simulation.
```
TOTAL_CORES = 60*nodes
NUM_NODES = nodes
NUM_CORES_PER_NODE = 60
```

**Comment by lizziel** [comment]
To be clear about the issue could you confirm the following?
1. Running with 1 node is successful
2. Running with 2 nodes is successful
3. Running 3+ nodes fails with consistent hang in prefetch at variable 130

**Comment by InterstellarPenguin** [comment]
I confirmed the issue again:

1. Running with 1 node is successful
2. Running with 2 node is successful which I'm using for my previous simulation
3. Running 5+ nodes fails with consistent hang in prefetch at variable 130

**Comment by lizziel** [comment]
I believe this issue is related to MPI and/or libfabric. You could try using OpenMPI instead of Intel MPI to see if that fixes the issue.

**Comment by InterstellarPenguin** [comment]
Thank for your patience @lizziel, I'm in the process of switching to OpenMPI, which might take some time to complete.

**Comment by InterstellarPenguin** [comment]
I'm back now, with the change from IntelMPI to OpenMPI, the simulation runs smoothly.

**Comment by lizziel** [comment]
Thanks for following up and I'm glad it works now.
