### ISSUE TITLE
Does GCHP support ARM architecture?

### ISSUE THREAD

**Issue by yuanjianz** [geoschem/gchp#460]
### Your name

Yuanjian Zhang

### Your affiliation

WashU

### Please provide a clear and concise description of your question or discussion topic.

I am well-aware that on Compute1, Cannon and Discover, the compute nodes are currently x86_64. But I see some HPC nodes (Hpc7g) for AWS EC2 instances are using AWS Graviton processors, which is under arm64 architecture. Is it possible for GCHP to work under arm64?

Tagging @yidant @yantosca

**Comment by yantosca** [comment]
Thanks @yuanjianz.  So this would depend on wither ARM processors are supported by (1) ESMF and (2) MAPL.  I think ARM may be supported by ESMF but not sure about MAPL.  Maybe MAPL 3.0.0 might have this feature.  Tagging @lizziel @tclune @bena-nasa

**Comment by bena-nasa** [comment]
We have built and run the full GEOS model (albeit at extremely low resolution) on Apple silicon laptops with gcc/gfortran/openmpi. So if the system has the compilers there is no reason another ARM system couldn't in principle build the software stack (ESMF, NetCDF, MAPL, etc...) and GCHP...

**Comment by yuanjianz** [comment]
@bena-nasa @yantosca, thanks for the info. I would give it a shot when I got chance.
