### ISSUE TITLE
[FEATURE REQUEST] Debug printing during regridding portion of ExtData

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCHP#53]
The MAPL debug print option gives lots of information during the information collection stage of MAPL ExtData, such as parsing Extdata.rc and finding files with the right times. However, the regridding part of ExtData is very murky and GCHP seemlingly stalls for a while without any printing at all during this phase. If the run times out due to an issue not caught with error handling then it is hard to know where it went wrong.

This feature request is really for GEOS-ESM/MAPL but we can put it in with GCHP in mind and then submit it as a PR to go to the upstream MAPL.

**Comment by LiamBindle** [comment]
For house keeping, I think we could lump this into #101.

**Comment by lizziel** [comment]
Sounds good to me!
