### ISSUE TITLE
[QUESTION] Daily diagnostics with Monthly_Diag=1

### ISSUE THREAD

**Issue by luxiao-atchem** [geoschem/GCHP#70]
# Ask a question about GCHP:

 

Hi all,

I have a question about the diagnostic frequency in GCHP. Is there an in hand option to output, say, daily ozone concentration, while still keep the monthly output for other diagnostics in the multi-run mode with Monthly_Diag=1?

Thanks,
Xiao

**Comment by LiamBindle** [comment]
Hi Xiao, thanks for writing.

You could accomplish this by adding a new collection to HISTORY.rc. For example, here is a custom collection with daily O3, NO, and NO2, CO

```
  MyDailyCollection.template:   '%y4%m2%d2_%h2%n2z.nc4',
  MyDailyCollection.format:     'CFIO',
  MyDailyCollection.frequency:  240000
  MyDailyCollection.duration:   240000
  MyDailyCollection.mode:       'time-averaged'
  MyDailyCollection.fields:     'SpeciesConc_O3          ', 'GCHPchem',
                                'SpeciesConc_NO          ', 'GCHPchem',
                                'SpeciesConc_NO2         ', 'GCHPchem',
                                'SpeciesConc_CO          ', 'GCHPchem',
::
```
(**Note**: the `::` terminates the collection.)

Then, you'll just need to add `"MyDailyCollection"` to the list of `COLLECTIONS:` (near the top of HISTORY.rc). E.g.:
```
COLLECTIONS: 'AerosolMass',
             'Aerosols',
             'Budget',
             #'CloudConvFlux',
             #'ConcAboveSfc',
             'ConcAfterChem',
             'DryDep',
             'Emissions',
             'JValues',
             'Metrics',
             'KppDiags',
             'LevelEdgeDiags',
             'ProdLoss',
             #'RRTMG',
             'SpeciesConc',
             'StateChm',
             'StateMet',
             #'WetLossConv',
             #'WetLossLS',
             'MyDailyCollection',
::
```
Let me know if you have any questions,
-Liam

**Comment by luxiao-atchem** [comment]
Thanks Liam for the quick response. I was thinking even though the new collection would be overwritten by the monthly frequency but now I realize that it wouldn’t. The question can be closed.
