### ISSUE TITLE
[QUESTION] How to change default MET path for MERRA2 2x25, GCHP v 12.9.3 / 13

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#81]
Hello, 
I am using GCHP (version 12.9.3 and now trying to switch to v.13) with c48 resolution. After compiling, the default MET path points to MERRA2 with native resolution (0.5x0.625). I am wondering how I can change this path to point to MERRA2 2x2.5. 

I am not sure if I can specify the MERRA2 relosution before compaling (probably defining the grid when using cmake) or after creating the run directory (changing manually the path in Extdata.rc)

I would appreciate it if you could give me some additional information for my issue. 
Thank you in advance, 
Maria

**Comment by joeylamcy** [comment]
I have a similar situation (GCHP with MERRA-2 2x2.5) and I just followed the instructions on the [geos-chem wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Running_GCHP:_Configuration_v12#Inputs) to change the MET path after creating the run directory. It works for both v12.9.3 and v13.

**Comment by mtsivlidou** [comment]
Thanks a lot!
