### ISSUE TITLE
[QUESTION] How to include/exclude UCX in GCHP full chemistry ?

### ISSUE THREAD

**Issue by mtsivlidou** [geoschem/GCHP#82]
Hello, 
I am using GCHP v 12.9.3 and just started with 13. 
I would like to create two simulations; one including stratsophere UCX and another that does not. From my understanding, the standard fullchemistry run includes UCX by default. 
In order to exclude UCX, I modified the chemistry menu in the input.geos: 

%%% CHEMISTRY MENU %%%  :
Turn on Chemistry?      : T
Use linear. strat. chem?: F
 => Use Linoz for O3?   : T
Use UCX strat. chem?    : F
Active strat. H2O?      : F
Overhead O3 for FAST-JX :---
 => Online O3 from model: T
 => O3 from met fields  : T
 => TOMS/SBUV O3        : F
Gamma HO2               : 0.2

Could you please confirm that this is the way to include and exclude UCX. 
Thank you in advance, 
Maria Tsivlidou

**Comment by msulprizio** [comment]
This is included as an option in GEOS-Chem Classic that can automatically be handled for you by `createRunDir.sh` script. We could add this in GCHP's `createRunDir.sh` script if there is demand for non-UCX simulations (i.e. chemistry only up to the tropopause) in GCHP. 

Essentially, we recommend creating a separate run directory for your run excluding UCX. Then you will need to change the switches indicated below in the code taken from GEOS-Chem Classic's `createRunDir.sh`.

```
#!/bin/bash

#=============================================================================
#### Define function to replace values in config files
#=============================================================================
replace_colon_sep_val() {
    KEY=$1
    VALUE=$2
    FILE=$3
    #printf '%-30s : %-20s %-20s\n' "${KEY//\\}" "${VALUE}" "${FILE}"

    # replace value in line starting with 'whitespace + key + whitespace + : +
    # whitespace + value' where whitespace is variable length including none
    sed -i -e "s|^\([\t ]*${KEY}[\t ]*:[\t ]*\).*|\1${VALUE}|" ${FILE}
}

#=============================================================================
# Modify input files for troposphere-only chemistry grids
#=============================================================================
if [[ "x${chemgrid}" == "xtrop_only" ]]; then
    replace_colon_sep_val "=> Set init. strat. H2O"  F input.geos
    replace_colon_sep_val "Settle strat. aerosols"   F input.geos
    replace_colon_sep_val "Online PSC AEROSOLS"      F input.geos
    replace_colon_sep_val "Perform PSC het. chem.?"  F input.geos
    replace_colon_sep_val "Calc. strat. aero. OD?"   F input.geos
    replace_colon_sep_val "Use UCX strat. chem?"     F input.geos
    replace_colon_sep_val "Active strat. H2O?"       F input.geos
    replace_colon_sep_val "--> STATE_PSC"        false HEMCO_Config.rc
    replace_colon_sep_val "--> GMI_PROD_LOSS"    false HEMCO_Config.rc
    replace_colon_sep_val "--> UCX_PROD_LOSS"     true HEMCO_Config.rc
    sed -i -e "s|'Chem_StatePSC|#'Chem_StatePSC|"      HISTORY.rc
fi
```

**Comment by sdeastham** [comment]
I should note - if you're using the reduced vertical resolution with linearized stratospheric chemistry, I'm not sure what "turning off" the UCX would do or accomplish. My understanding (please correct me if I'm wrong on this @msulprizio !) is that the chemical mechanism is not made any simpler, and the extra processes in the stratosphere should (?) already be essentially disabled. It would be interesting to see, for sure!

**Comment by msulprizio** [comment]
Correct @seastham. The instructions I provided above assume a user is sticking with the 72-level vertical grid. I'm not sure if anyone has tried running with reduced vertical resolution (i.e. 47 levels) in GCHP -- it's my understanding that still is not recommended.

**Comment by sdeastham** [comment]
That's fair. In theory there's no reason that 47 levels wouldn't work in GCHP (or rather, would work any worse than it does in GC-Classic), but it would require some potentially-unpleasant plumbing work. Thanks for the clarification!

**Comment by mtsivlidou** [comment]
Hello, 
Thank you for your answers. 
How can I check which tropospheric chemistry scheme and stratospheric chemistry scheme is used in GCHP v 12.9.3 standard simulation? I was trying to find this information in input.geos but nothing was specified.

Thank you in advance, 
Maria

**Comment by yantosca** [comment]
Hi @mtsivlidou.  By default the standard simulation includes the UCX chemistry mechanism with the simpleSOA option.
