### ISSUE TITLE
[BUG/ISSUE] Intel 2021 compilers/MPI/OneAPI might require CMake >= 3.19

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#85]
### Description of the problem
The recent Intel compilers and Intel MPI (2021.1.2 in our case, with OneAPI) might require a very recent version of CMake. Initially we tried Intel 2021.1.2 with CMake 3.17.5, but got this error during the `Find MPI` step:

``` 
CMake Error in /scratch1/fs1/rvmartin/bs6/liam.bindle/QA-setup/build/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path
    "/scratch1/fs1/rvmartin/bs6/liam.bindle/QA-setup/GCHP/'/opt/intel/oneapi/mpi/latest/include'"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not
  provide.
```

Note the weird `INTERFACE_INCLUDE_DIRECTORIES` path: ` "/scratch1/fs1/rvmartin/bs6/liam.bindle/QA-setup/GCHP/'/opt/intel/oneapi/mpi/latest/include'"` (it should be `/opt/intel/oneapi/mpi/latest/include`). The import target for MPI is provided by Intel & CMake.

### The solution
Upgrade CMake. In our case, we upgraded to 3.19.4 and that fixed the issue. This only affects users that encounter the error I showed above. 

### GEOS-Chem version
Affects GEOS-Chem (GCHP and GCClassic) versions 13.0 and higher because they use CMake. 

### Software versions
- Compilers (Intel or GNU, and version): Intel 2021.1.2 (with OneAPI)
- NetCDF version: n/a
- MPI version: Intel MPI 2021.1.2 (with OneAPI)
- ESMF version: n/a

### Notes
Thanks @sleongmgi for identifying the error and fix.

**Comment by LiamBindle** [comment]
@mathomp4 Not sure if you've ran into this, but I thought I would pass on the fyi!

**Comment by mathomp4** [comment]
@LiamBindle Yes. I move `GEOSenv` at NCCS to use CMake 3.19.3 because of Intel oneAPI 😄

**Comment by LiamBindle** [comment]
@mathomp4 Good to know. Thanks!
