### ISSUE TITLE
[BUG/ISSUE] Segfault with Intel 2021.1 in gFTL

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#87]
### Description of the problem
With Intel 2021.1 we get a segfault in gFTL. To use Intel 2021 we just need to pull in the gFTL upstream (`src/gFTL-shared`). 

### The solution
Pull in upstream gFTL. 

### GEOS-Chem version
GCHP version 13.0

### Software versions
- Compilers (Intel or GNU, and version): Intel 2021.1.2
- NetCDF version: n/a
- MPI version: n/a
- ESMF version: n/a

### Related issues
- https://github.com/Goddard-Fortran-Ecosystem/gFTL/issues/119

**Comment by LiamBindle** [comment]
@yantosca @msulprizio @lizziel @WilliamDowns I lean towards including this in 13.1---what do you think? 

I think it would be safe in 13.0, but it just seems too close. I can create a hotfix branch for it in the next couple days&mdash;then any users that want to use Intel 2021.1 with GCHP v13 could checkout that branch.

**Comment by yantosca** [comment]
We can issue a 13.0.1 patch version for this.  That would be safest.

**Comment by lizziel** [comment]
The gchp/main branch of gftl-shared is now at v1.2.0. Updating this and other libraries will be part of 13.1.
