### ISSUE TITLE
Docker option for GCHP

### ISSUE THREAD

**Issue by Rob-Fletcher** [geoschem/GCHP#89]
I would like to be able to run GCHP but I need to do so in a docker container. I see that there is a repo with dockerfiles at https://github.com/geoschem/geos-chem-docker but these seem to be very out of date. Are there any plans to provide dockerfiles for GCHP v13?

**Comment by LiamBindle** [comment]
Hi @Rob-Fletcher, thanks for opening this question. We're in the early stages of supporting Docker. Currently we have a release pipleine that automatically builds/pushes a container with GCHP to DockerHub. You can find that container here: https://hub.docker.com/r/geoschem/gchp. Here's an example of using 

```console
$ docker run -it geoschem/gchp:13.0.0-beta.1-13-g924e47f
root@bb9c0d8fdf13:/# wget https://github.com/geoschem/MinimumStandaloneTransportTracer/archive/1.0.0.zip
root@bb9c0d8fdf13:/# unzip 1.0.0.zip
root@bb9c0d8fdf13:/# cd MinimumStandaloneTransportTracer-1.0.0/
root@bb9c0d8fdf13:/MinimumStandaloneTransportTracer-1.0.0# export OMPI_MCA_btl_vader_single_copy_mechanism=none
root@bb9c0d8fdf13:/MinimumStandaloneTransportTracer-1.0.0# mpirun --allow-run-as-root -np 6 gchp
      MAPL: No configure file specified for logging layer.  Using defaults.
     SHMEM: NumCores per Node = 6
     SHMEM: NumNodes in use   = 1
     SHMEM: Total PEs         = 6
     SHMEM: NumNodes in use  = 1
 Integer*4 Resource Parameter: HEARTBEAT_DT:600
 NOT using buffer I/O for file: cap_restart
 Character Resource Parameter: ROOT_CF:GCHP.rc
 Character Resource Parameter: ROOT_NAME:GCHP
 Character Resource Parameter: HIST_CF:HISTORY.rc
 Character Resource Parameter: MAPL_ENABLE_TIMERS:YES
 Character Resource Parameter: MAPL_ENABLE_MEMUTILS:YES

 ======================
 Contents of  CollList
... <lots more output> ...
```

That's just a quick demo for illustration purposes. Note that the `OMPI_MCA_btl_vader_single_copy_mechanism` is important to avoid a bunch of benign read errors. (note: in practice you wouldn't want to use the `--allow-run-as-root` option either, but hopefully this illustrates its usage).

The dockerfile that builds it is [here](https://github.com/geoschem/GCHP/blob/main/.ci-pipelines/release.dockerfile). Note that the top-level of the GCHP source code should be your working directory if you want to build it yourself.

Any and all suggestions, tweaks, PRs related to improving our Docker support would be greatly appreciated!

**Comment by LiamBindle** [comment]
In practice, I suspect this container is suitable for simulations up to ~500 cores (good enough for C180 global, and very fine stretched-grid simulations). Our default base image doesn't include mellanox drivers for Infiniband though, so if you would like to run on >500 cores (where Infiniband becomes very important), you might need to build your own base image. 

We aren't sure of a good way to support Docker with the Infiniband drivers. IIUC, the Mellanox drivers need to have matching major and minor versions (in the container, and on the host system). I supose the "proper" way to do it would be providing images per driver version, but at this time, I don't think we have the capacity to take that on.

**Comment by Rob-Fletcher** [comment]
@LiamBindle This is great news thank you! Im in a bit of a strange situation where I need to try to get this running in a kubernetes environment. I think its fine to start with running on just a few cores, but my hope is that eventually I can get it to run distrubuted across several containers either by splitting up the simulation (maybe geographically?) or trying to get the mpi to work across kubernetes pods. Ill take a look at what you linked and try it out. If I get anything interesting working I will definitely let you know.

Thanks again.

**Comment by LiamBindle** [comment]
Cool! That sounds interesting! I'm not familiar with Kubernetes (beyond general concepts), but I'd definitely be interested in your findings. Feel free to ping me or open issues here for technical support.

That all should be doable. The parallel decomposition in GCHP is geographic chunking&mdash;essentially each core gets a chunk of the globe.

Here at WashU we run GCHP in Docker containers in multinode instances (up to ~1000 cores). Similarly, @WilliamDowns is working on running GCHP in multinode instances on AWS, and I'm sure he has some valuable insight. 

In terms of resources for getting started, reproducing the example I showed above is a good first step. You might encounter an issue where the environment isn't loaded when the container starts. If this happens, you might need to `source /init.rc`. Also note that you need to manually delete `cap_restart` and `gcchem*` in between runs (as explained in the Youtube tutorial, and on ReadTheDocs). 

Once you have that running, a good next step would be creating a full-fledged run directory. You could following along with this [Youtube tutorial](https://www.youtube.com/watch?v=K6frcfCjpds)&mdash;it's mostly the same. The `createRunDir.sh` script should be available in the `$PATH`, but if you run into problems, you can download the source code and run the script in the `run/` subdirectory. For this you will also need to download some input data. There are some basic instruction for that [here](https://gchp.readthedocs.io/en/latest/user-guide/getting-input-data.html).

Let me know if you run into any issues, or if you have questions.

**Comment by Rob-Fletcher** [comment]
Hi @LiamBindle, I tried running your example above but it doesnt seem that mpirun is in the path anywhere. 
```bash
root@51be020f743a:/# mpirun --allow-run-as-root -np 6 gchp
bash: mpirun: command not found
```
Do you know where the binary is installed to? Or do you have a dockerfile for the base container you are using in this one?
