### ISSUE TITLE
[QUESTION] How do I add an export to a grid comp?

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCHP#95]
I'm a bit confused what I'm doing wrong. I'm trying to add a new export to the Env grid comp called "MFZr8" (for vertical mass flux). I've added the `MAPL_AddExportSpec()` and then got a pointer with `MAPL_GetPointer()`, but as soon as I try to assign a values to the array I get a segfault. 

Here's what I added to `GCHPctmEnv_GridCompMod.F90`:

```fortran
subroutine SetServices ( GC, RC )
    ...
    call MAPL_AddExportSpec ( gc,                                      &
        SHORT_NAME = 'MFZr8',                                          &
        LONG_NAME  = 'pressure_weighted_accumulated_upward_mass_flux', &
        UNITS      = 'Pa m+2 s-1',                                     &
        PRECISION  = ESMF_KIND_R8,                                     &
        DIMS       = MAPL_DimsHorzVert,                                &
        VLOCATION  = MAPL_VLocationEdge,             RC=STATUS  )
        _VERIFY(STATUS)
    ...
subroutine Run ( GC, IMPORT, EXPORT, CLOCK, RC )
    ...
    real(r8), pointer, dimension(:,:,:) ::     MFZr8=> null()
    ...
    call MAPL_GetPointer ( EXPORT, MFZr8, 'MFZr8', RC=STATUS )
    _VERIFY(STATUS)
    MFZr8(:,:,:) = 0.0d0  ! <---- Segfault happens here.
    call fv_getVerticalMassFlux(MFXr8, MFYr8, MFZr8, dt)
```

@lizziel @sdeastham (or anyone else) Do you see what's wrong here? 

(posting this here so others might come across it in the future)

**Comment by sdeastham** [comment]
On very brief comparison to other exports in AdvCore, two thoughts:

1. Are you sure that you want to assign `MFZr8 => null()` in the variable declaration? That might be doing something funky (I think this will assign it the `SAVE` attribute).
2. You may need to give the argument `ALLOC=.TRUE.` when calling `MAPL_GetPointer`. Not sure exactly what it does, mind..

**Comment by LiamBindle** [comment]
Thanks Seb. I'm looking into those.

**Comment by LiamBindle** [comment]
Thanks Seb, the `ALLOC=.TRUE.` keyword ended up being what I needed.

For future reference, here is an example of a PR adding a new export to a grid comp: https://github.com/geoschem/GCHP/pull/96.

**Comment by lizziel** [comment]
Could you give more info on why you ended up needing this? We generally don't need to do this, and I want to make sure this is not introducing a memory leak. i.e. allocation without deallocation.

I wonder if the code would work without `ALLOC` if you allocate a local array, assign it zero, pass it to the subroutine, then assign the result to the local pointer, and deallocate at the end. An example would be `UCr8` in `GCHPctmEnv_GridCompMod.F90`. If it works, I think that method is preferable since there is precedent for it. Otherwise we just need to make sure using `ALLOC` doesn't do unexpected things. And if it doesn't, it raises the question on if we should be using it elsewhere rather than pass array temporaries.

**Comment by LiamBindle** [comment]
I'm actually not sure yet, but I agree we should figure that out. That's one of the reasons I marked #96 WIP.

Thanks for reopening---that's a good call.

I can ask about this on Friday during the MAPL telecon. So far, all I know is that the pointer returned by `MAPL_GetPointer()` wasn't associated, and I had to add the `ALLOC` kwarg to get it to be associated.

**Comment by LiamBindle** [comment]
@bena-nasa @atrayano @tclune Here is the HISTORY collection that I was using 

```
COLLECTIONS: 'VertDiagnEdges',
             'VertDiagnCenters',
::
  VertDiagnEdges.template:         '%y4%m2%d2_%h2%n2z.nc4',
  VertDiagnEdges.format:           'CFIO',
  VertDiagnEdges.frequency:        010000
  VertDiagnEdges.duration:         010000
  VertDiagnEdges.mode:             'time-averaged'
  VertDiagnEdges.fields:           'UpwardsMassFlux                ', 'GCHPctmEnv',
                                   'Met_PS1DRY         ', 'GIGCchem',
                                   'Met_PS1WET         ', 'GIGCchem',
::
```

**Comment by bena-nasa** [comment]
That's why it is not allocated. You are not outputting "MFZr8" in that History collection. If history does not ask for it or it is not nameed in a connectivity, the export will not be automatically allocated

If you want this to be always allocated you must add the alloc=.true. argument to getpointer

**Comment by lizziel** [comment]
For performance I think the calculation should be in an if associated since no need to allocate and do the computation if not outputting the diagnostic. 

```
subroutine SetServices ( GC, RC )
    ...
    call MAPL_AddExportSpec ( gc,                                      &
        SHORT_NAME = 'UpwardsMassFlux',                                          &
        LONG_NAME  = 'pressure_weighted_accumulated_upward_mass_flux', &
        UNITS      = 'Pa m+2 s-1',                                     &
        PRECISION  = ESMF_KIND_R8,                                     &
        DIMS       = MAPL_DimsHorzVert,                                &
        VLOCATION  = MAPL_VLocationEdge,             RC=STATUS  )
        _VERIFY(STATUS)
    ...
subroutine Run ( GC, IMPORT, EXPORT, CLOCK, RC )
    ...
    real(r8), pointer, dimension(:,:,:) ::     MFZr8=> null()
    ...
    call MAPL_GetPointer ( EXPORT, MFZr8, 'UpwardsMassFlux', RC=STATUS )
    _VERIFY(STATUS)
    if associated( MFZr8 ) then
       MFZr8(:,:,:) = 0.0d0
       call fv_getVerticalMassFlux(MFXr8, MFYr8, MFZr8, dt)
    endif
```

**Comment by LiamBindle** [comment]
@bena-nasa Oops, sorry, I mixed up my notation there. I have two copies---one that used a `SHORT_NAME='MFZr8'` and another that used `SHORT_NAME='UpwardsMassFlux'`. I got them mixed up in the snippet I posted.

That snippet I shared above should have been:
```
COLLECTIONS: 'VertDiagnEdges',
             'VertDiagnCenters',
::
  VertDiagnEdges.template:         '%y4%m2%d2_%h2%n2z.nc4',
  VertDiagnEdges.format:           'CFIO',
  VertDiagnEdges.frequency:        010000
  VertDiagnEdges.duration:         010000
  VertDiagnEdges.mode:             'time-averaged'
  VertDiagnEdges.fields:           'MFZr8              ', 'GCHPctmEnv',
                                   'Met_PS1DRY         ', 'GIGCchem',
                                   'Met_PS1WET         ', 'GIGCchem',
::
```

Sorry for the confusion

**Comment by LiamBindle** [comment]
> For performance I think the calculation should be in an if associated since no need to allocate and do the computation if not outputting the diagnostic.

Cool! I didn't know this was a capability. Thanks for letting me know
